### ISSUE TITLE
Use jszip for save downloaded files

### ISSUE THREAD

**Issue by yfdyh000** [danny0838/webscrapbook#1]
https://stuk.github.io/jszip/

And even allow convert existing items, allowing the configuration of compression levels and other parameters.

**Comment by danny0838** [comment]
Done. Easier than have thought. See 0.2.0.

**Comment by yfdyh000** [comment]
Looks good. I suggest split the `capturer.saveDocument` to modular and async.

As well as, should allow configuration of the compression level, which will help for CPU time and solid compression for items.

**Comment by yfdyh000** [comment]
Also, the saved zip probably should be the time instead of the page title, or configurable.

**Comment by danny0838** [comment]
I don't get your point. "capturer.saveDocument" is modularized and is async, isn't it?

**Comment by danny0838** [comment]
In my opinion, configuration for zip compression level would be too tricky. Currently blobs don't get much smaller (and could occasionally get bigger) after compression which doesn't worth its resources consumption. Text-based files generally gets much smaller after compression, but tiny ones could get no smaller or even bigger. Therefore the best strategy would probably be variable by file type, and potential configurations are countless and trivial. I'd prefer using a single rule of thumb that gets a good result for most cases (currently we use compression 9 for documents and text files > 128 bytes, and no compression for other files). If the user really really cares about it, they should probably unpack it and pack it by themself, or hack our source code.

**Comment by yfdyh000** [comment]
I expected the `"capturer.saveDocument"` function call different functions for different options, so that there may be better scalability.

I expect to allow configuration the `options.compression` and `options.compressionOptions` for generateAsync. STORE only will help solid compression for multiple items, like backup to 7z file.

Oh, I found you said the program, it looks pretty good, but I would prefer it to be configurable and detachable (modular), zip support and other functions that look messy.
