### ISSUE TITLE
 <noscript> nodes in MAFF file are not hidden in the viewer

### ISSUE THREAD

**Issue by nightson** [danny0838/webscrapbook#10]
<noscript> nodes in web pages are not properly hidden in the viewer as they should be when saved as MAFF file.0

Example URL: http://www.ebay.com/itm/182829397448

When saved as single HTML, <noscript> node is properly hidden:
![1](https://user-images.githubusercontent.com/843241/31574938-67a6e7f8-b10d-11e7-8143-a9e8970f5d19.jpg)

When saved as MAFF, <noscript> node is not hidden. It seems to be a bug of the viewer, as the node is not shown if you browser the file using the old MAFF extension in Firefox 56:
![2](https://user-images.githubusercontent.com/843241/31574937-6771253c-b10d-11e7-8b74-ee6b629bfe1d.jpg)

**Comment by danny0838** [comment]
This is actually a [bug of Firefox core](https://bugzilla.mozilla.org/show_bug.cgi?id=830076) for many years (!) and would be better fixed by Mozilla. We may find a workaround someday.

**Comment by nightson** [comment]
Seems to be fixed in the latest version. Thank you!
