### ISSUE TITLE
有没有在网页底部增添原地址和创建时间的选项？

### ISSUE THREAD

**Issue by loveshoooooot** [danny0838/webscrapbook#101]
这个真的超好用啊，谢谢大佬。
修改的部分也可以保存下来，我直接在网页上做笔记贴便签了。
因为保存时有删改元素，所以希望浏览页面时，能有个按钮跳到原网址。

**Comment by danny0838** [comment]
直接在擷取頁面加入互動按鈕有技術困難，也可能衍生其他問題，目前不考慮。

側欄系統會提供檢視元資料及前往原始網址的功能，進一步信息請關注 #2。

**Comment by loveshoooooot** [comment]
更新36.1看到了'获取书签'。
标题一样很好排序，非常感谢。
