### ISSUE TITLE
Capturing pdf from ftp not allowed

### ISSUE THREAD

**Issue by i3v** [danny0838/webscrapbook#102]
Capturing a pdf file from an ftp server e.g. this: `ftp://iristor.vub.ac.be/patio/SURF/pub/DATAtransit%20SURF-INTERNVUB/oscars/Oxford/X-MaxN%20SEM%20DataSheet.pdf` does not work (grayed our) in Waterfox 56.2.8 (64-bit).

**Comment by danny0838** [comment]
`ftp` scheme is not supported by underlying APIs and thus it's not possible.

**Comment by i3v** [comment]
That's a pity, but thanks for the details!
