### ISSUE TITLE
您好，殷切盼望webscrapbook能尽快完善！

### ISSUE THREAD

**Issue by minshifu** [danny0838/webscrapbook#104]
### Danny Lin您好，

         我在firefox官网上给您留过言，主要表达的就是广大Scrap X 老用户对于quantum版本下替代扩展的殷切盼望之意。希望webscrapbook 可以尽可能还原Scrap X的原始功能和操作界面。辛苦了！             

         祝您一切顺利！

**Comment by danny0838** [comment]
感謝支持。

100% 還原 ScrapBook X 所有功能和介面是做不到的。有些是現代瀏覽器擴充套件的架構限制而做不到；有些是無法做到跨平台支援只好放棄；有些雖技術上可行，但實做起來極為麻煩，由於我們時間有限，只好把優先順序排到很後面。當然，反過來說，現代瀏覽器技術也讓 WebScrapBook 可以做到一些 ScrapBook X 做不到的事，包括更完善的擷取自訂性、把網頁儲存為壓縮格式等等。

相關討論主要集中在[這個帖](https://github.com/danny0838/webscrapbook/issues/2)，如對目前做法有什麼想法，歡迎針對細節提出具體內容，否則我們只能照目前的主觀想法去做，結果就不一定切合大家的需要。
