### ISSUE TITLE
Fatal error: Promised response from onMessage listener went out of scope

### ISSUE THREAD

**Issue by woyaojizhu8** [danny0838/webscrapbook#107]
保存所有网页均失败，出现如上所述的错误提示。环境是macOS 10.13， Firefox 63.0.3，webscrapbook 0.39.2

**Comment by danny0838** [comment]
你的擷取選項是怎麼設定的？（可匯出 json 附上，敏感信息可適當遮蔽）以及你如何操作擷取（擷取分頁？擷取原貌？等等）

**Comment by woyaojizhu8** [comment]
设置都是默认的，操作就是普通的抓取页面（capture tab)

**Comment by danny0838** [comment]
很遺憾我們手上目前沒有 Mac 電腦可以測試，不過一般來說除了 PC 和 Android 版差異以外，應該不會和作業系統相關，如果有也是 Firefox 本身的問題。

請先測試最新版的 Firefox，使用全新設定檔，不安裝其他擴充套件下問題是否仍存在。如果問題還存在，請附上擷取視窗裡的全部訊息；除此之外也可測試同樣操作在 Windows 電腦是否有問題。

**Comment by woyaojizhu8** [comment]
升级Firefox到最新版后问题消失。不过新发现一个问题，就是很多data URL的内容无法保存，比如保存本页会出现错误提示如下：
Capturing (document) [28] https://github.com/danny0838/webscrapbook/issues/107 ... Error downloading file (data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAABCAYAAACsXeyTAAAACXBIW%E2%80%A6sTAAALEwEAmpwYAAAAFUlEQVQIHWNIS0sr/v//PwMMDzY+ADqMahlW4J91AAAAAElFTkSuQmCC): String contains an invalid character
Error downloading file (): URL not resolved.
保存其他网页也有很多data URL 内容无法保存的提示。

**Comment by danny0838** [comment]
擷取下來的頁面打開來看有沒有問題？

那些 data URL 似乎並不是本頁的內容，你有沒有安裝其他瀏覽器套件？如果有請全部停用試試。

**Comment by woyaojizhu8** [comment]
谢谢！确实是其他扩展的问题。这是一个阅读模式扩展叫做 简悦，看起来会向每个页面插入data:image/png。
