### ISSUE TITLE
浏览网页时显示当前页面已经被捕获过的设计

### ISSUE THREAD

**Issue by woyaojizhu8** [danny0838/webscrapbook#108]
Scrapbook x是在右下角出现一个提示框，显示当前标签页有几个捕获的版本，这个设计感觉对用户比较有侵入性。我的想法是，最好还是用在地址栏显示一个图标，上面有当前标签页被捕获版本计数（为0则不显示这个图标）的方法吧。点击这个图标就显示具体捕获页面的列表，上有标题和捕获时间，点击即可打开页面。
不过即使做这个功能，可能也得等到PyWebScrapbook完善，得比较久以后了吧。

**Comment by danny0838** [comment]
已於 0.85.0 加入此功能
