### ISSUE TITLE
Firefox 附加组件管理器中，图标缺失

### ISSUE THREAD

**Issue by yfdyh000** [danny0838/webscrapbook#11]
仅概览中缺失，附加组件详情中不会。加 `    "48": "core/scrapbook_128.png",` 可解决。
自动缩放就可以，提供两份图片则或许有细微性能提升，减少缩放一个1KB 128px的图片。
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/icons

**Comment by danny0838** [comment]
我現在看沒這個問題，舊版也沒有這個問題。似乎不是因為你說的原因，而是因為初次發布正式版本時還沒向 AMO 上傳圖標，而從 AMO 下載的附加元件似乎會更優先使用上傳的圖標。

**Comment by yfdyh000** [comment]
我这里依旧有此问题。加载修改前的代码有此问题，修改后无问题。
试着[https://bugzilla.mozilla.org/show_bug.cgi?id=1410673 报了bug]。

**Comment by danny0838** [comment]
原來的圖片來回縮放畫質會變差，而且新版本新氣象，也許我們設計一個新的向量圖標，再根據需要匯出不同大小的點陣圖會比較好。

不過我美術苦手orz

**Comment by danny0838** [comment]
0.14.2 先加上 32*32 圖標

**Comment by danny0838** [comment]
@yfdyh000 能否麻煩你確認一下，在最新版中，問題是否仍存在？

**Comment by yfdyh000** [comment]
没问题了。
