### ISSUE TITLE
How to respect browser download preference in version 0.39.0 and later?

### ISSUE THREAD

**Issue by laniakea64** [danny0838/webscrapbook#110]
I have my browser set to always ask where I want to save downloads.  WebScrapBook 0.38.5 and older respected this preference.  0.39.0 and later ignore my download preference, instead saving directly to a "scrapbook folder".

1) How do I set the current version of WebScrapBook to just respect the browser download preference?
The only other option I can find is to save captured data to "Backend server", but I don't want to run a server for this.  I save only occasional pages as MAFF packages and would like WebScrapBook to present these MAFF files the same way as normal downloads.

2) If it is not possible to get the old behavior back, how do I set the scrapbook folder to be just the `<default download folder>` itself?
The subfolders are awkward to work with in my setup.  For my use of WebScrapBook, having it save directly in the default download folder might be sufficient to the point that I might not need the old behavior restored.

Thanks

**Comment by danny0838** [comment]
Unfortunately, both are not possible in current version. We have removed the behavior as our primary target is to store indexed archive like legacy ScrapBook, and saving as single file doesn't match the goal, complicates things, and causes inconsistency and incompatibility. If there are still people expecting the behavior, we may consider reintroduce it.

**Comment by laniakea64** [comment]
Thanks danny0838 for the quick reply and info.  I didn't realise that respecting browser download preference was complicated and problematic.

What about allowing to use `<default download folder>` as scrapbook folder?
I played with the code a bit, and simply allowing specifying `.` as scrapbook folder works well in Chromium and Waterfox, but doesn't get it working in Firefox :confused:  Stripping leading `./` at `browser.downloads.download` calls got it working in Firefox too.
Would it be helpful if I submit a pull request?

**Comment by danny0838** [comment]
Using `<default download folder>` as scrapbook folder is not the preferable way since WebScrapBook wants saved web pages be indexable, while `<default download folder>` is usually mixed with lots of other downloads such as executables, and the user will get a bad index if he attempts to index it.

Compared with that, recovering the "save to file" seems the relatively better solution, although we still need to handle related issues first.

**Comment by danny0838** [comment]
Implemented in 0.43.0—reintroduce saveTo = "file", at least for now.

**Comment by laniakea64** [comment]
Thanks danny0838 for restoring this useful feature! :smiley:
