### ISSUE TITLE
stall on capture and capture source firefox 60.6.2esr in linux 64bits

### ISSUE THREAD

**Issue by ag88** [danny0838/webscrapbook#111]
webscrapbook release: 0.42.0
when attempting to perform capture tab, stall and if frame is resized:
Capturing (document) [67] https://kotlinlang.org/docs/reference/comparison-to-java.html ... Fatal error: Promised response from onMessage listener went out of scope

when attempting to perform capture source, stall and if frame is resized:
Capturing (source) https://kotlinlang.org/docs/reference/comparison-to-java.html ...
no further response

this is a new install opensuse linux 15.1 firefox 60.6.2esr 64bits

**Comment by danny0838** [comment]
What does "stall" and "if frame is resized" mean?

I cannot see an issue capturing the provided page with capture or capture (source), though I may be missing something by not understanding the above words.

**Comment by shooter0106** [comment]
@danny0838 Hello!

After a click on "Capture tab" menu element, small empty browser window will be shown. If i try a resize it, his content now been a visible:
```
Capturing (document) [79] https://github.com/danny0838/webscrapbook/issues/111 ... 
Fatal error: Promised response from onMessage listener went out of scope
```

So, i have a same problem on webscrapbook 0.43.0 and firefox 60.6.3esr (64-bit).

Thanks!

**Comment by ag88** [comment]
hi

i'm inserting a screen print here, of the 'capture tab' of this page
![capture tab error](https://i.imgur.com/96IOv0F.png) 

the error message:
"Capturing (document) [51] https://github.com/danny0838/webscrapbook/issues/111 ... Fatal error: Promised response from onMessage listener went out of scope"
is displayed

**Comment by danny0838** [comment]
Does it always happen when capture or just occasionally? Do you do anything during the capture (such as moving or closing the tab being catpured)?

Also try right-clicking on the capture dialog > elements > console and report the messages in it.

**Comment by ag88** [comment]
it happens all the time, selecting capture tab brings up a blank internal frame, if that frame is resized the error message appears:
```
Error
​
columnNumber: 1
​
fileName: "moz-extension://1c6f82db-06f4-4b61-9ce7-d65dc551b593/capturer/capturer.js"
​
lineNumber: 2199
​
message: "Promised response from onMessage listener went out of scope"
​
stack: "@moz-extension://1c6f82db-06f4-4b61-9ce7-d65dc551b593/capturer/capturer.js:2199:1\n"
​
__proto__: Object { … }
common.js:1897:5
capturer.captureDocument
moz-extension://1c6f82db-06f4-4b61-9ce7-d65dc551b593/capturer/common.js:1897:5
```
i tried to open the nested structures in the console, but apparently there are many items and very deep. hence i kind of expanded the summaries and posted it here

**Comment by danny0838** [comment]
It's a defect of the API in Firefox < 65. We added an workaround to get it work. 0.43.1 should fix the issue.

**Comment by ag88** [comment]
thanks you very much ! :)
