### ISSUE TITLE
不保存隐藏元素？

### ISSUE THREAD

**Issue by woyaojizhu8** [danny0838/webscrapbook#114]
有些元素是被广告屏蔽扩展屏蔽（隐藏）了的，但是保存网页以后发现被隐藏了的元素仍然被保存了。可不可以给个选项，不保存隐藏元素？

**Comment by danny0838** [comment]
技術上可以做到，但是這樣做並不保證安全，有些時候刪除隱藏的頁面元素仍有可能改變頁面呈現（參見 #122）。

**Comment by danny0838** [comment]
0.53 已加入此功能
