### ISSUE TITLE
How can I make a donation?

### ISSUE THREAD

**Issue by Michaelsy** [danny0838/webscrapbook#115]
I want to support the development of webscrapbook. How can I make a donation?

**Comment by danny0838** [comment]
Donation is available via [PayPal](https://www.paypal.me/danny0838/5usd) and is welcome. Though we 'd be more appreciated if someone could help solve [hard issues](https://github.com/danny0838/webscrapbook/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22), localization, or improvements of the [documentation wiki](https://github.com/danny0838/webscrapbook/wiki).
