### ISSUE TITLE
0.44 在處理 href 會有找錯路徑的狀況

### ISSUE THREAD

**Issue by gakinccc** [danny0838/webscrapbook#116]
更新到0.44版之後發現之前版本能正常擷取的CSS或是跟CSS有關的其他物件，在0.44版會變成404 not found所以沒存下來
用firefox 的debug查看網頁，發現如果href下的css如果不是在當前路徑而是上層的其他路徑就會出錯
之前的版本可以正常處理這種寫法

**Comment by danny0838** [comment]
能否提供實際案例的網址？

**Comment by gakinccc** [comment]
https://www.ganganonline.com/contents/goblindk/
用0.44存這個網頁會出現很多png檔案not found的狀況，但是0.43.2會正常存下來

**Comment by danny0838** [comment]
我測試沒遇到問題。請問你使用的作業系統、瀏覽器，以及擷取選項（可匯出檔案貼出來，若有隱私訊息自己適當加碼）？

**Comment by gakinccc** [comment]
試過Firefox 67.0，66.0.5以及cent browser。OS有試過Windows 7跟Windows 10
下面的設定是在沒有裝backend server的電腦匯出的，在另一台有啟動backend server的電腦上的結果都一樣
  "server.url": "",
  "server.user": "",
  "server.password": "",
  "server.scrapbook": "",
  "capture.saveTo": "folder",
  "capture.saveFolder": "WebScrapBook/data",
  "capture.saveAs": "zip",
  "capture.saveFilename": "%ID%",
  "capture.saveAsciiFilename": false,
  "capture.saveBeyondSelection": false,
  "capture.saveFileAsHtml": false,
  "capture.saveDataUriAsFile": true,
  "capture.autoCloseDialog": false,
  "capture.image": "save",
  "capture.imageBackground": "save",
  "capture.favicon": "save",
  "capture.canvas": "save",
  "capture.audio": "save",
  "capture.video": "save",
  "capture.embed": "blank",
  "capture.object": "blank",
  "capture.applet": "blank",
  "capture.frame": "save",
  "capture.font": "save",
  "capture.style": "save",
  "capture.styleInline": "save",
  "capture.rewriteCss": "url",
  "capture.script": "blank",
  "capture.noscript": "save",
  "capture.base": "blank",
  "capture.formStatus": "keep",
  "capture.downLink.mode": "header",
  "capture.downLink.extFilter": "###image\nbmp, gif, ico, jpg, jpeg, jpe, jp2, png, tif, tiff, svg\n###audio\n#aac, ape, flac, mid, midi, mp3, ogg, oga, ra, ram, rm, rmx, wav, wma\n###video\n#avc, avi, flv, mkv, mov, mpg, mpeg, mp4, wmv\n###archive\n#zip, rar, jar, bz2, gz, tar, rpm, 7z, 7zip, xz, jar, xpi, lzh, lha, lzma\n#/z[0-9]{2}|r[0-9]{2}/\n###document\n#pdf, doc, docx, xls, xlsx, ppt, pptx, odt, ods, odp, odg, odf, rtf, txt, csv\n###executable\n#exe, msi, dmg, bin, xpi, iso\n###any non-web-page\n#/(?!$|html?|xht(ml)?|php|py|pl|aspx?|cgi|jsp)(.*)/i",
  "capture.downLink.urlFilter": "###skip common logout URL\n/[/=]logout\\b/i",
  "capture.removeIntegrity": true,
  "capture.requestReferrer": "auto",
  "capture.recordDocumentMeta": true,
  "capture.recordRemovedNode": false,
  "capture.recordRewrittenAttr": false,
  "capture.recordSourceUri": false,
  "capture.recordErrorUri": true,
  "viewer.useFileSystemApi": true,
  "viewer.viewHtz": true,
  "viewer.viewMaff": true,
  "indexer.fulltextCache": true,
  "indexer.fulltextCacheFrameAsPageContent": true

**Comment by danny0838** [comment]
我用你提供的選項還是沒遇到問題。你有沒有試過瀏覽器使用新的使用者設定檔，並移除WebScrapBook以外所有其他擴充套件？

**Comment by gakinccc** [comment]
我測試用Cent browser Portable 模擬一個新安裝的瀏覽器，只有安裝WebScrapBook一個extension，結果還是相同
使用0.44抓我提供的網頁訊息是這樣
Capturing (document) [7] https://www.ganganonline.com/contents/goblindk/ ... Error downloading file (https://www.ganganonline.com/contents/images/common/gn_bg.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/common/gn_header_gmenu_wlist.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/common/gn_header_gmenu_wlist.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/common/gn_header_gmenu_award.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/common/gn_header_gmenu_award.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/common/gn_header_gmenu_update.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/common/gn_header_gmenu_update.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/common/gn_header_btn_addmaga.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/common/gn_header_gmenu_enq.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/common/gn_header_gmenu_enq.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/common/gn_header_btn_inquiry.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/common/gn_header_btn_twitter.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/common/gn_footer_icon_arrow.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/clist/gn_clist_ttl_comic_bg.jpg): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/clist/gn_clist_h2_icon.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/clist/gn_clist_ttl_novel_bg.jpg): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/clist/gn_clist_ttl_special_bg.jpg): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/clist/gn_clist_ttl_event_bg.jpg): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/award/gn_award_h2_icon.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/archive/gn_archive_h2_icon.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/faq/gn_faq_h2_icon.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/faq/gn_faq_h2_icon.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/top/gn_top_h4_bg.jpg): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/top/gn_whatnew_alert_icon.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/info/gn_info_h2_icon.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_info_h2_icon.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_story_h2_icon.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_story_h2_icon.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_topics_h2_icon.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/common/gn_footer_bg.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_media_h2_icon.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_download_h2_icon.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_tvcm_h2_icon.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_flag_h2_icon.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_chara_h2_icon.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_comics_h2_icon.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_original_h2_icon.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_related_h2_icon.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_download_btn_1024x728.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_download_btn_1024x728.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_download_btn_1024x728.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_download_btn_1280x800.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_download_btn_1280x800.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_download_btn_1280x800.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_download_btn_1280x1024.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_download_btn_1280x1024.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_download_btn_1280x1024.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_download_btn_1920x1080.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_download_btn_1920x1080.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_download_btn_1920x1080.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_download_btn_1920x1200.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_download_btn_1920x1200.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_download_btn_1920x1200.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_download_btn_640x1136.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_download_btn_640x1136.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_download_btn_640x1136.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_download_btn_1440x1280.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_download_btn_1440x1280.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_download_btn_1440x1280.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_download_btn_2048x2048.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_download_btn_2048x2048.png): 404 Not Found
Error downloading file (https://www.ganganonline.com/contents/images/detail/gn_detail_download_btn_2048x2048.png): 404 Not Found
Preparing download... Done.

用0.43.2出現的訊息是
Capturing (document) [7] https://www.ganganonline.com/contents/goblindk/ ... Preparing download... Done.

**Comment by danny0838** [comment]
看起來出問題的地方是要登入才能看的部分，很遺憾我沒有帳號orz....

可能要麻煩你協助找出出問題的 css，並提供原始網路路徑、網路原始檔、以及 0.43.2 和 0.44 分別抓下來的檔案內容了...

**Comment by gakinccc** [comment]
我分析了幾個會抓錯的網址後，發現0.44會出錯的情況是CSS裡面用了../或是./來指定位置
例如 https://www.ganganonline.com/contents/goblindk/ 的head用了style.css
https://www.ganganonline.com/common/css/style.css
url(../images/common/gn_header_gmenu_wlist.png)會被抓錯位置，0.43會用 https://www.ganganonline.com/common/images/common/gn_header_gmenu_wlist.png 去抓
0.44 變成找 https://www.ganganonline.com/contents/images/common/gn_header_gmenu_wlist.png 這個位置
另一個找錯的例子是這個網頁 https://www.megahit.co.jp/products/detail.php?product_id=127673 
https://www.megahit.co.jp/user_data/packages/default/css/import.css 中 url("./reset.css") 在0.44會找 https://www.megahit.co.jp/products/reset.css 這個位置，0.43會去 https://www.megahit.co.jp/user_data/packages/default/css/reset.css 抓
所以很明顯有問題的情況就是CSS當中用../或是./指定檔案位置的時候，應該從CSS所在的位置去找對應路徑，但是0.44不知道為什麼變成從當前網頁位置去找對應路徑
這兩個網頁我都沒有login就可以出現這個結果，因為我沒申請帳號所以都是在沒有login的狀況下試出來的
[data.zip](https://github.com/danny0838/webscrapbook/files/3233303/data.zip)

**Comment by danny0838** [comment]
找到原因了。是因為 0.44.0 打包錯誤，把一些開發中的東西包進去了。
0.44.1 修了一個新發現的小 BUG，順便重新打包，應該就不會再有這問題了。

**Comment by gakinccc** [comment]
我測試的結果0.44.1已經可以正常擷取了
