### ISSUE TITLE
Scrapbook for Firefox Quantum

### ISSUE THREAD

**Issue by rkoe** [danny0838/webscrapbook#117]
Hi,

I just want to let you know, that I'm currently also working on a Scrapbook for Firefox Quantum,
but I'm using a different approach, and hope it will soon be as easy to use as Scrapbook X: https://github.com/rkoe/scrapbookmark/
(I've not yet uploaded the code and instructions, but this will follow soon.)

Read-accessing old Scrapbook X-data and organizing them in folders is really easy, storing pages is currently partially working (and work-in-progress).

And of course @danny0838: Thanks for all the years of Scrapbook X!

**Comment by danny0838** [comment]
Thank you for the idea. However, as we have been evaluated, bookmarklet with Python script may have several technical issues:

1. How does the bookmarklet invoke the Python script on the system? Is it possible?

1. If capture of the web page is done via a local Python script, it may be unable to capture the currently displaying content in the browser (and gets pre-script-processed content instead), and content that requires authentication in the browser (e.g. cookie, localStorage, or HTTPS).

1. It cannot run on mobiles, such as Firefox for Android, as Android doesn't have the Python script.

Do you have a good idea to solve such issues?

**Comment by rkoe** [comment]
Bookmarklets unfortunately do have some drawbacks -- especially due to the current Firefox-CSP-bug and since Firefox removed rel=sidebar in FF63. Without these, bookmarklets would be a good (and easily extenable) alternative; but with these, I will probably (have to) convert it to a WebExtensions-addon (or a mix of an addon and bookmarklets) to make saving pages easier.

>     1. How does the bookmarklet invoke the Python script on the system? Is it possible?
It only invokes it as MIME-handler to unpack saved pages to the filesystem.

>     2. If capture of the web page is done via a local Python script,
No, the capture is completely done by the bookmarklet. Python only unpacks the data (and fixed the bookmarks before FF63).

>     3. It cannot run on mobiles, such as Firefox for Android, as Android doesn't have the Python script.
Actually, Python can run on at least some mobiles. I've running Python via Termux on Android.

> Do you have a good idea to solve such issues?

The main problems of my bookmarklet-solution currently are (a) the CSP-bug (but this may be solved) and (b) that creating bookmarks via bookmarklets is quite cumbersome since FF63. And (b) can only be solved by creating a WebExtensions-addon.

**Comment by danny0838** [comment]
> > ```
> > 1. How does the bookmarklet invoke the Python script on the system? Is it possible?
> > ```
> 
> It only invokes it as MIME-handler to unpack saved pages to the filesystem.
> 
> > ```
> > 2. If capture of the web page is done via a local Python script,
> > ```
> 
> No, the capture is completely done by the bookmarklet. Python only unpacks the data (and fixed the bookmarks before FF63).
> 
What do you mean "Python script as a MIME handler"? Do you mean setting the Python script as the handler of certain .pack format which is used for the captured file? It sounds like the `wsbview` in the [PyWebScrapBook](https://github.com/danny0838/PyWebScrapBook)?

AFAIK browsers are restricted by the SOP (same origin policy) and cannot access a resource from another origin of a web page. Is it possible for a bookmarklet to save a `http://site-B.com/path/to/image.jpg` embeded in a page `http://site-A.com/path/to/page.html`?

**Comment by rkoe** [comment]
> What do you mean "Python script as a MIME handler"? Do you mean setting the Python script as the handler of certain .pack format which is used for the captured file?

More or less, yes. I use a special MIME type (application/scrapbookmark) and tell Firefox in about:preferences to use my Python script as "Action" for this "Content Type".

> It sounds like the `wsbview` in the [PyWebScrapBook](https://github.com/danny0838/PyWebScrapBook)?

I don't know wsbview in detail. But all my Python script does, is unpack the packed data to the harddisk.

> AFAIK browsers are restricted by the SOP (same origin policy) and cannot access a resource from another origin of a web page. Is it possible for a bookmarklet to save a `http://site-B.com/path/to/image.jpg` embeded in a page `http://site-A.com/path/to/page.html`?

Partly. Currently it seems, that this might be the reason to switch from bookmarklets to an addon (since I've resolved the usability issues with bookmarklets now).
But even without it, it already works well for me -- since I'm usually using uMatrix to block cross-site-requests anyway.
