### ISSUE TITLE
No scrapbook folder on kubuntu 17.10

### ISSUE THREAD

**Issue by brochignac** [danny0838/webscrapbook#12]
Hi,
I use firefox 58.0a1 with the last version of webscrapbook (0.14.2) under Kubuntu 17.10.
If I define a folder to save (Options -> Capture - Saving -> Scrapbook Folder -> webscrapbook or ~/webscrapbook), I can't find this folder in my home folder. In fact, I have no scrapbook save.
If I define an other place, like "/media/svg/webscrapbook", it doesn't work too.
Thanks

**Comment by danny0838** [comment]
Do you have the option *Save captured data in ScrapBook* checked?

**Comment by brochignac** [comment]
So, the _Save captured data in ScrapBook_ option was unchecked.
I try now with the checked option _Save captured data in ScrapBook_ with all the different options _Save captured data as:_ Folder / htz / maff package or single HTML.
I click on the Web Scrapbook icon -> _Capture tab_ and I search a named "webscrapbook" folder in my home folder with :
$ find ~ -name webscrapbook -type d
No "webscrapbook" folder and when I click on _View archived page_, any page is available.

**Comment by brochignac** [comment]
So, the Save captured data in ScrapBook option was unchecked.
I try now with the checked option Save captured data in ScrapBook with all the different options Save captured data as: Folder / htz / maff package or single HTML.
I click on the Web Scrapbook icon -> Capture tab and I search a named "webscrapbook" folder in my home folder with :
$ find ~ -name webscrapbook -type d
No "webscrapbook" folder and when I click on View archived page, any page is available.

**Comment by danny0838** [comment]
The path is related to default download directory of the browser> It's not related to your home directory, nor the absolute system path.

**Comment by brochignac** [comment]
I have no download directory of my browser, Firefox asks me where I want to download.
And if I select a download directory, I have no more folder or saved page.

**Comment by danny0838** [comment]
I don't quite understand your problem. Were those pages saved? They should appear in the download list of Firefox, where you can find the actual save path. So, what was the actual save path you get?

**Comment by brochignac** [comment]
In _Capture - saving_ option , I have _Scrapbook Folder:_ webscrapbook
_Save captured data as:_ is _htz package_ (I tried the others options too)
_Save captured data in ScrapBook_ is checked
When I click on _Capture tab_, and after I want to _View archived page_, I have nothing, no page saved, no folder named webscrapbook where page can be saved.
I have nothing in the download list of Firefox too.
I hope I'm clearer.

**Comment by danny0838** [comment]
You mean that when you attempt to run capture tab, there is nothing saved? Is there a small red-backgrounded number showing at the toolbar button of Web ScrapBook?

**Comment by brochignac** [comment]
That's right, nothing saved.
And no small red-backgrounded number, nothing, only the toolbar button

![spectacle x17274](https://user-images.githubusercontent.com/33000312/31865173-98404a36-b76a-11e7-8998-aa883b745e0c.png)

**Comment by brochignac** [comment]
I use Firefox 56.0 too, I use Scrapbook and I can choose the folder where I save my pages.
But with the new versions of Firefox and the webextension, I try to use your Web scrapbook and may be it's not as usual.

**Comment by danny0838** [comment]
What is the web page you tried to capture?

Did you tried Capture tab (source) and did it work?

Could you also try this using a new Firefox profile (by adding a "-p" in the command line) or using Chrome, and report whether it works or not?

**Comment by brochignac** [comment]
So, I only tested to save the options tab of webscrapbook with my usual Firefox nightly (v58.a01).
 And when I wanted to save this options tab of webscrapbook with webscrapbook (my tests), a click on the icon in the toolbar gave me the list with the same grey color text. No difference between possible and no possible selection (why, I don't know, maybe a theme problem).
 So I tried with a fresh Firefox nightly profile, and I discover the different colors of the list (dark if not available, clear if available).
 I discover too it isn't not possible to save a "local" tab like "about:config" of Firefox or "moz-extension://xxxxxxxx-xxxxxxx-xxxxx-xxxxx/core/options.html" of webscrapbook options.
 So, I tested with extern hppt/https web pages and it works, saves are in a webscrapbook/data folders.
 Rarely, there is a small red-backgrounded number.
 After, to open an archive:
 - _Folder_ option : I click on the index.html in the webscrapbook/data/dateofsavexxxxxxx/index.html to open a new Firefox window, 
 - _htz/maff package_ : it open a "View archive page" tab and wait with a blank page, (such as to open a web link with no internet connexion),
 - _single HTML_ : I have the "Unable to open web page archive: Can't find end of central directory : is this a zip file ? If it is, see http://stuk.github.io/jszip/documentation/howto/read_zip.html" error.

Not entirely friendly but great job.

**Comment by danny0838** [comment]
It seems to work fine according to your description.

A single HTML file can be opened by the browser directly and you don't have to (and can't) open it with the archive viewer.

When a small red-backgrounded number appear, it means tha there is an error detected by Web ScrapBook. You can record the condition to reproduce it and report to us.
