### ISSUE TITLE
Not all webpage styles are saved

### ISSUE THREAD

**Issue by laniakea64** [danny0838/webscrapbook#124]
WebScrapBook 0.56.0
Firefox 69.0.3
new profile

Using "Capture tab" on https://wiki.gnome.org/Projects/gvfs/backends does not save all of that webpage's styles.

Screenshot of saved page:
![20191013](https://user-images.githubusercontent.com/16628411/66718336-d54b0000-edb0-11e9-87e6-e05a376d46a9.png)

**Comment by danny0838** [comment]
Please test if it's fixed in 0.56.1.

**Comment by laniakea64** [comment]
0.56.1 works.  Thanks for the fast fix! :smiley:
