### ISSUE TITLE
儲存速度異常

### ISSUE THREAD

**Issue by DCGoner** [danny0838/webscrapbook#125]
D大您好，

0.52.1 儲存速度正常，但從 0.52.2 到 0.56.0，只要容量大一點的網頁，速度明顯變慢
以這為例：https://www.ptt.cc/bbs/Beauty/M.1570638722.A.6F1.html

網頁載入完成後儲存（檔案大小約 12MB）：
0.52.1：02～03s
0.56.0：14～15s
觀察網頁載入完成的時間：12～13s

感覺從 0.52.2 開始，
儲存網頁不會從快取抓圖片，而是重新下載圖片（但看工作管理員火狐沒有流量在跑）
測試 gif 更多的網頁，
例如檔案大小 20～30MB，大約會到一分多鐘，而 0.52.1 大約只會多個一秒

用新的 profiles 測試，只安裝網頁剪貼簿和 Tampermonkey（PTT Imgur Fix、PTT Long Change）：
0.52.1：01～02s
0.56.0：05～06s
有變快一點，但沒有 0.52.1 那種秒存的感覺
用其它格式儲存，只有資料夾和 HTML 有秒存的感覺

以前存 100MB～200MB 以上的時間（HTZ）大約是三到四秒多左右，現在要等超久
不曉得是哪邊出了問題，還請 D大看看

附上作業環境：

系統：Windows 7 Service Pack 1 (Build 7601.24515) 64bit
瀏覽器：Firefox 70.0a1（2019-10-10）（64 位元）
儲存方式：都是選第一個「擷取分頁」這個選項
儲存格式：都是用 HTZ 檔來儲存
儲存設定：樣式圖片、字體和腳本我選「清空」，音訊和視訊我選「連結」
元資料有勾選「紀錄原始的 URL」
檢視器有勾選「使用 Filesystem API」
其它設定沒什麼改動

**Comment by danny0838** [comment]
看起來主要和把 JSZip 版本[從 3.1.5 升級到 3.2.2](https://github.com/Stuk/jszip/blob/master/CHANGES.md) 有關。照他們的改版說明是加上[清理記憶體緩衝區](https://github.com/Stuk/jszip/pull/506)以提高安全性，但不可避免地會導致速度變慢。

因為是和安全性有關，除非有高手能出面說明，否則我們暫時不會改動。
