### ISSUE TITLE
Fatal error when capturing a document with a custom element that generates a shadowRoot automatically

### ISSUE THREAD

**Issue by qdinar** [danny0838/webscrapbook#128]
on saving https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=14689 :

Capturing (document) [6] https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=14689 ...
Fatal error: An attempt was made to use an object that is not, or is no longer, usable

i will try to attach options later, here is no button for that.

firefox 68.2.0esr (32-bit)

-- System Information:
Debian Release: 10.1
  APT prefers stable-updates
  APT policy: (500, 'stable-updates'), (500, 'stable')
Architecture: i386 (i686)

Kernel: Linux 4.19.0-6-686-pae (SMP w/4 CPU cores)
Locale: LANG=en_GB.UTF-8, LC_CTYPE=en_GB.UTF-8 (charmap=UTF-8), LANGUAGE=en_GB:en (charmap=UTF-8)
Shell: /bin/sh linked to /usr/bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

**Comment by qdinar** [comment]
options:

{
  "server.url": "",
  "server.user": "",
  "server.password": "",
  "server.scrapbook": "",
  "capture.saveTo": "folder",
  "capture.saveFolder": "WebScrapBook/data",
  "capture.saveAs": "downloads",
  "capture.saveFilename": "%ID%",
  "capture.saveAsciiFilename": false,
  "capture.saveBeyondSelection": false,
  "capture.saveFileAsHtml": false,
  "capture.saveDataUriAsFile": true,
  "capture.saveDataUriAsSrcdoc": true,
  "capture.autoCloseDialog": true,
  "capture.pageSizeLimit": null,
  "capture.resourceSizeLimit": null,
  "capture.image": "blank",
  "capture.imageBackground": "remove",
  "capture.favicon": "remove",
  "capture.canvas": "save",
  "capture.audio": "blank",
  "capture.video": "blank",
  "capture.embed": "blank",
  "capture.object": "blank",
  "capture.applet": "blank",
  "capture.frame": "save",
  "capture.frameRename": true,
  "capture.font": "remove",
  "capture.style": "save",
  "capture.styleInline": "save",
  "capture.rewriteCss": "url",
  "capture.mergeCssResources": true,
  "capture.script": "blank",
  "capture.noscript": "save",
  "capture.base": "blank",
  "capture.formStatus": "keep",
  "capture.shadowDom": "save",
  "capture.removeHidden": "none",
  "capture.precludeSelector": "",
  "capture.linkUnsavedUri": false,
  "capture.downLink.mode": "none",
  "capture.downLink.extFilter": "###image\n#bmp, gif, ico, jpg, jpeg, jpe, jp2, png, tif, tiff, svg\n###audio\n#aac, ape, flac, mid, midi, mp3, ogg, oga, ra, ram, rm, rmx, wav, wma\n###video\n#avc, avi, flv, mkv, mov, mpg, mpeg, mp4, wmv\n###archive\n#zip, rar, jar, bz2, gz, tar, rpm, 7z, 7zip, xz, jar, xpi, lzh, lha, lzma\n#/z[0-9]{2}|r[0-9]{2}/\n###document\n#pdf, doc, docx, xls, xlsx, ppt, pptx, odt, ods, odp, odg, odf, rtf, txt, csv\n###executable\n#exe, msi, dmg, bin, xpi, iso\n###any non-web-page\n#/(?!$|html?|xht(ml)?|php|py|pl|aspx?|cgi|jsp)(.*)/i",
  "capture.downLink.urlFilter": "###skip common logout URL\n/[/=]logout\\b/i",
  "capture.removeIntegrity": true,
  "capture.requestReferrer": "auto",
  "capture.recordDocumentMeta": true,
  "capture.recordRemovedNode": false,
  "capture.recordRewrittenAttr": false,
  "capture.recordSourceUri": false,
  "editor.autoInit": true,
  "editor.lineMarker.checked": null,
  "editor.lineMarker.style.1": "background-color: #FFFF00; text-shadow: 0 0 1px black;",
  "editor.lineMarker.style.2": "background-color: #00FF00; text-shadow: 0 0 1px black;",
  "editor.lineMarker.style.3": "background-color: #00FFFF; text-shadow: 0 0 1px black;",
  "editor.lineMarker.style.4": "background-color: #FF0000; text-shadow: 0 0 1px black;",
  "editor.lineMarker.style.5": "border-bottom: 2px solid #00FF00;",
  "editor.lineMarker.style.6": "border-bottom: 2px solid #FF0000;",
  "editor.lineMarker.style.7": "border-bottom: 2px dotted #0000FF;",
  "editor.lineMarker.style.8": "border-bottom: 2px dotted #FF0000;",
  "editor.lineMarker.style.9": "background-color: #FFFF99; color: #000000; border: thin dashed #FFCC00;",
  "editor.lineMarker.style.10": "background-color: #CCFFFF; color: #000000; border: thin solid #0099FF;",
  "editor.lineMarker.style.11": "border: medium double #993399;",
  "editor.lineMarker.style.12": "background-color: #EE3311; color: #FFFFFF; font-weight: bold;",
  "viewer.useFileSystemApi": true,
  "viewer.viewHtz": true,
  "viewer.viewMaff": true,
  "indexer.fulltextCache": true,
  "indexer.fulltextCacheFrameAsPageContent": true
}

**Comment by qdinar** [comment]
wsb 0.56.3

**Comment by danny0838** [comment]
Fixed in 0.56.4.
