### ISSUE TITLE
Tor Browser dont save

### ISSUE THREAD

**Issue by newsdos** [danny0838/webscrapbook#129]

**Comment by danny0838** [comment]
I tested several web pages with Tor Browser 9.0.2 and cannot see a problem. Could you be more specific about the issue you meet? Including your OS version, browser version, WSB version, the web page URL you are trying to save, WSB options, more description about how you save the web page, and possibly screenshots.

**Comment by danny0838** [comment]
Close an issue without enough information and further response.
