### ISSUE TITLE
Question on importing ScrapBook data

### ISSUE THREAD

**Issue by RuralHunter** [danny0838/webscrapbook#132]
Hi, 
I just found this extension and tried to import my old data from ScrapBook. I followed the [instruction](https://github.com/danny0838/webscrapbook/wiki/Import) and got the tree/map.html and frame.html. But when I open them, I only get the index of all the articles with timestamps such as '20100101153820', no original titles, not original folders. The article contents are fine though. Is this expected result? Or did I miss something?

**Comment by danny0838** [comment]
The site indexer generates only the index. You need to manually merge them into the original scrapbook folder, as the step 5 in the instruction says.

**Comment by RuralHunter** [comment]
hmm...of coz I had completed step 5 already. I meant the tree/map.html and tree/frame.html in step 6.

**Comment by danny0838** [comment]
I'm not sure if I understand you correctly. Could you provide screenshots to illustrate what you have said "no original titles, not original folders"?

**Comment by RuralHunter** [comment]
This what I get when I open tree/map.html:
[Image Link](https://ibb.co/KKJZkGm)

**Comment by danny0838** [comment]
Seems something wrong. Could you provide the log of the site indexer for further investigation?

**Comment by RuralHunter** [comment]
Where can I get the log?

**Comment by danny0838** [comment]
When you run the site indexer you can see the log output like:

```
Got directory 'webscrapbook-1'.
Inspecting files...
Found 457 files.
Importing 'tree/meta.js'...
Importing 'tree/toc.js'...
Inspecting data files...
Inspecting metadata...
Inspecting TOC...
Adding new items to TOC...
Inspecting favicons...
Checking for created and updated files...
Generating fulltext cache...
Importing 'tree/fulltext.js'...
Generating zip file...
If the download doesn't start, click me.
Done.

Time spent: 0.522 seconds.
```

Just copy all of them and paste here.

**Comment by RuralHunter** [comment]
`
选择网页剪贴簿文件夹或其 ZIP 压缩文件。你可以拖放它们至此页，或使用以下按钮：
选择文件夹 选择 ZIP 压缩文件
Got directory 'scrapBook1'.
Found 6507 files.
Found 'scrapbook.rdf' for legacy ScrapBook. Importing...
Inspecting data files...
Inspecting metadata...
Removed metadata entry for '20060829112625': Missing index file.
Removed metadata entry for '20110829110228': Missing index file.
Removed metadata entry for '20051202095157': Missing index file.
Removed metadata entry for '20131210220651': Missing index file.
Removed metadata entry for '20101223105210': Missing index file.
Removed metadata entry for '20060326144009': Missing index file.
Removed metadata entry for '20101229113733': Missing index file.
Removed metadata entry for '20060713095654': Missing index file.
Removed metadata entry for '20110829110239': Missing index file.
Removed metadata entry for '20081007113453': Missing index file.
Removed metadata entry for '20091004105815': Missing index file.
Removed metadata entry for '20061124173402': Missing index file.
Removed metadata entry for '20070128205706': Missing index file.
Removed metadata entry for '20110121091336': Missing index file.
Removed metadata entry for '20060418213445': Missing index file.
Removed metadata entry for '20051213151144': Missing index file.
Removed metadata entry for '20120515235920': Missing index file.
Removed metadata entry for '20051017092838': Missing index file.
Removed metadata entry for '20120515235823': Missing index file.
Removed metadata entry for '20090515134718': Missing index file.
Removed metadata entry for '20100219171617': Missing index file.
Removed metadata entry for '20080827132945': Missing index file.
Removed metadata entry for '20090924111353': Missing index file.
Removed metadata entry for '20050707153704': Missing index file.
Removed metadata entry for '20061129155927': Missing index file.
Inspecting TOC...
Removed TOC reference '20131210220651' from 'root': Missing metadata entry.
Removed TOC reference '20120515235920' from 'root': Missing metadata entry.
Removed TOC reference '20110829110228' from 'root': Missing metadata entry.
Removed TOC reference '20110121091336' from 'root': Missing metadata entry.
Removed TOC reference '20101229113733' from 'root': Missing metadata entry.
Removed TOC reference '20100219171617' from 'root': Missing metadata entry.
Removed TOC reference '20090515134718' from 'root': Missing metadata entry.
Removed TOC reference '20081007113453' from 'root': Missing metadata entry.
Removed TOC reference '20080827132945' from 'root': Missing metadata entry.
Removed TOC reference '20061129155927' from 'root': Missing metadata entry.
Removed TOC reference '20061124173402' from 'root': Missing metadata entry.
Removed TOC reference '20060829112625' from 'root': Missing metadata entry.
Removed TOC reference '20051213151144' from 'root': Missing metadata entry.
Removed TOC reference '20051202095157' from 'root': Missing metadata entry.
Removed TOC reference '20060326144009' from 'root': Missing metadata entry.
Removed TOC reference '20060418213445' from 'root': Missing metadata entry.
Removed TOC reference '20070128205706' from 'root': Missing metadata entry.
Removed TOC reference '20090924111353' from 'root': Missing metadata entry.
Removed TOC reference '20091004105815' from 'root': Missing metadata entry.
Removed TOC entry '20060829112625': Missing metadata entry.
Removed TOC entry '20110829110228': Missing metadata entry.
Removed TOC entry '20051202095157': Missing metadata entry.
Removed TOC entry '20131210220651': Missing metadata entry.
Removed TOC entry '20101223105210': Missing metadata entry.
Removed TOC entry '20060326144009': Missing metadata entry.
Removed TOC entry '20101229113733': Missing metadata entry.
Removed TOC entry '20060713095654': Missing metadata entry.
Removed TOC entry '20110829110239': Missing metadata entry.
Removed TOC entry '20081007113453': Missing metadata entry.
Removed TOC entry '20091004105815': Missing metadata entry.
Removed TOC entry '20061124173402': Missing metadata entry.
Removed TOC entry '20070128205706': Missing metadata entry.
Removed TOC entry '20110121091336': Missing metadata entry.
Removed TOC entry '20060418213445': Missing metadata entry.
Removed TOC entry '20051213151144': Missing metadata entry.
Removed TOC entry '20120515235920': Missing metadata entry.
Removed TOC entry '20051017092838': Missing metadata entry.
Removed TOC entry '20120515235823': Missing metadata entry.
Removed TOC entry '20090515134718': Missing metadata entry.
Removed TOC entry '20100219171617': Missing metadata entry.
Removed TOC entry '20080827132945': Missing metadata entry.
Removed TOC entry '20090924111353': Missing metadata entry.
Removed TOC entry '20050707153704': Missing metadata entry.
Removed TOC entry '20061129155927': Missing metadata entry.
Adding new items to TOC...
Appended '20050707153750' to root of TOC.
Appended '20050707153828' to root of TOC.
Appended '20050707153846' to root of TOC.
Appended '20050707153919' to root of TOC.
Appended '20050707153939' to root of TOC.
Appended '20050707153958' to root of TOC.
Appended '20050707154015' to root of TOC.
Appended '20050707154120' to root of TOC.
Appended '20050707154139' to root of TOC.
Appended '20050707154203' to root of TOC.
Appended '20050707154224' to root of TOC.
Appended '20050707154251' to root of TOC.
Appended '20050707154318' to root of TOC.
Appended '20050707154345' to root of TOC.
Appended '20050707154408' to root of TOC.
Appended '20050707154435' to root of TOC.
Appended '20050707154454' to root of TOC.
Appended '20050707154512' to root of TOC.
Appended '20050707154535' to root of TOC.
Appended '20050707154554' to root of TOC.
Appended '20050707154621' to root of TOC.
Appended '20050707154700' to root of TOC.
Appended '20050707154725' to root of TOC.
Appended '20050707154750' to root of TOC.
Appended '20050707154813' to root of TOC.
Appended '20050707154830' to root of TOC.
Appended '20050707154855' to root of TOC.
Appended '20050707154914' to root of TOC.
Appended '20050707154933' to root of TOC.
Appended '20050707154951' to root of TOC.
Appended '20050707155022' to root of TOC.
Appended '20050707155047' to root of TOC.
Appended '20050707155113' to root of TOC.
Appended '20050707155138' to root of TOC.
Appended '20050707155201' to root of TOC.
Appended '20050707155223' to root of TOC.
Appended '20050707155252' to root of TOC.
Appended '20050907142710' to root of TOC.
Appended '20050907142912' to root of TOC.
Appended '20050907142923' to root of TOC.
Appended '20050907142946' to root of TOC.
Appended '20050907224146' to root of TOC.
Appended '20050909234204' to root of TOC.
Appended '20050921193712' to root of TOC.
Appended '20051017092741' to root of TOC.
Appended '20051018151053' to root of TOC.
Appended '20051109100225' to root of TOC.
Appended '20051109151827' to root of TOC.
Appended '20051109171407' to root of TOC.
Appended '20051115165621' to root of TOC.
Appended '20051115170522' to root of TOC.
Appended '20051115170646' to root of TOC.
Appended '20051202095223' to root of TOC.
Appended '20051202095733' to root of TOC.
Appended '20051212100658' to root of TOC.
Appended '20051213151150' to root of TOC.
Appended '20051218111846' to root of TOC.
Appended '20051218112106' to root of TOC.
Appended '20051219194650' to root of TOC.
Appended '20060119101546' to root of TOC.
Appended '20060312231902' to root of TOC.
Appended '20060312232030' to root of TOC.
Appended '20060312232059' to root of TOC.
Appended '20060326144002' to root of TOC.
Appended '20060414124043' to root of TOC.
Appended '20060415134453' to root of TOC.
Appended '20060417095918' to root of TOC.
Appended '20060418213437' to root of TOC.
Appended '20060418213552' to root of TOC.
Appended '20060418213608' to root of TOC.
Appended '20060418213650' to root of TOC.
Appended '20060418213757' to root of TOC.
Appended '20060418214035' to root of TOC.
Appended '20060418214059' to root of TOC.
Appended '20060516162139' to root of TOC.
Appended '20060519001423' to root of TOC.
Appended '20060528120032' to root of TOC.
Appended '20060529155646' to root of TOC.
Appended '20060529155724' to root of TOC.
Appended '20060529204216' to root of TOC.
Appended '20060530122115' to root of TOC.
Appended '20060605145328' to root of TOC.
Appended '20060713095700' to root of TOC.
Appended '20060724131349' to root of TOC.
Appended '20060802151635' to root of TOC.
Appended '20060821173520' to root of TOC.
Appended '20060829112631' to root of TOC.
Appended '20060830160324' to root of TOC.
Appended '20060901142310' to root of TOC.
Appended '20060918140549' to root of TOC.
Appended '20060918230717' to root of TOC.
Appended '20060925155312' to root of TOC.
Appended '20060928102543' to root of TOC.
Appended '20061019151624' to root of TOC.
Appended '20061022113506' to root of TOC.
Appended '20061107235740' to root of TOC.
Appended '20061113173249' to root of TOC.
Appended '20061117134127' to root of TOC.
Appended '20061124171108' to root of TOC.
Appended '20061124173406' to root of TOC.
Appended '20061129160200' to root of TOC.
Appended '20061214093526' to root of TOC.
Appended '20070124014548' to root of TOC.
Appended '20070128205657' to root of TOC.
Appended '20070128205840' to root of TOC.
Appended '20070128205925' to root of TOC.
Appended '20070128210033' to root of TOC.
Appended '20070128210134' to root of TOC.
Appended '20070128210302' to root of TOC.
Appended '20070128211057' to root of TOC.
Appended '20070129185750' to root of TOC.
Appended '20070131122918' to root of TOC.
Appended '20070131160044' to root of TOC.
Appended '20070203093410' to root of TOC.
Appended '20070203093951' to root of TOC.
Appended '20070203095844' to root of TOC.
Appended '20070203113032' to root of TOC.
Appended '20070208124024' to root of TOC.
Appended '20070214105123' to root of TOC.
Appended '20070215211913' to root of TOC.
Appended '20070216164640' to root of TOC.
Appended '20070309172012' to root of TOC.
Appended '20070331002130' to root of TOC.
Appended '20070331165114' to root of TOC.
Appended '20070402134938' to root of TOC.
Appended '20070402135824' to root of TOC.
Appended '20070421103046' to root of TOC.
Appended '20070426230437' to root of TOC.
Appended '20070515235824' to root of TOC.
Appended '20070530212712' to root of TOC.
Appended '20070906135214' to root of TOC.
Appended '20070910172507' to root of TOC.
Appended '20070910172555' to root of TOC.
Appended '20070910172624' to root of TOC.
Appended '20070910172649' to root of TOC.
Appended '20071016165241' to root of TOC.
Appended '20071017143610' to root of TOC.
Appended '20071122164301' to root of TOC.
Appended '20071122164434' to root of TOC.
Appended '20071202012106' to root of TOC.
Appended '20071202201559' to root of TOC.
Appended '20071213091143' to root of TOC.
Appended '20071225155138' to root of TOC.
Appended '20071225233932' to root of TOC.
Appended '20080109160746' to root of TOC.
Appended '20080109160832' to root of TOC.
Appended '20080109160905' to root of TOC.
Appended '20080109164952' to root of TOC.
Appended '20080111001528' to root of TOC.
Appended '20080116091208' to root of TOC.
Appended '20080204175249' to root of TOC.
Appended '20080213160229' to root of TOC.
Appended '20080213160350' to root of TOC.
Appended '20080314164728' to root of TOC.
Appended '20080314165053' to root of TOC.
Appended '20080314170029' to root of TOC.
Appended '20080314170131' to root of TOC.
Appended '20080314171836' to root of TOC.
Appended '20080325151731' to root of TOC.
Appended '20080401171804' to root of TOC.
Appended '20080407104417' to root of TOC.
Appended '20080418220937' to root of TOC.
Appended '20080418235716' to root of TOC.
Appended '20080505133817' to root of TOC.
Appended '20080506152720' to root of TOC.
Appended '20080522203316' to root of TOC.
Appended '20080522213800' to root of TOC.
Appended '20080529210711' to root of TOC.
Appended '20080529211944' to root of TOC.
Appended '20080603113747' to root of TOC.
Appended '20080604000437' to root of TOC.
Appended '20080626210559' to root of TOC.
Appended '20080708171330' to root of TOC.
Appended '20080801114826' to root of TOC.
Appended '20080808161231' to root of TOC.
Appended '20080827132951' to root of TOC.
Appended '20080827133018' to root of TOC.
Appended '20080827133036' to root of TOC.
Appended '20080827133052' to root of TOC.
Appended '20080827133115' to root of TOC.
Appended '20080827133137' to root of TOC.
Appended '20080827133156' to root of TOC.
Appended '20080827133229' to root of TOC.
Appended '20080827133311' to root of TOC.
Appended '20080923165409' to root of TOC.
Appended '20081006114239' to root of TOC.
Appended '20081007113459' to root of TOC.
Appended '20081008152604' to root of TOC.
Appended '20081026222949' to root of TOC.
Appended '20081031150425' to root of TOC.
Appended '20081216202420' to root of TOC.
Appended '20090105155245' to root of TOC.
Appended '20090105155337' to root of TOC.
Appended '20090106094019' to root of TOC.
Appended '20090226160019' to root of TOC.
Appended '20090321234039' to root of TOC.
Appended '20090421202128' to root of TOC.
Appended '20090422151546' to root of TOC.
Appended '20090505102213' to root of TOC.
Appended '20090515134736' to root of TOC.
Appended '20090702173810' to root of TOC.
Appended '20090705234407' to root of TOC.
Appended '20090712152547' to root of TOC.
Appended '20090816122923' to root of TOC.
Appended '20090821100828' to root of TOC.
Appended '20090822000116' to root of TOC.
Appended '20090920170929' to root of TOC.
Appended '20090924111306' to root of TOC.
Appended '20091004105809' to root of TOC.
Appended '20091004111308' to root of TOC.
Appended '20091007225023' to root of TOC.
Appended '20091022144009' to root of TOC.
Appended '20091027100906' to root of TOC.
Appended '20091030141227' to root of TOC.
Appended '20091103224303' to root of TOC.
Appended '20091129231940' to root of TOC.
Appended '20091205154135' to root of TOC.
Appended '20091205154225' to root of TOC.
Appended '20091219235817' to root of TOC.
Appended '20100104085745' to root of TOC.
Appended '20100128092928' to root of TOC.
Appended '20100201160925' to root of TOC.
Appended '20100208195733' to root of TOC.
Appended '20100216230750' to root of TOC.
Appended '20100219171625' to root of TOC.
Appended '20100312120730' to root of TOC.
Appended '20100402090055' to root of TOC.
Appended '20100403211340' to root of TOC.
Appended '20100405191054' to root of TOC.
Appended '20100409120011' to root of TOC.
Appended '20100409132834' to root of TOC.
Appended '20100505104840' to root of TOC.
Appended '20100505111007' to root of TOC.
Appended '20100604104031' to root of TOC.
Appended '20100625163912' to root of TOC.
Appended '20100625163939' to root of TOC.
Appended '20100705093955' to root of TOC.
Appended '20100729120352' to root of TOC.
Appended '20100801132101' to root of TOC.
Appended '20100808220650' to root of TOC.
Appended '20101005091439' to root of TOC.
Appended '20101005232538' to root of TOC.
Appended '20101016190319' to root of TOC.
Appended '20101021192749' to root of TOC.
Appended '20101223105201' to root of TOC.
Appended '20101223105740' to root of TOC.
Appended '20101223105810' to root of TOC.
Appended '20101223105901' to root of TOC.
Appended '20101223110207' to root of TOC.
Appended '20101223110334' to root of TOC.
Appended '20101224213550' to root of TOC.
Appended '20101229113745' to root of TOC.
Appended '20110103211112' to root of TOC.
Appended '20110106142101' to root of TOC.
Appended '20110109213852' to root of TOC.
Appended '20110110173440' to root of TOC.
Appended '20110112135737' to root of TOC.
Appended '20110112230309' to root of TOC.
Appended '20110121091343' to root of TOC.
Appended '20110121091458' to root of TOC.
Appended '20110123000259' to root of TOC.
Appended '20110123211955' to root of TOC.
Appended '20110224091124' to root of TOC.
Appended '20110302132602' to root of TOC.
Appended '20110308092048' to root of TOC.
Appended '20110325171915' to root of TOC.
Appended '20110330142114' to root of TOC.
Appended '20110330172928' to root of TOC.
Appended '20110330221107' to root of TOC.
Appended '20110401154601' to root of TOC.
Appended '20110406215852' to root of TOC.
Appended '20110412172348' to root of TOC.
Appended '20110412205323' to root of TOC.
Appended '20110608094705' to root of TOC.
Appended '20110611151341' to root of TOC.
Appended '20110611230047' to root of TOC.
Appended '20110614164625' to root of TOC.
Appended '20110617150704' to root of TOC.
Appended '20110623152310' to root of TOC.
Appended '20110623152655' to root of TOC.
Appended '20110704230520' to root of TOC.
Appended '20110812172024' to root of TOC.
Appended '20110826100946' to root of TOC.
Appended '20110829110252' to root of TOC.
Appended '20110904093329' to root of TOC.
Appended '20110930173921' to root of TOC.
Appended '20111121150917' to root of TOC.
Appended '20111206144647' to root of TOC.
Appended '20111210213952' to root of TOC.
Appended '20111213143138' to root of TOC.
Appended '20111213143159' to root of TOC.
Appended '20111216112443' to root of TOC.
Appended '20111218102446' to root of TOC.
Appended '20111220132235' to root of TOC.
Appended '20111220141507' to root of TOC.
Appended '20111229100610' to root of TOC.
Appended '20111229102453' to root of TOC.
Appended '20111229120632' to root of TOC.
Appended '20120106162356' to root of TOC.
Appended '20120111161239' to root of TOC.
Appended '20120112101005' to root of TOC.
Appended '20120130151301' to root of TOC.
Appended '20120203174321' to root of TOC.
Appended '20120218104758' to root of TOC.
Appended '20120331203318' to root of TOC.
Appended '20120506144311' to root of TOC.
Appended '20120510095047' to root of TOC.
Appended '20120515235838' to root of TOC.
Appended '20120816104451' to root of TOC.
Appended '20120816122611' to root of TOC.
Appended '20120912174007' to root of TOC.
Appended '20120926171606' to root of TOC.
Appended '20121010121958' to root of TOC.
Appended '20121012224956' to root of TOC.
Appended '20121012225035' to root of TOC.
Appended '20121012225059' to root of TOC.
Appended '20121203161813' to root of TOC.
Appended '20121209002035' to root of TOC.
Appended '20130427221546' to root of TOC.
Appended '20130517134623' to root of TOC.
Appended '20130604152755' to root of TOC.
Appended '20130614111349' to root of TOC.
Appended '20130821154121' to root of TOC.
Appended '20130823011427' to root of TOC.
Appended '20130826134452' to root of TOC.
Appended '20131210220658' to root of TOC.
Appended '20131212205248' to root of TOC.
Appended '20131216151925' to root of TOC.
Appended '20140110163017' to root of TOC.
Appended '20140712191428' to root of TOC.
Appended '20140712191606' to root of TOC.
Appended '20140815233911' to root of TOC.
Appended '20140817153158' to root of TOC.
Appended '20141214224444' to root of TOC.
Appended '20141214224523' to root of TOC.
Appended '20141214224550' to root of TOC.
Appended '20141214224625' to root of TOC.
Appended '20141214224653' to root of TOC.
Appended '20150130140224' to root of TOC.
Appended '20150530204145' to root of TOC.
Appended '20160221190230' to root of TOC.
Inspecting favicons...
Checking for created and updated files...
Generating fulltext cache...
Creating cache for '20050909234204'...
Creating cache for '20061019151624'...
Creating cache for '20080213160229'...
Creating cache for '20101016190319'...
Creating cache for '20130826134452'...
Creating cache for '20080827132951'...
Creating cache for '20080401171804'...
Creating cache for '20080109160832'...
Creating cache for '20050707155047'...
Creating cache for '20080603113747'...
Creating cache for '20090106094019'...
Creating cache for '20050707154318'...
Creating cache for '20051018151053'...
Creating cache for '20111210213952'...
Creating cache for '20110109213852'...
Creating cache for '20071122164434'...
Creating cache for '20060414124043'...
Creating cache for '20060415134453'...
Creating cache for '20060802151635'...
Creating cache for '20060529155724'...
Creating cache for '20070128210302'...
Creating cache for '20101223105201'...
Creating cache for '20110121091458'...
Creating cache for '20050907142946'...
Creating cache for '20120106162356'...
Creating cache for '20061117134127'...
Creating cache for '20060418214059'...
Creating cache for '20080604000437'...
Creating cache for '20051017092741'...
Creating cache for '20100201160925'...
Creating cache for '20050707154830'...
Creating cache for '20091219235817'...
Creating cache for '20110106142101'...
Creating cache for '20080808161231'...
Creating cache for '20091030141227'...
Creating cache for '20060519001423'...
Creating cache for '20140110163017'...
Creating cache for '20051115170522'...
Creating cache for '20080109160905'...
Creating cache for '20050707154933'...
Creating cache for '20130823011427'...
Creating cache for '20050921193712'...
Creating cache for '20080505133817'...
Creating cache for '20090515134736'...
Creating cache for '20130614111349'...
Creating cache for '20050707154408'...
Creating cache for '20141214224653'...
Creating cache for '20051109171407'...
Creating cache for '20060529155646'...
Creating cache for '20090920170929'...
Creating cache for '20090421202128'...
Creating cache for '20070214105123'...
Creating cache for '20080923165409'...
Creating cache for '20090105155245'...
Creating cache for '20060713095700'...
Creating cache for '20110412205323'...
Creating cache for '20081216202420'...
Creating cache for '20120912174007'...
Creating cache for '20070426230437'...
Creating cache for '20080213160350'...
Creating cache for '20111213143138'...
Creating cache for '20110330142114'...
Creating cache for '20050707154120'...
Creating cache for '20120515235838'...
Creating cache for '20080827133115'...
Creating cache for '20070128210033'...
Creating cache for '20111220141507'...
Creating cache for '20080522203316'...
Creating cache for '20070402135824'...
Creating cache for '20090822000116'...
Creating cache for '20070910172555'...
Creating cache for '20110826100946'...
Creating cache for '20101223110207'...
Creating cache for '20060418213608'...
Creating cache for '20070906135214'...
Creating cache for '20100625163912'...
Creating cache for '20050707154203'...
Creating cache for '20140712191606'...
Creating cache for '20070208124024'...
Creating cache for '20060312232059'...
Creating cache for '20051115170646'...
Creating cache for '20060228105149'...
Creating cache for '20110406215852'...
Creating cache for '20060918140549'...
Creating cache for '20120506144311'...
Creating cache for '20050707154435'...
Creating cache for '20080314171836'...
Creating cache for '20070402134938'...
Creating cache for '20100505104840'...
Creating cache for '20110930173921'...
Creating cache for '20121010121958'...
Creating cache for '20070203095844'...
Creating cache for '20050907224146'...
Creating cache for '20050707155201'...
Creating cache for '20090105155337'...
Creating cache for '20080522213800'...
Creating cache for '20110103211112'...
Creating cache for '20090821100828'...
Creating cache for '20051218112106'...
Creating cache for '20050707154951'...
Creating cache for '20110608094705'...
Creating cache for '20060312232030'...
Creating cache for '20060418213650'...
Creating cache for '20070215211913'...
Creating cache for '20141214224625'...
Creating cache for '20131212205248'...
Creating cache for '20130517134623'...
Creating cache for '20090226160019'...
Creating cache for '20080111001528'...
Creating cache for '20080801114826'...
Creating cache for '20110401154601'...
Creating cache for '20120926171606'...
Creating cache for '20061124171108'...
Creating cache for '20091004111308'...
Creating cache for '20070309172012'...
Creating cache for '20121012225035'...
Creating cache for '20061124173406'...
Creating cache for '20060418214035'...
Creating cache for '20060821173520'...
Creating cache for '20080827133229'...
Creating cache for '20050707154512'...
Creating cache for '20071213091143'...
Creating cache for '20070910172507'...
Creating cache for '20101224213550'...
Creating cache for '20050707153846'...
Creating cache for '20091205154135'...
Creating cache for '20100604104031'...
Creating cache for '20110829110252'...
Creating cache for '20050707154621'...
Creating cache for '20110330221107'...
Creating cache for '20091103224303'...
Creating cache for '20070331002130'...
Creating cache for '20141214224550'...
Creating cache for '20141214224523'...
Creating cache for '20080314170029'...
Creating cache for '20100705093955'...
Creating cache for '20110617150704'...
Creating cache for '20130604152755'...
Creating cache for '20060925155312'...
Creating cache for '20080116091208'...
Creating cache for '20120510095047'...
Creating cache for '20080827133156'...
Creating cache for '20080827133052'...
Creating cache for '20090505102213'...
Creating cache for '20050707155223'...
Creating cache for '20050707153919'...
Creating cache for '20071016165241'...
Creating cache for '20051202095733'...
Creating cache for '20080708171330'...
Creating cache for '20130427221546'...
Creating cache for '20100312120730'...
Creating cache for '20101229113745'...
Creating cache for '20110112135737'...
Creating cache for '20050707153828'...
Creating cache for '20060326144002'...
Creating cache for '20100208195733'...
Creating cache for '20080407104417'...
Creating cache for '20050907142912'...
Creating cache for '20060418213437'...
Creating cache for '20110614164625'...
Creating cache for '20081031150425'...
Creating cache for '20070203113032'...
Creating cache for '20051109151827'...
Creating cache for '20111229120632'...
Creating cache for '20080529210711'...
Creating cache for '20100801132101'...
Creating cache for '20090321234039'...
Creating cache for '20050707154700'...
Creating cache for '20091007225023'...
Creating cache for '20120203174321'...
Creating cache for '20080827133137'...
Creating cache for '20100505111007'...
Creating cache for '20070131122918'...
Creating cache for '20081007113459'...
Creating cache for '20051109100225'...
Creating cache for '20110330172928'...
Creating cache for '20091027100906'...
Creating cache for '20111206144647'...
Creating cache for '20081008152604'...
Creating cache for '20050707154914'...
Creating cache for '20100808220650'...
Creating cache for '20110623152655'...
Creating cache for '20100409120011'...
Creating cache for '20070129185750'...
Creating cache for '20060830160324'...
Creating cache for '20111229102453'...
Creating cache for '20051218111846'...
Creating cache for '20110611151341'...
Creating cache for '20080314170131'...
Creating cache for '20050707154750'...
Creating cache for '20111213143159'...
Creating cache for '20111220132235'...
Creating cache for '20140712191428'...
Creating cache for '20051212100658'...
Creating cache for '20050707155252'...
Creating cache for '20061107235740'...
Creating cache for '20060312231902'...
Creating cache for '20050907142923'...
Creating cache for '20050707154224'...
Creating cache for '20080109160746'...
Creating cache for '20071017143610'...
Creating cache for '20110302132602'...
Creating cache for '20141214224444'...
Creating cache for '20081006114239'...
Creating cache for '20090702173810'...
Creating cache for '20050707154345'...
Creating cache for '20070128210134'...
Creating cache for '20060207222845'...
Creating cache for '20071202201559'...
Creating cache for '20100729120352'...
Creating cache for '20131216151925'...
Creating cache for '20060119101546'...
Creating cache for '20130821154121'...
Creating cache for '20080314165053'...
Creating cache for '20100403211340'...
Creating cache for '20110812172024'...
Creating cache for '20110110173440'...
Creating cache for '20100625163939'...
Creating cache for '20061022113506'...
Creating cache for '20060829112631'...
Creating cache for '20110224091124'...
Creating cache for '20060918230717'...
Creating cache for '20140817153158'...
Creating cache for '20150130140224'...
Creating cache for '20071122164301'...
Creating cache for '20130704220929'...
Creating cache for '20071202012106'...
Creating cache for '20060418213552'...
Creating cache for '20091205154225'...
Creating cache for '20080109164952'...
Creating cache for '20110325171915'...
Creating cache for '20050707154725'...
Creating cache for '20121012225059'...
Creating cache for '20051115165621'...
Creating cache for '20120218104758'...
Creating cache for '20091022144009'...
Creating cache for '20060605145328'...
Creating cache for '20070331165114'...
Creating cache for '20050707155022'...
Creating cache for '20140815233911'...
Creating cache for '20051219194650'...
Creating cache for '20090816122923'...
Creating cache for '20060901142310'...
Creating cache for '20090422151546'...
Creating cache for '20070515235824'...
Creating cache for '20121209002035'...
Creating cache for '20100128092928'...
Creating cache for '20120112101005'...
Creating cache for '20071225233932'...
Creating cache for '20110308092048'...
Creating cache for '20101223110334'...
Creating cache for '20070910172649'...
Creating cache for '20080827133036'...
Creating cache for '20120816122611'...
Creating cache for '20101005091439'...
Creating cache for '20100104085745'...
Creating cache for '20101223105810'...
Creating cache for '20100409132834'...
Creating cache for '20090924111306'...
Creating cache for '20110611230047'...
Creating cache for '20070203093410'...
Creating cache for '20050707154454'...
Creating cache for '20070910172624'...
Creating cache for '20080314164728'...
Creating cache for '20110904093329'...
Creating cache for '20120816104451'...
Creating cache for '20050707153750'...
Creating cache for '20070203093951'...
Creating cache for '20111121150917'...
Creating cache for '20080325151731'...
Creating cache for '20071225155138'...
Creating cache for '20050707155113'...
Creating cache for '20160221190230'...
Creating cache for '20050707154251'...
Creating cache for '20110623152310'...
Creating cache for '20120130151301'...
Creating cache for '20070128205925'...
Creating cache for '20050907142710'...
Creating cache for '20070128205657'...
Creating cache for '20090712152547'...
Creating cache for '20100219171625'...
Creating cache for '20070530212712'...
Creating cache for '20060417095918'...
Creating cache for '20091004105809'...
Creating cache for '20080529211944'...
Creating cache for '20080204175249'...
Creating cache for '20050707154535'...
Creating cache for '20120111161239'...
Creating cache for '20100402090055'...
Creating cache for '20101223105901'...
Creating cache for '20051213151150'...
Creating cache for '20051202095223'...
Creating cache for '20110112230309'...
Creating cache for '20070216164640'...
Creating cache for '20050707153939'...
Creating cache for '20101005232538'...
Creating cache for '20110123000259'...
Creating cache for '20070128211057'...
Creating cache for '20080418220937'...
Creating cache for '20061113173249'...
Creating cache for '20120331203318'...
Creating cache for '20110412172348'...
Creating cache for '20100216230750'...
Creating cache for '20060530122115'...
Creating cache for '20050707154855'...
Creating cache for '20050707154554'...
Creating cache for '20080418235716'...
Creating cache for '20081026222949'...
Creating cache for '20091129231940'...
Creating cache for '20111218102446'...
Creating cache for '20061214093526'...
Creating cache for '20111216112443'...
Creating cache for '20111229100610'...
Creating cache for '20060529204216'...
Creating cache for '20110123211955'...
Creating cache for '20100405191054'...
Creating cache for '20110704230520'...
Creating cache for '20080626210559'...
Creating cache for '20080506152720'...
Creating cache for '20121203161813'...
Creating cache for '20060724131349'...
Creating cache for '20070124014548'...
Creating cache for '20060928102543'...
Creating cache for '20050707154015'...
Creating cache for '20050707153958'...
Creating cache for '20080827133311'...
Creating cache for '20050707154813'...
Creating cache for '20101223105740'...
Creating cache for '20101021192749'...
Creating cache for '20060418213757'...
Creating cache for '20050707154139'...
Creating cache for '20150530204145'...
Creating cache for '20070128205840'...
Creating cache for '20061129160200'...
Creating cache for '20060516162139'...
Creating cache for '20131210220658'...
Creating cache for '20060528120032'...
Creating cache for '20070131160044'...
Creating cache for '20080827133018'...
Creating cache for '20110121091343'...
Creating cache for '20050707155138'...
Creating cache for '20090705234407'...
Creating cache for '20070421103046'...
Creating cache for '20121012224956'...
Generating zip file...
If the download doesn't start, click me.
Done.

Time spent: 15.063 seconds.
`

**Comment by danny0838** [comment]
It seems that your scrapbook.rdf records does not match your data files. For example, 20060829112625 and 20110829110228 are recorded in scrapbook.rdf but corresponding data files are missing. On the other hand, 20050707153750 and 20050707153828 are in the 'data' directory but not recorded in the scrapbook.rdf file. It may be that your scrapbook.rdf be corrupted due to some reason, or you have done something wrong during the import.

Here are some hints that may help further investigation:
1. Provide the name and version of your OS, browser, and legacy ScrapBook addon you have been using.
2. Check if your original scrapbook data folder is all right. And try running sidebar > tools > calcation of size using your legacy ScrapBook Addon and see if there's any error reported.
3. Run the [import steps](https://github.com/danny0838/webscrapbook/wiki/Import) ([Chinese version](https://github.com/danny0838/webscrapbook/wiki/(zh-tw)Import) also available) **without step 1, 2, and 7**. That is, directly drag your original scrapbook folder to the site indexer, and see if the generated index is correct.

**Comment by RuralHunter** [comment]
1. Win10 64bit, Firefox 72.0.1(64bit), ScrapBook 1.5.14
2. Can not do this since ScrapBook is not supported in Firefox new versions.
3. The result is same. 
I tried another addon Scrapyard and it can import ScrapBook data correctly.

**Comment by danny0838** [comment]
That's odd. Could you provide your scrapbook.rdf? (You can pack it in a zip file and drag to upload here.)

**Comment by RuralHunter** [comment]
Here it is:
[scrapbook.zip](https://github.com/danny0838/webscrapbook/files/4062729/scrapbook.zip)

**Comment by danny0838** [comment]
Thank you. It seems that your scrapbook.rdf is using an unexpected namespace ("NS2" rather than "NS1")  due to an unknown reason, causing the site indexer failed to read the metadata. We've added a patch to deal with such case. Please install 0.58.1 and check if the issue is resolved.

**Comment by RuralHunter** [comment]
It works. Thanks a lot for the quick fix!
