### ISSUE TITLE
webscrapbook扩展有计划支持保存为其他格式吗？如markdown格式

### ISSUE THREAD

**Issue by hhaoao** [danny0838/webscrapbook#133]
浏览器：`firefox 72.0.1 (64 位)`

我看了readme貌似可用markdown编写笔记，但我保存后发现并没有反应(还是文本)，保存的格式也只能是html格式。中文文档wiki则没有相关内容。

**Comment by danny0838** [comment]
目前沒有，因為除了 HTML （或壓縮形式的 MAFF、HTZ）以外目前找不到可完整保存原貌的格式。如果您有建議的格式可提出來，我們再評估看看。

用 markdown 編寫筆記是有支援的，首先要先安裝後端伺服器，然後從側欄工具欄的 [新增筆記] 就能用 markdown 編寫筆記。

**Comment by fygul** [comment]
FYI: [joplin](https://github.com/laurent22/joplin) with its web-clipper

**Comment by hhaoao** [comment]
@danny0838 喔哦，原来倾向于保护原来的格式，一百个网站有一百种排版风格，我个人觉得统一为相同样式阅读体验会更好,一般来说，有记笔记习惯的人都有自己的笔记管理工具，就缺个把网页变为自己喜欢的文件格式的工具。我找了很多插件像`markdown-clipper`都是只能直接下载，无法剪裁网页和下载图片等资源文件，webscrapbook只缺个输出markdown格式就完美符合我的要求。
    如果webscrapbook扩展很好改动的话我自己想试试能不能结合html to markdown的库加上这个功能。

**Comment by hhaoao** [comment]
@fygul This extension relies on the joplin tool, I don't like this.

**Comment by fygul** [comment]
@hhaoao
我沒寫清楚，容許我補充一下：那個web-clipper是要給 @danny0838 做參考的。
它可存成markdown 格式，不過是儲進資料庫中；圖片則是集中在同一資料夾中。

我自己個人對 joplin 目前的儲存方式也不怎麼滿意，不過它的主要設計是做筆記簿之類的用途，擷取網頁只是它的選項功能而已。這兩種功能，我已習慣用其他軟體了，我也沒採用joplin。

**Comment by danny0838** [comment]
@hhaoao 有人寫了 [Maoxian web clipper](https://mika-cn.github.io/maoxian-web-clipper/index-zh-CN.html) 支援把網頁擷取成 Markdown，你可以試試。不過我自己試用的感想是對於稍微複雜的頁面，基本上完全無法可靠地處理，根本原因是 Markdown 支援的格式遠少於 HTML（雖然 Markdown 允許內嵌 HTML，但能內嵌的子集各家支援不一），而遇到不支援的格式應該怎麼轉寫，可能性有無窮多種，我們就算做了也未必符合你的需求，就算符合你的需求也未必符合其他人的需求。

WebScrapBook 主要還是著重在保存網頁原貌，至於其他輸出方式，未來可找大牛發明專門的轉檔程式（例如傳統 ScrapBook X 就一律儲存成資料夾，另外有[轉換器](https://github.com/danny0838/firefox-scrapbook-converter)可以轉存成 MAFF、EPUB、單一 HTML、Evernote 等等）。事實上我們還在考慮取消支援儲存成單一網頁，原因就是不保真，要是哪天使用者後悔了就沒輒；而如果是儲存成網頁（或可完全互轉的 HTZ、MAFF）加上轉檔程式的方式，未來想怎麼轉都還可以選擇。

**Comment by hhaoao** [comment]
非常非常感谢，`Maoxian web clipper`正是我需要的。我选择`markdown`格式的原因就是它足够精简，不用费心思关注复杂样式，对于复杂页面，比如[bilibili](https://www.bilibili.com/)`番剧`表,周一至周日中的内容，就没有多好的方式处理，面对这种情况我想最好的方式就是用[HTTrack](www.httrack.com)设置规则擷取。
正如你所说，`WebScrapBook `正因为保存了网页原貌，输出格式有很大的操作空间，能转任意格式。最后，希望能發明轉檔程式的大牛及时出现。

**Comment by fygul** [comment]
@hhaohao
若對轉檔程式有興趣的話，可看一下 [pandoc](https://pandoc.org/)
