### ISSUE TITLE
Fatal error: Unable to invoke unknown command 'capturer.captureDocumentOrFile'.

### ISSUE THREAD

**Issue by qdinar** [danny0838/webscrapbook#134]
> Fatal error: Unable to invoke unknown command 'capturer.captureDocumentOrFile'.

seems this error appears on all pages. for example, https://en.wikipedia.org/wiki/Main_Page .
ff 68.4.1esr (32-bit)
debian 10 32 bit
wsb 0.60.0

**Comment by eugeny54** [comment]
Confirm this.
In Web-Console(F12) appears:
"Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://b55174e6-35f9-431d-84d6-a6c82f3621a4/lib/browser-polyfill.js
Source Map URL: browser-polyfill.js.map" and points to https://developer.mozilla.org/en-US/docs/Tools/Debugger/Source_map_errors
Firefox 72.0.2 (x64) Win7 with WebScrapBook 0.60.0

**Comment by danny0838** [comment]
Firefox implements an unexpected sandbox mechanism causing this issue. v0.60.1 should have fixed it.
