### ISSUE TITLE
clicking firefox main windows does not make saving report move below, in linux

### ISSUE THREAD

**Issue by qdinar** [danny0838/webscrapbook#135]
in windows, as i remember, i used to click page, and saving report window was going under the firefox, i used this to not have it hindering to see the page. but in debian 10 xfce and linux mint 19 cinnamon, it does not go below firefox, it stays on top.

**Comment by danny0838** [comment]
WSB does not explicitly set focus of the capturer window and it's mainly controlled by the browser. This may be an issue of Firefox itself and should be reported to Firefox developers.

Unfortunately I don't have the environment described above to test and confirm. You may have to report by yourself. If there's a difficult and you need some help, you can provide the version of your WSB, Firefox, and OS, and short videos (or screenshot series) to illustrate the problematic behavior and the normal behavior on another browser/OS.

**Comment by danny0838** [comment]
FYI: You can check the "Auto-close dialog when capture succeeded" option, which may do some help.

**Comment by qdinar** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1612413

**Comment by danny0838** [comment]
Thank you. Seeing the recent comment it seems to be an issue of Firefox on Linux. We close this issue as it's due to Firefox, and should be followed in Bugzilla.
