### ISSUE TITLE
meta refresh tag makes page broken

### ISSUE THREAD

**Issue by qdinar** [danny0838/webscrapbook#136]
when i saved a google results page, and tried to open it, it redirects to a "file not found" page, with "file:" in address bar. the saved file has `<meta content="0;url=/search?q=linux&amp;......" http-equiv="refresh">` in it. i think it causes it.

**Comment by danny0838** [comment]
What is the web page URL you are trying to capture?

**Comment by qdinar** [comment]
try any google results page. but, i think, problem with it appears only with scripts disabled for file:// by noscript addon. because the meta html tag is in noscript html tag. just save it (for example https://www.google.com/search?q=123 ), look for html source of saved file, search for "meta" and you should see it.

**Comment by qdinar** [comment]
i tried it and see no problem. this time i was logged in. problem was when i searched logged out, from private window.

**Comment by danny0838** [comment]
I' confused with your description. Could you provide a **minimal, complete, and verifiable example**?

- What is your OS, browser, and WSB version?
- Is it required that NoScript extension be installed to trigger the issue?
- Is it required that you don't log in Google account to trigger the issue? (Or Firefox sync account?)
- Is it required that you visit the page in private window to trigger the issue?

**Comment by qdinar** [comment]
making minimal example was harder and worthless than reporting this way...

1. "normal" fresh versions, they should all be similar. i think this should be understood by default...

2. noscript is just a tool to disable scripts... i think, "noscript" tag is triggered by browser, because, as i know, this tag was initially designed for browsers which do not run scripts at all. probably ff gets info from noscript and behaves like a no script browser and enables noscript tag content.

wsb already does not save scripts. so, scripts should be like disabled even when scripts are enabled. i have become doubtful, and i have made 1 more experiment... i tried to open the file after enabling scripts with nosript for the local files. and it works, as i expected...

3, 4. private window was just a tool to be logged out. seems google has the noscript tag for logged out users, and does not has it for logged in users. and probably that tag it is saved as it is. same problem appears also with ff's own "save as html only", not only with wsb.

**Comment by qdinar** [comment]
to say more correctly, the file itself is not broken, but it meta refresh tag makes redirection, but that target url, in this case it starts with / , ie refers to same domain, when it is opened normally from internet, does not exist on the local computer "file:" space. it can be considered a google bug, assuming they should care about how their pages are saved, but wsb also can fix it, by removing or disabling meta refresh elements.

**Comment by qdinar** [comment]
and i saved google page with scripts enabled. i think i did not say about this because this is default.

**Comment by qdinar** [comment]
i tried to make a minimal example. open https://jsbin.com/goyodifuwo and save it. then install noscript and if you have scripts enabled for file://, in noscript settings, remove that permission. then open the saved file. it should show "OK" but it will redirect to and show "/" directory listing in linux. i do not know what does it show on windows.

**Comment by danny0838** [comment]
This issue can be reduced to: viewing the captured version of a web page having a `meta` refresh element in a `noscript` element with JavaScript disabled causes a redirect.

This is not something we can fix easily because it is the design of the web page, and removing either the noscript or the meta element could harm faithfulness. We may consider adding options for them, but a careful design is required to prevent trivial options.

For now, you can use the "preclude elements" option to exclude unwanted elements. For example, `noscript` or `meta[http-equiv~="refresh"]` will do the job.

Also, there's a bug that the meta refresh of the captured page is broken, as it should target the original google search page instead. We have released 0.61.1 to fix it.

**Comment by danny0838** [comment]
We decided not to implement further ad hoc feature for this issue. Write a site-specific capture helper to remove page elements like `noscript meta[http-equiv="refresh"i]` if there's a need.
