### ISSUE TITLE
how "Access browsing history" and "Access browser activity during navigation" permissions are used?

### ISSUE THREAD

**Issue by qdinar** [danny0838/webscrapbook#137]
why "Access browsing history" and "Access browser activity during navigation" permissions are needed?

**Comment by danny0838** [comment]
Good question. Maybe we should explain this in detail in the documentation wiki someday.

"Access browsing history" is used to erase history of WebScrapBook pages to prevent generation of unnecessary history entries, and to prevent the user from accidentally invoke a capture by clicking on the history of a capture page. 

"Access browser activity during navigation" is probably the webNavigation API, which is used to access information about frames in a tab—well, it's somehow bizarre for "Access browser activity during navigation" to do this, but the API is designed so.

**Comment by danny0838** [comment]
We are considering removing the "Access browsing history" permission, after we come up with a solution to prevent invoking a capture accidentally, and a re-evaluation whether leaving "capture ..." pages of WSB in the history is appropriate.

**Comment by danny0838** [comment]
Revoked history permission in 0.62.0.
