### ISSUE TITLE
Standalone Archive Viewer

### ISSUE THREAD

**Issue by entone** [danny0838/webscrapbook#138]
Hey just wanted to say thanks for the extension! I put together a small Elixir based system with full text search to view the archive files. Reads everything directly from the zip files.

Check it out here, https://github.com/entone/web_archive_viewer

**Comment by danny0838** [comment]
Thank you. We are glad to see more applications available. Just FYI, we already have [PyWebScrapBook](https://github.com/danny0838/PyWebScrapBook) that supports viewing archive web page through opening directly. It also provides a full protocal to host local scrapbook(s). Just don't reinvent the wheel if you find some feature that is already provided.
