### ISSUE TITLE
"Could not establish connection." error when capturing a page in Firefox Add-Ons site

### ISSUE THREAD

**Issue by qdinar** [danny0838/webscrapbook#139]
while saving
https://addons.mozilla.org/ru/firefox/search/?q=vk.com&platform=Linux&appver=73.0

Capturing (document) [42] https://addons.mozilla.org/ru/firefox/search/?q=vk.com&platform=Linux&appver=73.0 ...
Unable to execute content script ([42:0] https://addons.mozilla.org/ru/firefox/search/?q=vk.com&platform=Linux&appver=73.0): Missing host permission for the tab
Fatal error: Could not establish connection. Receiving end does not exist.

**Comment by danny0838** [comment]
This is restricted by the browser due to security concerns. See [FAQ](https://github.com/danny0838/webscrapbook/wiki/FAQ#why-an-error-always-occur-when-capturing-a-page-in-chrome-web-store-or-firefox-add-ons) for further details.
