### ISSUE TITLE
Twitter Pages Not Saved Completely

### ISSUE THREAD

**Issue by sj365** [danny0838/webscrapbook#140]
Hello,
A recent change to Twitter sometime around January 18, 2020 (based on my last correctly saved twitter webpage) is causing webscapbook to only save a part of the page even after pre-scrolling to ensure all elements/pics/vids are open and visible.  This is true on all current twitter pages.  When you review saved versions take care to use both Chrome and Firefox to view because there is sometimes significant difference how a saved html is displayed with WSB between them.

https://twitter.com/Liz_Wheeler/status/1182389648372355072?s=20

[twitter ex.zip](https://github.com/danny0838/webscrapbook/files/4289843/twitter.ex.zip)

**Comment by danny0838** [comment]
Twitter seems to automatically unload some formerly loaded contents when the user scrolls down. This is designed by the web site and is not something that WSB (and other web page capturing tools) can handle. For this issue you probably need a site-specific userscript to block Twitter's default behavior.

**Comment by sj365** [comment]
thanks for working on this.  Singlefile and Save Page WE were experiencing the same problem with the Twitter changes.  Singlefile just recently was able to solve it somehow.

**Comment by Davidgithub1** [comment]
What's a good spider tool? Every tool I've used was not able to download websites that ScrapbookX was able to.
