### ISSUE TITLE
Chrome Firefox issues opening .maff

### ISSUE THREAD

**Issue by sj365** [danny0838/webscrapbook#141]
-issue moved to its own thread-

Firefox cannot be tested because WSB is unable to save/open WSB or MAF .maff files at this time. (see included error msgs).  Appears to be only for certain sites. Cnet, wsj.com work fine.

[webscrapbk options.zip](https://github.com/danny0838/webscrapbook/files/4299079/webscrapbk.options.zip)

Update: Chrome now has the same issue intermittently

[wsb open maff 2020-03-06_102846.zip](https://github.com/danny0838/webscrapbook/files/4299112/wsb.open.maff.2020-03-06_102846.zip)

chrome 80 windows 10

In case it is related to scripting, i disabled everything scripting related I could think of: ublock, tampermonkey, adblock but still not working.  Of course I've saved plenty of times/post articles before using WSB with ublock, adblock, tampermonky on so I dont think they are the cause.

**Comment by danny0838** [comment]
Oops. It's something related with previous fix 0.61.1 that a `<frame>` in `<noscript>` is not handled correctly. It should be fixed in 0.61.2.
