### ISSUE TITLE
Capture of specific page shows "style is undefined" on Firefox 55

### ISSUE THREAD

**Issue by Binjohn** [danny0838/webscrapbook#142]
我試著擷取[這個網頁](https://chemistry.meta.stackexchange.com/questions/443/which-symbols-are-written-in-roman-upright-font-and-which-are-italicized)，但跳出以下訊息

> Capturing (document) [8] https://chemistry.meta.stackexchange.com/questions/443/which-symbols-are-written-in-roman-upright-font-and-which-are-italicized ... 
> Fatal error: style is undefined

不過我用新版Firefox就沒問題了，所以不是大問題，只是要花點力氣切換版本而已。

OS: Windows 7 64-bit SP1
Firefox version: 55.0.3 64-bit
WebScrapBook version: from 0.50.0 to 0.61.2

**Comment by danny0838** [comment]
我用 Firefox 55.0 / WSB 0.61.2 測試沒發現異常。能否再試幾次，確認是每次都有問題或只是偶發狀況。

如果每次都有問題，請再嘗試：
1. 停用所有其他附加元件
2. 使用全新的 Profile

是否仍會發生同樣問題。感謝。

**Comment by Binjohn** [comment]
感謝回覆。我這邊是每次都會發生。

我去抓了[FirefoxPortable 55.0](https://sourceforge.net/projects/portableapps/files/Mozilla%20Firefox%2C%20Portable%20Ed./Mozilla%20Firefox%2C%20Portable%20Edition%2055.0/) English + WSB 0.61.2，結果跳出一樣的訊息。請問還有什麼差異是我可以試的嗎？

另外我發現，用「擷取原貌」就可以正常運作。

PS. 從WSB的功能表按「設定」沒反應，要從Firefox的附加元件設定按才出得來。
PPS. 還有一個怪現象，我現有版本的附加元件設定裡的WSB評論區網址是錯的，會連到... /firefox/addon/web-scrapbook/reviews ，網址多一個hyphen。

還是這跟前一陣子Firefox憑證過期有關係？以上都是我亂猜的……如果無關可以不要理我沒關係。

**Comment by danny0838** [comment]
1. 確認是否真的是在 55.0 版，以及是在全新 profile、無其他擴充套件的情況下測試（Firefox 切換 profile 有時怪怪的，會切換到之前用的 Firefox 的 profile，因此要稍微確認一下）
2. 你擷取時是全部使用預設選項？或有更改過任何選項？
3. 再來可能就是確定受到影響的 Firefox 版本了……比如 Fx 56, 57, ... 及 54, 53, ...，稍微瞭解大概有哪些版本有問題。

如果受影響的版本不多，有可能是 Firefox 55 版本身的 bug（我用 55.0 也發生下拉選單的 options 點擊無反應的情況，而且下拉選單開了就不會自動關閉……感覺是 Firefox 本身有一些 bug）

> PPS. 還有一個怪現象，我現有版本的附加元件設定裡的WSB評論區網址是錯的，會連到... /firefox/addon/web-scrapbook/reviews ，網址多一個hyphen。
現有版本是指 Firefox （或 WSB？）哪個版本？

WSB 在 30 版以前名稱有加空格（Web ScrapBook），31 版才改為「WebScrapBook」，在 Firefox Add-Ons 站上的網址也有更動，但 ID 沒有變。如果你曾經安裝過 30 版以前的 WSB，有可能是瀏覽器沒有正常更新記錄（最早是從 web-scrapbook 下載，Firefox 就一直沿用舊連結）。可移除再重裝一次試試是否有解決問題。

**Comment by Binjohn** [comment]
>     1. 確認是否真的是在 55.0 版，以及是在全新 profile、無其他擴充套件的情況下測試（Firefox 切換 profile 有時怪怪的，會切換到之前用的 Firefox 的 profile，因此要稍微確認一下）

我有再用全新profile測試過一次，真的不行。但是這個做法Firefox會一直想要更新我，所以後續測試我都是去抓FirefoxPortable用，他一安裝完都是firstrun，應該是全新沒錯。

>     2. 你擷取時是全部使用預設選項？或有更改過任何選項？

全部預設。
我試過改存至資料夾、檔案，改存成HTZ、單一HTML，改檔名，也都無效。
剩下的設定我都沒動。

PS. 要把WSB恢復成原樣除了砍profiles/.../storage-sync.sqlite，還有別的嗎？

>     3. 再來可能就是確定受到影響的 Firefox 版本了……比如 Fx 56, 57, ... 及 54, 53, ...，稍微瞭解大概有哪些版本有問題。

我用FirefoxPortable試到71.0才會動。
不行：53.0, 55.0, 57.0, 59.0, 61.0, 63.0, 65.0, 67.0, 69.0
可以：71.0, 72.0.1, 73.0.1

> > PPS. 還有一個怪現象，我現有版本的附加元件設定裡的WSB評論區網址是錯的，會連到... /firefox/addon/web-scrapbook/reviews ，網址多一個hyphen。
> 現有版本是指 Firefox （或 WSB？）哪個版本？
> WSB 在 30 版以前名稱有加空格（Web ScrapBook），31 版才改為「WebScrapBook」，在 Firefox Add-Ons 站上的網址也有更動，但 ID 沒有變。如果你曾經安裝過 30 版以前的 WSB，有可能是瀏覽器沒有正常更新記錄（最早是從 web-scrapbook 下載，Firefox 就一直沿用舊連結）。可移除再重裝一次試試是否有解決問題。

是指我正在用的Firefox 55.0 + WSB 0.61.2。
因為我之前移除重裝WSB，網址一樣沒修正，所以我一直以為網址是存在附加元件的檔案本身。後來發現只有我正在用的profile有這個問題，新安裝的73.0.1裡面連WSB的討論區的連結都不見了。所以我把這個殘廢的profile稱為「現有版本」。
但看來這跟問題無關？無視好了。

**Comment by danny0838** [comment]
> > 1. 確認是否真的是在 55.0 版，以及是在全新 profile、無其他擴充套件的情況下測試（Firefox 切換 profile 有時怪怪的，會切換到之前用的 Firefox 的 profile，因此要稍微確認一下）
> 
> 我有再用全新profile測試過一次，真的不行。但是這個做法Firefox會一直想要更新我，所以後續測試我都是去抓FirefoxPortable用，他一安裝完都是firstrun，應該是全新沒錯。
瞭解。

> > 1. 你擷取時是全部使用預設選項？或有更改過任何選項？
> 
> 全部預設。
> 我試過改存至資料夾、檔案，改存成HTZ、單一HTML，改檔名，也都無效。
> 剩下的設定我都沒動。
> 
> PS. 要把WSB恢復成原樣除了砍profiles/.../storage-sync.sqlite，還有別的嗎？
按選項最下面的「重設」再儲存即可。

> > 1. 再來可能就是確定受到影響的 Firefox 版本了……比如 Fx 56, 57, ... 及 54, 53, ...，稍微瞭解大概有哪些版本有問題。
> 
> 我用FirefoxPortable試到71.0才會動。
> 不行：53.0, 55.0, 57.0, 59.0, 61.0, 63.0, 65.0, 67.0, 69.0
> 可以：71.0, 72.0.1, 73.0.1
> 
看來還是和 Firefox 版本有關。但我目前還是找不到重現問題的方法。可能要等更有空的時候再詳細研究了……。

如果你懂HTML/CSS/JavaScript，可以在發生錯誤時到擷取視窗和被擷取的網頁按右鍵 > 檢測元素，切換到主控台分頁看看有哪些錯誤訊息。

**Comment by Binjohn** [comment]
我有試過，但力有未逮，還望大大幫忙給個方向。
PS. 為什麼WSB要吃掉主控台的快速鍵Ctrl + Shift + K呢……

首先是主控台只有一行訊息

`TypeError: style is undefined
堆疊追蹤:
inspectDocOrShadowRoot@moz-extension://6158e9b6-44c7-4af9-b2e9-8f1a4dfb93d5/capturer/common.js:3114:11`

去看code，裡面寫

```
        for (const elem of root.querySelectorAll("*")) {
          const {style} = elem;

          fontFamilyMapper.use(style.getPropertyValue('font-family'));
          animationMapper.use(style.getPropertyValue('animation-name'));
```

看不出來是`style`這個變數出包，還是font-family抓不出來，但直覺告訴我是後者，因為網頁中到處都是數學式。

後來我測試出來，只要把[那個網頁](https://chemistry.meta.stackexchange.com/questions/443/which-symbols-are-written-in-roman-upright-font-and-which-are-italicized)的MathJax設定修改一下就會變得可以擷取。

    MathJax元件 → 右鍵 → Accessibility → 取消「Assistive MathML」

這功能好像是讓MathJax在原始碼中插入原生的MathML方便方程式可以被語音引擎朗讀。

於是我猜是MathML出包，然後就去找了MathML的網頁。不論是[範例1](https://developer.mozilla.org/en-US/docs/Mozilla/MathML_Project/test-mathml-css)、[範例2](https://mdn.mozillademos.org/en-US/docs/Mozilla/MathML_Project/MathML_Torture_Test$samples/MathML_Torture_Test?revision=1506691)、[範例3](http://fred-wang.github.io/MathFonts/)，全部都不能擷取。

有可能是因為Firefox的MathML會因為作業系統上安裝的字型不同而有不同行為，所以你無法重現我的問題？你是用Windows嗎？

接著我做了一些測試：

1. 把我電腦上所有的math font全砍了，只留Windows的Cambria Math，沒用。
2. 範例2裡面可以切換字體，換哪個都沒用。
3. 範例3裡面可以切本機或者web font，也是沒用。

有一個可疑的點是，在Firefox裡面接換math font，是沒辦法在主控台看到任何改變的，不知道是不是因為MathML在Firefox有獨立的引擎，所以WSB會無法處理？

我只測到這裡，沒招了。

**Comment by danny0838** [comment]
> `TypeError: style is undefined 堆疊追蹤: inspectDocOrShadowRoot@moz-extension://6158e9b6-44c7-4af9-b2e9-8f1a4dfb93d5/capturer/common.js:3114:11`
> 
> 去看code，裡面寫
> 
> ```
>         for (const elem of root.querySelectorAll("*")) {
>           const {style} = elem;
> 
>           fontFamilyMapper.use(style.getPropertyValue('font-family'));
>           animationMapper.use(style.getPropertyValue('animation-name'));
> ```
> 

就是這個了！就如錯誤訊息 `style is undefined` 所言，因為 style 為 undefined，讀不到 getPropertyValue，所以在那一行出錯。

原因是舊版 Firefox 不支援 `<math>` 元素的 `style` 屬性。此外像 Chrome 也不支援 `<math>` 元素，一樣會發生這個錯誤。

加點程式碼略過不支援 style 的元素就解決了。

> PS. 為什麼WSB要吃掉主控台的快速鍵Ctrl + Shift + K呢……

這些快捷鍵本來是做成和 ScrapBook X 相容，而且在 Chrome 沒什麼問題。不過 Firefox 內建快捷鍵太多了，而且禁止擴充套件覆蓋內建的；偏偏舊版 Firefox 有時又可覆蓋，而且還不能改……。

把快捷鍵全部拔掉好了，要用的自己設定（還不支援設定的舊版就GG）。

是說現在還在用 Firefox 55，是為了什麼舊附加元件啊？

**Comment by Binjohn** [comment]
> 就是這個了！就如錯誤訊息 `style is undefined` 所言，因為 style 為 undefined，讀不到 getPropertyValue，所以在那一行出錯。
> 
> 原因是舊版 Firefox 不支援 `<math>` 元素的 `style` 屬性。此外像 Chrome 也不支援 `<math>` 元素，一樣會發生這個錯誤。
> 
> 加點程式碼略過不支援 style 的元素就解決了。

原來真的是`style`有問題，感謝修正！
那如果都略過`style`的話，擷取下來的網頁還會正常顯示數學式的字型嗎？

> 這些快捷鍵本來是做成和 ScrapBook X 相容，而且在 Chrome 沒什麼問題。不過 Firefox 內建快捷鍵太多了，而且禁止擴充套件覆蓋內建的；偏偏舊版 Firefox 有時又可覆蓋，而且還不能改……。
> 
> 把快捷鍵全部拔掉好了，要用的自己設定（還不支援設定的舊版就GG）。

原來如此，我忘了WSB其實是跨平台的附加元件。
Firefox快速鍵互衝的問題真的是從我第一天開始用就持續到今天了，數十年如一日。


> 是說現在還在用 Firefox 55，是為了什麼舊附加元件啊？

主要是bbsfox和FireGestures。
FireGestures好像有堪用的取代品，應該是可以解決；
bbsfox可以改用WebSocket版直接連PTT，但卡在找不到能用的等寬字型……
除非我自已用fontforge東挖西補弄一個字型出來，但真的沒空。（都有空找bug了?!）
結果我現在瀏覽很多網頁都要用User-Agent Switcher調過，不然都一直煩我要更新。

**Comment by danny0838** [comment]
> 原來真的是`style`有問題，感謝修正！
> 那如果都略過`style`的話，擷取下來的網頁還會正常顯示數學式的字型嗎？

瀏覽器不支援 style 屬性都可以正常顯示了，擷取時略過這屬性又怎麼會有問題呢？真的擔心的話，測試一下就知道了。:)

> > 是說現在還在用 Firefox 55，是為了什麼舊附加元件啊？
> 
> 主要是bbsfox和FireGestures。
> FireGestures好像有堪用的取代品，應該是可以解決；
> bbsfox可以改用WebSocket版直接連PTT，但卡在找不到能用的等寬字型……
> 除非我自已用fontforge東挖西補弄一個字型出來，但真的沒空。（都有空找bug了?!）
> 結果我現在瀏覽很多網頁都要用User-Agent Switcher調過，不然都一直煩我要更新。

原來如此。我個人是習慣用獨立的 PCMan 上 BBS（不過已經很少上了），如果一定要用瀏覽器的話的確選擇不多。不過等寬字體感覺不像會是個問題，或許可以聯絡作者問看看？

**Comment by Binjohn** [comment]
> 瀏覽器不支援 style 屬性都可以正常顯示了，擷取時略過這屬性又怎麼會有問題呢？真的擔心的話，測試一下就知道了。:)

說的也是，感謝解說。我真的是跟這個不熟……

> 原來如此。我個人是習慣用獨立的 PCMan 上 BBS（不過已經很少上了），如果一定要用瀏覽器的話的確選擇不多。不過等寬字體感覺不像會是個問題，或許可以聯絡作者問看看？

可是我是在PTT看到WSB的文章才開始用的耶！
以前都是擷取成MHT，Firefox砍了MHT附加元件後，想了很久，最後看到大大詳細的解說才決定換到WSB。
請務必繼續宣傳呀。

結果我剛才真的想去找PTTChrome作者，才發現這問題他早就解決了……有一半要感謝大大叫我去找。
很難挖到的古早文章有說，他自製的字型SymMingLiu就是為等寬字型而做的workaround，只要把這個字型排在fallback list的最前面就可以解決很多問題，然而我完全沒理解他的苦心……有一半是因為他根本沒寫說明啊，我找得好苦。

看來我終於可以迎接Firefox Quantum了！意外的收穫。

**Comment by Binjohn** [comment]
我更新了WSB 0.61.3，現在可以正常擷取，但是字型有問題。
在Firefox 55.0.3上擷取[那個網頁](https://chemistry.meta.stackexchange.com/questions/443/which-symbols-are-written-in-roman-upright-font-and-which-are-italicized)的時候，MathJax使用的字型（例如MathJax_Main.woff）並沒有被存下來。要去WSB的設定把「字體」從「儲存使用」改成「儲存」才會正常。

**Comment by danny0838** [comment]
哪個地方的字型有問題？

「儲存使用」基本上就是不會下載未使用的字型。當然，如果字型真的有被使用卻沒被下載，那就是有問題了。

**Comment by Binjohn** [comment]
就是所有的數學式，字型都不對。

原網頁：

![01](https://user-images.githubusercontent.com/43265566/76680996-dff01680-6628-11ea-9b6a-53ccc3bde5c7.png)

擷取結果：

![02](https://user-images.githubusercontent.com/43265566/76680995-de265300-6628-11ea-8c12-6bf455a7cb50.png)

不過擷取後顯示的字型也不是fallback的結果，這應該是Firefox的bug，用Chrome會fallback到Times New Roman沒錯。

**Comment by danny0838** [comment]
> 就是所有的數學式，字型都不對。
> 
> 原網頁：
> 
> ![01](https://user-images.githubusercontent.com/43265566/76680996-dff01680-6628-11ea-9b6a-53ccc3bde5c7.png)
> 
> 擷取結果：
> 
> ![02](https://user-images.githubusercontent.com/43265566/76680995-de265300-6628-11ea-8c12-6bf455a7cb50.png)
> 
> 不過擷取後顯示的字型也不是fallback的結果，這應該是Firefox的bug，用Chrome會fallback到Times New Roman沒錯。

這個好像和後來抓到的另一個bug有關，先試試 0.61.4 有沒有解決問題。（Firefox 應該很快會出現，不過 Chrome 版還在龜速審查，可能要等一陣子......orz）

簡而言之儲存現用比較麻煩的是需要追蹤所有被使用過的字體/樣式圖片，但 CSS 的設計似乎本來就不是要讓人追蹤的，追蹤起來特麻煩，牽涉到 shadowRoot 更麻煩 * n 倍。可能到時候要整個架構打掉重寫……總之如果牽涉到字體/樣式圖片莫名消失，尤其是 shadowRoot 裡的，就暫時先改成全部儲存吧。

**Comment by Binjohn** [comment]
> 這個好像和後來抓到的另一個bug有關，先試試 0.61.4 有沒有解決問題。（Firefox 應該很快會出現，不過 Chrome 版還在龜速審查，可能要等一陣子......orz）

成功了！完全正常，謝謝！

> 簡而言之儲存現用比較麻煩的是需要追蹤所有被使用過的字體/樣式圖片，但 CSS 的設計似乎本來就不是要讓人追蹤的，追蹤起來特麻煩，牽涉到 shadowRoot 更麻煩 * n 倍。可能到時候要整個架構打掉重寫……總之如果牽涉到字體/樣式圖片莫名消失，尤其是 shadowRoot 裡的，就暫時先改成全部儲存吧。

對……我也在想說，CSS就長這樣，到底是要怎麼追蹤元素有沒有實際使用過?!
（但我第一次聽到shadowRoot，目前只查了一點資料，改天繼續研究）

又能原樣擷取、又能縮減容量，謝謝大大寫出WSB。

**Comment by danny0838** [comment]
> > 簡而言之儲存現用比較麻煩的是需要追蹤所有被使用過的字體/樣式圖片，但 CSS 的設計似乎本來就不是要讓人追蹤的，追蹤起來特麻煩，牽涉到 shadowRoot 更麻煩 * n 倍。可能到時候要整個架構打掉重寫……總之如果牽涉到字體/樣式圖片莫名消失，尤其是 shadowRoot 裡的，就暫時先改成全部儲存吧。
> 
> 對……我也在想說，CSS就長這樣，到底是要怎麼追蹤元素有沒有實際使用過?!
> （但我第一次聽到shadowRoot，目前只查了一點資料，改天繼續研究）

總之就是要用一大堆程式碼去檢查網頁中所有樣式表、所有元素的樣式值等等，說來話長，有興趣自己看程式碼研究吧XD

不過最近發現 shadowRoot 還算相對好解決，更大的魔王是 CSS variable 和 JavaScript 動態載入的資料……

> 又能原樣擷取、又能縮減容量，謝謝大大寫出WSB。

相較於其他類似工具，WSB 其實沒有在縮減容量上下很多工夫。話說 SingleFile 作者超強大又超勤勞，新版本一直出，在壓縮檔案大小方面下的工夫比 WSB 更多。要不是就資料保存考量不支持單一 HTML 檔案，我也想考慮跳槽了XD

順便調查一下：你一般使用是儲存成什麼檔案格式？是否有裝後端伺服器及側欄？

**Comment by Binjohn** [comment]
我都存成單一HTML檔案。沒有後端伺服器及側欄。

我差不多是把單一HTML檔案當成PDF用的感覺，但把網頁刷成PDF實在太詭異，無法接受。
平常都是存一些參考資料、需要留紀錄的畫面、感覺快消失的網站，存好就開資料夾整理這些檔案。
這樣的用法單檔比較方便，然後留紀錄的畫面會要傳給別人，所以單一HTML比較方便。

前天升級Firefox 74.0了！然後我才終於知道「側欄」是什麼東西……
還有為什麼之前WSB安裝完就會跳出側欄，原來是因為舊版Firefox不支援側欄，囧。
如果未來我有做筆記的需求（像WSB的GitHub首頁顯示的那樣），也許會裝後端伺服器，但目前沒有。

**Comment by Binjohn** [comment]
> 相較於其他類似工具，WSB 其實沒有在縮減容量上下很多工夫。話說 SingleFile 作者超強大又超勤勞，新版本一直出，在壓縮檔案大小方面下的工夫比 WSB 更多。要不是就資料保存考量不支持單一 HTML 檔案，我也想考慮跳槽了XD

不行，我要支持國產又追求不失真保存的WSB。現在硬碟愈做愈大，沒問題的。
我記得一開始換WSB的時候好像有比過檔案大小，是有比UnMHT的檔案大一點，不過我完全不在意直接砍了UnMHT，哈哈。

> 順便調查一下：你一般使用是儲存成什麼檔案格式？是否有裝後端伺服器及側欄？

我都存成單一HTML檔案。沒有後端伺服器及側欄。

我差不多是把單一HTML檔案當成PDF用的感覺，但把網頁刷成PDF實在太詭異，無法接受。
平常都是存一些參考資料、需要留紀錄的畫面、感覺快消失的網站，存好就開資料夾整理這些檔案。
這樣的用法單檔比較方便，然後留紀錄的畫面會要傳給別人，所以單一HTML比較方便。

前天升級Firefox 74.0了！然後我才終於知道「側欄」是什麼東西……
還有為什麼之前WSB安裝完就會跳出側欄，原來是因為舊版Firefox不支援側欄，囧。
如果未來我有做筆記的需求（像WSB的GitHub首頁顯示的那樣），也許會裝後端伺服器，但目前沒有。
