### ISSUE TITLE
having a little trouble installing webscrapbook

### ISSUE THREAD

**Issue by gred22** [danny0838/webscrapbook#143]
I love scrapbook and scrapbook x and have many years and many gigabytes of scrapbook data.  I am installing webscrapbook in brave and want to set up the backend server.  I have installed the webscrapbook extension in Brave, installed python, and think I have installed the PyWebScrapBook package as well.  

I have followed the instructions here: https://github.com/danny0838/PyWebScrapBook#host-a-scrapbook and get down to running the server, which seems to start fine.

I can get the command path, but have problems with: "Set default application of MAFF/HTZ file to the command at that path to open them directly in the browser with double-click."  I can't seem to find a MAFF/HTZ file.  Where is this, please?

And, the Webscrapbook side panel says "Backend server is not configured."  The settings for webscrapbook has a place to specify the address, user, and password for the backend server, but I don't know what to put here.  Can you help me?

Thanks - Mark

**Comment by danny0838** [comment]
> I can get the command path, but have problems with: "Set default application of MAFF/HTZ file to the command at that path to open them directly in the browser with double-click." I can't seem to find a MAFF/HTZ file. Where is this, please?

MAFF or HTZ file is one of the supported file format for saving a web page. You won't have one if you haven't save any yet, and you can simply skip this step. 

You can see [FAQ](https://github.com/danny0838/webscrapbook/wiki/FAQ#how-to-choose-the-save-format-for-the-captured-web-page) for details about supported file formats and their pros and cons.

Additionally, using PyWebScrapBook is one way to view an HTZ or MAFF archive file. See [here](https://github.com/danny0838/webscrapbook/wiki/View) for other options.

> And, the Webscrapbook side panel says "Backend server is not configured." The settings for webscrapbook has a place to specify the address, user, and password for the backend server, but I don't know what to put here. Can you help me?

It depends on how you configure the backend server and will show in the console when you start it, such as:

![圖片](https://user-images.githubusercontent.com/531417/76386504-a22c8d00-639f-11ea-8e46-68794f3410b3.png)

Note that you have to add a trailing `/` to represent the root path, such as `http://localhost:8080/`, as the help message says:

![圖片](https://user-images.githubusercontent.com/531417/76386647-f20b5400-639f-11ea-9bc2-6b91d730677a.png)

**Comment by gred22** [comment]
Thanks so much for the prompt response and assistance.  I'm a step or two closer, but still with problems.  I'm getting excited with the prospect of having webscrapbook in brave and being able to access/import my scrapbook x data from firefox.

I started the wsb server, got the address, added the /, inputted the address into wsb options, set Save captured data to backend server, and set Save captured data as to folder.  This is what the cmd window showed:

D:\bravescrapbook>wsb serve
WebScrapBook server starting up...
Document Root: D:\bravescrapbook
Listening on http://localhost:8080
Hit Ctrl-C to shutdown.

Launching browser at http://localhost:8080 ...
127.0.0.1 - - [11/Mar/2020 20:46:56] "GET / HTTP/1.1" 200 2084
127.0.0.1 - - [11/Mar/2020 20:46:56] "GET /index.css?a=static HTTP/1.1" 200 1849
127.0.0.1 - - [11/Mar/2020 20:46:56] "GET /common.js?a=static HTTP/1.1" 200 2368
127.0.0.1 - - [11/Mar/2020 20:46:56] "GET /common.css?a=static HTTP/1.1" 200 1056
127.0.0.1 - - [11/Mar/2020 20:46:56] "GET /index.js?a=static HTTP/1.1" 200 27712
127.0.0.1 - - [11/Mar/2020 20:46:56] "GET /fclose.png?a=static HTTP/1.1" 200 752
127.0.0.1 - - [11/Mar/2020 20:46:57] "GET /favicon.ico HTTP/1.1" 404 727
127.0.0.1 - - [11/Mar/2020 20:49:56] "GET /?a=config&f=json&ts=1583974195934 HTTP/1.1" 200 605
127.0.0.1 - - [11/Mar/2020 20:49:56] "GET /tree/?a=list&f=json HTTP/1.1" 400 65
127.0.0.1 - - [11/Mar/2020 20:49:56] "GET /?a=token&f=json HTTP/1.1" 200 72
127.0.0.1 - - [11/Mar/2020 20:49:56] "POST /tree/?a=mkdir&f=json HTTP/1.1" 200 54
127.0.0.1 - - [11/Mar/2020 20:49:56] "GET /tree/?a=list&f=json HTTP/1.1" 200 29

But when I told wsb to capture a tab, this is what popped up in a capture page window:

Capturing (document) [120] https://chrome.google.com/webstore/detail/webscrapbook/oegnpmiddfljlloiklpkeelagaeejfai/related ...
Unable to execute content script ([120:0] https://chrome.google.com/webstore/detail/webscrapbook/oegnpmiddfljlloiklpkeelagaeejfai/related): The extensions gallery cannot be scripted.
Fatal error: Could not establish connection. Receiving end does not exist.

Do you have any idea what I am doing wrong?
Where will the captured tabs/pages be stored in folders?
Is there a way to specify different folders within the wsb storage where to put the saved page, like the drop down window from the scrapbook x save page as?

Thanks again for all your assistance.

Mark

**Comment by danny0838** [comment]
The extension store is blacklisted by the browser and cannot be captured, see [FAQ](https://github.com/danny0838/webscrapbook/wiki/FAQ#why-an-error-always-occur-when-capturing-a-page-in-chrome-web-store-or-firefox-add-ons) for etails.

Just try capturinga web page from another site.

**Comment by gred22** [comment]
Thanks, yes - that was the problem.  I'm almost there.  Now I can capture pages.   But I still have some questions.

When I select manage with scrapbook x, a manager window opens and I can add and specify new databases and paths.  However, when I select Manage in wsb, I get a new wsb window showing the captured page, but no add/edit/remove for the wsb storage.

Where on my disk is wsb storing the captured pages?
How can I specify a different location?

If I want to access my various old scrapbook x databases from within wsb, should I import each of those into a separate wsb storage, or have everything in one common storage?

Again, thanks so much for your assistance.

Is there a place to make donations to help support your development efforts?

Mark

**Comment by danny0838** [comment]
> Where on my disk is wsb storing the captured pages?
> How can I specify a different location?

It's determined by PyWebScrapBook. Captured data will be saved at the directory PyWebScrapBook is hosting—or a subdirectory, determined by how PyWebScrapBook is configured. Run `wsb --help`, or more specifically, `wsb help config` for details.

> If I want to access my various old scrapbook x databases from within wsb, should I import each of those into a separate wsb storage, or have everything in one common storage?

You'd have to import them to a directory you like. [Here](https://github.com/danny0838/webscrapbook/wiki/Import) is a documentation about that. After import you can host the directory to get it show in the sidebar.

**Comment by gred22** [comment]
Thanks again for the quick response.

I will definitely contribute after I get it all working.

I am sorry to be so naive - but I got the very thorough wsb help config information.  But I cannot for the life of me find the .ini file.  The help talks of user: at "~/.wsbconfig" and book: at "<book>/.wsb/config.ini".  But I cannot find any directory or file realted to these.  And I have Copernic search that is usually very good at finding files and emails.

Can you help me locate where these files are stored so that I may modify them?

Thanks - Mark

**Comment by danny0838** [comment]
> I am sorry to be so naive - but I got the very thorough wsb help config information. But I cannot for the life of me find the .ini file. The help talks of user: at "~/.wsbconfig" and book: at "/.wsb/config.ini". But I cannot find any directory or file realted to these. And I have Copernic search that is usually very good at finding files and emails.

The config file don't exist unless you generate one, by running `wsb config` or by manually create one. Run `wsb config --help` for further details.

`~/.wsbconfig` is the Unix style notation meaning the user's home directory. In Windows it's by default something like `C:\Users\<Your User Name>\.wsbconfig`, while `<book>/.wsb/config.ini` is relative to a scrapbook directory. For example, if you have followed the doc of PyWebScrapBook and have run `wsb config -ba` in a directory (say `/path/to/dir`), you should already have a config file at `/path/to/dir/.wsb/config.ini`. You can open it with a plain text editor or run `wsb config -be` at the same directory to edit the config file via launching text editor automatically.

**Comment by gred22** [comment]
OK, I found where wsb is storing data - the path I selected in the cmd window when running the server: D:\bravescrapbook which is where wsb has put the .wsb and data and tree folders.  I ran wsb config just like that and got no feedback, but there is the config.ini file in D:\bravescrapbook\.wsb.

I made no changes to config.ini, however, now whenever I try to capture a page, I get a window reporting errors, like this one:

Capturing (document) [118] https://github.com/danny0838/webscrapbook/issues/143 ...
Error downloading file (): Source URL is empty.
Error downloading file (): Source URL is empty.
Error downloading file (): Source URL is empty.
Done.

What did I break?

**Comment by danny0838** [comment]
> I made no changes to config.ini, however, now whenever I try to capture a page, I get a window reporting errors, like this one:
> 
> Capturing (document) [118] #143 ...
> Error downloading file (): Source URL is empty.
> Error downloading file (): Source URL is empty.
> Error downloading file (): Source URL is empty.
> Done.
> 
> What did I break?

This is also in the [FAQ](https://github.com/danny0838/webscrapbook/wiki/FAQ#why-does-the-capture-dialog-always-show-yellow-error-messages). In most cases there's no big deal getting warning of empty URLs. It may be that there's an image or a CSS background image happens to be empty due to some reason: bad HTML or script in the source page, bad content inserted by another extension, or sometimes, a bug of WSB. If the captured page is getting something wrong and you need our help investigating on it, please disable all other extensions, refrash the web page, and see if same issue still happen. If yes, please provide full URL of the source web page and the capture options you are using (you can export the options and copy from the exported file).

**Comment by gred22** [comment]
I have advanced a good bit, and am able to save pages from brave, and organize and manage the pages and folders.  The one thing I don’t like about brave (chrome) is that with many tabs open, they do not scroll like in firefox.  They just keep getting smaller and smaller in the available space.

I have consolidated and moved folders of scrapbook and scrapbook x data to my current laptop, for input into wsb.  I have over 13 GB of data copied, and more to go.  Decades of data.  It is going to be great to be able to access all this, search it, and have it on a current browser.  I plan to donate $100 to you after I get it all worked out.  I really appreciate all your efforts to develop such an outstanding tool, and your support you have provided me.

I dragged a folder of scrapbook x data to the site indexer page.  It was a little disconcerting to me that the dragged folder image indicated “move” and I only wanted to index.  Then a window popped up with a folder unrealted indicated, which I canceled.  The site indexer indicated that it generated the zip file, but I have no idea where it put it and cannot find it.  It is not in my wsb\.wsb or wsb\data or wsb\tree folders.

In addition to looking in those folders I did searches with windows explorer and copernic and could not find a generated zip file.

But another concern is that on the site indexer page, there are three buttons - index for server, pick a folder, and pick zip files.  But clicking on these three buttons does not do anything - none of the three.

Thanks - Mark

**Comment by danny0838** [comment]
There's also guide for [running the indexer](https://github.com/danny0838/webscrapbook/wiki/Indexer) and more specifically, [import data from legacy ScrapBook (X)](https://github.com/danny0838/webscrapbook/wiki/Import).

Basically, the generated index will be download to the default download folder if you pick one or more folders to index, and then you have to merge it into your data folder(s). It's cunbersome but it's the only possible way we can think under browser restriction. At last, you can run backend server for that data directory(s).

If you run the indexer on the server, it reindexes data in the server (which is probably not desired when you want to import data.)

**Comment by gred22** [comment]
Hello - thanks, but I have a new problem.  I switched to the Vivaldi browser.  And I installed webscrapbook, and can initiate the local server, etc.  But when I save pages, they show they saved, but they don't appear in my database and I can't find the files anywhere.  What did I do wrong?

**Comment by danny0838** [comment]
It depends on what you option are, so just check them. By default it is saved at a subdirectory of the default download folder. If you really need further help, export your options and post it here.

**Comment by gred22** [comment]
Yes, I should have looked there - when I switched from Brave to Vivaldi, I forgot to specify store in backend server.  Thanks

**Comment by gred22** [comment]
Well, while changing browsers between chrome, brave, and vivaldi, I ended up with captured tabs in three different folders.  I moved the mistaken two data folder contents to the desired data folder and indexed, and everything is where it should be.

(1) However, I have a question before I import, and I hope you can understand why.  I have 30 scrapbook and scrapbook x data folders from back to 2008, with over 88 GB !!! of data. One thing I definitely want to make sure of is that the scrapbook structures with their folders will be preserved.  If I simply copy the contents of the scrapbook data folders into the webscrapbook folder, then re-index, how can I make sure the scrapbook folder structure is preserved from the scrapbook.rdf file?

(2) Along the same lines, I was looking for where in scrapbook a particular saved page was stored.  A search told me the folder name (date and time) of the page in question, but looking in scrapbook.rdf, I cannot determine which scrapbook folder this page is associated with.  How can I do that?

(3) As you can tell from the amount of scrapbook data I accumulated, I depend on it a lot.  One of the great things about scrapbook was that with each page saved, I could select what scrapbook folder to put it into, and even create a new folder for it during the save process.  It appears that with webscrapbook, all I can do is capture a tab and then later go into wsb management to create a new folder, use modify metadata to change the folder name to what I want, then move the saved page into this (or another) folder.  Is there some better way to do all this?

Thanks

**Comment by danny0838** [comment]
(1) I don't quite understand your question. If you do follow [the guide provided above](https://github.com/danny0838/webscrapbook/issues/143#issuecomment-600368774) to import ScrapBook X data, WebScrapBook should have already preserved items recorded in scrapbook.rdf.

(2) If you follow the guide provided above to import every ScrapBook X folder, and [host them using PyWebScrapBook](https://github.com/danny0838/webscrapbook/wiki/Backend#host-multiple-scrapbooks-under-the-backend-server), WebScrapBook would info which scrapbook a search result item is in.

For example, [this screenshots](https://raw.githubusercontent.com/wiki/danny0838/webscrapbook/images/screenshots/firefox-007.png) shows that the search results are in the "WebScrapBook" scrapbook.

(3) No currently. As the WebExtension framework doesn't support modal dialog, implementing a dialog in a web page during a capture is extremely difficult and error-prone, and we haven't come up with a solution/workaround to deal with it yet.

**Comment by danny0838** [comment]
Close stale issue.
