### ISSUE TITLE
"server.bookId is null" error

### ISSUE THREAD

**Issue by ngirard** [danny0838/webscrapbook#144]
Using WebScrapBook 0.61.7 and PyWebScrapBook 0.13.1 on Ubuntu 19.04 / Firefox 72.0.1.

Everything was setup using your instructions.
Clicking "Capture tab" leads to the following error:
```
Capturing (document) [334] https://github.com/danny0838/webscrapbook ...
Error downloading file (): Source URL is empty.
Error downloading file (): Source URL is empty.
Error downloading file (): Source URL is empty.
Preparing download...
Error downloading file (https://github.com/danny0838/webscrapbook): server.bookId is null
Fatal error: server.bookId is null
```

After looking at [this line](https://github.com/danny0838/webscrapbook/blob/d45e62b478dd170975355a0607537144d9c5f123/src/scrapbook/server.js#L119), I added a "scrapbook" option to the "server" group in the `.wsb/config.ini`, but it didn't solve the problem.

Any ideas ?
Cheers

**Comment by danny0838** [comment]
I cannot reproduce the issue. Can you confirm whether this issue always or occasionally happens? Does it happen on other web pages?

Also, open the browser console of the capture window and report the error messages in it. And provide your `.wsb/config.ini` settings.

**Comment by danny0838** [comment]
Can you provide your `.wsb/config.ini` and WebScrapBook options (export it and provide the content)?

Also, try opening the browser console of the capture window with error and report the error messages in it.

**Comment by danny0838** [comment]
@ngirard Hello, it's been a long time. Is this issue still reproducible in the latest version?

**Comment by danny0838** [comment]
Close stale issue due to lack of further information.
