### ISSUE TITLE
Can't Edit Pages Once Saved With SinglePage Addon

### ISSUE THREAD

**Issue by bytos** [danny0838/webscrapbook#146]
SinglePage is a simple addon that allows you to "Save selection" and the resulting HTML file size is much smaller than WebScrapbook captures (412KB vs 1.5MB).

I like the editing DOM/text and highlighting functions of WebScrapbook, but can't replace SinglePage with WebScrapbook to save web pages since the difference in file size is significant.

I do like WebScrapbook's DOM/text editing and text highlighting, but can't go back to edit pages once they are saved with SinglePage.

**Comment by danny0838** [comment]
WebScrapBook also support capture selection, just make a select and perform a capture using the toolbar dropdown or the context menu.

WebScrapBook tries to be as faithful as possible by default, if size is an important concern, consider [tweaking the options](https://github.com/danny0838/webscrapbook/wiki/FAQ#why-the-web-page-captured-by-webscrapbook-is-larger-in-size-than-those-captured-by-other-tools) for it.

Lastly, a page captured by SinglePage can be imported into WebScrapBook and being further edited and saved, just put them under the data directory and run the aite indexer.

For more support, please provide the URL of pages you have a size issue, and we may investigate whether there's some more thing we can do for them.

**Comment by bytos** [comment]
1) Saw the "Capture selected range(s)" in the context menu, but don't have the same option in the drop-down menu, only "Capture tab", "Capture tab (source)", "Capture tab (bookmark)", "Batch capture".

2) If the "Capture selected range(s)" had a shortcut like "Edit tab" does could avoid the additional context menu. (hint: request)

3) How do you import in WebScrapbook? The name of the addon is SingleFile (not SinglePage :))

This are my settings for SingleFile (for reference):

![a](https://user-images.githubusercontent.com/16452541/79249878-49478d00-7e54-11ea-9f33-fddee59d378f.png)

**Comment by danny0838** [comment]
1\. 2. If there's a selection in the tab, capture tab captures the selected range(s) only, as the tooltip shows:

![](https://raw.githubusercontent.com/wiki/danny0838/webscrapbook/images/screenshots/firefox-001.png)

3\. As mentioned above, **put them under the data directory and run the site indexer**. Where the data directory is depends on how you configure the options, [Here](https://github.com/danny0838/webscrapbook/wiki/Intro#four-principal-approaches) are 4 principal approaches for WebScrapBook.

If you want to be able to edit a captured page and save it again, you need to setup the backend server, i.e. the approach 4, where the data directory is by default (if you do follow the approach) `<scrapbook directory>/data/`. Just put the pages captured by SingleFile under it and run the site indexer.

If you just want a quick import, you can follow approach 3, where the default data directory is  `<default download directory>/WebScrapBook/data/` (if you haven't modify the `Scrapbook folder:` option), and you can drag the `<default download directory>/WebScrapBook/` directory to the site indexer after having put the pages under the data directory. But in such case you won't be able to edit and save those pages.

**Comment by danny0838** [comment]
Close stale issue. Feel free to respond if you still have problem about this topic.

**Comment by bytos** [comment]
Thanks for the help. Found out that the SingleFile (actual name) addon has an "Annotate and save the page..." command, which provides text highlighting.

![S216](https://user-images.githubusercontent.com/16452541/88492977-0a61c100-cf85-11ea-9b5b-c531520cd2dd.png)
