### ISSUE TITLE
can NOT highlight 

### ISSUE THREAD

**Issue by andrewchenshx** [danny0838/webscrapbook#147]
firefox 75.0 (64-bit)
webscrapbook 0.67.0
backend: 127.0.0.1:9999 (webscrapbook 0.15.2)
after captured, open the article from the sidebar, select one sentence(more than one word), then press the highlight marker in the toolbar, but the selected words is NOT highlighted.

**Comment by danny0838** [comment]
Can you provide the URL of the page you captured from and the range you selected before the highlight?

**Comment by andrewchenshx** [comment]
url:https://computers.tutsplus.com/tutorials/beyond-highlighting-how-to-get-the-most-from-your-annotations--cms-20013

selected words:Marvin also lets you view all your bookmarks and highlights on a separate page,

**Comment by danny0838** [comment]
Fixed in 0.67.1.
