### ISSUE TITLE
WebScrapbook UI

### ISSUE THREAD

**Issue by Atanacius** [danny0838/webscrapbook#15]
Ok. Again, more a question than an issue...
Anyway, I think, it's an important reguards question on visual side of WebScrapbook.

Well, today, I was aware of how will be the UI of the new version based on WebExtension of Scrapbook, named as WebScrapbook.

## I mean, it is a final UI ?
Is it impossible to have side panels like we had in Scrapbook X ?
It's great for organizing with a side bar panel (always opened in my Firefox, at work/at home !
I can think to live without but it would be a pain to organize/accessing!

_I KNOW you do your best and must develop the new version based on what WebExtension authorize.. so there is no any workaround possible?_
Since it seems not as you said it here: https://github.com/danny0838/webscrapbook/issues/2#issuecomment-317823391

**The fatal day is coming... 
I'm worry about the futur of addons with WebExtension, but more worrying about the UI of WebScrapbook, how it would be without sidebar!?**

## Explications on what I reffering as sidebar:
In Scrapbook X we had that sidebar: https://addons.cdn.mozilla.net/user-media/previews/full/146/146924.png?modified=1416635343
In WebScrapbook the sidebar seems gone and as UI we have that instead: https://addons.cdn.mozilla.net/user-media/previews/full/190/190179.png?modified=1508913059

_Thanks for answer, and keep up your great work, again, do your best!_

**Comment by yfdyh000** [comment]
I guess the author needs a reliable local server (APIs) program to manipulate the file system. Then, make a new user interface, #2.

**Comment by Atanacius** [comment]
No doubt but will be it possible at least...
I mean WebExtensions API's are not yet full implemented in Firefox 57 !
OK. There is some new API that was implemented in this week, but not all that are important to making a sufficient workaround to help Scrapbook X to survive with the new WebScrapbook transition code !

... The future is not brighter anymore on Firefox scene.
Hope @danny0838 can make a great, solid, and good-looking/good-ergonomic WebScrapbook.

I hope... but... it will be so difficult, therefore, I do not know all stuff going on future plans of Mozilla...
But I think Firefox is on a transition era that will make a GREAT HOLE of add-ons issues and behaviors !

Have a nice day @yfdyh000 !

**Comment by danny0838** [comment]
Note: To avoid a distraction, we are going to focus similar discussion in #2. Please go there for such issues.
