### ISSUE TITLE
Support annotation in a web page

### ISSUE THREAD

**Issue by andrewchenshx** [danny0838/webscrapbook#151]
currently, i can select a fewer words and then click the "marker" to highlight the selection.
while i don't how to annotate the selection. here by "annotate", i mean to input some words/comment.
thanks

**Comment by danny0838** [comment]
An annotation for an item can be written in the metadata from the sidebar. Adding annotation in the page using the page editor is currently a pending feature, as there's still a consideration and technical difficulty. A custom annotation can be artificially crafted (via the devtool or maybe another extension the suports web page editing) by creating an item with `data-scrapbook-elem="custom"` or `data-scrapbook-elem="custom-wrapper"`, see [data scheme](https://github.com/danny0838/webscrapbook/wiki/Scheme) for more details.

**Comment by danny0838** [comment]
Implemented tooltiped linemarker and sticky note in 0.70.0. Feedback if you have additional good idea about it.
