### ISSUE TITLE
Source YouTube page broken after performing a capture

### ISSUE THREAD

**Issue by qdinar** [danny0838/webscrapbook#152]
my all videos page, for example: https://www.youtube.com/user/QDinar/videos .

after saving youtube all videos page with w.s.b., it is no longer possible to open context menu of videos there, by clicking 3 dots at right end of their titles, which is under thumbnail. the context menu allows to add video to watch later, to playlist, and to play queue.

**Comment by danny0838** [comment]
Such interactive feature requires script interaction with the original site and **it's impossible for a captured page to do so** due to loss of such environment. It's something like that it's impossible for a captured Gmail page being able to send and receive emails, or a captured Twitter page being able to send a Tweet.

**Comment by qdinar** [comment]
i mean, the original page breaks.

**Comment by danny0838** [comment]
As mentioned above, the context menu on clicking the "3 dots" and the "add video to watch later" are both script and server integration related.

**Comment by qdinar** [comment]
you said

> script interaction with the original site and it's impossible for a captured page to do so 

i say: i do not say about how behaves captured page, i say about how behaves original page.

**Comment by danny0838** [comment]
I don't get you. You want the captured page working like the original page, don't you?

**Comment by Michaelsy** [comment]
Sorry for my intervention. As far as I understand qdinar, after captering a page this captured original page don't work like before the captering.

**Comment by qdinar** [comment]
> You want the captured page working like the original page, don't you?

no, i do not want that.

Michaelsy has said correctly.

**Comment by danny0838** [comment]
Ok. I get it.

This is a bizarre issue. When performing a capture, WebScrapBook makes a full clone of document nodes, operates on the cloned nodes, and then retrieve HTML from them. This should not alter the source page anyway.

However, it seems that it IS the nodes cloning that breaks it. To illustrate this, just open a YouTube page and run below code in the browser console:

    document.documentElement.cloneNode(true);

After running the code YouTube clicking on the tricolon (`⁝`) of a video no more pops a context menu.

This happens on both latest versions of Firefox and Google Chrome.

Currently it doesn't seem to be an issue of WebScrapBook but one of YouTube. YouTube has some code that interfere (or are interfered) with node cloning. As YouTube scripts are obfuscated, it's really hard to investigate on it further. A help from an expert may be needed.

**Comment by danny0838** [comment]
Fortunately we found the cause, and solution.

The constructor of a defined custom element is triggered when a custom element is generated by a clone, and can thus interfere the original web page. Generate a new document and use importNode can fix the issue.
