### ISSUE TITLE
WebScrapBook is almost complete!

### ISSUE THREAD

**Issue by danny0838** [danny0838/webscrapbook#153]
After a 4-year struggle, the tremendous migration of [ScrapBook X](https://github.com/danny0838/firefox-scrapbook) to [WebScrapBook](https://github.com/danny0838/webscrapbook) is almost complete.

Most features of ScrapBook X, such as faithful page capture, annotation and editing, organization, and fulltext search are now available in WebScrapBook. Unfortunately, due to the limitation of the new WebExtension framework, a collaborating backend server (which can be set up using [PyWebScrapBook](https://github.com/danny0838/PyWebScrapBook)) is required for some advanced features.

WebScrapBook has also implemented many improvements, such as cross-platform support, mobile support, remote access support, more supported file format (ZIP-based archive and single HTML file), more faithful page capture, new capture customizations, improved annotation features (such as tooltip annotation on any highlight, CSS- and JS-supported sticky note, and revertable erasing) and better multi-scrapbook support (such as cross-scrapbook item locating and fulltext search). WebScrapBook also implements a unit test mechanism to prevent a bad regression during an upgrade. More details about this is available in the [documentation](https://github.com/danny0838/webscrapbook/wiki/Diffs).

Data saved via ScrapBook and ScrapBook X can be migrated to WebScrapBook just fine (check the [doc](https://github.com/danny0838/webscrapbook/wiki/Import)). Just beware that due to the many new features WebScrapBook has implemented, an item saved using WebScrapBook cannot be directly used in ScrapBook X and needs a conversion, for which an automated tool is not yet available and needs to be done manually.

Something that are currently still not available are in-depth capture, re-capture, and item importing and exporting:

* **In-depth capture**: Current investigation suggests that a code rework is required to support it. There are also design issues such as how to keep a map of the saved resources and metadata, as the original design of legacy ScrapBook has many issues, and we may need some ideas about that.

  We are still not sure whether it can really be done or not. This has been regarded as a minor feature as ScrapBook is basically designed to capture the currently rendered page and not for headlessly capturing a whole site, which can be done by lots of good spider tools. If we cannot do that we may consider an alternative or just forget about it.

* **Re-capture**: Frankly speaking, I am not sure why it should exist currently. Personally I would choose to just capture the original page again if I really need an update, as re-capture will basically overwrite everything—old content, old annotation, old resource files, etc.—and can possibly introduce a conflicting state, as resource files used by the old version and not by the new version are not removed, and as a re-capture is performed in a headless way.

  The value I can currently think of is that it preserves the original item metadata (except for the modify time), but keeping an old metadata with new content is kind of inconsistent and I don't like it... 

  If we are going to implement it, the current idea is to move the old page files to a backup path (such as from `./*` to ./.history/<timestamp>/*), save a new capture, and update the modify time metadata of the item. This should not be too difficult to implement, but how to support it for an item of ZIP-based archive or single HTML would be an issue. We may consider simply don't provide this feature for them if we cannot come up with a good solution.

  Is there still someone that likes the re-capture feature? I'd like to know how you use it, why you like it, and how would you like it be implemented in WebScrapBook. Please share with us if you have an idea.

 * **Importing and exporting**: This is also something that needs investigation. Due to the limitation of WebExtension framework, it's not possible for a user to just pick any directory for exporting. We may consider restricting the exporting directory to a fixed directory, such as `./tree/.exports`, or to provide a "move item between scrapbooks" feature instead. How do you think about this? Please share with us.

WebScrapBook 1.0 will come to live as such issues are resolved.

Is there still something you really love in legacy ScrapBook or ScrapBook X that is not available in WebScrapBook? Do you have a good idea about how WebScrapBook should be? Feel free to share with us.

**Comment by Buckskin-Cowboy** [comment]
I use both In-depth and Recapture for saving stories I read. Most are uploaded over many weeks and consist of anywhere between 1 and 100 linked pages.
I use Recapture because it is easy to update and add additional pages as they are uploaded. A Recapture button that used the existing root link (rather than having to go to the page and capture again), saved the new download and then deleted the exiting files would be fine.
I have no idea how you would do this

**Comment by Copyrites** [comment]
I am soooo ready to move to WebScrapbook.  I keep a legacy firefox install around just for ScrapbookX and I can't wait to drop it.

One feature that I rely on heavily in ScrapbookX is the notifications during browsing when the current page is already in the scrapbook.  It keeps me from saving duplicates - my scrapbook is just too big to keep track manually.

I tried 0.75.2 with the wsb backend server and unless I missed a config option it doesn't seem to show notifications.  Ideally I'd like to see notifications in a manually-closable bar across the top of the page, much like ScrapbookX does now with a count of how many copies are in the scrapbook.   One enhancement over X's behavior would be to optionally (on a per saved page basis) check against the base url, so ? parameters could be ignored.  

For example:  foo.bar/baz.html and foo.bar/baz.html?zed=true would be considered the "same" URL for notification purposes, and if you show the full saved URL(s) in the notification then as the user I can determine if the parameters are relevant.  

Regardless, I just want you to know how much I appreciate ScrapbookX, its my most used firefox "application."  Combined with the recoll full-text indexer its been a game changer for how I use the web.  Thank you so much.

**Comment by danny0838** [comment]
@Copyrites No. Current WSB does not support notification for a captured page. This seems technically implementable but not quite easy, as we need to keep syncing with the backend server but cannot do it too often to prevent too much unnecessary network traffic.

Also we don't like a prompting notification, which is quite annoying to the user. We are considering showing a badge at the toolbar button instead.

**Comment by denisabt** [comment]
Fantastic work! I am so happy to be able to access my saved data after years, thanks to your dedicated work! Highly appreciated!

**Comment by spiralofhope** [comment]
I've always thought of "re-capture" as "delete this cache and replace it with a totally new copy", which also keeps any user contributions like comments.

**Comment by danny0838** [comment]
@Copyrites This feature has been implemented in 0.86.0 and should work better.

When the option "hint captured pages" is checked, a badge number will be shown at the webscrapbook toolbar button, with different color for the level of matched captured pages: red for same URL (excluding the `#fragment`), yellow for same path(excluding `?query` and `#fragment`), green for same origin, and blue for same domain (e.g. `http:` vs `https:` or `www.*` vs `*`).

There's also a "view captured pages" command available to search for all matched captured pages in the scrapbook(s) for the current tab. Furthermore, you can select multiple tabs and get them checked at once.

**Comment by danny0838** [comment]
Re-capture is nearly resolved. Import/export is still difficult to implement, and we consider replacing it with cross-scrapbook item copying instead, for details see #158.

In-depth capture is a much more complicated issue. We consider demark it as an extra feature, which is something to be extended and won't be included in 1.0. 

So 1.0 should come out when re-capture and import/export/cross-scrapbook item copying is ok.

**Comment by danny0838** [comment]
Fortunately we found a way to implement in-depth capture (at least the basic features). There are still some minor issues about them, however, as mentioned in issues #164, #165, and #158, and we need some ideas/suggestions.

If there's nothing important to change, we are going to release 1.0. Also, contribution of localization is welcome, just edit [src/_locales/*/message.json](https://github.com/danny0838/webscrapbook/tree/master/src/_locales) and issue a pull request.

**Comment by danny0838** [comment]
We are going to release 1.0 in few updates.

One thing to mention is that previous converter from legacy ScrapBook (X) (including the site indexer in WebScrapBook < 0.78 and the sb2wsb converter in PyWebScrapBook < 35) converts mostly `scrapbook.rdf` and does not support conversion of all data pages.

PyWebScrapBook 35 has implemented the conversion of all data pages to convert all special elements generated by legacy ScrapBook (X), such as highlights, annotations, and combined pages, into corresponding WebScrapBook elements, which are  cross-browser compatible. Just follow the [guide](https://github.com/danny0838/webscrapbook/wiki/Diffs#compatibility) to perform a migration with `wsb convert sb2wsb` or `wsb convert migrate0`.

Additionally, **we plan to remove the current incomplete downward compatibility support of legacy ScrapBook (X) elements before WebScrapBook 1.0**, to improve performance and maintainability of the code, and prevent a potential confusion or mishandling.

**Comment by sulisu** [comment]
Is merge pages function implementated in webscrapbook? It will be very useful when the site seperate an article into several pages.

Thanks for this great work.

**Comment by danny0838** [comment]
> 
> 
> Is merge pages function implementated in webscrapbook? It will be very useful when the site seperate an article into several pages.
> 

You can use [in-depth capture](https://github.com/danny0838/webscrapbook/wiki/Basic#capture-linked-web-pages-in-depth-capture) for that.

If backend server is used, there's also a [merge capture](https://github.com/danny0838/webscrapbook/wiki/Basic#merge-capture) feature, but it's rather experimental and might have some issues.

**Comment by danny0838** [comment]
@Everest8 More good features have been implemented in WebScrapBook recently, such as the capture details dialog and site map. The current latest WebScrapBook version (0.135) is almost a release candidate and there should be no significant feature change before 1.0.

We wish that the first 1.* version of WebScrapBook be good enough for legacy ScrapBook X users to migrate to. Welcome to give it a try and report if there is still any question or any issue that blocks your from migration, so that we can do the essential updates before releasing 1.*.

You can always read the [documentation for WebScrapBook](https://github.com/danny0838/webscrapbook/wiki/Intro) and [migration guide and compatibility notes](https://github.com/danny0838/webscrapbook/wiki/Diffs#compatibility) from the wiki.

> Unfortunately, the latest Firefox version is not yet available in AMO since some young Mozilla reviewers are looking for trouble of our add-on and made the whole review process slow. You may have to install by using a developer version and packing the source, or try on a Chromium-based browser, at least for now.

**Comment by Everest8** [comment]
OK, thank you. I will try it during the holiday season. Thank you very much
for your great work! What you are doing is priceless.

Vitaly

**Comment by danny0838** [comment]
Released 1.0.0.
