### ISSUE TITLE
can't save the image on zhihu

### ISSUE THREAD

**Issue by PGKANG** [danny0838/webscrapbook#157]
This extension can work best on many website
But when I save a webpage of zhihu , it can't save the image on the page
And instead, the position of image will become blank
Here is my testing webpage https://zhuanlan.zhihu.com/p/25994179

**Comment by PGKANG** [comment]
And I use the server backend

**Comment by danny0838** [comment]
The web page loads only images that are scrolled into view, and thus you have to scroll the screen down to load them.

**Comment by PGKANG** [comment]
Yes but it still doesn't work. 
Have you tested my website https://zhuanlan.zhihu.com/p/25994179  and if it works, maybe it's the problem of my other extensions.

**Comment by PGKANG** [comment]
After I tested many times, the "capture tab" option can work but the "capture tab(original)" option can't. As the "capture tab(original)" is faster than "capture tab", I always use that option, but it's like the option sometimes doesn't work well.

**Comment by danny0838** [comment]
They work exactly as said. Capture (source) saves the source HTML befroe processed by any script. Since the page loads images dynamically via scripts, you of course won't get images using it.
