### ISSUE TITLE
Implementation of export/import and reworking of site indexer

### ISSUE THREAD

**Issue by danny0838** [danny0838/webscrapbook#158]
One important issue we have to work with is the **export/import** functionality, and the **site indexer** accordingly.

Due to the restriction of WebExtension framework, the user cannot simply pick a file system directory as the data directory to import or export scrapbook items. As a workaround, we may add a `export directory` config for PyWebScrapBook and make all exported files go there.

As for the importer, it may simply take all items from the `export directory` for importation, and optionally we may add a support to import via drag and drop of files and folders from the file explorer.

Current implementation of site indexer is a mix of data validator, importer, fulltext cache generator, and static site generator, and can index the backend server or a dropped directory or ZIP file from the filesystem. This makes it rather complicated and sometimes non-performant.

We plan to split the site indexer into a data validator (which works more like the `Calculation of Size` of legacy ScrapBook), a fulltext cache generator, and a static site generator.

As a side effect, manual site indexing (via drag and drop to the site indexer) and automatic importing (via adding files to the data directory and run site indexer again) will be dropped, and installing the backend server will be the only way to do site indexing. But as manual site indexing is rather cumbersome and many features can simply not be supported, we think it's the way to go.

Do you have any idea about this? Feel free to share with us.

**Comment by KitchM** [comment]
I'm totally against this.  If it can't be done automatically, it is far too much work for the user to perform.  Worse yet at the instructions at your link:
[(https://github.com/danny0838/webscrapbook/wiki/Intro#4-browser-sidebar-approach)]
Why should a user have to jump thru hoops to learn a new language (Python) to make something install correctly?  The error given is:
`Collecting webscrapbook
  Could not find a version that satisfies the requirement webscrapbook (from versions: )
No matching distribution found for webscrapbook
`
Yeah, it just doesn't work.  Kind of sad really.  No one can say I haven't given it a good try.

**Comment by danny0838** [comment]
@KitchM Using a backend server is because the browser extension framework simply forbid file system access, and after all it's an option rather than requirement. If you find it too hard or too bothering to install Python and PyWsb you can simply choose other approaches.

If you need a help to get PyWsb work, please provide more details: your OS, installed Python version, and the steps you used to install PyWsb, and full CLI messages, so that we can provide more assistant about that.

**Comment by KitchM** [comment]
I am always skeptical of any statement to the effect that something can't be done.  In your case, the answer is "Use a different framework".

Whenever the user might need help in installing and using a plugin, it isn't worth the effort.  That is why I removed it.

**Comment by danny0838** [comment]
The fact that browser does not support direct file system access has been there for a very long time, and related bugs or feature requests have been available in the bug tracker of the major browsers. You can simply Google to prove or disprove it.

You do can "use a different browser extension framework"—if you can invent a new browser and let people use it, or you can persuade Chromium or Mozilla developer to implement it. Unfortunately we don't have the resource to do it.

**Comment by KitchM** [comment]
I don't understand what you're writing about.  Any browser I use has menus that include File>Open File.

**Comment by danny0838** [comment]
File system access means direct access to the filesystem via script (or browser extension script). This is never supported by all major browsers, mostly due to security concern (imaging how dangerous would it be if a web site can directly read/write files from your disk).

Opening a file from the filesystem through the browser menu manually has nothing to do with it.

**Comment by KitchM** [comment]
> Opening a file from the filesystem through the browser menu manually has nothing to do with it.

Maybe it should.

**Comment by DudeMacDude** [comment]
Import/export is the functionality I need the most. One of the old scrapbooks had it, I assumed this did when I installed. Wish I could help.

Backend server works great though.

**Comment by danny0838** [comment]
@DudeMacDude Import/export has been implemented in PyWebScrapBook 0.25.0, but currently only CLI is provided.

Due to the restriction of new browser extension frameqork, the user can no more pick a local folder directly for importing and exporting directly, and we'll need a different design for exporting/importing using the GUI from the browser extension side.

**Comment by danny0838** [comment]
@DudeMacDude In WebScrapBook 0.89.0 support of cross-scrapbook item copying is added. Items can now be migrated to another scrapbook through the `Copy to` command in the context menu or through dragging and dropping (to obtain a window of another scrapbook, use the `Manage` command). The copied item will remain same ID, but if it's used in the target scrapbook, a new ID will be generated and used.

Cross-scrapbook item migration should be able to cover many use cases of exporting and importing, such as to migrate items to another scrapbook or to make a backup copy of items. 

Currently we still cannot come up with a good design for import/export, such as how to select a folder for importing/exporting, where and how to import/export if the server is remote. We are considering replacing import/export with cross-scrapbook item copying simply.

What are the usual cases you use import/export? Do you think cross-scrapbook item copying can replace import/export?

**Comment by danny0838** [comment]
We currently haven't found a better way to make the importer/exporter work with WebScrapBook, but will probably keep them for special purpose, until we found a better way to rework them.
