### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by KitchM** [danny0838/webscrapbook#159]
Under "Save captured data to:" and "Scrapbook folder:" why are these not combined into one like other programs?  This is confusing and seemingly unnecessary.  How is the user to find these places?  Can't you simply state the exact location?

**Comment by danny0838** [comment]
I don't get you. Saving to the backend server, download to a specified subdirectory, and download as a single save are just different things. How do you think they can be combined? Like which other program?

**Comment by KitchM** [comment]
As explained in my other post, I had misunderstood that your program works best as a client/server setup, and that changes everything.
