### ISSUE TITLE
Not able to install onto FF android

### ISSUE THREAD

**Issue by areimunde** [danny0838/webscrapbook#16]
It says addon is corrupted after downloading... Using FF android v49

**Comment by danny0838** [comment]
It seems to be an issue of Firefox Android core that installing an addon sometimes fails with an error saying that the addon is corrupted, but the addon is just ok and can be perfectly installed on Firefox Desktop. Installing on another time or restarting Firefox Android can solve this issue. Upgrading Firefox Android to the latest version may help, too.

**Comment by areimunde** [comment]
Thank you. I'll try those different options.

​Regards
,

*Alfonso Reimunde de Alfaro*

2017-11-10 7:06 GMT+01:00 Danny Lin <notifications@github.com>:
