### ISSUE TITLE
Backend Server Is Not Available

### ISSUE THREAD

**Issue by KitchM** [danny0838/webscrapbook#160]
I am using Debian 10 with Xfce 4.12 and Firefox Quantum  68.9.0esr.  Webscrapbook version is 0.75.2.

I left-click on icon and select Open ScrapBook.  I get the side-bar with a message in red that states "Backend server is not configured".

Why isn't it?  Why wasn't that done automatically?  Why should I need it if the data is just on one computer?  What must be done now?

**Comment by danny0838** [comment]
Have you set up the backend server? If not, [do it first](https://github.com/danny0838/webscrapbook/wiki/Intro#4-browser-sidebar-approach).

**Comment by KitchM** [comment]
You didn't directly answer my questions but I can make some assumptions based upon the link you provided.

And don't misunderstand; I do appreciate people who make add-ons to solve problems with the browser.  It is just that those who need to have help doing something do not need more work getting the solution to the problem in the first place.

From what I have learned, the basic concept is that your program requires a client/server setup and something running in the background to make the GUI portion of the program work for web page retrieval and viewing.  I must say that I do not like the idea of the extra overhead on my system.

I'll definitely have to consider this more carefully.

Thank you.
