### ISSUE TITLE
webscrapbook 0.68.0 以上版本在Firefox v52 ESR 版本 选中 捕获方式会出caNode.getRootNode错误

### ISSUE THREAD

**Issue by LFYG** [danny0838/webscrapbook#162]
如下面网站:

Capturing (document) [10] https://www.cnblogs.com/xiaozi/p/12963549.html ... 
Fatal error: caNode.getRootNode is not a function

webscrapbook 0.68.0 就会显示上面错误提示
webscrapbook 0.67.1 版本可以正常保存

**Comment by danny0838** [comment]
Firefox 52 不支援 getRootNode 才會出錯。0.75.3 已加上特殊處理。

**Comment by LFYG** [comment]
感谢 问题以解决
