### ISSUE TITLE
Post-it seems to move automatically

### ISSUE THREAD

**Issue by PGKANG** [danny0838/webscrapbook#163]
Sometimes i made a post-it note like this
![捕获1](https://user-images.githubusercontent.com/36464840/86861793-7e354a00-c0fa-11ea-81c2-8b95992e86f6.PNG)
But  after a few days , it would be like this 
![捕获2](https://user-images.githubusercontent.com/36464840/86861870-a8870780-c0fa-11ea-8f7b-c6047083882c.PNG)
It seems to move automatically

**Comment by danny0838** [comment]
Can you make sure whether the issue happens just after saving and reloading the page? And can you provide the source page URL?

**Comment by PGKANG** [comment]
This problem does not happen immediately.
This problem only occurs after a few days after I saved the page.
Here is my page URL 
https://zhuanlan.zhihu.com/p/37803719

**Comment by danny0838** [comment]
Do you resize the window?

Sticky notes are pixel-fixed, and thus their relative position to the web page content may shift when the window is resized like this:

![圖片](https://user-images.githubusercontent.com/531417/87752970-24d4c580-c834-11ea-8374-5ecc08bb81ba.png)
width = 890

![圖片](https://user-images.githubusercontent.com/531417/87752974-27371f80-c834-11ea-9507-35e4353f2683.png)
width = 793

This is normal behavior.

**Comment by PGKANG** [comment]
Yes, I do resize the window, and when I turn it back, the Sticky notes will come back in right place. Thanks !

**Comment by danny0838** [comment]
Close issue. Thank you for the feedback.
