### ISSUE TITLE
Capture again as ScrapBook X

### ISSUE THREAD

**Issue by danny0838** [danny0838/webscrapbook#165]
(excerpted from #153)

Frankly speaking, I am not sure why it should exist currently. Personally I would choose to just capture the original page again if I really need an update, as re-capture will basically overwrite everything—old content, old annotation, old resource files, etc.—and can possibly introduce a conflicting state, as resource files used by the old version and not by the new version are not removed, and as a re-capture is performed in a headless way.

The value I can currently think of is that it preserves the original item metadata (except for the modify time), but keeping an old metadata with new content is kind of inconsistent and I don't like it...

If we are going to implement it, the current idea is to move the old page files to a backup path (such as from `./*` to `./.history/<timestamp>/*`), save a new capture, and update the modify time metadata of the item. This should not be too difficult to implement, but how to support it for an item of ZIP-based archive or single HTML would be an issue. We may consider simply don't provide this feature for them if we cannot come up with a good solution.

Is there still someone that likes the re-capture feature? I'd like to know how you use it, why you like it, and how would you like it be implemented in WebScrapBook. Please share with us if you have an idea.

**Comment by spiralofhope** [comment]
I've always thought of "re-capture" as "delete this cache and replace it with a totally new copy", which also keeps any user contributions like comments.

**Comment by danny0838** [comment]
@spiralofhope Thank you for the feedback. We have thought about that, but as the page may change, it'd be difficult and somehow impossible to determinate where each comment in the old version page should go in the new version page.

**Comment by spiralofhope** [comment]
Maybe:

- If any inline comments exist, prompt to destroy them.
- If only that one main description area (at the bottom of the page) exists, and if no inline comments exist, then perform a delete-and-replace.

Personally I've used this functionality only because I'm too lazy to visit the source, delete my scrapbook then re-save it.

**Comment by danny0838** [comment]
Implemented in 0.87.0.

**Comment by spiralofhope** [comment]
If it's easy, would you consider keeping old comments and prepending them to the replacement download?

**Comment by danny0838** [comment]
You mean to migrate old highlights, sticky annotations etc from the old version to the new capture?

That's definitely not easy. As the page could change, the script cannot easily know where an old annotation should be placed in the new page.

**Comment by danny0838** [comment]
In 0.88.0 a basic annotation migration is implemented. Capture again will now attempt to migrate highlights and sticky annotations to the new capture, and warn about those that cannot be migrated due to DOM change of the newly capture.

Note that the current implementation is still rather basic. Implementing a reliable algorithm to determine where an annotation in the old version should be placed in the new version is very hard, some many complicated cases are not yet supported (such as an annotation in an iframe or shadow root, or an annotation of legacy ScrapBook), and a bad migration might still happen in some cases.

**Comment by spiralofhope** [comment]
What I meant was to just dump difficult annotations into a note so the data isn't lost.

**Comment by danny0838** [comment]
@spiralofhope 
> What I meant was to just dump difficult annotations into a note so the data isn't lost.

This seems interesting, but I still don't get it.

What are "difficult" annotations? For those that WSB doesn't know how to migrate, they are indeed difficult. But even more difficult ones are those that WSB doesn't even known they exist, let alone to do anything to it and let the data not lost.

What do you mean "a note"? Do you mean a new note item, the comment for the item being recaptured, or something else?

Also I can't get them matched with your previous comment:

> Maybe:
> 
>     * If any inline comments exist, prompt to destroy them.
> 
>     * If only that one main description area (at the bottom of the page) exists, and if no inline comments exist, then perform a delete-and-replace.

Do you mean highlights and sticky annotations when you say "inline comments"? But why prompt to destroy them?

What is "that one main description area (at the bottom of the page) exists"? You mean the item comment in legacy ScrapBook X? In WSB item comments will be kept as-is for a re-capture, so this probably isn't something we need to worry about.

**Comment by spiralofhope** [comment]
@danny0838 

I feel like I'm making things convoluted; I'm sure you've already made good decisions with this!

> What are "difficult" annotations? For those that WSB doesn't know how to migrate, they are indeed difficult. But even more difficult ones are those that WSB doesn't even know they exist, let alone do anything to them and let the data not lost.

Well I guess just remind the user that this might happen.

> What do you mean "a note"? Do you mean a new note item, the comment for the item being recaptured, or something else?

Sorry, I did mean the comment area.

> Do you mean highlights and sticky annotations when you say "inline comments"? But why prompt to destroy them?

Import them if possible.  If it is not possible to know where they go, then put them in the comment area.  If there is no way to know if there are comments or not, warn the user.

**Comment by danny0838** [comment]
@spiralofhope 
> Import them if possible. If it is not possible to know where they go, then put them in the comment area. If there is no way to know if there are comments or not, warn the user.

We do can append warnings to the comment, but we are not sure whether it's desired, as it doesn't seem more obvious than showing in the capture dialog. If warnings are already shown in the capture dialog, is it still meaningful to add them to the comment, or we can simply let the users who want that to copy them by themselves? Also, such information is probably useless if the user disables backup, in which case he won't be able to investigate what exact annotations are not migrated even if he's notified that some go wrong.

So currently we tend to show the warnings in the capture dialog only. There are still some issues to consider for current implementation, however:
1. If the user disables backup, the warning message about annotation migration failure is likely too late. Should we force backup if annotation migration failure is detected? Or, no, it's the user himself wants no backup, so just let it go?
2. Warnings may be ignored if the user checks `Auto-close capture dialog if successful`. Maybe we should rework that feature to `no auto-close`, `auto-close if no warning or error`, `auto-close if no error`, and `auto-close anyway`?

**Comment by spiralofhope** [comment]
@dann

> or we can simply let the users who want that to copy them by themselves?
> such information is probably useless if the user disables backup

These are good points.  As long as the user has been informed of the limitations and dangers, then everything is okay.

> 1. If the user disables backup, the warning message about annotation migration failure is likely too late. Should we force backup if annotation migration failure is detected? Or, no, it's the user himself wants no backup, so just let it go?

I suppose just inform them when they disable backups.  If they have disabled backups, and a problem is detected, just let it go.

If they have enabled backups, and a problem is detected, tell them and maybe identify the item (change its name to prepend `import problem - ` or something).

> 2. Warnings may be ignored if the user checks `Auto-close capture dialog if successful`. Maybe we should rework that feature to `no auto-close`, `auto-close if no warning or error`, `auto-close if no error`, and `auto-close anyway`?

Well a warning does not really mean "successful".  `:)`  So I suppose keep the dialog open.

**Comment by danny0838** [comment]
> > or we can simply let the users who want that to copy them by themselves?
> > such information is probably useless if the user disables backup
> 
> These are good points. As long as the user has been informed of the limitations and dangers, then everything is okay.
> 
> > 1. If the user disables backup, the warning message about annotation migration failure is likely too late. Should we force backup if annotation migration failure is detected? Or, no, it's the user himself wants no backup, so just let it go?
> 
> I suppose just inform them when they disable backups. If they have disabled backups, and a problem is detected, just let it go.
> 
> If they have enabled backups, and a problem is detected, tell them and maybe identify the item (change its name to prepend `import problem - ` or something).

Currently there is already a notice for the backup option, which a user attempting to disable auto backup should have read about:

![圖片](https://user-images.githubusercontent.com/531417/99073311-a83ed180-25f0-11eb-8549-5581501d481c.png)

Currently each backup is designed to be named as pure timestamp like `20200101000000000`. We do can add more details like `20200101000000000-recapture` or even `20200101000000000-recapture (with issues)`, but this may have a side effect and need more consideration. (For example, we may implement an auto backup management feature in the future, which automatically removes old backups, but may be designed to recognize only pure timestamp folders so that a user can mark a backup as notable/important and exempted from auto-removing by adding a description)

> 
> > 1. Warnings may be ignored if the user checks `Auto-close capture dialog if successful`. Maybe we should rework that feature to `no auto-close`, `auto-close if no warning or error`, `auto-close if no error`, and `auto-close anyway`?
> 
> Well a warning does not really mean "successful". `:)` So I suppose keep the dialog open.

A warning is not an error, and it may be possible for a normal capture to have a warning due to various causes. We already have [a doc about this](https://github.com/danny0838/webscrapbook/wiki/FAQ#why-does-the-capture-dialog-always-show-yellow-error-messages).

As a user who wants the capture dialog to be auto-closed may have different intention, we currently provide all possible behaviors and let the user decide:

![圖片](https://user-images.githubusercontent.com/531417/99074891-872bb000-25f3-11eb-9628-fad62006e1ac.png)
