### ISSUE TITLE
為什麼，不能編輯用webscrapbook保存的單一html文檔

### ISSUE THREAD

**Issue by newsdos** [danny0838/webscrapbook#166]
用webscrapbook保存的html單一文檔 用firefox打開後，此時卻不能編輯，而用其他的類似webedit卻可以。

用s i n g l e file 保存的單一html文檔打開時，也不能編輯。是什麽原因啊？

環境:firefox 78

**Comment by danny0838** [comment]
Firefox 對安全性要求比較嚴格，禁止所有本地硬碟（file:// 開頭的網址）的存取，因為一但開放，瀏覽器套件可以讀取所有本機硬碟的資料，有比較大的資安疑慮。

但即使允許編輯，直接編輯 file:// 也不符合 WebScrapBook 的設計，因為這樣編輯只能重新擷取，會儲存成另一檔案，且源網址、儲存時間等都會改動。

要編輯已儲存的頁面，請[透過後端伺服器及瀏覽器側欄](https://github.com/danny0838/webscrapbook/wiki/Intro-(zh_TW)#4-%E7%80%8F%E8%A6%BD%E5%99%A8%E5%81%B4%E6%AC%84%E5%9E%8B)。

**Comment by danny0838** [comment]
Close stale issue.
