### ISSUE TITLE
[Feature Request] Automatically save full-text index when saving web pages

### ISSUE THREAD

**Issue by PGKANG** [danny0838/webscrapbook#167]
After I saved a page, it can't be searched unless I generate site index for backend server. But this will take a long time because it will generate site index for all pages I have saved.

**Comment by danny0838** [comment]
For the current implementation, updating the fulltext cache requires downloading and re-uploading the whole fulltext cache file, which could be as large as tens to hundreds of MBs large. Doing this for every captured page is a large network traffic if hosted remotely.

We probably need to implement server-side scrapbook support beforehand, and, unfortunately, this is not a small work. We need some investigation for how to implement it.

**Comment by danny0838** [comment]
Implemented in 0.79.0
