### ISSUE TITLE
Change "Capture Folder" location

### ISSUE THREAD

**Issue by vsc55** [danny0838/webscrapbook#17]
You can not change the location where you save the captures.
When you put another location, replace the symbols: o .. with _ and use the desktop directory as a base.

![options_-_2017-11-15_12 08 02](https://user-images.githubusercontent.com/13438676/32833028-c0069764-c9fd-11e7-8134-7b416c93847a.png)

**Comment by vsc55** [comment]
OK thanks for the advice.

**Comment by Atanacius** [comment]
Symbolic Links works only under Linux if I remember well ..
In Windows, it's Shortcuts as far I know and not working as same Symbolic Links Linux would works!

**Comment by danny0838** [comment]
A symbolic link can be created using the `MKLINK` command in Windows.

**Comment by vsc55** [comment]
I have done it on windows with `mklink` and it works ok.

**Comment by vsc55** [comment]
Hi.
I've been looking and WebExtension if you can save data, right?
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/local

**Comment by danny0838** [comment]
You should head for #2 for this different question. Basically it is the "Browser database approach" mentioned and the restriction were also described there.
