### ISSUE TITLE
【Solved】"Browser sidebar approach" not working, help me please!!!

### ISSUE THREAD

**Issue by ssc777** [danny0838/webscrapbook#170]
![image](https://user-images.githubusercontent.com/33096569/92300741-dfa95600-ef8f-11ea-8cf1-e4ef9f117659.png)

After generating the config and launching the server, my Sidebar says "Unable to init tree: Directory does not exist."

I use the default settings recommended in the tutorial.

![image](https://user-images.githubusercontent.com/33096569/92300773-2dbe5980-ef90-11ea-958b-27929cf3cbb7.png)

How can I fix this?

Did I run the server correctly?
![image](https://user-images.githubusercontent.com/33096569/92300783-4e86af00-ef90-11ea-8531-f9f55d18098e.png)

**Comment by danny0838** [comment]
Seems there's currently a bug causing an error shown when the tree directory has not been generated.

Currently you can simply capture any webpage and then refresh the sidebar, and it should work correctly afterwards.

We'll fix this issue ASAP.

**Comment by ssc777** [comment]
> Seems there's currently a bug causing an error shown when the tree directory has not been generated.
> 
> Currently you can simply capture any webpage and then refresh the sidebar, and it should work correctly afterwards.
> 
> We'll fix this issue ASAP.

Currently, when I try to capture webpage, this thing shows up:
![image](https://user-images.githubusercontent.com/33096569/92304183-33c33300-efae-11ea-878e-0d15c9b8477a.png)

Also, nothing happens when I refresh the sidebar.

I was able to capture this webpage before I try the "Sidebar" related settings. 
Sidebar is the reason I need Web Scrapbook. So without the Sidebar, everything is nothing.

**Comment by danny0838** [comment]
> Currently, when I try to capture webpage, this thing shows up:
> ![image](https://user-images.githubusercontent.com/33096569/92304183-33c33300-efae-11ea-878e-0d15c9b8477a.png)
> 
> Also, nothing happens when I refresh the sidebar.
> 
> I was able to capture this webpage before I try the "Sidebar" related settings.
> Sidebar is the reason I need Web Scrapbook. So without the Sidebar, everything is nothing.

I was wrong... Only capturing a bookmark works, or manually create a `tree` folder under the scrapbook root directory (in your case it should be `D:\Scrapbook\tree`.

We have released a new version 0.75.6 that should fix this bug. It's already up in Firefox Addon site, but may take a few days to be available in Chrome Web Store, which requires review (which is sometimes very slow).

**Comment by ssc777** [comment]
> > Currently, when I try to capture webpage, this thing shows up:
> > ![image](https://user-images.githubusercontent.com/33096569/92304183-33c33300-efae-11ea-878e-0d15c9b8477a.png)
> > Also, nothing happens when I refresh the sidebar.
> > I was able to capture this webpage before I try the "Sidebar" related settings.
> > Sidebar is the reason I need Web Scrapbook. So without the Sidebar, everything is nothing.
> 
> I was wrong... Only capturing a bookmark works, or manually create a `tree` folder under the scrapbook root directory (in your case it should be `D:\Scrapbook\tree`.
> 
> We have released a new version 0.75.6 that should fix this bug. It's already up in Firefox Addon site, but may take a few days to be available in Chrome Web Store, which requires review (which is sometimes very slow).

Holy shit, it is working now!
Just manually create a folder named "tree", as you said, and it works....
![image](https://user-images.githubusercontent.com/33096569/92305800-219cc100-efbd-11ea-9f1b-664cf8ee4b6b.png)
And this is my first Scrapbook archive:
![image](https://user-images.githubusercontent.com/33096569/92305859-a12a9000-efbd-11ea-9e3a-a9b92275a226.png)
Damn, you are the boss!
Good job!
It's amazing!

**Comment by danny0838** [comment]
Further investigation revealed that this issue is related with a slight behavior change in the latest backend version.

In summary: for PyWebScrapBook < 0.17.0, 0.60.0 <= WebScrapBook <= 0.75.5 should work fine, while PyWebScrapBook >= 0.17.0 requires WebScrapBook >= 0.75.6
