### ISSUE TITLE
無法保存任何網頁，後端服務器初始化錯誤

### ISSUE THREAD

**Issue by yibie** [danny0838/webscrapbook#172]
每一次保存網頁都提示後端服務器初始化錯誤：

>后端服务器初始化错误: Require server app version >= 0.17.0.

請問這個是什麼意思，我應當如何應對？

**Comment by danny0838** [comment]
WebScrapBook 更新後 PyWebScrapBook 也要跟著升級才能相容。參見隔壁棚 #171
