### ISSUE TITLE
Test failures due to file permissions

### ISSUE THREAD

**Issue by maxnikulin** [danny0838/webscrapbook#174]
On Linux some tests fail, e.g.
```
code 403, message CGI script is not executable ('/capture_file/big5.py')
...
code 403, message CGI script is not executable ('/viewer-validate/htz-good.py')
```
There are at least a couple of dozens such files. Just setting executable bit is not enough
```
"GET /viewer-validate/htz-good.py HTTP/1.1" 200 -
/usr/bin/env: ‘python3\r’: No such file or directory
```
So it seems it is necessary to convert files from dos to unix newlines.

**Comment by danny0838** [comment]
Quickly fixed it. Thank you for reporting.

**Comment by maxnikulin** [comment]
Have I missed something and cgi scripts could be run the test server without executable permission bits set?
