### ISSUE TITLE
Use `Accept` header in reqests to specify response format

### ISSUE THREAD

**Issue by maxnikulin** [danny0838/webscrapbook#177]
Currently `f=json` or `f=sse` URL query parameter is added in the case of API call expecting non-default format. It is specific to particular backend application and makes implementation of robust external authentication (mentioned in https://github.com/danny0838/webscrapbook/issues/169#issuecomment-691151893) depending on internal details. If authentication is failed, error should be sent in the format requested by extension: JSON in the case of API call, HTML if the page is requested by regular browser tab.

In HTTP response format could be specified through sending `Accept` header, e.g. `application/json`.

To support standard way, modification of extension (noticeable) and backend (minor) is required. To maintain compatibility, at the first step both `f=` parameter and `Accept` header could be sent.

Backend might report supported features through `config` API endpoint. Extension might drop redundant `f=` parameter if it is notified that Accept header is supported.

**Comment by maxnikulin** [comment]
I have a draft, but it touches a file that had CRLF format that cause problems due to recent addition of .gitattributes, so #175 is some form is required at first.

**Comment by maxnikulin** [comment]
Since CLRF issue has been fixed, I have added a pull request to extension.

**Comment by maxnikulin** [comment]
Unsure if it is better to discuss general questions here or in particular pull requests

https://github.com/danny0838/PyWebScrapBook/pull/19#issuecomment-692556228 (backend)

> One reason is that there may be more than one format that map to same MIME type, such as different text/html output templating.

Certainly my concern is **MIME type** only, I "do not care" which particular **template** is used for result rendering. The aim is to provide response in correct format. `server.request`, besides setting of `Accept` header. could add parameters (to URL query or to body form fields) depending on the value of the `format` argument (other name could be used) if necessary.

https://github.com/danny0838/webscrapbook/pull/178#issuecomment-692547542 (extension)

> Although the current implementation expects JSON, it can safely fallback if the response format doesn't comply, especially for error responses that the response body is only informative.

I am aware of it. Of course extension should handle 500 errors with HTML from reverse proxy. On the other hand it is better to send response in the requested format.

This is a kind of proposal. If you need time to evaluate possible consequences of such change, it is up to you.

**Comment by danny0838** [comment]
Implemented (with some tweaks) in 0.78.0
