### ISSUE TITLE
too long a time before the save_dialog_box shows up

### ISSUE THREAD

**Issue by noisnemid** [danny0838/webscrapbook#18]
if there was only one add-on could be used, that will be scrapbook[x].
then the firefox updates to 'quantum', and the lovely scrapbook x could not work.
luckily we have this one, and thanks to you.
-------------------
there's a small problem with it:
[env = Firefox Quantum, nightly build, 58.0b4 (x64), windows 10 x64]
if a url could not be opened quickly according to the connection quality, the saving opreation of WEBSCRAPBOOK will get the user a long time to wait before the save_dialog_box shows up to chose a path where to save the MAF doc.
and what's worse, during this waiting moment, the WEBSACAPBOOK was UNAVAILABLE, all options except the last two could not be used.
there are 2 advices:
1. change the operation logic: show the save_dialog_box firstly, and gain the data secondly.
2. if the webpage was already opened, (it seemed naturally of this occasion), just gain the data from the cache(why not?)
-------------------
best regards.

**Comment by danny0838** [comment]
We'd investigate on it. But your assumption are probably not true:
1. All network traffic are async, that is, the GUI is not blocked even if the network traffic is extremely slow. The block of GUI mostly happen in a sync procedure, for example, the web page is vary large and WSB takes much time to analyse its DOM.

2. It is impossible to prompt the save dialog before we get the data to save.

3. Whether we can data from the cache is controlled by Firefox core, not our addon. Additionally, this is probably not the issue, as the 1. mentioned above.

**Comment by AI9906753** [comment]
i'll re-check it later on, thanks for replying.

**Comment by danny0838** [comment]
We improved the UI for capture. Please check if this issue still happens on the latest version.

**Comment by noisnemid** [comment]
it seems much better this time!
thank you so much!
