### ISSUE TITLE
Newest chrome ext ver. giving backend server ver. error

### ISSUE THREAD

**Issue by JustSomeCarrotSoup** [danny0838/webscrapbook#181]
I very recently updated all extensions in all of my browsers, and updated to newest PyWebScrapBook version (0.23.2).

Chrome webscrapbook extension (version 0.78.2 in both chrome in Chrome & Edge Dev) is giving error: **'Backend initilization error: Server app requires extension version >= 0.79.0.'**

Firefox webscrapbook extension (version 0.79.1) is working fine.

**Comment by danny0838** [comment]
We already sunitted the latest version to Chrome Web Store. Unfortunately Google seems to  review it slowly. 
 
Currently just wait for the latest version pass the review. If you are in need of using it with Chrome, you can selectively install the lower version of PyWebScrapBook:

    python -m pip install -U webscrapbook==0.22.0

**Comment by danny0838** [comment]
WebScrapBook 0.79.0 has passed review and available in Chrome Web Store now.
