### ISSUE TITLE
Configure The Backend 

### ISSUE THREAD

**Issue by Scarlett9999** [danny0838/webscrapbook#188]
Sorry To Bother Y'all 
Can someone give a step by step on how to configure the backend ?
Kali

**Comment by danny0838** [comment]
We already have the [documentation about setting up the backend server](https://github.com/danny0838/webscrapbook/wiki/Intro#3-browser-sidebar-approach). If you have a difficulty when attempt to follow any step, please describe in detail so that we can provide further assistant.

**Comment by Scarlett9999** [comment]
Hi there its saying it is still not configured - if it's not too much
trouble can you list all steps ?

**Comment by danny0838** [comment]
All steps are already listed in the linked documentation mentioned above, please just read it.

If you still have difficultly following those steps, please be specific on which step you have problem with, or maybe provide a video or a series of screenshots to show what you have done. If you can't even do those, you may have to find someone who can do those for you.

We are not aside you, unfortunately. We probably cannot provide more assistant if you don't provide more details.

**Comment by danny0838** [comment]
Close stale thread due to lack of further information.
