### ISSUE TITLE
[wishlist] Open multiple archive files in the viewer

### ISSUE THREAD

**Issue by fweng322** [danny0838/webscrapbook#19]
Just like the "Open all pages in tabs" in old ScrapBook, now WebScrapbook can only open a file at one time.  For the tree view we may handle it manually now (to change the filename, to put it into folder, ... etc.) if there are so many restrictions in WebExtension.  However if it can open all the pages in a folder by dragging the folder it will be a lot convenient (to me).

**Comment by danny0838** [comment]
It's a good idea to support opening multiple archive files at once. But I wonder whether to open a lot of tabs at once is a good idea. We may consider a little change: generate a list of link for each available page from the input archive files so that the user can click to view them (likely in a new tab, since the page is temporal and will be refreshed if the user clicks back). And if there is exactly one available page, redirect the viewer page to it.

**Comment by fweng322** [comment]
I'm not sure what you meant by "generate a list of link for each available page from the input archive files".  Did you mean when we drag a folder in, a temporary page including all the links to archived pages under the folder, and we click the link to open in new tabs?

When using old Firefox (<56) and Google chrome I frequently open about 15 bookmarked pages at the same time.  It's convenient to me especially when I was preparing for a speech (I gave a lot of speeches everywhere so it's even more important).  Your way (if I understand it correctly) works too but I just don't really realize what would happen or would harm to browsers or even systems when opening multiple tabs at the same time.

**Comment by danny0838** [comment]
> Did you mean when we drag a folder in, a temporary page including all the links to archived pages under the folder, and we click the link to open in new tabs?

You are almost there. But we probably would show them in the viewer page itself. (The viewer page is a temporary page)

> I just don't really realize what would happen or would harm to browsers or even systems when opening multiple tabs at the same time.

It is possible the folder the user drag contains a lot of subfolders and files, for example, hundreds or thousands, and it's probably not a good idea to open all of them in tabs at once.

**Comment by fweng322** [comment]
Well, it sounds like to prevent bad users behavior, but maybe a simple restriction and warning like "You can't open more than 20 archived pages at the same time" can do it.  At least in my usage about 15 pages opened at once didn't do any harm even using Google chrome.

**Comment by danny0838** [comment]
It sounds ok. However, if we consider dragging a folder with a lot of files to be an error and should be avoided, I wonder if there's a need to support dropping folders—as support of dropping multiple files is generally enough for this purpose.

For most common applications such as MS Word, dropping multiple files to open is acceptible, but dropping directories is not.

**Comment by fweng322** [comment]
Okay.  In the old ScrapBook or in the Google Chrome they didn't drag a folder either.  The operations were to right clicked the folder and select "open in tabs" in the context menu.  I think choosing multiple files instead of a folder to drag into the viewer is a reasonable behavior.  Thanks.

**Comment by danny0838** [comment]
Implemented on 0.19.0.
