### ISSUE TITLE
請問可以用於 Edge 嗎？

### ISSUE THREAD

**Issue by yibie** [danny0838/webscrapbook#190]
Edge 比 Chrome 要更加輕量

**Comment by danny0838** [comment]
可以，README 就有寫。但 Edge 商店能否上架還要研究其上架規範等細節才知道，目前可以先從 Chrome Web Store 安裝。

**Comment by danny0838** [comment]
已在 [Edge 商店](https://microsoftedge.microsoft.com/addons/detail/%E7%B6%B2%E9%A0%81%E5%89%AA%E8%B2%BC%E7%B0%BF/lodlipoddpmffbngkadebncbbidnambc)上架。

**Comment by yibie** [comment]
很棒，谢谢
