### ISSUE TITLE
No option to generate the tree file map.html (v 0.95.0)

### ISSUE THREAD

**Issue by MisterAlanBradley** [danny0838/webscrapbook#192]
Hi,

im running the latest version of server an extension and I am missing the option to generate the tree file. In the past there was an option in the context menu. But I can't find it anymore. Has that feature been removed? Or has it just moved?

**Comment by danny0838** [comment]
Site indexer has been moved to `backend server - indexer` and `- Checker` sections in the options since [0.79](https://github.com/danny0838/webscrapbook/blob/master/CHANGELOG.md#0790---2020-10-06).

**Comment by danny0838** [comment]
Close stale issue wihout further feedback.
