### ISSUE TITLE
Can't scrape chrome webstore page

### ISSUE THREAD

**Issue by acowdont** [danny0838/webscrapbook#194]
Capturing (document) [3092] https://chrome.google.com/webstore/detail/webscrapbook/oegnpmiddfljlloiklpkeelagaeejfai ...
Unable to execute content script ([3092:0] https://chrome.google.com/webstore/detail/webscrapbook/oegnpmiddfljlloiklpkeelagaeejfai): The extensions gallery cannot be scripted.
Fatal error: Could not establish connection. Receiving end does not exist.

**Comment by danny0838** [comment]
As the error messages says, the extensions gallery cannot be scripted (and thus captured by extensions, including WebScrapBook). See [related FAQ](https://github.com/danny0838/webscrapbook/wiki/FAQ#why-an-error-always-occur-when-capturing-a-page-in-chrome-web-store-or-firefox-add-ons) for more details.
