### ISSUE TITLE
网页抓取后功能缺失

### ISSUE THREAD

**Issue by lsj8924** [danny0838/webscrapbook#198]
https://www.qianbo.com.cn/Tool/Beautify/Js-Formatter.html
html抓取很好，但是js具体功能没有了。

**Comment by danny0838** [comment]
可以試試修改「腳本」擷取選項，但不保證所有腳本都能在離線環境下正常運作，詳見[FAQ](https://github.com/danny0838/webscrapbook/wiki/FAQ-(zh_TW)#%E6%93%B7%E5%8F%96%E9%81%B8%E9%A0%85%E5%8B%BE%E9%81%B8%E4%BA%86%E8%85%B3%E6%9C%AC%E4%BD%86%E5%84%B2%E5%AD%98%E7%9A%84%E8%85%B3%E6%9C%AC%E7%84%A1%E6%B3%95%E9%81%8B%E4%BD%9C)。
