### ISSUE TITLE
Infobar Not Present on DailyBeast and similar technology saved pages

### ISSUE THREAD

**Issue by sj365** [danny0838/webscrapbook#199]
WebScrapBook v0.97.0
Chrome Version 88.0.4324.96 (Official Build) (64-bit)

Save page of DailyBeast web article, page will save properly but without Infobar. 
Save page of MSN.com or other internet webpage, page will save properly and have Infobar.

Windows 10 Education
20H2
19042.746
Windows Feature Experience Pack 120.2212.551.0

Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz 2.81 GHz
32.0 GB Ram
64-bit operating system, x64-based processor

**Page saved Infobar missing**
https://www.thedailybeast.com/brandon-hunt-maga-obsessed-x-ray-ultra-nyc-court-worker-charged-with-threatening-to-murder-democrats

[brandon-hunt-maga-obsessed-x-ray-ultra-nyc-court-worker-charged-with-threatening-to-murder-democrats (1).zip](https://github.com/danny0838/webscrapbook/files/5849372/brandon-hunt-maga-obsessed-x-ray-ultra-nyc-court-worker-charged-with-threatening-to-murder-democrats.1.zip)

**Page saved Infobar present**
https://www.msn.com/en-us/autos/news/best-marantz-cd6007-deals-2021/ar-BB1cXhmf

[ar-BB1cXhmf.zip](https://github.com/danny0838/webscrapbook/files/5849395/ar-BB1cXhmf.zip)

**Comment by danny0838** [comment]
The site banner is set to be almost the largest z-index (2147483646, while the largest is 2147483647), causing the infobar be covered up.

The infobar was set to be a very large z-index (2147483640) to prevent overriding some important site banner, but it seems that we should force it to be uppermost instead. This will be implemented in the next release.
