### ISSUE TITLE
[wishlist] Edit highlight in grabbed page and save

### ISSUE THREAD

**Issue by fweng322** [danny0838/webscrapbook#20]
This is a very important feature in ScrapBook.  It will be great and I'll appreciate very much if this feature can be implemented

**Comment by danny0838** [comment]
Currently this still depends on #2.

**Comment by leedoyle** [comment]
Can't wait to see this feature again.

**Comment by danny0838** [comment]
Implemented basic highlighting features in 0.54.0.
