### ISSUE TITLE
Request for enhancement OR request for enlightment of a dull user

### ISSUE THREAD

**Issue by uhu53** [danny0838/webscrapbook#203]
Hi all,
I have been a frequent user of Scrapbook and -X and tried to squeeze WebScrapBook (wsb) to handle  HTML-Documenation-Trees residing on the Web (1) or locally in FS trees (2). I appreciate wsb's ability to annotate HTML.

**(1) download with wsb the head of the HTML tree \<URL\>**
- note the directory \<dir\> it creates
- cd <dir> (e.g. ~/var/WebScrapBook/\<dir\>)
- wget -rk -A\<something\> \<URL\>
**- ALL DONE**

**(2) HTML tree residing on the local FS (e.g. under /usr/share/doc/\<something\>)**
- \# cd /usr/share/doc/\<something\>
- \# chown -R \<user\>:\<user\> \<html\>
- download with wsb \<something\>
- note the directory <dir> it creates
- cd \<dir\>/.. (e.g. ~/var/WebScrapBook)
- rm -fr \<dir\>
**- ln -s /usr/share/doc/\<something\> \<dir\>**
**- ALL DONE, BUT ...**

after having annotated (parts of the HTML tree) and wsb SAVED the annotations, the next day and time I booted the machine the annotations have been lost. WHY?
Is it me to be blamed or what is it? Where and how are the wsb-annotations saved, written to the FS? I had a quick look at <wsbDir>/data and <wsbDir>/.wsb but came to no clue.

I don't remember having lost annotations I created with method (1)

I appreciate your answer very much
thank you
Ueli Hugenschmidt

**Comment by danny0838** [comment]
WSB saves annotation just in the HTML DOM. You can either (1) run `Edit page` on a web page, add annotation in it, and then save (which simply makes a capture) the web page with the annotations; or (2) set up the backend server, capture the web page, open the captured page from the sidebar, add annotation, and then save it (which saves the modification back to the backend server). 

You should not annotate a captured web page that is opened from the local FS instead of via the backend server. In this case the saving will create a new capture instead of saving, just like the above (1) case.

**Comment by uhu53** [comment]
sorry danny,

many thank for your immediate response!

I struggled with HTML edit to post my request, i.e. escape \\< and \\>.
I'm therefore not sure whether I made myself clear OR -
does your answer apply too for the corrected version?

I got that the annotations are written into the HTML DOM, i.e. the captured HTML itself.
Yes, I use the backend server

**Comment by danny0838** [comment]
Sorry, I still don't understand your question...

- What is `the head of the HTML tree`?
- What is the wget for (1)? I don't see anything about WSB capture and the backend server...
- What is the `# cd /usr/share/doc/<something>` and `# chown -R <user>:<user> <html>`?
- How do you `download with WSB` in case (2)?
- What does the `rm` and `ln` for in the case (2)?
- How do you visit the WSB capture the next day and time you booted the machine?
- ......

**Comment by uhu53** [comment]
Hi Danny,
another block I stumbled upon, I did not check the EMail but stared at
GitHub/wsb... (and went to bed afterwards)So, sorry for the late answer
I use wsb mainly to make annotations (mostly highlighting) in SW or HW
manuals and as a bookshelf for interesting web pages and HTML files
(files that lie around on my computer).
I use wsb with it's backend server.I have learned that the wsb
annotations are stored in the HTML DOM, the HTML file itself.
 * method (1): WebScrapBook got useful for me, as I found a workaround
for the yet missing recursive or deep capture.
 * method (2): The other squeeze of wsb  I came up with, was to let
WebScrapBook point to a HTML manual that I have already on my
filesystem (FS)This might be a manual that came with the software or
sometimes with hadware like a graphic card. Why have that manual twice
on the computer, e.g. under 	/usr/share/doc/<some softwareDocu> 	
	and wsb's data directory like 	<home>/var/WebScrapBook/<some
wsb identifier>? For me the software package that contains that manual
is the source, has prevalence. Although as I notice now, when I get a
software update, this manual with its probable annotations gets
overwritten, if I don't pay attention.

> What is the head of the HTML tree?
as head of a HTML tree I understand some HTML page <TheURL> with links,
e.g. to subchapters. 
Let's say this HTML page is the front page or the table of contents of
a manual. 
I would like to have the whole manual under wsb = I would like to have
the whole HTML tree, directory tree (FS tree), wherein the HTML files
of that manual are reside.
So a manual, a book in general, has for me a tree structure, if it's
coded in HTML, it's a HTML tree.
> What is the wget for (1)? I don't see anything about WSB capture and
> the backend server...
wget is the instrument to fetch that entire HTML tree, manual  (not
always possible).
wget as a workaround for the yet missing recursive or deep capture
(like the original Scrapbook had). 

like: wget -R(ecursive) -k (transform the links within the fetched HTML
files for local FS use) -A(ccept) <eg.*.html (files)> <TheURL>

wget produces a filesystem (FS) tree (directory tree structure)
following the structure of the file storage of the webserver.  The web
pages are HTML files in that FS tree.
In method (1) I place that FS tree under a directory created by and
known by wsb.
> What is the # cd /usr/share/doc/<something> and # chown -R
> <user>:<user> <html>?
The user root (allmighty administrator of the computer) is the owner of
/usr/share/doc and its many subdirectories and of all the files
therein. As I run the wsb backend server as normal user I have to
change the ownership of the concerning FS subtree to the normal user I
use.

> How do you download with WSB in case (2)?
I don't, all the HTML files are already here, see above under method
(2)
 * What does the rm and ln for in the case (2)?With wsb and its backend
server I fetched beforhand some page and placed that under <some name>
in wsb's content tree (in my case the tree I see in the left panel in
firefox).Associated with this <some name> is on the FS in wsb's data
directory (like <home>/var/WebScrapBook/<someNumber> in my case) with
an arbitray number as name <wsbSomeNumberDir>; arbitrary for me.My
squeeze to let wsb point to some arbitrary directory of the FS is the
following: I replace the wsb generated directory <wsbSomeNumberDir>
with a softlink (FS pointer). That softlink has the same name as
<wsbSomeNumberDir> and it point to the head of the FS tree where the
HTML manual resides in. In the example above, it points to
/usr/share/doc/<someSoftwareDocu>.The rm phrase removes first the wsb
generated directory <wsbSomeNumberDir>the ln followup creates the
softlink to /usr/share/doc/<someSoftwareDocu> under the softlink name
<wsbSomeNumberDir>.

> How do you visit the WSB capture the next day and time you booted the
> machine?
I opened it in wsb, backend server running, in firefox
P.S. * As I added in some Versions to the Issue(s)  in GitHub:  I don't
remember to have seen any error/warning message upon my wsb-saves (in
the issue under (2).
 * If it's not some phanthom born in my head alone that I hunt: could
it be that the wsb backend server can't cope with unix symlinks -  +/-
equivalent to MS Windows shortcuts
 * I don't remember to have experienced any annotation losses under
method (1), BUT ...?
 * Could it be that I have overseen some advice that came with some wsb
update?
 * A vage idea concerning the 'recapture problem' - I too stumbled upon
it above, last phrase under method (2) - well, very banal, one would
have to integrate some pre-existing HTML compare tool, that leads the
user through all differences between the old and current captured
versions. Like MS Word's review function: accept / reject /... the wsb
annotation, all annotations in matching cases, list annotation orphans.
For sure not an ease and cheap enhancement at all!
 * and lastly, I worked the last 18 years, before my retirement two
years ago, as a software engineer with SGML manuals, i.e. Aircraft and
Engine maintenance manuals (SGML -> HTML -> XML) for an Aircraft and
Engine Maintenance Company. Mostly with perl and SGML parsers, but also
Oracle and other languages, mixed Unix and Windows environment.

So, many thanks for your kind involvement
btw: what's the timeshift between Taiwan and Zurich in Switzerland? Ah:
+7hrs, you're in the middle of the night or earliest morning.
Ueli

**Comment by uhu53** [comment]
Danny,
I must correct myself and hope that I did not lead you too far into
wrong directions.
Sorry for that!
I have a look at the wrong encoding wsb complains about.  I already saw
other inconsitencies/errors in my setup.
We will see.
have a nice day
Ueli
Update to method (2):I oversaw the error messages of wsb that actually
have been there. 
Upon a quick test of what I have done, wsb-save spits the error
message:
Saving (document) [29] 
http://localhost:8080/20210204201503340/configtwinview.html ...
Unable to save a file with non-UTF-8 encoding (
http://localhost:8080/20210204201503340/configtwinview.html).
Updating server index for item "20210204201503340"...
Done.
and the same as wider screenshot




-------- Forwarded Message --------From: uhu <
u.hugenschmidt@swissonline.ch>Reply-To: u.hugenschmidt@swissonline.chTo
: 
reply@reply.github.comSubject
: Re: [danny0838/webscrapbook] Request for enhancement OR request for
enlightment of a dull user (#203)Date: Fri, 05 Feb 2021 20:30:45 +0100
Hi Danny,
another block I stumbled upon, I did not check the EMail but stared at
GitHub/wsb... (and went to bed afterwards)So, sorry for the late answer
I use wsb mainly to make annotations (mostly highlighting) in SW or HW
manuals and as a bookshelf for interesting web pages and HTML files
(files that lie around on my computer).
I use wsb with it's backend server.I have learned that the wsb
annotations are stored in the HTML DOM, the HTML file itself.
 * method (1): WebScrapBook got useful for me, as I found a workaround
for the yet missing recursive or deep capture.
 * method (2): The other squeeze of wsb  I came up with, was to let
WebScrapBook point to a HTML manual that I have already on my
filesystem (FS)This might be a manual that came with the software or
sometimes with hadware like a graphic card. Why have that manual twice
on the computer, e.g. under 	/usr/share/doc/<some softwareDocu> 	
	and wsb's data directory like 	<home>/var/WebScrapBook/<some
wsb identifier>? For me the software package that contains that manual
is the source, has prevalence. Although as I notice now, when I get a
software update, this manual with its probable annotations gets
overwritten, if I don't pay attention.

> What is the head of the HTML tree?
as head of a HTML tree I understand some HTML page <TheURL> with links,
e.g. to subchapters. 
Let's say this HTML page is the front page or the table of contents of
a manual. 
I would like to have the whole manual under wsb = I would like to have
the whole HTML tree, directory tree (FS tree), wherein the HTML files
of that manual are reside.
So a manual, a book in general, has for me a tree structure, if it's
coded in HTML, it's a HTML tree.
> What is the wget for (1)? I don't see anything about WSB capture and
> the backend server...
wget is the instrument to fetch that entire HTML tree, manual  (not
always possible).
wget as a workaround for the yet missing recursive or deep capture
(like the original Scrapbook had). 

like: wget -R(ecursive) -k (transform the links within the fetched HTML
files for local FS use) -A(ccept) <eg.*.html (files)> <TheURL>

wget produces a filesystem (FS) tree (directory tree structure)
following the structure of the file storage of the webserver.  The web
pages are HTML files in that FS tree.
In method (1) I place that FS tree under a directory created by and
known by wsb.
> What is the # cd /usr/share/doc/<something> and # chown -R
> <user>:<user> <html>?
The user root (allmighty administrator of the computer) is the owner of
/usr/share/doc and its many subdirectories and of all the files
therein. As I run the wsb backend server as normal user I have to
change the ownership of the concerning FS subtree to the normal user I
use.

> How do you download with WSB in case (2)?
I don't, all the HTML files are already here, see above under method
(2)
 * What does the rm and ln for in the case (2)?With wsb and its backend
server I fetched beforhand some page and placed that under <some name>
in wsb's content tree (in my case the tree I see in the left panel in
firefox).Associated with this <some name> is on the FS in wsb's data
directory (like <home>/var/WebScrapBook/<someNumber> in my case) with
an arbitray number as name <wsbSomeNumberDir>; arbitrary for me.My
squeeze to let wsb point to some arbitrary directory of the FS is the
following: I replace the wsb generated directory <wsbSomeNumberDir>
with a softlink (FS pointer). That softlink has the same name as
<wsbSomeNumberDir> and it point to the head of the FS tree where the
HTML manual resides in. In the example above, it points to
/usr/share/doc/<someSoftwareDocu>.The rm phrase removes first the wsb
generated directory <wsbSomeNumberDir>the ln followup creates the
softlink to /usr/share/doc/<someSoftwareDocu> under the softlink name
<wsbSomeNumberDir>.

> How do you visit the WSB capture the next day and time you booted the
> machine?
I opened it in wsb, backend server running, in firefox
P.S. * As I added in some Versions to the Issue(s)  in GitHub:  I don't
remember to have seen any error/warning message upon my wsb-saves (in
the issue under (2).
 * If it's not some phanthom born in my head alone that I hunt: could
it be that the wsb backend server can't cope with unix symlinks -  +/-
equivalent to MS Windows shortcuts
 * I don't remember to have experienced any annotation losses under
method (1), BUT ...?
 * Could it be that I have overseen some advice that came with some wsb
update?
 * A vage idea concerning the 'recapture problem' - I too stumbled upon
it above, last phrase under method (2) - well, very banal, one would
have to integrate some pre-existing HTML compare tool, that leads the
user through all differences between the old and current captured
versions. Like MS Word's review function: accept / reject /... the wsb
annotation, all annotations in matching cases, list annotation orphans.
For sure not an ease and cheap enhancement at all!
 * and lastly, I worked the last 18 years, before my retirement two
years ago, as a software engineer with SGML manuals, i.e. Aircraft and
Engine maintenance manuals (SGML -> HTML -> XML) for an Aircraft and
Engine Maintenance Company. Mostly with perl and SGML parsers, but also
Oracle and other languages, mixed Unix and Windows environment.

So, many thanks for your kind involvement
btw: what's the timeshift between Taiwan and Zurich in Switzerland? Ah:
+7hrs, you're in the middle of the night or earliest morning.
Ueli

**Comment by danny0838** [comment]
1\. It would be better to post via GitHub UI rather than email, which could cause many typography issue as GitHub parses markdown syntax, which is not visible in general email editors.

2\. The latest WSB DOES support deep capture, via `Capture - capture links > Depth to capture linked pages`, and using wget should be not required.

3\. PyWSB generally expects that data files are under its root folder (the one that contains the `.wsb` folder). Symlinking an item to local file system files may work, but is generally not encouraged as it's not portable. PyWSB does not guarantee that symlinks will be well-supported, although there's been no reason to strictly forbid it currently.

If you simply want a reference to local FS files, you probably should capture the index page as a bookmark. If you want to annotate the pages, you probably should perform a deep capture of the index page, which creates a copy of all pages in WSB.

4\. As the error message you've provided, it's clear that WSB rejects to save the annotated page as the encoding is not supported. WSB supports only UTF-8 encoded HTML pages currently, as the browser support for encoding conversion is limited. Another possible issue is, as you have mentioned, that the source web pages may get overwritten when the system updates, and the added annotations will be gone.

**Comment by uhu53** [comment]
Hi Danny,
thanks for your help!
Update to method(2):I changed in the html-files the encoding to UTF-8
<meta ... content=" ... charset=UTF-8"> and wsb-save works.

In order to protect my annotations from unprepared updates (via
software pgk updates) , I copied the html-files from somewhere into
the corresponding wsb data directory.
In wsb itself I cannot replace the files unintentionally with a newer
version from the web, as wsb does not find its source indication in the
file itself. Even better.

At the moment everything works fine
again, many thanks
Ueli-------- Forwarded Message --------From: uhu <
u.hugenschmidt@swissonline.ch>Reply-To: u.hugenschmidt@swissonline.chTo
: 
reply@reply.github.comSubject
: UPDATE: Re: [danny0838/webscrapbook] Request for enhancement OR
request for enlightment of a dull user (#203)Date: Sat, 06 Feb 2021
11:25:48 +0100
Danny,
I must correct myself and hope that I did not lead you too far into
wrong directions.
Sorry for that!
I have a look at the wrong encoding wsb complains about.  I already saw
other inconsitencies/errors in my setup.
We will see.
have a nice day
Ueli
Update to method (2):I oversaw the error messages of wsb that actually
have been there. 
Upon a quick test of what I have done, wsb-save spits the error
message:
Saving (document) [29] 
http://localhost:8080/20210204201503340/configtwinview.html ...Unable
to save a file with non-UTF-8 encoding (
http://localhost:8080/20210204201503340/configtwinview.html).
Updating server index for item "20210204201503340"...Done.
and the same as wider screenshot





-------- Forwarded Message --------From: uhu <
u.hugenschmidt@swissonline.ch>Reply-To: u.hugenschmidt@swissonline.chTo
: 
reply@reply.github.comSubject
: Re: [danny0838/webscrapbook] Request for enhancement OR request for
enlightment of a dull user (#203)Date: Fri, 05 Feb 2021 20:30:45 +0100
Hi Danny,
another block I stumbled upon, I did not check the EMail but stared at
GitHub/wsb... (and went to bed afterwards)So, sorry for the late answer
I use wsb mainly to make annotations (mostly highlighting) in SW or HW
manuals and as a bookshelf for interesting web pages and HTML files
(files that lie around on my computer).
I use wsb with it's backend server.I have learned that the wsb
annotations are stored in the HTML DOM, the HTML file itself.
 * method (1): WebScrapBook got useful for me, as I found a workaround
for the yet missing recursive or deep capture.
 * method (2): The other squeeze of wsb  I came up with, was to let
WebScrapBook point to a HTML manual that I have already on my
filesystem (FS)This might be a manual that came with the software or
sometimes with hadware like a graphic card. Why have that manual twice
on the computer, e.g. under 	/usr/share/doc/<some softwareDocu> 	
	and wsb's data directory like 	<home>/var/WebScrapBook/<some
wsb identifier>? For me the software package that contains that manual
is the source, has prevalence. Although as I notice now, when I get a
software update, this manual with its probable annotations gets
overwritten, if I don't pay attention.

> What is the head of the HTML tree?
as head of a HTML tree I understand some HTML page <TheURL> with links,
e.g. to subchapters. 
Let's say this HTML page is the front page or the table of contents of
a manual. 
I would like to have the whole manual under wsb = I would like to have
the whole HTML tree, directory tree (FS tree), wherein the HTML files
of that manual are reside.
So a manual, a book in general, has for me a tree structure, if it's
coded in HTML, it's a HTML tree.
> What is the wget for (1)? I don't see anything about WSB capture and
> the backend server...
wget is the instrument to fetch that entire HTML tree, manual  (not
always possible).
wget as a workaround for the yet missing recursive or deep capture
(like the original Scrapbook had). 

like: wget -R(ecursive) -k (transform the links within the fetched HTML
files for local FS use) -A(ccept) <eg.*.html (files)> <TheURL>

wget produces a filesystem (FS) tree (directory tree structure)
following the structure of the file storage of the webserver.  The web
pages are HTML files in that FS tree.
In method (1) I place that FS tree under a directory created by and
known by wsb.
> What is the # cd /usr/share/doc/<something> and # chown -R
> <user>:<user> <html>?
The user root (allmighty administrator of the computer) is the owner of
/usr/share/doc and its many subdirectories and of all the files
therein. As I run the wsb backend server as normal user I have to
change the ownership of the concerning FS subtree to the normal user I
use.

> How do you download with WSB in case (2)?
I don't, all the HTML files are already here, see above under method
(2)
 * What does the rm and ln for in the case (2)?With wsb and its backend
server I fetched beforhand some page and placed that under <some name>
in wsb's content tree (in my case the tree I see in the left panel in
firefox).Associated with this <some name> is on the FS in wsb's data
directory (like <home>/var/WebScrapBook/<someNumber> in my case) with
an arbitray number as name <wsbSomeNumberDir>; arbitrary for me.My
squeeze to let wsb point to some arbitrary directory of the FS is the
following: I replace the wsb generated directory <wsbSomeNumberDir>
with a softlink (FS pointer). That softlink has the same name as
<wsbSomeNumberDir> and it point to the head of the FS tree where the
HTML manual resides in. In the example above, it points to
/usr/share/doc/<someSoftwareDocu>.The rm phrase removes first the wsb
generated directory <wsbSomeNumberDir>the ln followup creates the
softlink to /usr/share/doc/<someSoftwareDocu> under the softlink name
<wsbSomeNumberDir>.

> How do you visit the WSB capture the next day and time you booted the
> machine?
I opened it in wsb, backend server running, in firefox
P.S. * As I added in some Versions to the Issue(s)  in GitHub:  I don't
remember to have seen any error/warning message upon my wsb-saves (in
the issue under (2).
 * If it's not some phanthom born in my head alone that I hunt: could
it be that the wsb backend server can't cope with unix symlinks -  +/-
equivalent to MS Windows shortcuts
 * I don't remember to have experienced any annotation losses under
method (1), BUT ...?
 * Could it be that I have overseen some advice that came with some wsb
update?
 * A vage idea concerning the 'recapture problem' - I too stumbled upon
it above, last phrase under method (2) - well, very banal, one would
have to integrate some pre-existing HTML compare tool, that leads the
user through all differences between the old and current captured
versions. Like MS Word's review function: accept / reject /... the wsb
annotation, all annotations in matching cases, list annotation orphans.
For sure not an ease and cheap enhancement at all!
 * and lastly, I worked the last 18 years, before my retirement two
years ago, as a software engineer with SGML manuals, i.e. Aircraft and
Engine maintenance manuals (SGML -> HTML -> XML) for an Aircraft and
Engine Maintenance Company. Mostly with perl and SGML parsers, but also
Oracle and other languages, mixed Unix and Windows environment.

So, many thanks for your kind involvement
btw: what's the timeshift between Taiwan and Zurich in Switzerland? Ah:
+7hrs, you're in the middle of the night or earliest morning.
Ueli

**Comment by danny0838** [comment]
Again, please reply using GitHub UI rather than Email, as it makes lots of typography issues and make me hard to read, quote, and reply your comment.

Copying HTML files into a WSB item folder is better, but is still an "off-label use" and may cause a side effect, such as incomplete fulltext indexing. Read [scheme](https://github.com/danny0838/webscrapbook/wiki/Scheme) for further details.
