### ISSUE TITLE
是否可以將資料直接獲取到某個資料夾內？

### ISSUE THREAD

**Issue by yibie** [danny0838/webscrapbook#207]
因為平時很喜歡用 Scrapbook 來匯集資料，然而，資料獲取數量變多後，發現在整理方面變得麻煩起來。

我會給資料分類成不同的文件夾，不同方向的資料會放進不同的文件夾裡。然而，因為 Scrapbook 本身是樹狀列表，網頁資料的移動單純依靠鼠標，因此在整理通常要花很大的力氣。

不知道這是否可以構成功能改進的建議？

再次感謝開發者開發了這麼好的瀏覽器套件，在下使用十分愉快。

**Comment by danny0838** [comment]
與#202重複。我知道目前功能還沒那麼友善，不過目前還沒有夠好的設計方案……

**Comment by yibie** [comment]
了解了，看來是瀏覽器採用沙盒安全機制有關，隔離瀏覽器套件與本地文件的交互

**Comment by danny0838** [comment]
該串有人主張擷取時直接放到抓側欄選擇的資料夾，但是側欄選擇的不一定就是想存放的，可能造成混淆；此外也可能發生多開側欄的情況。

目前看起來大部分使用者還是比較偏好像傳統 ScrapBook 在擷取時選擇目標資料夾的方式，目前WSB 是有「擷取為」，只是要修改 JSON，沒那麼友善，但 JSON 功能很靈活，所以一時半刻還想不出如何做成圖形介面…目前比較接近的方式是可以從側欄拖放資料夾到 JSON 編輯欄位的 parentId。

有什麼建議可以回覆原討論串（中文可，不過已經有老外參與所以能的話盡量用英文方便大家討論）
