### ISSUE TITLE
Can't find how to use Include these URLs or URL filter options

### ISSUE THREAD

**Issue by marjorieRobert** [danny0838/webscrapbook#210]
Hello, 
I'm using WebScrapBook Firefox add-on to save an entire web site.
I would like to save the pages from the web site http://www-bananas.abc.de.fr but I can't find how to limit the capture to the pages from this domain URL.
I tried to 'include these URLs'
```
###allow only bananas
bananas
```
or to exclude others URLs by using "URL filter" options
```
###skip common logout URL
/[/=]logout\b/i
## skip others
wikimedia
```

But the log shows that it doesn't work...
```
Capturing (document) [1] http://www-bananas.abc.de.fr/doku.php ...
Error downloading file (http://upload.wikimedia.org/wikipedia/en/1/18/Monobook-bullet.png): 404 Not Found
Saving data...
Rebuilding links...
Saved to "C:\Users\RobertM\Downloads\WebScrapBook\data\20210315220852094\index.html"
Done.

```
Can you help me to write the good expression? I tried a lot of combinaison but the filter never works.
Thank you.

**Comment by danny0838** [comment]
You can only specify a full URL or a RegExp. Such as:

    # allow http://www-bananas.abc.de.fr/bananas only
    http://www-bananas.abc.de.fr/bananas

    # allow any URL containing "bananas"
    /bananas/

    # allow any URL containing "bananas" regardless of case
    /bananas/i

Or exclude URLs without "bananas" using RegExp (which is a little more complicated and you need to know advanced RegExp syntax):

    # forbid a URL not containing "bananas"
    /^((?!bananas).)*$/i

**Comment by danny0838** [comment]
Close stale issue. It's welcome to reply if you still need support or want to provide a feedback.
