### ISSUE TITLE
cannot save pages in chrome, but can in vivaldi

### ISSUE THREAD

**Issue by gred22** [danny0838/webscrapbook#211]
I usually use vivaldi, but more and more pages will not accept it, mainly because reCAPTCHA rejects it.  So, then I use chrome.  I can save pages fine in vivaldi, but in chrome, I get an error = Fatal error: Backend server not configured.

However, the extension in both is 0.102.1
and the options for server are set the same in both
I have webscrapbook 0.34.2 abd pip 21.0.1

Can you help me find the problem?

thanks - Mark

PS - I had problems last fall we could not resolve, and I set wsb aside.  But recently I updated everything, and no longer have the problems I was experiencing last fall.

**Comment by danny0838** [comment]
As the message "Fatal error: Backend server not configured." says, do you forget to set URL for the backend server?

Do you mean the issue #26.?

**Comment by gred22** [comment]
Sorry - I'm not sure what was different - the options for the server were the same on the two options pages, but I exported the options from vivaldi, and imported them into chrome, and it works, so something was different I did not see.  Thanks again for being so responsive, and so patient.

**Comment by danny0838** [comment]
The only reason for this error message is missing (or invalid) value of the backend server address. You probably forgot to set it (or forgot to save options after setting).

![圖片](https://user-images.githubusercontent.com/531417/111763549-3ef00780-88dd-11eb-92d7-2b4dc30b603a.png)
