### ISSUE TITLE
Add  a (?) icon and description to the "Show hint when browsing..." checkbox in the options page.

### ISSUE THREAD

**Issue by OscarL** [danny0838/webscrapbook#212]
As the title says, I suggest adding a description, like the following one from https://github.com/danny0838/webscrapbook/issues/153#issuecomment-717359343:

> When the option "hint captured pages" is checked, a badge number will be shown at the webscrapbook toolbar button, with different color for the level of matched captured pages: red for same URL (excluding the #fragment), yellow for same path (excluding ?query and #fragment), green for same origin, and blue for same domain (e.g. http: and https: or www.example.com and example.com are considered same).

I got so confused about why I was seeing "weird count" on pages I knew I had not captured (but on the same domain of one that I did). and was about to open an Issue about that "bug".

Seeing that it is indeed not a bug, but a feature... You might consider documenting that fact, so we can make better use of that feature?

Thanks a lot for your work!!! I was SEVERELY missing an viable alternative to Scrapbook X!

**Comment by danny0838** [comment]
Done in 0.109.0. Thank you for the feedback.
