### ISSUE TITLE
抓取后的文件夹名称不正常

### ISSUE THREAD

**Issue by GeeRobin** [danny0838/webscrapbook#214]
webscrapbook版本：0.113.0
浏览器：Google Chrome  89.0.4389.114（正式版本） （64 位）
操作系统：Microsoft Windows [版本 10.0.18363.1440]
在选项设置页面，有一个名为  保存文件名  的设置项，我设置的是%ID% - %TITLE% (%HOST% %DATE% %TIME%)。
我抓取到的文件夹：20210421040652205 - 硬盘涨价真相：代理压货，卖家按小时涨价，囤货1天赚300万_腾讯新闻 (  )
尾部的括号是空的，%HOST% %DATE% %TIME%无法正常设置。
以前正常时，抓取后的文件夹名称如下：
20210328060246915 - 养不起鸡的养殖户：被鸡苗价格和饲料成本联合逼退_腾讯新闻 (new.qq.com 2021-03-28 14-02-46)
问题从4月6日开始出现，之前一直正常（括号内不为空）。。
PS：我用过不少扩展，大部分扩展即使能满足我的需求，也会有或这或那各种不如意的地方。本扩展不一样，不仅功能强大，更是百分百符合我的要求，我甚至想不出一点可以改进的地方，太强了。。

**Comment by danny0838** [comment]
0.108.0 版以後格式有更新（詳見[更新日誌](https://github.com/danny0838/webscrapbook/blob/master/CHANGELOG.md)），主要是為了和後端伺服器複製項目資訊的格式一致，並且支援 POSIX strftime 和 UTC 時間。

請再參見選項中的說明重新設定，應該是用 `%id% - %title% (%source-host% %create-F% %create-T%)` 就可以了。

**Comment by GeeRobin** [comment]
按你說的操作，問題已解決，謝謝。
     有一個小小的提議，你提到更新日誌，之前我是不知道有這東西的，你可以考慮下，每當用戶瀏覽器的webscrapbook更新為新本版後自動跳轉到 更新日誌 頁面。目前的情況是：webscrapbook靜默升級，用戶根本不知道webscrapbook什麼時候就自動升級為最新版本了。
     我曾用過的一款截圖擴展，叫FireShot，你可以試用一下該擴展，該擴展每次版本升級後，圖標就會發生變化，鼠標點擊該圖標瀏覽器就會跳轉的FireShot的官方網站，網站上有一些簡單介紹。這樣的做的好處是，1，告訴用戶，你使用的擴展升級了；2，跳轉後的頁面可以顯示簡單介紹，更新日誌之類的信息，避免再次出現像此次這樣的Issues。
     最後，再次感謝你的工作為我帶來的便利。 。 。
==============
     按你说的操作，问题已解决，谢谢。
     有一个小小的提议，你提到更新日志，之前我是不知道有这东西的，你可以考虑下，每当用户浏览器的webscrapbook更新为新本版后自动跳转到 更新日志 页面。目前的情况是：webscrapbook静默升级，用户根本不知道webscrapbook什么时候就自动升级为最新版本了。
     我曾用过的一款截图扩展，叫FireShot，你可以试用一下该扩展，该扩展每次版本升级后，图标就会发生变化，鼠标点击该图标浏览器就会跳转的FireShot的官方网站，网站上有一些简单介绍。这样的做的好处是，1，告诉用户，你使用的扩展升级了；2，跳转后的页面可以显示简单介绍，更新日志之类的信息，避免再次出现像此次这样的Issues。
     最后，再次感谢你的工作为我带来的便利。。。

**Comment by danny0838** [comment]
感謝回饋，不過目前還在開發期，版本更動較快，而且大多可能是使用者不會感興趣的變動，每次更新都跳個視窗可能比較具侵入性。另外寫這個更新推播也是有一些代碼工程要做，而每次更新除了 changelog 以外還要另外撰寫更新頁面（甚至全部本地化，也會讓更新發布的工作量增加不少……。

因此短期內可能不會實做，未來出正式版會再慢慢考慮。
