### ISSUE TITLE
link to how-to-transfer-data-between-scrapbooks in wiki points to nowhere

### ISSUE THREAD

**Issue by kantrol** [danny0838/webscrapbook#217]
In the FAQ Section of the wiki, last sentence:

"Or import them to a newly generated scrapbook and then transfer them to another scrapbook as previously introduced."

The link of "previously introduced." seems to point to nowhere:
https://github.com/danny0838/webscrapbook/wiki/FAQ#how-to-transfer-data-between-scrapbooks

**Comment by danny0838** [comment]
Link fixed. Thank you for reporting.
