### ISSUE TITLE
wsb tree view missing

### ISSUE THREAD

**Issue by mojorissin23** [danny0838/webscrapbook#218]
using linux mint 20.1 // VPN off // wsb version 0.44.1 // wsb FireFox version 0.121.1 - had to reinstall via Timeshift - sytem restore utility . 
wsb works in that it will save new pages but all my tree view data in the left hand column under WebScrapBook scrapbook is missing ? 
in the last few days i have read through the Issues & tried to solve my problem using the codes in the Wiki to no avail ?
i am not able to resuscitate the tree view i need  , used daily - very important to me .

any advice to solve this problem will be greatfully received , 
thanks
mojorissin

**Comment by danny0838** [comment]
1. Can you recall what you have done before his happens? E.g. Upgraded WSB or PyWSB, rebooted server, rebooted devicr, saw any error when doing something, etc.?

2. Go to the menu button (the one near aside the search button) and show scrapbook directory in file manager and check if it's the correct path. Check if you are not running bavkend server at a wrong path.

3. Check the tree files (usually `<path/to/scrapbook>/tree/...`) and see if `toc.js` and `meta.js` exist.

If not, check the backup firectory (by default `<path/to/scrapbook>/.wsb/backup`) and see if there's a recent backup with `-transaction` suffix.

**Comment by mojorissin23** [comment]
hello Danny & thanks for prompt reply - been working on answering you . 1. wsb was working just fine for me i saw no error . i know my file system was dodgy maybe corrupted & i was trying to clean up a programme called Callibre ( used for books ) & i had to re-install the system .

2. go to menu button & click View root directory locally i think you mean . Yes it shows /home/mojorissin/ nemo files folder system - this path looks OK .
check backend server path - i think wsb config -e --book = config.ini . I attache copy below . I do not know if this is correct ?

3. if you mean path to webscrapbook then : /home/mojorissin/webscrapbook/tree/ toc.js 109.6 kB & meta.js 2.1mb looks OK

thanks & over to you
mojorissin

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by danny0838** [comment]
If `toc.js` and `tree.js` are intact, your data should be save. You probably was just running the backend server at a wrong path.

Please kill all running backend server processes of PyWSB (or maybe reboot your system) and restart the server at `/home/mojorissin/webscrapbook` (cd to `/home/mojorissin/webscrapbook` and run `wsb serve`, or run `/home/mojorissin/webscrapbook/.wsb/serve.py`, or run `wsb --root /home/mojorissin/webscrapbook serve`) and see if the problem is solved.

If still not, you may have to provide more details for issue tracking, such as the missing config file attachment (Do not attach a file via email reply, it won't work. Do it via GitHub web interface.)

**Comment by mojorissin23** [comment]
config.ini
; Run "webscrapbook help config" for details

[app]
; name = WebScrapBook
; theme = default
; root = .
; base =
; index =
; backup_dir = .wsb/backup
; content_security_policy = strict
; allowed_x_for = 0
; allowed_x_proto = 0
; allowed_x_host = 0
; allowed_x_port = 0
; allowed_x_prefix = 0

[book ""]
name = scrapbook
top_dir = 
data_dir = data
tree_dir = tree
index = tree/map.html
no_tree = false

; [auth "user1"]
; user = myuser1
; pw = 73337dfdaf99b87be97cb4b4f16645e059da6e5f
; pw_salt = mysalt1
; pw_type = sha1
; permission = all

; [auth "user2"]
; user = myuser2
; pw = pass2mysalt2
; pw_salt = mysalt2
; pw_type = plain
; permission = read

[server]
; port = 8080
; host = localhost
; ssl_on = true
; ssl_key = ./wsb/webscrapbook.key
; ssl_cert = ./wsb/webscrapbook.crt
; browse = true

[browser]
; command =
; cache_prefix = webscrapbook.
; cache_expire = 259200
; use_jar = false

**Comment by mojorissin23** [comment]
apologies Danny NOT closed
mojorissin

**Comment by danny0838** [comment]
Have you confirmed that kill all processes and restarting the backend server solves the issue? It seems that your config is just default value and there should be problem with it.

**Comment by mojorissin23** [comment]
Does not solve the problem , but if i run 1 or 2 of your codes like : run wsb --root /home/mojorissin/webscrapbook serve - then what i see is the tree of the "old scrapbook" on the left ( but most data missing ) . I want to see WebScrapBook . The current WebScrapBook is a copy from the 27th last month copied from either BackinTime or Timeshift - are there any other files that should be copied over at the same time ?

mojorissin

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by danny0838** [comment]
Sorry, I don't know what is BackinTime or Timeshift, nor do I know how have you used them. It seems like they are system backup/restore tools and you have configured them incorrectly or have done something wrong about them.

It seems that there is nothing wrong about your WSB or PyWSB, and there's nothing I could help more.
