### ISSUE TITLE
[Issue] ZIP/Maff/HTZ are not read very well when File Converter (ScrapBook X extension) has been used in some options

### ISSUE THREAD

**Issue by Atanacius** [danny0838/webscrapbook#22]
OK.

Well, I used (just before making the update of Firefox 57) File Converter 
(which is an extension of ScrapBook X), but as ZIP file not MAFF or HTZ.

ZIP are ok-readable in WebScrapbook aswell it says.
In fact, it working, but, what not working is.. WHEN "Directory Name" option has been selected when Converted through File Converter.

WHY?
Because that:

Web ScrapBook search for a direct root file named as index.html in the ZIP.

_BUT.._

Option "Directory Name" .. adds a sub-folder in the ZIP file named the same name the ZIP file is named (I didn't really know that, but I can't rollback.. so this issue can be fixed quickly by letting WebScrapBook reading index.html like that:

1) In ZIP it would search a root file named "index.html", if it isn't found, it will then use the ZIP NAME as sub-folder and then in this SUB-Folder search for a file named index.html !

**ACTUALLY WORK:**

```
20140210163203.zip
  |- index.html
  |- some other files... (such as resources: images, css, js, etc..)
```

**ACTUALLY DON'T WORK:**

```
20140210163203.zip
  | 20140210163203
         |- index.html
         |- some other files... (such as resources: images, css, js, etc..)
```

Thanks for considering this issue for making the thing smooth for everyone..

**Comment by danny0838** [comment]
For simplicity we won't change the current behavior that only the index.html in the HTZ is checked and load.

The ZIP conversion in ScrapBook X Converter did not intentionally designed to be Web ScrapBook compatible. Currently only when "top directory" is selected will if be Web ScrapBook compatible.

**Comment by Atanacius** [comment]
Ah yeah.... I thought it was just compatible by using ScrapBook X Converter to create ZIP of each "folder"..

Understood for the non-compatibility purpose between ZIP structure of ScrapBook X Converter and ZIP/MAFF/HTZ structure of WebScrapBook!

Anyway...

**I'm not sure to understand very well that answer of you** :

_"Currently only when "top directory" is selected will if be Web ScrapBook compatible."_ ❓ 

So.. For helping me to understand very well purpose..
Can you **pretty please** explain me precisely and step by step how it will be compatible if I want export my ScrapBook Datas as ZIP in WebScrapBook.

For a bit more than actually at least...

**I ask that because:**

In ScrapBook X Converter the option 'top directory create aswell a sub-folder in the ZIP...
So.. It's not what WebScrapBook will search to parse the index.html !

**Then, two other questions:**

- 1) Can I ZIP myself (with WinZIP or even 7z Unzipper) each "folder" normally just by respecting this structure (meaning no-sub-folder to put index.html):

```
20140210163203.zip
  |- index.html
  |- some other files... (such as resources: images, css, js, etc..)
```

- 2) Or is it not working to parse by WebScrapBook ?


Thanks very much for the work involved to WebScrapBook, the road seems long before it's become greater and greater just like ScrapBook X was...
Anyway, many month/years will pass before it will be the case I think, do your best as usual, (web)ScrapBook team rocks !

**Comment by danny0838** [comment]
Sorry for the typo, it should have been 'Currently only when "**No** top directory" is selected will **it** be Web ScrapBook compatible.' ZIPs generated in this way will be viewable by Web ScrapBook, and you are free to rename them to HTZ. Additionally, MAFFs are also viewable by Web ScrapBook.

We won't say "compatible" since some misc information stored in the html DOM structure are still in ScrapBook X compliant format, but they are rather minor and don't lose during the conversion anyway. We may implement a full convertion in the future.
