### ISSUE TITLE
How to install and running webscrapbook

### ISSUE THREAD

**Issue by fxnull** [danny0838/webscrapbook#220]
hello.
I am an avid user of scrapbook since the beginning.
as with a new version branch i had serious problem to install. some how its a bit cryptic. 
I used waterfox and already install phyton 3.9 via windows 10 microsoft store.
but its cannot work out of the box.
Please show me the easist clear way to install and configured it,

thank you

**Comment by danny0838** [comment]
WHAT is not working? Is it that you don't know how to install [PyWebScrapBook](https://github.com/danny0838/PyWebScrapBook)? Or is it that you can't run PyWebScrapBook? Or is it that PyWebScrapBook has been run successfully but you can't [configure WebScrapBook](https://github.com/danny0838/webscrapbook/wiki/Basic#3-browser-sidebar-approach) to work with it?

**Comment by danny0838** [comment]
@sulisu See related issue: https://github.com/danny0838/PyWebScrapBook/issues/46

**Comment by sulisu** [comment]
> @sulisu See related issue: [danny0838/PyWebScrapBook#46](https://github.com/danny0838/PyWebScrapBook/issues/46)

Hi,

My suggestion seems to be different and easier to impliment.

"WinPython is a portable distribution of the Python programming language for Windows (http://winpython.github.io)." The size of the core installation file is no more than 24MB and it is acturally a self-extract 7-zip file. Extract it into a directory. Install pywebscrapbook with pip using the "winpython command prompt.exe" which is in the extracted folder. And then run wsb with some modified version batch file based on the batch file come with Winpython.

I have packaged the one i am using, someone brave enough can give it a try in a vm.
link：https://pan.baidu.com/s/18hap2g2uQz1iqU2q7l6R9Q 
pass：hc3t 

Run scripts\cmd_for_webscrapbook.bat to start the server. Above link will be valid for 7 days.

**Comment by danny0838** [comment]
@sulisu This is out of topic. Please respond in that thread or raise another issue in PyWSB.

Do you still have problem getting WSB work with the backend? We are going to close this issue if not.
