### ISSUE TITLE
Dropdown forms not captured

### ISSUE THREAD

**Issue by michellek8xv** [danny0838/webscrapbook#222]
If you try capturing a page with a dropdown, the actual form is not captured, even in beta.

Example page: https://www.parkers.co.uk/honda/civic/hatchback-2012/used-prices/
[Example of same URL in Scrapbook Beta format- 20210619220106800.zip](https://github.com/danny0838/webscrapbook/files/6681388/20210619220106800.zip)

Is this a possible bug, or just the limitations of that particular site, or WebScrapbook?

**Comment by danny0838** [comment]
Thr page [loads images dynamically](https://github.com/danny0838/webscrapbook/wiki/Basic#capture-web-pages). You have to scroll the screen down to load all images before performing a capture. 

You may [configure the capture helper](https://github.com/danny0838/webscrapbook/wiki/FAQ#some-web-pages-load-images-only-after-the-screen-is-scrolled-down-is-there-a-way-to-capture-the-complete-page-without-scrolling-the-screen) to do that automatically in some cases.
