### ISSUE TITLE
[feature request] automatic reopen of the edited version of the page

### ISSUE THREAD

**Issue by vinniec** [danny0838/webscrapbook#224]
this is a strange request, I'm trying now your plugin and for now I like it very much, but I would like that every time I reach the same original address of the modified page. the edited version is loaded instead of the original one.
Unfortunately this opens a version problem, because if the original page is modified the changes should be notified.
Maybe asking this is too complex, maybe simply allowing the automatic reopening of the modified page would be enough.

**Comment by danny0838** [comment]
What is the "edited version"? You mean the captured version?

This is probally impossible... What if there are multiple captured versions? What if the backend server is not configured? ...

You can take advantage of "nofity captured pages" to see if there are captured versions of the visiting pave and the "search captured pages" to find them (if the backend server is configured).

**Comment by vinniec** [comment]
Um, okay, it's not critical needing.
In the meantime I tried your plugin even better and it's really nice, but I noticed though that I can't edit local files (file:///...), this prevents from editing previously saved pages.

**Comment by danny0838** [comment]
Extensions are not allowed to save to local files. Configure the backend server to edit captured pages.

**Comment by vinniec** [comment]
Ok, thanks for the help :)
