### ISSUE TITLE
Not seeing new captured page in the Scrapbook window (probably not a bug)

### ISSUE THREAD

**Issue by donw9876** [danny0838/webscrapbook#225]
Context: I'm a new user of wsb. I've been using Scrapbook and Scrapbook X for 10+ years. 

I've successfully (I think) done the following: (on Linux Mint 19.3)

- Installed WebScrapBook Version 0.125.1 to Opera 77.0.4054.254. Where it happily captures a tab I select.
- Installed the WebScrapBook PY server at the command line using pip.
- Observed that webscrapbook within Opera now supports the menu command "Open Scrapbook" which was disabled before adding the magic URL for a server to the options page.
- Imported an existing 3000+ item Scrapbook X collection to WebScrapBook.
- Can see the folder structure of the old ScrapBook X collection in WebScrapbook's listing window in the browser. The window pops up outside the browser, awkward but better than nothing. I can open most pages by clicking on the page name in the list.

What I don't see is where the heck, or if, or how, WebScrapBook creates a new, fresh indexed scrapbook listing entry on the fly for a captured page. In other words I wanna capture a page and then see it pop up in the list. It does not do that.

I captured a page from a plain old text BBS web site page with the wsb server running. The page successfully gets written to the same directory where the imported legacy page captures now live.

But there is no insertion of this page into the WebScrapBook listing page.

Therefore I gotta wade through a file manager to find the captured page  rather than what I rightfully desired which is to have the captured page show up as an entry at the end of the scrapbook list window.

Also, I left the settings alone that choose "save as directory" (so each new captured page gets a new directory under 'data' with the date and time of day encoded as the name.) the new captured page is sitting there, but your server didn't do anything with it.

The options page has a gazillion checkboxes and options that I would have no use for. Did I diddle something that disabled this vital feature?

I certainly hope we don't have to do some manual indexing procedure in order to see captured pages get added.

Thanks for any help.

**Comment by danny0838** [comment]
Can you see the newly captured item after refreshing the sidebar? If yes, it's normal behavior.

There are currently some technical concerns that prevents implementation of auto-refreshing, so a manual refresh is required after a capture. Alternatively, you can drag the "capture tab" command to the sidebar for a capture with a customized location and auto refreshing. See [related doc](https://github.com/danny0838/webscrapbook/wiki/Basic) for further details.

**Comment by danny0838** [comment]
> Can see the folder structure of the old ScrapBook X collection in WebScrapbook's listing window in the browser. The window pops up outside the browser, awkward but better than nothing. I can open most pages by clicking on the page name in the list.

Unfortunately, Chromium-based browsers (such as Google Chrome, Edge, and Opera) do not support window sidebar. Switch to Firefox Desktop (which is the only browser that supports sidebar) if this is a concern.

**Comment by donw9876** [comment]
Thanks for the fast reply. If you mean the refresh icon next to the search icon at the top right of the pop up Scrapbook window: I tried that and I don't see the new captured page. A page I captured last night has never shown up after a system shutdown and restarting the wsb server. A page I just captured now also does not show up. If it were working properly for me, would captured pages appear initially at the top level of the list at the bottom?

Is there a debug mode I can put something in to see what's going on better?

**Comment by donw9876** [comment]
Having a neatly integrated sidebar isn't a big deal. I'm trying to wean off of Firefox browsers because their plugin situation is a mess and Waterfox (which I've been using lately) is broken for about 2/3 of the websites I need.

**Comment by danny0838** [comment]
Can you provide your options? (hint: use the export button. Note that if you fill the user name and password in the options, which is convenient but not recommended, they may be included in the exported file. Be sure to remove sensitive data before posting)

If possible, please also provide the log in the capture window for an unsuccessful capture attempt?

**Comment by donw9876** [comment]
I've attached my (json) options renamed as txt.

I have no idea what capture via dragging means for this tool. A screen shot would be immensely helpful.

Example of capture which does not make it to the index list: 

Capturing (document) [154] https://github.com/danny0838/webscrapbook/issues/225 ...
Error downloading file (): Failed to construct 'URL': Invalid URL
Error downloading file (): Failed to construct 'URL': Invalid URL
Error downloading file (): Failed to construct 'URL': Invalid URL
Error downloading file (): Failed to construct 'URL': Invalid URL
Saving data...
Saved to "/home/dlw/Downloads/WebScrapBook/data/20210718171747316/index.html"
Done.

[webscrapbook.options.20210718.txt](https://github.com/danny0838/webscrapbook/files/6836651/webscrapbook.options.20210718.txt)

**Comment by danny0838** [comment]
Seems you don't set `Save captured data to:` to `Backend server`. It should work after doing that.

Drag the `capture tab` button in the dropdown list into the sidebar, like this: https://github.com/danny0838/webscrapbook/issues/202#issuecomment-792479575

**Comment by donw9876** [comment]
The setting change worked. The capture log window now shows "Saving to server" and it shows up in the list. Thank you.

Good lord, with all of the minor options mixed with major ones like that at the same flat level I never noticed this.

How can I capture directly to a particular folder in the scrapbook? Or do I have to capture and then move the item?

**Comment by danny0838** [comment]
> How can I capture directly to a particular folder in the scrapbook? Or do I have to capture and then move the item?

Please see the dragging solution mentioned above. It's exactly designed for this.

**Comment by donw9876** [comment]
I found this and it does work for me. Very much appreciated.
