### ISSUE TITLE
便利貼批注在不同分辨率的電腦上位置不同

### ISSUE THREAD

**Issue by JohnsonTam9527** [danny0838/webscrapbook#229]
您好，現在發現個問題：在一台小屏幕的電腦上使用便利貼批注功能後，發現批注後的文章在大屏電腦上使用時，會出現便利貼位置改變的情況，個人猜測是因爲分辨率的關系，請問有什麽好的解決方法嗎？

**Comment by danny0838** [comment]
便利貼是定位於固定的網頁座標，因此會隨網頁總寬高變化。目前應該沒什麼好的解法，要嘛是調整瀏覽器視窗大小，要嘛是修改網頁CSS使之在任何設備上都鎖定為固定寬高。
