### ISSUE TITLE
Import data from old scrapbook folder

### ISSUE THREAD

**Issue by strannick-ru** [danny0838/webscrapbook#23]
Hello.
I have old (really old) folders with Scrapbook data.

May I import it to webscrapbook?

**Comment by RvdGijp** [comment]
We have the same problem!

**Comment by danny0838** [comment]
Duplicate of #14. Use built-in site indexer for full index build up and [ScrapBook X File Converter](https://addons.mozilla.org/firefox/addon/scrapbookx-converter/) to convert to other archive formats.
