### ISSUE TITLE
"Open Scrapbook" is greyed out?

### ISSUE THREAD

**Issue by raelb** [danny0838/webscrapbook#230]
Hi,

The "Open Scrapbook" link/button is grey out. (FF and Chrome). What do I need to do to enable it?

![image](https://user-images.githubusercontent.com/13108198/127470477-653ee3ba-9aea-4266-bfc2-9593baf886a3.png)

Thanks

**Comment by danny0838** [comment]
You have to [set up the backend server](https://github.com/danny0838/webscrapbook/wiki/Basic#3-browser-sidebar-approach) first.

**Comment by raelb** [comment]
Ok, Thanks
