### ISSUE TITLE
Fatal error: Backend server not configured.

### ISSUE THREAD

**Issue by bluelovers** [danny0838/webscrapbook#231]
![image](https://user-images.githubusercontent.com/167966/128098931-bcef852f-eda7-4eaf-b922-e8d4058346a5.png)

![image](https://user-images.githubusercontent.com/167966/128098948-153781c2-6130-4a2f-8c67-265faea2503a.png)

![image](https://user-images.githubusercontent.com/167966/128098969-0452bc13-0dcc-496a-a800-23e38c41127a.png)

![image](https://user-images.githubusercontent.com/167966/128099031-8987ea8e-7f54-4de7-bea2-14ba0eec442f.png)

**Comment by danny0838** [comment]
Seems you haven't [set backend server address in the options](https://github.com/danny0838/webscrapbook/wiki/Basic-(zh_TW)#3-%E7%80%8F%E8%A6%BD%E5%99%A8%E5%81%B4%E6%AC%84%E5%9E%8B).

**Comment by bluelovers** [comment]
選項內不存在可以設定伺服器位置的地方

**Comment by bluelovers** [comment]
位置也差得太遠一點了吧

![image](https://user-images.githubusercontent.com/167966/128099921-faf8f676-3b84-4c59-87b4-d89bb326ac03.png)

**Comment by danny0838** [comment]
後端伺服器不是只為了擷取功能服務的。後面還有一堆後端伺服器專用工具集，如果把後端伺服器的選項放到上面，豈不是後端伺服器相關功能彼此離很遠？

在還沒人能想到更好的設計方案前，只好暫時先這樣了XD

**Comment by bluelovers** [comment]
加上自動設定伺服器預設值之後應該會好一點
https://github.com/danny0838/webscrapbook/pull/232

**Comment by danny0838** [comment]
@bluelovers 我要再考慮一下。

我可以理解會選擇擷取到後端伺服器的人應該也會想設定後端伺服器，但基於安全考量，我覺得後端伺服器的位址應該要由使用者自己輸入，自動填上 localhost:8000 並不可靠，甚至有可能不小心連到不該連的東西（如果使用者有安裝其他服務）造成不可預期的後果。

而且這樣做會造成介面不一致，因為不是只有擷取會用到後端伺服器，其他像開啟剪貼簿、搜尋剪貼簿、檢視已擷取的頁面等等，都會用到後端伺服器。使用者沒填寫後端伺服器網址時，做這些動作時出現的錯誤訊息應該已經足夠提示使用者要改設定了。

至於有沒有其他改進方案……如果把錯誤訊息改為「backend server address not configured」之類會不會更好一點？

**Comment by bluelovers** [comment]
> @bluelovers 我要再考慮一下。
> 
> 我可以理解會選擇擷取到後端伺服器的人應該也會想設定後端伺服器，但基於安全考量，我覺得後端伺服器的位址應該要由使用者自己輸入，自動填上 localhost:8000 並不可靠，甚至有可能不小心連到不該連的東西（如果使用者有安裝其他服務）造成不可預期的後果。

那改成在初始化伺服器設定時就同時詢問 port 不要預設為 8080 這種常見 port 例如 8989 如何

**Comment by danny0838** [comment]
> > @bluelovers 我要再考慮一下。
> > 我可以理解會選擇擷取到後端伺服器的人應該也會想設定後端伺服器，但基於安全考量，我覺得後端伺服器的位址應該要由使用者自己輸入，自動填上 localhost:8000 並不可靠，甚至有可能不小心連到不該連的東西（如果使用者有安裝其他服務）造成不可預期的後果。
> 
> 那改成在初始化伺服器設定時就同時詢問 port 不要預設為 8080 這種常見 port 並且提供預設值（當直接按下enter時）例如 8989 如何

「初始化伺服器設定時」是什麼意思？

**Comment by bluelovers** [comment]
> wsb config -ba

....

> server port? (default: 8989)
> <enter> or <input new port>

server port is 8989

**Comment by bluelovers** [comment]
怕案太快可以改成 要輸入 yes 或 y 才會用預設值
然後依直到使用者輸入允許的內容為止

**Comment by danny0838** [comment]
我不懂這樣做如何能解決問題。

你的提案是當使用者設定擷取至後端伺服器時，如果伺服器網址是空白的，就自動填上 http://localhost:8080 作為預設值。現在又說後端伺服器啟動時要求使用者指定 port，那要如何讓 WebScrapBook 知道伺服器用的 port 從而填上正確的預設值？

前面提到介面不一致的問題也還沒有解決。

**Comment by bluelovers** [comment]
因為你說不希望使用者使用 8080 這種預設值避免讀到其他伺服器阿
所以我才提議說在建立 伺服器初始化時 就先要求使用者選定要用的 port

**Comment by danny0838** [comment]
你沒有回答到問題。

WebScrapBook 又不會通靈，如果後端伺服器的 port 還要使用者自己決定，WebScrapBook 如何自動填寫？

**Comment by bluelovers** [comment]
> 你沒有回答到問題。
> 
> WebScrapBook 又不會通靈，如果後端伺服器的 port 還要使用者自己決定，WebScrapBook 如何自動填寫？

那就選定一個很少用到的 port 當預設值阿

如果使用者在建立伺服器時輸入了其他 port 就跳個訊息告訴他要記得去設定

**Comment by danny0838** [comment]
請問 WebScrapBook 要如何知道使用者在啟動後端伺服器時是否有自訂 port？

**Comment by bluelovers** [comment]
無法連上時就知道要使用者去檢查設定嚕

如果要避免帳密傳出去
可以在伺服器端做一個特殊路由用來回傳他是 相容於ScrapBook伺服器的簡易資料

然後 WebScrapBook 再登入之前 先請求那個路由來判定伺服器是不是對的
如果是對的 則才發送登入請求
