### ISSUE TITLE
Unable to capture an error page

### ISSUE THREAD

**Issue by qdinar** [danny0838/webscrapbook#234]
i opened a site and see "Error code: SSL_ERROR_RX_RECORD_TOO_LONG" message. i wanted to save this error message. but wsb said "fatal error". i propose idea to save such pages.

more completely, these messages of wsb:

Capturing (document) [2812] https://....net/ ...
Unable to execute content script ([2812:0] https://....net/): Missing host permission for the tab
Fatal error: Could not establish connection. Receiving end does not exist.

**Comment by danny0838** [comment]
The error `Unable to execute content script` your provided is because WSB cannot inject content script and cannot capture that web page. This mostly happens when the web page is in the browser extension store, but it can happen on some other cases as well. Can you provide your browser and WSB version, and the URL of the page you tried to capture?

**Comment by qdinar** [comment]
this page does not show that error any more. now, it redirects to https://forbidden.yota.ru/ . ff 89.0, wsb 0.125.2 .

**Comment by danny0838** [comment]
Capturing the page you provided doesn't seem to go wrong. Regretfully we probably can't go any further as the page in issue no more exists. Reach us back if this issue still happen in the future.

**Comment by qdinar** [comment]
similar situation:
Capturing (document) [4413] https://syzlek.ru/ ...
Unable to execute content script ([4413:0] https://syzlek.ru/): Missing host permission for the tab
Fatal error: Could not establish connection. Receiving end does not exist.
firefox says:
Unable to connect
Firefox can’t establish a connection to the server at syzlek.ru.
The site could be temporarily unavailable or too busy. Try again in a few moments.
If you are unable to load any pages, check your computer’s network connection.
If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

**Comment by danny0838** [comment]
@qdinar I cannot connect to that URL. For an non-connectable URL, it's normal to be not-capturable.
