### ISSUE TITLE
I want to rip an entire site?

### ISSUE THREAD

**Issue by d351r3d** [danny0838/webscrapbook#240]
I want to rip a full site and while the extension is amazing one page at a time is rough for like 3 million. I'd like to rip a site since httrack and other software won't work since the site is behind cloudflare. This is the only thing that seems to work really well but turning all the links into one that direct to local versions would be weird.

**Comment by danny0838** [comment]
I don't get your point. Doesn't a capture just mean to turn it into a local version?

**Comment by d351r3d** [comment]
If there's a website with more than a single page it'll rip the entire website, not just a single page? I'm new to all of this. I'll test it tomorrow. I just ripped a single page and had no idea how to cooy a large website with many pages.

**Comment by danny0838** [comment]
Set depth. Read the [manual](https://github.com/danny0838/webscrapbook/wiki/Basic) for details.

**Comment by d351r3d** [comment]
Thank you good friend. +1

**Comment by danny0838** [comment]
@d351r3d 
> How do I make the links relative and not to the original website.

[In-depth capture](https://github.com/danny0838/webscrapbook/wiki/Basic#capture-linked-web-pages-in-depth-capture) should be what you want.

> Also how would I mirror the structure of the site and not have to do this stuff manually?

How do you define "mirror the structure of the site"? In one sense, in-depth capture will capture pages with linked pages, and you can browse them like in the original site. In another sense (keeping same relative path/filename as the original site), this is impossible (e.g. an URL query (followed by `?`) is not a physical file cannot be saved as "same file name").

> How do it make sure that I'll on the site instead of trying to copy the entire internet. I just want one domain. I don't want it to go off the domain.

Set a filter like `/^http://example\.com//` in the `Include these URLs:` option, as the `?` tooltip says. You may need to learn some RegExp syntax, however.

----
Please add a new comment for providing additional information. An edit is mostly for simple typo and/or grammar fix. We won't be notified by edits and can't review all issues often, and your edits may easily get missed.

**Comment by d351r3d** [comment]
I was just wondering if I had to write the full thing because I didn't and it didn't care. I'll try again. /^http://example\.com//

I've been figuring some stuff out like the setting it up in folders with rhe name of the domain is nice.

I'll definitely have to try out those filters. Much appreciated.

**Comment by danny0838** [comment]
It depends. The RegExp `/^http://example\.com//` means "starting with `http://example.com/`". You can tweak the RegExp to test for a full-string match or test for a substring anywhere, though.
