### ISSUE TITLE
在Chrome上webscrapbook插件似乎与Chrono下载管理器插件冲突导致无法正常获取网页？

### ISSUE THREAD

**Issue by higogou** [danny0838/webscrapbook#242]
在chrome上使用webscrapbook获取网页时，会在弹出的窗口中出现下列信息，然后Chrono下载管理器不停的下载失败网页中的图片等元素直到出现最后一句失败的信息。不知道是否是因为Chrono下载管理器的下载规则干扰到了websrcapbook。
Capturing (document) [549] https://www.guancha.cn/ ...
Saving data...
Fatal error: Download interruped: USER_CANCELED.

**Comment by danny0838** [comment]
請停用一個套件試試

**Comment by higogou** [comment]
我在发帖之前，已试过禁止chrono插件，所以知道是它冲突了webscrapbook，我之所以提出来，一是我并不知道问题的技术细节，也许你那里有解决之道，毕竟插件冲突常有，也许能解决呢！二是提示和我一样同时装有这两个插件的普通用户，不会因为初次使用不畅，而以为webscrapbook不堪使用。
你这里也清楚的说明了问题的所在及可能的解决方案，就像你判定的这不是一个至关重要的严重bug，如果后续没有其它相关的问题，就不再浪费你的时间了，thanks！

**Comment by danny0838** [comment]
感謝您的回饋。不過一開始就主動說明測試停用套件的結果，會對除錯更有幫助，畢竟你不說沒人知道你測試過。

後續請自行視需要聯繫Chrono開發者。
