### ISSUE TITLE
在不能直接访问chrome插件商店情况下，安卓手机上有哪些浏览器，可以手动加载运行webscrapbook呢？

### ISSUE THREAD

**Issue by git2wing** [danny0838/webscrapbook#243]
电脑上一直在用，配合pywebscrapbook后台很棒。
手机上也想使用，尝试了下，始终不得其法：
--由于这里不能直接访问chrome插件商店和playstore，yandex安卓版开发模式手工安装下载（chrome商店）离线下来的crx时，提示json错误。
--而firefox 安卓，预设插件列表里没有加载项，而访问其插件商店下载下来的xpi，不知如何加载？ff andriod可以手工加载吗？
或者有其他浏览器可以加载吗？

**Comment by git2wing** [comment]
yandex和firefox android版本，都是最新的，是否要用老版本才行？

**Comment by danny0838** [comment]
[文件有說明](https://github.com/danny0838/webscrapbook/wiki/Issues-(zh_TW)#firefox-for-android)，Frefox for Android 79 版以後要用比較複雜的方式安裝，或者找較低的版本。

Yandex 和 Kiwi如何安裝 CWS 以外的套件我們並不清楚，可能要問開發者了……

**Comment by danny0838** [comment]
@git2wing 你試過 Kiwi Browser 嗎？我在擴充功能管理頁面勾選「開發人模式」，直接安裝打包檔並沒有問題。

如果有問題，或許有可能是下載的版本有問題？你可以試試從原始碼打包（從本版本庫 Download ZIP 下載最新版原始碼，執行 build 目錄下的 pack.cmd 或 pack.sh 產生打包，dist 目錄下會有 WebScrapBook.xpi (Firefox 版) 和 WebScrapBook.zip (Chromium 版) 可供安裝），看看是否仍有同樣問題。

**Comment by git2wing** [comment]
好的，我试试，谢谢了 @danny0838

**Comment by git2wing** [comment]
成功安装了，还是kiwi最为方便。
webscrapbook实在太棒了 @danny0838

**Comment by danny0838** [comment]
感謝回饋。目前手機上可能Kiwi是最好的選擇了。Firefox 最新版安裝程序麻煩，舊版好一點，但兩者都不允許商店以外的封裝檔安裝，而附加元件在商店上架又一堆冗長耗時的審核程序卡著，可能還要好一段時間才會比較可用了……。

稍微在 wiki 加上了關於安裝的指引。如果有空可幫忙看看及協助改進，感謝。
