### ISSUE TITLE
Webscrapbook struggles with NYTimes pages

### ISSUE THREAD

**Issue by sj365** [danny0838/webscrapbook#245]
Attempt to save page will complete, but when you open saved page it is blank.  I noticed this a few weeks ago as Webscrapbook has worked quickly on NYTimes in the past.

https://ufile.io/acbz6jki

**Comment by danny0838** [comment]
If all you mean is that a page captured from NYTimes loads slowly (since around 4:20 in your video), it dosn't seem like a bug of WSB.

Saving as single HTML is known to cause a performance issue as data URL is generally loaded slower. This should have been well explained in the [related FAQ](https://github.com/danny0838/webscrapbook/wiki/FAQ#how-to-choose-the-save-format-for-the-captured-web-page).

I tried capturing the same page as single HTML and it loads almost instantly on my devices (even in IE and Firefox for Android), and it seems to be other issues of your browser or device. Please try:
* Disable other browser extensions, or use a clean browser profile.
* Load the captured page on another browser or device.
* Capture with another format.

And see if there's a difference.

**Comment by danny0838** [comment]
@sj365 Is there any follow-up of this issue?

**Comment by sj365** [comment]
I have not discovered any other chrome extension that is interfering with
the NYTimes save.  If I find out I will send a message.

**Comment by danny0838** [comment]
@sj365 Have you tried loading the captured page on another device and capturing as folder?

**Comment by sj365** [comment]
As per your request, I set up wsb on another machine.  Capture/Save for
Nytimes was normal (few seconds).  There were elements from nytimes not
being hidden on the new machine saved page, so i copied over the settings
from my main machine and the extended wait period problem came back.  So,
the issue would be definitely in the wsb settings.  I dont know which one
so it will take a while to figure out.  Im attaching the settings file for
you to review.  Maybe you can figure it out faster.  The new machine saved
page just opened after the wait warning message in wsb and the nytimes
elements are gone now.  Definitely something with wsb settings.

**Comment by sj365** [comment]
Sorry, I should have provided the test page im using:

https://www.nytimes.com/2021/11/15/opinion/diversity-equity-inclusion.html

**Comment by danny0838** [comment]
1. It seems that you have attached a file in the email. Don't do this. GitHub does not support attachments through email. You need to upload to GitHub using the web interface or upload to another cloud service.

2. As previously mentioned, it is highly suspected that `Save captured data as: single HTML` causes this. Try capturing as another format and see if there's a difference.

**Comment by sj365** [comment]
-Issue Resolved-

-The problem was one of the WSB options activated which should not have been.  To determine which one was causing the problem, compare the options bad to options good attachments.  I cant check them right now myself as Im leaving for an appointment.  (By options bad I mean settings that will produce issues saving as Single html file)

-Save Captured data as: single HTML works great.  You just have to make sure to have the correct set of options activated.  It works on the majority of web pages I have come across.  It does have issues with certain extra fancy web pages that incorporate sliding videos and other action type movements on the same page.  Once I realized the issue was in the options, I reset WSB options to default, reselected the essential ones, and the delayed save/reopening problem is fixed. 

-If a page was saved using the options bad settings, the options good settings will still open it; it will just take a few more seconds.

[webscrapbook.options.20211116.zip](https://github.com/danny0838/webscrapbook/files/7548873/webscrapbook.options.20211116.zip)

**Comment by sj365** [comment]
Updated Options File - Ascii removed

Its best to keep unchecked Save ASCII filename.  The performance is still good with it checked but any apostrophis in title name will add many extra characters to file name.

[ideal single html webscrapbook.options.20211116.zip](https://github.com/danny0838/webscrapbook/files/7550021/ideal.single.html.webscrapbook.options.20211116.zip)

**Comment by danny0838** [comment]
I suspect that only the "font" option is related. NYTimes has lots of fonts in the CSS while only a small set are really used in the page. Using `save` will include lots of unused font files that makes the page large and slow, especually when it's saved as single HTML.

Anyway, this seems to be a priblem of performance, which may vary caaoridng to the web page, your device, and the options you uae. Just select what works well for you. You can also check [related FAQ](https://github.com/danny0838/webscrapbook/wiki/FAQ#why-the-web-page-captured-by-webscrapbook-is-larger-in-size-than-the-one-captured-by-another-tool) for further details.
