### ISSUE TITLE
Specify folder name during capture

### ISSUE THREAD

**Issue by loshran** [danny0838/webscrapbook#25]
Hello friend. I have a question about folder tree. May be I am old-fashioned, but for comfortable information  searching is a tree structure. I not saying about old interface like scrapbook X, but may be add text-box for typing folder name in a save process? It just for generation tree.

**Comment by danny0838** [comment]
You can use the site indexer to build the tree if the downloads were saved in the ScrapBook folder.

**Comment by danny0838** [comment]
Related behaviors has been changed in 39.0. The user can now specify the saved filename (or folder name if saved as folder), with optionally the subdirectory path, and the indexer will work for them. Unfortunately, download prompt is not supported, as it could cause many issues.
