### ISSUE TITLE
新建文件夹，将项目拖入该文件夹后，排序变更

### ISSUE THREAD

**Issue by Delectate** [danny0838/webscrapbook#250]
旧版：
某文件夹，并将项目拖入该文件夹，项目自动追加到目标文件夹尾部；

新版：
某文件夹，并将项目拖入该文件夹，项目自动添加到目标文件夹头部，目标文件夹其余项目下沉；

期望：
提供可选项，追加到尾部，还是附加到头部。
谢谢。

**Comment by danny0838** [comment]
Duplicate of #120. Please follow that thread.
