### ISSUE TITLE
How to use rich-text sticky note?

### ISSUE THREAD

**Issue by kcthrn** [danny0838/webscrapbook#251]
How to apply bold, italics, etc. to text in the rich-text sticky note?

**Comment by danny0838** [comment]
Right click on the note button of the editor toolbar and select `insert sticky note (rich text)` to insert a sticky note that allows internal rich text.

However, it may be some bother to apply styles as HTML editor does not work in the sticky note currently. You do can do it through the browser inspector or by copy and paste, though.
