### ISSUE TITLE
Folder disappeared from the TOC

### ISSUE THREAD

**Issue by lefth** [danny0838/webscrapbook#253]
I noticed a lot of pages I saved were no longer showing in the sidebar, and I determined the cause was that a whole folder was gone. In toc.js I was able to find the folder and its children, but the folder was not under "root" nor was it under any other folder. It was not recycled (based on the meta or toc data). I wonder how this could have happened, and if the problem can be prevented in the future?

Here is the toc with the missing folder (an unparented folder, "20211026153925832"):
[missing-20211026153925832_toc.js.txt](https://github.com/danny0838/webscrapbook/files/7579511/missing-20211026153925832_toc.js.txt)

Background info:

- I think I moved the folder parent after it was created and populated.
- The folder was nested, not root level.
- I temporarily ran out of disk space on the drive that the WSB server runs in, but that was days after the folder was initially moved.

Let me know if there's any more info I can give, or ways I can help. If this can't reasonably be debugged or fixed, I'm still grateful the server doesn't do aggressive cleanups (recovery was easy). Thanks!

**Comment by danny0838** [comment]
1. What is the version of your browser, WSB, and PyWSB?
2. How did you move the parent folder?
3. Did you see any error message during the moving or an operation before or after it?
4. Is there a backup in the backup directory? ( By default should be something like  `.wsb/backup/<id>-transaction`)

**Comment by lefth** [comment]
1. Firefox 94.0.1 (64-bit) on Windows, WSB 0.143.0, PyWSB 0.45.0 running in WSL.
2. I moved the folder by dragging it in the WSB sidebar. (It's possible I created/moved the folder much earlier but didn't populate it until more recently.)
3. I don't remember any error.
4. The missing folder appears in a transaction: `.wsb/backup/20211104033422181-transaction`. In that folder, meta.js looks correct:
```
  "20211026153925832": {
    "title": "TheFolderTitle",
    "type": "folder",
    "create": "20211026153925832",
    "modify": "20211026153925832"
  },
```
And the toc references the folder twice, as it should:
```
  "20211026141419036": [
	// ...
    "20211026153925832"
  ],
  "20211026153925832": [
    "20211026153323587" // only one child
  ],
```
But the folder only has one child, so I must have been in the middle of reorganizing when this transaction was made. I know I added an unusually large number of children at once (multi-selecting and dragging them into the folder): 417, so I wonder if that's part of the problem.

I searched for the ID of the parent folder (the one that didn't disappear), but it isn't part of any other transactions (aside from 20211104033422181-transaction, mentioned above).

**Comment by danny0838** [comment]
What folder did you drag? The missing folder, other items, or both? And, what items? The ancestor, sibling, or descendants?

Did the folder disappear immediately after you had performed the move or it was noticed after several operations afterwards?

**Comment by lefth** [comment]
I don't remember the origin of the folder (that disappeared): I may have created it then dragged it into place, or I may have created it in its final place. When I populated the folder, I think it was already in its final place (a child of a top-level folder). The 400+ items I dragged in were top-level captures (no folders). I think the folder did not disappear right away--I'm sure I at least glanced at the contents. I noticed it was missing ~10 days later.

**Comment by danny0838** [comment]
You mean the folder was moved at about 10 days ago?

If that's the case, the operations were performed using an earlier version of WSB, which had an issue that could cause the sidebar tree not reloaded correctly when updated. If there were other simultaneously running tasks (such as capturing a web page) during your operations, it may cause the tree be in an inconsistent status.

If that's the case, you should not encounter the same issue using the latest versoin of WSB.

**Comment by lefth** [comment]
Good to know, thanks!
