### ISSUE TITLE
Mojibake in viewing archived page

### ISSUE THREAD

**Issue by ray4423** [danny0838/webscrapbook#254]
"view archived page..." displays in Mojibake on rare occasions.

I captured in HTZ package and drop HTZ file to "view archived page". It display in Mojibake.
I unpacked HTZ package and drop local index.html to new tab. It display without any problems.

I assume UTF-8-encoded Japanese text(specified charset=UTF-8 in .html) is displayed as Windows-1252 or ISO-8859-1 encoding.

original:
学生向けプログラミング入門
https://mrradiology.hatenablog.jp/
![original screenshot](https://user-images.githubusercontent.com/1713571/142858909-13fef0ac-f1ac-4a9b-9b66-11d8ab57009e.png)

viewing archived page:
![view in archived page screenshot](https://user-images.githubusercontent.com/1713571/142859009-7b752ffe-d30a-4271-b576-0704a52a53a2.png)

unpacked local index.html:
![unziped page screenshot](https://user-images.githubusercontent.com/1713571/142859148-563891bc-ac72-471c-9f62-5a34c47b4883.png)

HTZ package file:
[testデミオ.整備書.学生向けプログラミング入門.2021-11-22_20-45-04_20211122204504.htz.zip](https://github.com/danny0838/webscrapbook/files/7580924/test.2021-11-22_20-45-04_20211122204504.htz.zip)

exported options:
[webscrapbook.options.20211122.json.txt](https://github.com/danny0838/webscrapbook/files/7580811/webscrapbook.options.20211122.json.txt)

Firefox 91.3.0esr
WebScrapBook 0.142.0

thanks for great extension!

**Comment by danny0838** [comment]
Seems a feature of the browser. The browser may ignore a `meta[charset]` element if it does not reside in a short range from the beginning of a document.

For the `index.html` of your archive, the `meta[charset]` is at around 3400th byte from the beginning, causing the browser to ignore it.

We probably cannot resolve this issue easily as it depends on the browser. A workaround is to modify the file and to decrease HTML code before `meta[charset]`. You may also set up a capture helper to do it automatically.

**Comment by ray4423** [comment]
Thanks for yor answer.
I don't understand a little, 
but why can firefox display index.html extracted from the HTZ package normally?

**Comment by danny0838** [comment]
It may be possible that the browser implements different ignoring criteria for a normal page and an iframe (the archive viewer embeds the content in an iframe).

**Comment by danny0838** [comment]
This issue seems not reproduced in Firefox 97.

**Comment by danny0838** [comment]
@ray4423 Can you help us confirm that whether this issue is still reproduced in the latest Firefox release?

**Comment by ray4423** [comment]
It doesnot seems to reproduce in
WebScrapBook 1.4.0
Firefox portable 98.0 (64-bit)

Still  reproduced in
Firefox potable 91.7.0esr (64-bit)

Thank you for letting me know!
I'm using ESR so I'll wait for a while.

**Comment by danny0838** [comment]
Thank you for confirmation. Close issue.
