### ISSUE TITLE
(Almost)Infinite asking windows for all web site elements

### ISSUE THREAD

**Issue by Ygarr** [danny0838/webscrapbook#255]
When choose "Capture tabs" the app begin to ask to save every part of site so it is goes on endlessly. And I cannot to cancel this process, after closing the submodal window(of saving separate file) — new one appears .

**Comment by danny0838** [comment]
Sees to be [the issue](https://github.com/danny0838/webscrapbook/wiki/Issues#chromium-based-browsers) of a Chromium-based browser. You have to uncheck the `Ask where to save each file before downloading` browser settings.
