### ISSUE TITLE
A page can't be saved, requests JavaScript running

### ISSUE THREAD

**Issue by Exchie** [danny0838/webscrapbook#259]
Hello,
OS: Linux 64 Slackware 14.2.
Browser: Firefox 95.0.2.
Back-end server is set.

Trying to capture the page at: [forum.url](url="https://forums.overclockers.ru/viewtopic.php?f=89&t=375155")
Used different methods: Capture tabs, Capture tabs (Source), Capture tabs as... The page is saved, shown in the side panel. When open it from the panel, it says that JavaScript must be on to see its content.
The default capture settings assume scripts removing.

**Comment by danny0838** [comment]
What is the exact URL of the web page?

Also, pleaae try setting the "Scripts" capture option to "Save" and see if it works.

**Comment by Exchie** [comment]
Sorry for missing [url](https://forums.overclockers.ru/viewtopic.php?f=89&t=375155).
Just tried to set "script" capture option to "save". The same result -- asks to turn on JavaScript.

**Comment by danny0838** [comment]
I cannot reproduce the problem you described.

Please provide the version of your OS, browser, and WebScrapBook, and capture options (copy from `Capture as` > `Advanced` or export from the options dialog).

If you have other extensions installed, please disable them and restart the browser before the capture in case there's a conflict.

**Comment by Exchie** [comment]
Tested with different add-ons on/off. That happens only when "uBlock Origin" is on. No other add-ons prevent from saving the page.

OS: Slackware 14.2
Browser: Firefox 95.0.2
Back-end server is set.
WebScrapBook: 1.1.0

WebScrapBook options are in the .zip file below (.html file +):
[Options.zip](https://github.com/danny0838/webscrapbook/files/7831088/Options.zip)

**Comment by danny0838** [comment]
> Tested with different add-ons on/off. That happens only when "uBlock Origin" is on. No other add-ons prevent from saving the page.

I don't get it. Do you still have the same issue when performing a capture after disabling all other extensions and restarting the browser?

I still cannot reproduce the issue till now. Can you provide a few screenshots illustrating the problem?

**Comment by Exchie** [comment]
I've created a new clean profile in Firefox. Installed only WebScrapBook and uBlock Origin add-ons. Configured to use the back-end server. No more settings touched.
There are five screenshots.
The initial state, only one page and a bookmark for the target page are in the scrapbook ![initial state](https://user-images.githubusercontent.com/24848707/148660471-7b89c071-2b16-457c-a7c1-308af2ac3d32.png)
uBO is on, the page is saved, then opened:
![saved ublock on on](https://user-images.githubusercontent.com/24848707/148660506-17b5e552-c102-4a02-b9c0-aa129aed4041.png)
After that uBO is turned off, the page was reloaded 
![saved ublock on off](https://user-images.githubusercontent.com/24848707/148660531-aaa95904-c787-4267-bd58-b921ca503c3c.png)

uBO is left off, capturing the original page again. Trying to load it:
![saved ublock off off](https://user-images.githubusercontent.com/24848707/148660568-7c51ade3-8c27-4882-ab19-d038b496387d.png)
uBO is on again, reloading...
![saved ublock off on](https://user-images.githubusercontent.com/24848707/148660581-511fc97d-42dc-4772-ab00-5075be60d592.png)

**Comment by danny0838** [comment]
This seems similar to what I see. The original page seems to be blanked when I have uBO turned on. It seems to be some uBO rule causing this, and you may need to report it to the developer or rules mainterer of uBO if the behavior is not expected.

I see only blank pages in the screenshots. What do you mean by saying "When open it from the panel, it says that JavaScript must be on to see its content." and "The default capture settings assume scripts removing."?

**Comment by Exchie** [comment]
If NoScript add-on is activated, then such a message appears (JS required):
![ask need js](https://user-images.githubusercontent.com/24848707/148834632-098060ad-1485-450a-bf86-44a0691c1b62.png)
The message says: "This site requires JavaScript is on to operate properly".
Disabling NoScript cause this message to disappear:
![noask need js](https://user-images.githubusercontent.com/24848707/148837615-a2b6a8a1-224c-47f6-bd15-139a2607ca95.png)
"The default capture settings assume script removing." I meant, that in my WSB settings an option is chosen to remove scripts. It's just for me by default.

**Comment by danny0838** [comment]
So the problem is NoScript, which hasn't been mentioned about before.

WSB normally saves `<noscript>` tags, which are shown only when the browser has JavaScript disabled, which is mimicked by NoScript when activated. This is independent to whether scripts are saved, as a page without scripts is not equivalent to a browser with JavaScript disabled/unsupported, and the user may want the `<noscript>` related info even if he captures a page "without scripts".

If you really don't want the `<noscript>` tags, you can set the hidden option `capture.noscript` to `blank` or `remove`.

We are considering whether to add a mode to unwrap the `<noscript>` tags when capturing a web page, and whether to add `capture.noscript` to the GUI.
