### ISSUE TITLE
Site Indexer problem(s)

### ISSUE THREAD

**Issue by ThePuterMan** [danny0838/webscrapbook#26]
The site indexer looked at the 4 files I selected to test it and finished up saying done but nothing happened after that. No index of the files.

Whilst (not?) creating the index it took the htz files and copied something to the downloads folder as zip files but did not remove these again when it had finished maybe because the process terminated incorrectly? Should there be 4 different zip files or am I not understanding what is supposed to happen?

Closing this because I don't think this does what I was expecting it to do.

**Comment by danny0838** [comment]
Only the WebScrapBook folder or the ZIP package of the WebScrapBook folder should be provided to the site indexer. It seems that what you have provided is an HTZ file, which is not what should be provided. We'd add a check to make the site indexer reject a bad provision.

Additionally, closing an issue means that we should not keep following it and working on it, mostly means it's done or it's been determined as invalid. You probably should not close this issue if is not the case.

**Comment by ThePuterMan** [comment]
Understood. Reopening

**Comment by danny0838** [comment]
@ThePuterMan What is your current problem now? Did you try providing a ScrapBook folder to build index? And does it work?

If there's no further problem we are going to close this issue.

**Comment by danny0838** [comment]
Added a check to reject a non-ScrapBook folder in 0.19.1.

**Comment by danny0838** [comment]
Close issue since no further problem going on.
