### ISSUE TITLE
How to start with PyWebScrapBook

### ISSUE THREAD

**Issue by GCRaistlin** [danny0838/webscrapbook#260]
I really don't understand how to make things work (I use Windows). I installed Python and PyWebScrapBook. Then I executed `wsb config -ba` and `wsb serve`. The first question is is there a way to run the last command in the background, as a service? Or do we need to have this console window on the screen all the way?
But okay, let's go further. I specified `http://localhost:8080/` as the backend server address in Options. I run the server. I open scrapbook and see:
![2022-01-13 WSB](https://user-images.githubusercontent.com/12427521/149235816-dc6f1dae-25d2-4281-bd95-4b4d1f27920a.jpg)
What did I miss?

**Comment by danny0838** [comment]
Most of your question should have been answered by [the documentation](https://github.com/danny0838/webscrapbook/wiki/Basic#3-browser-sidebar-approach). Have you checked it?

If you still have the same issue. Please provide the version of your OS, browser, WebScrapbook, and PyWebScrapBook (through `wsb --version`) for further investigation.

**Comment by josephfrances123** [comment]
Good day.. Is it possible to use it with Pydroid3? I tried but I don't know what to do next.. I think it's not included? 
![Uploading Screenshot_20220131_171352_ru.iiec.pydroid3.jpg…]()

**Comment by danny0838** [comment]
@josephfrances123 Can't read your image. You should be able to check whether PyWSB is installable and runnable through the interface and console log. Generally speaking, Python is restricted on Android and it should make more sense to host the PyWSB server remotely (either on your PC or an external server) and let the WSB on mobile access it.

**Comment by danny0838** [comment]
Close stale issue. Raise a new issue if you have a specific problem.
