### ISSUE TITLE
Where are datas cached while catching them before they get saved under "Downloads"?

### ISSUE THREAD

**Issue by LawnchairLarry** [danny0838/webscrapbook#262]
I asked that question on firefox Add-onn repository a few days ago. You answered that itnermidiate data are stored in internal storage. That means they are stored on RAM?
It's just becaused im afraid that data could become abandoned on my HDD if the add-on crashes, what it did a few times ;)

**Comment by danny0838** [comment]
No. The browser storage is some form of database in the hard disk. WSB has also implemented some criteria to clear staled cache, which won't live permanently.

**Comment by LawnchairLarry** [comment]
Ok, thx for your fast answer, i got you an additional star ;)
If i manage to download the stuff i want to download you get another one :D
