### ISSUE TITLE
Dark background in WebScrapBook Sidebar possible?

### ISSUE THREAD

**Issue by mseliger** [danny0838/webscrapbook#268]
Is it possible to have a dark background (and white text) in the sidebar WebScrapBook?
All my other sidebar elements like history, bookmarks, SingleFile etc. have a black or dark grey background - only WebScrapBook has a white background. I know that it is possible to change the background with css in the userChrome.css file. What is the name of the WebScrapBook tree (in former times it was #sbTree)?

**Comment by danny0838** [comment]
Sidebar is part of extension so you have to check it: basically [src/scrapbook/sidebar.html](https://github.com/danny0838/webscrapbook/blob/master/src/scrapbook/sidebar.html), [src/scrapbook/manage.html](https://github.com/danny0838/webscrapbook/blob/master/src/scrapbook/manage.html), and their related css files.

**Comment by guidomz** [comment]
Is there a way to tweak the css and html of the already installed package intead of on the source code of the precompiled extension? I've looked in the files of the installed packages but found nothing named sidebar.html or manage.html.

**Comment by danny0838** [comment]
> Is there a way to tweak the css and html of the already installed package instead of on the source code of the precompiled extension?

As above mentioned, use userChrome.css (or userContent.css).

> I've looked in the files of the installed packages but found nothing named sidebar.html or manage.html.

Well, it's just there in the source code. You probably have done something wrong if you can''t see it.

**Comment by guidomz** [comment]
In my debian install, I found the files I was looking for in here: ~/.config/chromium/Default/Extensions/oegnpmiddfljlloiklpkeelagaeejfai/2.0.4_0/scrapbook

Might help others. I guess I just wasn't looking hard enough earlier. Thanks.
