### ISSUE TITLE
Please need help for 'Backend initilization error: Unable to connect to backend server.'

### ISSUE THREAD

**Issue by toto1515** [danny0838/webscrapbook#269]
Hello,
I try to use Webscrapbook with sidebar.
I install python 3.8.5
I install pywebscrapbook
   _python -m pip install -U webscrapbook_
i start backend server in a folder:
   _E:\WebScrapBook>wsb config -ba_
   _Generating ".wsb\config.ini"..._
   _Generating ".wsb\serve.py"..._
   _Generating ".wsb\app.py"..._

   _E:\WebScrapBook>wsb serve_
   _WebScrapBook server starting up..._
   _Document Root: E:\WebScrapBook_
   _Listening on http://localhost:8080_
   _Hit Ctrl-C to shutdown._

in the options, i select http://localhost:8080 for the backend server
i set Save captured data to: Backend server

but when i try to 'capture a tab', or 'open scrapbook', i get a message 'Backend initilization error: Unable to connect to backend 
server.'

Can you tell me what is wrong?
Thanks

**Comment by danny0838** [comment]
Do you keep the command prompt opened when you open the sidebar? Can you see a directory list through visiting http://localhost:8080 in a new browser tab?

If not, it's likely that your device has another service listening to port 8080, and you have to specify another port (or shutdown the conflicting service) to prevent a conflict.

**Comment by toto1515** [comment]
Hello,
yes, i keep the command prompt opened when i open the sidebar.
i can also visit the directory list through visiting http://localhost:8080/ in a new browser tab.
i tried then to capture a tab and i got the same error.
Then, i tried the 'Open scrapbook' command and a new window appear with the correct view of the directory.
So all seem to work fine for now, capturing and browsing is Ok.
Thanks for your help.

i have an other question: the sidebar is not a sidebar but a popup window. is it normal?

**Comment by danny0838** [comment]
> Hello, yes, i keep the command prompt opened when i open the sidebar. so, i try to visit the directory list through visiting http://localhost:8080/ in a new browser tab and it shows the right directory. Then, i tried the 'Open scrapbook' command and a new window appear with the correct view of the directory. All seem to work fine, capturing and browsing is Ok. But i notice that if i close the 'http://localhost:8080/' Tab, it does not work. If i re-open a 'http://localhost:8080/' Tab, scrapbook works.
> 
> Another test : i try with http://localhost:8000/ and the same results occur, http://localhost:8000/' Tab must be present in the tabs list for scrapbook to work.
> 
> That's strange, isn't it? Thanks in advance for your help.

**Comment by danny0838** [comment]
> But i notice that if i close the 'http://localhost:8080/' Tab, it does not work.
> If i re-open a 'http://localhost:8080/' Tab, scrapbook works.

This is unexpected. Connection to the backend should work regardless of whether a tab visiting the backend is opened.

What is the version of your OS, browser, WebScrapBook and PyWebScrapBook?

Do you see any error or warning in the commnd prompt when you operate the sidebar without a tab opened?
