### ISSUE TITLE
Naming of files/folders

### ISSUE THREAD

**Issue by ThePuterMan** [danny0838/webscrapbook#27]
I don't now how to put an enhancement flag on this but....

Could the file name (htz etc) or folder name take the name of the tab? It worked once 'out of the box' but once I directed it it's default directory all I get is the date and time as a file or folder name.

**Comment by danny0838** [comment]
If "Save in ScrapBook folder" is checked, the saved file name is always a timestamp, this is to make the site indexer work better. Uncheck it if you simply want to archive each web page individually.

**Comment by ThePuterMan** [comment]
OK I unchecked that and now it saves the filename but to the downloads folder. What I would prefer is that scrapbook could save to a different folder but retaining the name, so that all the saved scrapbooks are in one place. Of course I can do this by selecting a folder but I save many pages a day which makes that a pain in the butt.

**Comment by danny0838** [comment]
There is currently a restriction for browser extension APIs that they can only save files to the download folder, or a prompt with a default filename, but the directory is fixed. We may check whether there's an available workaround.

**Comment by danny0838** [comment]
Implemented a more natural download when not saved in ScrapBook folder in 1.19.2.
