### ISSUE TITLE
capture website slideshow

### ISSUE THREAD

**Issue by bbxrider** [danny0838/webscrapbook#270]
I saved this website for a house for sale
https://www.redfin.com/CA/Sacramento/3317-22nd-Ave-95820/home/51679349
there is 1 page with a slideshow
The saved version doesn't have the slide show, I have tried with both chrome and ff
is it not possible to save slide shows? is there a webscrapbook setting that will allow this? is there anyway to save such a webpage?
thanks

**Comment by danny0838** [comment]
Such slide thing is controlled by page scripts. You can try checking the `scripts` option and see if it works.

If it still doesn't work, there is no simple solution. In such case the scripts are probably server environment dependent and it's not possible to get them work offline unless you are skilled enough to rewrite them.

**Comment by bbxrider** [comment]
ok thanks for the super quik response, tried the scripts option but same result, none of the slide show pics are in the saved files, I guess that means they are on the server, the pics evidently are accessed via links, there are urls in the webpage, sample, "https://cdn-3.eneighborhoods.com/x2/@v=-906314843@/60153/3/335/222031335/222031335_3.jpg"
I'm guessing this is the 3rd pic, and a script is necessary to really access it? there are similiar urls for all the other pics, oh well

**Comment by danny0838** [comment]
Generally speaking, to download resource files you want can usually be achieved through a site-specific browser extension, user script, or a bot. In some cases writing a capture helper for WebScrapBook can also work.

Any of them requires the knowledge of web design and front-end, though.

**Comment by bbxrider** [comment]
ok thanks again, if you can point to any references/tutorials/etc for scripts, or bots, I would give those a  try.  since I can access the slideshow pics via urls' like the one above, I'm guessing I would have to modify the saved .html, and try to  re-create a slide show with the url's or download them and create the slide show, either way lotsa work for what I wanted to do. the website is a listing for a house for sale, and there will be many. too bad used to be able save websites like this with the browser save function

**Comment by danny0838** [comment]
There's probably no single tutorial for that. What you are going to do is writing a bot. You need the general knowledge of web design (i.e. HTML, CSS, JavaScript) to read the code of the source site and write a code to extract what you want from it.
