### ISSUE TITLE
Can not save captures

### ISSUE THREAD

**Issue by drkhdrkh** [danny0838/webscrapbook#271]
I did the following with WebScrapBook 1.4.0 in Chrome 99.0.4844.74 under Windows 7. Every WebScrapBook option is kept default. The Chrome option:"Ask where to save each file before downloading" IS enabled.

(1)

Open https://en.wikipedia.org/wiki/Main_Page

(2)

Randomly select a segment of plain text

(3)

From right-click menu, select WebScrapBook > Capture selected ranges.

(4)

The "Capture page" dialogue pops out, together with a "Save As" dialogue for a file named fa30912f-09ff-48d4-9139-74cf0ea88c58. The Save button in the "Save As" dialogue is pressed.

(6)

A file differently named "a33b38c5-739d-4d62-83ad-232c1198f60d.tmp" is saved, but
the "Save As" dialogue appears again for the same fa30912f-09ff-48d4-9139-74cf0ea88c58 file. So, the Save button is pressed again.

(7)

What happens in the last step goes on and on. But the .tmp file changes filename each time the "Save AS" dialogue appears.

**Comment by danny0838** [comment]
First, uncheck the `Ask where to save each file before downloading` browser option to prevent the popups. This is an issue of Chromium, see [known issues](https://github.com/danny0838/webscrapbook/wiki/Issues#chromium-based-browsers) for more details.

However, the saved filenames shouldn't be all UUID if you use default options. It seems to be an issue of  Chrome that can happen due to unclear reaaon. Try creating a new user profile and aee if it ia resolved.

**Comment by drkhdrkh** [comment]
I found the culprit. It's the "Get CRX" extension.

Thank you for consideration and prompt reply.

**Comment by drkhdrkh** [comment]
Update.

Not only GetCRX prevents WebScrabBook from saving captures to folder. Other download manager extensions, such as DownThemAll! and Chrono Download Manager also make the same trouble. But not all extensions of the kind are troublesome. "Turbo Download Manager" and "Online Download Manager" are OK, I find.

Saving to file is not affected, though.

The aforementioned DownThemAll! even prevents GetCRX from re-naming its downloads, ensuing this red error message for GetCRX in Chrome's extension manager (an example) :"This extension failed to name the download "Google Translate 2.0.12.0.crx" because another extension (DownThemAll!) determined a different filename "".

That led me to find the following report on a similiar issue at DownThemAll!'s Github site:
[DownThemAll removes filename from downloads started by another extension](https://github.com/downthemall/downthemall/issues/246), in which someone by the nickname of Rob--W claims it's a Chrome bug and provides the following two links for it at bugs.chromium.org. I know almost nothing about programming, I  only guess these two bug reports may have something to do with what I'm reporting here and therefore may be of some interest to you:

["filename" of chrome.downloads.download is ignored when an onDeterminingFilename listener has been registered](https://bugs.chromium.org/p/chromium/issues/detail?id=1106297)

[Specified filename is not visible to event handlers in chrome.downloads API](https://bugs.chromium.org/p/chromium/issues/detail?id=1050821)

**Comment by danny0838** [comment]
This needs more investigation. Currently it seems like either an issue of the other extension or an issue of Chromium. We can do nothing for this except adding it to the [known issues list](https://github.com/danny0838/webscrapbook/wiki/Issues) if it's confirmed to be an issue of the browser.
