### ISSUE TITLE
disable save selected area

### ISSUE THREAD

**Issue by zwouip** [danny0838/webscrapbook#272]
Hello,

when we highlight an area in a webpage, only this part is saved in Webscrapbook. Is there an option or parameter to switch this off, so that even when a part of the page is highlighted, Webscrapbook will still save the whole page?

Thank you for your help!

**Comment by danny0838** [comment]
Currently not. But you can perform a full page capture through the context menu or through `capture as` => `Advanced` => add fullPage: true parameter (see the tooltip).

**Comment by zwouip** [comment]
Thank you for your answer.

I was able to add the fullPage: true parameter as you explained while saving a page, but to my understanding this works only for the page I was currently saving. Is there a way to edit the code so that this "fullPage:true" is always active?

**Comment by danny0838** [comment]
No, it's a task-specific config. The context menu may be a simpler solution, or simply don't select when performing a capture.
