### ISSUE TITLE
儲存的 capture 只包含幾張圖, 所存檔案的大小竟達 11.1MB

### ISSUE THREAD

**Issue by drkhdrkh** [danny0838/webscrapbook#274]
您好,

首先, 因有新發現, 三天前我給之前已 closed 的貼文:"Can not save captures #271"做了補充, 不知您看到了嗎?

此次的新問題如下:

我將下列網頁的部份範圍儲存為 single HTML, 儲存的內容只有幾張圖, 每張圖的大小都只有3,4百K, 但所存檔案的大小竟高達 11.1MB. 請問這正常嗎?

https://udn.com/news/story/7238/6205410

選取儲存範圍的起始處見下圖:
![highlight_start](https://user-images.githubusercontent.com/39482269/161207529-91dca32d-4c70-4086-a70c-c2cdd2c8c1d0.jpg)

選取儲存範圍的終結處見下圖:
![highlight_end](https://user-images.githubusercontent.com/39482269/161207836-ce1791ab-caf5-4d7c-bcfd-58184b1fe35b.jpg)

儲存前, 用 eraser 刪除了選取範圍內嵌入的影片:
![remove_video](https://user-images.githubusercontent.com/39482269/161207923-e686343e-0776-40c3-affc-5133e8e0e17f.jpg)

也用 DOM eraser 刪除了這些 icon:
![remove_icons](https://user-images.githubusercontent.com/39482269/161207989-57fa847f-69ea-41e9-b789-8e52ee443341.jpg)

**Comment by danny0838** [comment]
看起來沒問題。

這網頁有使用不同螢幕大小的備用圖片，所以預設選項會儲存同一張圖片不同解析度的版本，把 `圖片` 選項改成`儲存現用`可以減少很多。另外就是儲存格式，`單一HTML檔案`會讓內嵌的圖片大小變4/3倍，而如果用壓縮格式則能縮小一些。

我的測試結果；
- 預設儲存為資料夾，大概 7.33 MB。
- 儲存為資料夾，`圖片`改`儲存現用`，大概 2.46 MB。
- 儲存為 HTZ 封存檔，`圖片`改`儲存現用`，大概 2.07 MB。

細節詳見[FAQ](https://github.com/danny0838/webscrapbook/wiki/FAQ-(zh_TW)#%E7%82%BA%E4%BB%80%E9%BA%BC%E7%B6%B2%E9%A0%81%E5%89%AA%E8%B2%BC%E7%B0%BF%E6%93%B7%E5%8F%96%E7%9A%84%E7%B6%B2%E9%A0%81%E6%AF%94%E5%85%B6%E4%BB%96%E5%B7%A5%E5%85%B7%E5%84%B2%E5%AD%98%E7%9A%84%E7%B6%B2%E9%A0%81%E6%9B%B4%E8%82%A5%E5%A4%A7)。

**Comment by drkhdrkh** [comment]
啊! 現在我知道為什麼在 Capture - content 某些項目的儲存選項裏有一個 Save current 了. 多謝.
