### ISSUE TITLE
unable to connect to backend server in Tor

### ISSUE THREAD

**Issue by mojorissin** [danny0838/webscrapbook#275]
i am trying out Tor (11.0.9 (based on Mozilla Firefox 91.7.0esr) (64-bit)) but cannot connect to backend server of WSB  (up to date) ?

working in FireFox (98.0.2 (64-bit)) 

working in Brave ([Version 1.37.109 Chromium: 100.0.4896.60 (Official Build) (64-bit)

any help or tips to solve this please 

kind regards

mojorissin

**Comment by danny0838** [comment]
Tor connects through proxies and thus can't access localhost by default.

According to [this thread at Stack Exchange](https://tor.stackexchange.com/questions/11994/how-to-access-local-host-through-tor-browser), the `network.proxy.allow_hijacking_localhost` or `network.proxy.no_proxies_on` configs can be tweaked to allow connection to 127.0.0.1 etc., but there may be a security concern which may potentially break anonymity. Unfortunately I am not the security expert and don't know all the details. Use at your own risk anyway.

**Comment by mojorissin** [comment]
many thanks for guidance Danny .
