### ISSUE TITLE
Any way to disable or lower the background request frequency to the backend server?

### ISSUE THREAD

**Issue by awatuna** [danny0838/webscrapbook#276]
It keeps refreshing? the config and tree list while in background, this became a problem when it's a large archive over slow link.

It may have to do with firefox's addon management, is there a way to disable or lower the frequency?

 - - [05/Apr/2022 17:48:58] "GET /tree/?a=list&f=json HTTP/1.1" 200 -
 - - [05/Apr/2022 17:49:06] "GET /?a=config&f=json&ts=1649152145790 HTTP/1.1" 200 -
 - - [05/Apr/2022 17:49:06] "GET /tree/?a=list&f=json HTTP/1.1" 200 -
 - - [05/Apr/2022 17:49:09] "GET /?a=config&f=json&ts=1649152149347 HTTP/1.1" 200 -
 - - [05/Apr/2022 17:49:09] "GET /tree/?a=list&f=json HTTP/1.1" 200 -
 - - [05/Apr/2022 17:53:54] "GET /?a=config&f=json&ts=1649152434231 HTTP/1.1" 200 -
 - - [05/Apr/2022 17:53:54] "GET /tree/?a=list&f=json HTTP/1.1" 200 -
 - - [05/Apr/2022 17:54:05] "GET /?a=config&f=json&ts=1649152445077 HTTP/1.1" 200 -
 - - [05/Apr/2022 17:54:05] "GET /tree/?a=list&f=json HTTP/1.1" 200 -
 - - [05/Apr/2022 17:54:20] "GET /?a=config&f=json&ts=1649152460297 HTTP/1.1" 200 -
 - - [05/Apr/2022 17:54:20] "GET /tree/?a=list&f=json HTTP/1.1" 200 -
 - - [05/Apr/2022 17:54:24] "GET /?a=config&f=json&ts=1649152464407 HTTP/1.1" 200 -
 - - [05/Apr/2022 17:54:24] "GET /tree/?a=list&f=json HTTP/1.1" 200 -
 - - [05/Apr/2022 17:54:45] "GET /?a=config&f=json&ts=1649152485493 HTTP/1.1" 200 -
 - - [05/Apr/2022 17:54:45] "GET /tree/?a=list&f=json HTTP/1.1" 200 -
 - - [05/Apr/2022 17:55:30] "GET /?a=config&f=json&ts=1649152530550 HTTP/1.1" 200 -
 - - [05/Apr/2022 17:55:30] "GET /tree/?a=list&f=json HTTP/1.1" 200 -
 - - [05/Apr/2022 17:56:01] "GET /?a=config&f=json&ts=1649152561653 HTTP/1.1" 200 -
 - - [05/Apr/2022 17:56:02] "GET /tree/?a=list&f=json HTTP/1.1" 200 -
 - - [05/Apr/2022 18:00:53] "GET /?a=config&f=json&ts=1649152853344 HTTP/1.1" 200 -
 - - [05/Apr/2022 18:00:53] "GET /tree/?a=list&f=json HTTP/1.1" 200 -
 - - [05/Apr/2022 18:01:10] "GET /?a=config&f=json&ts=1649152870175 HTTP/1.1" 200 -
 - - [05/Apr/2022 18:01:10] "GET /tree/?a=list&f=json HTTP/1.1" 200 -

**Comment by danny0838** [comment]
The connections you listed are mostly sent when you visiting any web page. WSB requires frequent connection to the backend server to make sure if there is any update. These connections mostly transfers very small data and aren't proportionate to the data amount of the scrapbooks, and shouldn't be a real problem in most cases.

You can, however, uncheck the `Show hint when browsing a page having been captured` option to reduce such connections if you really want to.
