### ISSUE TITLE
Program crashes along with entire Edge browser after resetting links on a deep (4-steps) archive on Windows

### ISSUE THREAD

**Issue by alexlyee** [danny0838/webscrapbook#277]
I just left my computer for about 14 hours to download the majority of a website that I need to archive. It seemed to be setting the links for at least a few hours when it suddenly dumped an absurd amount of .tmp files into my downloads folder and crashed my browser. I was doing some minor browsing on Firefox during this time, but I hardly touched the edge browser. I can only presume something wrong happened with the program because I kept a close eye at my CPU and RAM utilization on my workstation with an r9 5950x and 64GB of RAM and it did not use half of my RAM and it was consistently using ~5% of my CPU whilst resetting the links.

How do I prevent this from happening? I need to archive this website.

-sincerely,
alex

**Comment by danny0838** [comment]
1\. Can you provide the URL of the source web page and the capture options (you can copy it from the `Advanced` dialog of `Capture as`)?

2\. Do you check the `Ask me what to do with each download` browser setting? It will cause the browser to prompt for every file to be downloaded and may crash the browser if the amount is very large. (See [Known Issues](https://github.com/danny0838/webscrapbook/wiki/Issues#chromium-based-browsers) for details)

3\. Do you have any other extension that handles downloads? This may cause a conflict (e.g. #271). Disabling all other extensions may help resolving the issue.

**Comment by danny0838** [comment]
Close stale issue due to lack of further information.
