### ISSUE TITLE
Folder creation - renaming

### ISSUE THREAD

**Issue by hermann-san** [danny0838/webscrapbook#278]
Hi, when I create a new folder,  WSB automatically create's a new folder with the name "new folder". 
So for me (and I assume for most other WSB user as well) I would like to rename the folder. It would be nice if WSB would automaticaly open the metadata pop-up window and highlight the text "new folder" so that I can start typing my new folder name right away. I do this very often and it would save me those 2 steps of opening the Metadata pop-up window and highlight the text. Is it possible to automate this now or in a future version of WSB?

![grafik](https://user-images.githubusercontent.com/7679654/162575965-8e7a3c86-6947-4b60-9783-2daed99ec01e.png)![Auswahl_003](https://user-images.githubusercontent.com/7679654/162575912-39ac10a0-2545-4666-991b-20692c6a1837.png)

**Comment by danny0838** [comment]
Implemented in 1.7.0
