### ISSUE TITLE
how to use "view index page" practically

### ISSUE THREAD

**Issue by grotesque** [danny0838/webscrapbook#279]
- click scrapbook extension icon
- select "open scrapbook"
- click 3 horizontal lines in top right corner of the new window that opens
- select the first option "view index page"

> Not Found
> The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

Scrapbook is configured with the webserver.

**Comment by danny0838** [comment]
By default the index page can be generated through the indexer (check `Generate static site pages` and run the indexer from the options). The index page can also be modified through the config of PyWSB.

**Comment by grotesque** [comment]
Danny I still don’t understand. Please elaborate. Thanks.

**Comment by danny0838** [comment]
“Check `Generate static site pages` and run the indexer from the options”.

Please elaborate on what specific part you have difficulty to follow if there's any.

**Comment by grotesque** [comment]
I was trying to understand what the idea of "static site pages" is.
I tried reading wiki but could not understand it. Can you please explain it to me?

It seems to be different from fulltext search cache from what I read.

**Comment by danny0838** [comment]
I think you can simply run the steps described above and see what happened, which speaks much more clear than language.

The static site pages are static html (or like) files listing the sidebar item tree of the scrapbook(s). This is generally used only when accessing the scrapbook remotely without the browser extension. You probably don't need to bother it at all if you simply never do that.
