### ISSUE TITLE
Can people who've been using Scrapbook use this extension? If so, how do we find & import the data? 

### ISSUE THREAD

**Issue by SalCanz** [danny0838/webscrapbook#28]
Hi, Danny & all,

Please forgive if I'm asking dumb questions or should have been able to figure out answers from what's already been written. My thanks to anyone who can answer my questions.
 
I'm one of those people who are so behind the times that I was still using Scrapbook by Gomita -- with lots of bookmarks saved. And Firefox set to automatically update. And not tuned in enough to know the Firefox 57/Quantum was coming. Then yesterday, Firefox updated. And I'm without a bunch of loved addons, most alarmingly Scrapbook. 

As you can see if you look at the reviews under Scrapbook at https://addons.mozilla.org/en-US/firefox/addon/scrapbook/reviews/  and on Mozilla help https://support.mozilla.org/en-US/questions/1188657      I'm not the only one.  The suggested work-arounds look difficult, and it does seem that, sooner or later, one should move to the new Firefox. 

I've gotten to the point of figuring out that Web Scrapbook is the successor to Scrapbook X, which was the successor to Scrapbook. And I've even figured out where my Scrapbook data is. I've also looked a bit at the Github page on Scrapbook X.

It looks to me like Web Scrapbook is the logical extension to use to replace Scrapbook and I'm ready to install it. But I have a question and a suggestion. 

Question: If I install it, can I bring in the data from Scrapbook? If so how?

Suggestion: The "Find a Replacement" on the Firefox 57 list of legacy extensions currently links to the MS OneNote Clipper add on -- which is not really the same as Scrapbook. Is there some way you can get Mozilla to change that and link to Web Scrapbook.

Finally, I am sure that I am not the only person who would be glad to contribute to support an extension to replace Scrapbook. You should add a donate link to the Web Scrapbook page.

**Comment by danny0838** [comment]
Yes, it's a duplicated question (e.g. #2, #14, #23), and we have [wiki documentation](https://github.com/danny0838/webscrapbook/wiki/Import) for it, too.

**Comment by SalCanz** [comment]
Danny,

I think you did not read beyond the re. line of my post. But it would be good for you if you did. 

I am not a techie, and I can't follow the earlier answers. (If I could, I wouldn't have asked the question.)
What I am is someone who would happily pay you to solve my problem. Instead, you've made me feel stupid, useless, & frustrated. 

Maybe you're not interested in being paid for your work but if you do want to get paid, you are missing an opportunity. There are other people like me who've just lost Scrapbook and are looking for a solution to their problem. I'm sure I'm not the only one who'd be happy to donate to support a replacement for Scrapbook. 

So I think it would be good for you to be more patient with people like me. But that's up to you. 

Good luck in your endeavors,

Sally
~~~~~~~~~~~~~~~~~~~~~~~~
Sally Canzoneri 
Sallycanzoneri@aol.com
(202) 625-2124 (H/W)
(202) 288-8074 (C)

> On Nov 23, 2017, at 10:32 PM, Danny Lin <notifications@github.com> wrote:
> 
> Yes, it's a duplicated question (e.g. #2, #14, #23), and we have wiki documentation for it, too.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

**Comment by danny0838** [comment]
@SalCanz What is the exact and specific difficulties when you attempted to follow the previous answers? Please state them with more detail, so that I'd be able to provide you more assistance besides those provides in the previous answers.
