### ISSUE TITLE
Error Capuring Pages

### ISSUE THREAD

**Issue by roguestar** [danny0838/webscrapbook#280]
Steps to reproduce: Capture any page with default settings

Expected behavior: Page is captured normally

Result: The following error occurs

> Capturing (document) [4] https://www.example.com/ ...
> Fatal error: capturer.getAdoptedStyleSheets(...) is undefined

### Webscrapbook Info
Browser: Firefox 99/100
Frontend: Firefox add-on 1.4.1
Backend: Web PIP webscrapbook-1.6.0

**Comment by danny0838** [comment]
This is a regression of 1.4.1 during a fix of an issue. Use 1.4.0 temporarily should fix the issue. we'll release a fix soon.

**Comment by danny0838** [comment]
Released 1.4.2 which should fix the issue.
