### ISSUE TITLE
"Capture page" fails with latest Firefox on beta channel

### ISSUE THREAD

**Issue by haquewell** [danny0838/webscrapbook#281]
Hi, on Firefox 101.0b9 with Windows, "capture page" fails with error in pop up as illustrated below.
               Capturing (document) [8] https://xkcd.com/ ...
               Fatal error: ({}) is not iterable

It is repeatable and on all pages attempted. The "capture source" works as always. All however seems well in my use of it in Firefox 100.0.2 (albeit on Apple MBP.) 

The first is on FF beta channel, the second is standard release. Potentially there is something coming down the pike which will beg refactoring?

**Comment by danny0838** [comment]
This is [a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1770592) of Firefox for version >= 101.0b8. You can set the config `layout.css.constructable-stylesheets.enabled` to false for a temporary fix before it's fixed officially.

**Comment by haquewell** [comment]
Thank you - you're the best!

**Comment by danny0838** [comment]
Regretfully Firefox has not fix the bug for the 101 release. We have released a quick fix for the browser bug in 1.4.3.
