### ISSUE TITLE
Python script serve.py returns an error

### ISSUE THREAD

**Issue by hermann-san** [danny0838/webscrapbook#284]
Hi,   next issue is coming up :-)
I've setup backend multi scrapbook on Windows 10 on the file share (Linux machine). It works fine on the Windows side.
Now I would like to open those scrapbooks on that Linux machine via multi scrapbook setup. Previously, single scrapbook setup worked fine. 
In my understanding there is actually nothing else to do on the Linux machine then simply executing serve.py  because
`wsb config -ba`
was ran already on the Windows machine. However , I've received an error when executing serve.py on Linux

```
$ [path to directory]./serve.py 
import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.
from: can't read /var/mail/webscrapbook
./serve.py: Zeile 3: Unexpected word syntax error »(«
'/serve.py: Zeile 3: `root = os.path.abspath(os.path.join(__file__, '..', '..'))
```

Is there something I'm missing here? 
Previously it worked fine to open a single scrapbook created on Windows from a Linux machine.  Does the serve.py need to be (or can be) adjusted to Linux OS? The script looks the same to me on Linux and Windows when I create a multi scrapbook from Linux. There is a line in the "app" section of the config.ini. 
; content_security_policy = strict

Thanks again for your help.

**Comment by danny0838** [comment]
Sorry, I can't see what happened without more detailed information.

Generally speaking, if you have successfully run the backend server with single scrapbook configuration on the same Linux device, the error should be nothing to do with the OS but something wrong with your configuration or the way you execute it. You may try moving the whole scrapbook directory to Windows and see if it works or not to confirm whether it's related with the OS.

**Comment by hermann-san** [comment]
thanks for your input.
yes, indeed. It's not a cross OS issue.  
I can't create a working multi scrapbook config on Linux. I get the same error when I try to run `serve.py` 
the command I run first is.
`/home/user/.local/bin/wsb config -ba`
change the config.ini to

[book ""]
name = book1
top_dir = book1
data_dir = 
tree_dir = .wsb/tree
index = .wsb/tree/map.html
no_tree = false

[book "book2"]
name = book2
top_dir = book2
data_dir = 
tree_dir = .wsb/tree
index = .wsb/tree/map.html
no_tree = false
![grafik](https://user-images.githubusercontent.com/7679654/179398900-cf7bbaf8-eac9-46da-a338-d5ea1d5960c5.png)

It works fine, but then ./serve.py give's me the above mentioned error (in the starter message on the top of this issue).
I think I had some issue's setting the path variable when I've installed python. I think that's why I used a workaround 
`/home/hermann/.local/bin/wsb serve`
to start the backend server.  But it worked fine.
Also I had to use the following for wsb config -ba
`/home/user/.local/bin/wsb config -ba`
Could this be the root cause of the error I get?

Thanks

**Comment by danny0838** [comment]
The error message `import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/408.` seems to be something related with ImageImagick.

I suspect that the `./serve.py` isn't run with Python due to unclear reason, and maybe running it with `/path/to/python ./serve.py` may fix it?

However, if this is true, you shouldn't be able to get it work with the single scrapbook, either. Provide your configuration of the previously working single scrapbook may do some help.

**Comment by hermann-san** [comment]
That command didn't work, but you where right. The script wasn't opened with Python apparently. I've opened the script with a file manager and the correct python path and it worked.  
I just don't know why it's not working when I add the path to my .profile file.
That issue drive's me crazy, but at least I now have a way how it will work. 

Thanks so much for your help :-)

**Comment by danny0838** [comment]
The default shebang `#!/usr/bin/env python3` should work as long as `python3` is in PATH. If it's not, there's probably something wrong with your python installation and/or environment settings. You can confirm it by checking whether `python3` or `which python3` works.

**Comment by hermann-san** [comment]
```
:/$ python3
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 

```
Python environment settings seems to be OK then, right?
```
echo $PATH
/home/Username/platform-tools:/home/username/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```
.profile  file
`export PYTHONPATH=/usr/bin/python3.8`

**Comment by danny0838** [comment]
Shebang `#!/usr/bin/env whatever` should work as long as `whatever` is in PATH. If is doesn't, it's either `whatever` is not in PATH or there's something wrong with the `/usr/bin/env`, and you need further trouble shooting. Alternatively you can replace the shebang with the value of `which python` to get the script executed with pgthon, or simply ignore it and keep running it using the current way.

Close the issue as Linux trouble shooting is out of scope of our support.
