### ISSUE TITLE
WashingtonPost Maps Not Saved Correctly

### ISSUE THREAD

**Issue by sj365** [danny0838/webscrapbook#286]
Hi Danny,

The map on this page https://www.washingtonpost.com/dc-md-va/2022/05/15/fairfax-streets-confederate-civil-war/    is not being saved correctly with WSB.  Please review the map image as seen on the Wpost page, vs the WSB saved .html file.

Thanks

Wpost map
![WPost map-2022-07-20_152517](https://user-images.githubusercontent.com/52141467/180066447-12c751b2-bb2e-4a75-9d42-8411257b300c.png)

WSB saved .html
![WSB map-2022-07-20_152249](https://user-images.githubusercontent.com/52141467/180066571-59d95ba3-2268-4243-a6d6-45cb86167026.png)

WebScrapBook 1.4.3
Chrome is up to date
Version 103.0.5060.114 (Official Build) (64-bit)

Processor 11th Gen Intel(R) Core(TM) i9-11980HK @ 2.60GHz 3.30 GHz
Installed RAM 32.0 GB (31.7 GB usable)
System type 64-bit operating system, x64-based processor
Pen and touch Touch support with 10 touch points
Edition Windows 11 Home
Version 21H2
Installed on ‎1/‎31/‎2022
OS build 22000.795
Experience Windows Feature Experience Pack 1000.22000.795.0

**Comment by danny0838** [comment]
It's a canvas with some advanced technique, and unfortunately cannot be accessed and captured by a browser extension. As [Known Issues](https://github.com/danny0838/webscrapbook/wiki/Issues) has said.
