### ISSUE TITLE
Batch or a bulk mode

### ISSUE THREAD

**Issue by Gabarito007** [danny0838/webscrapbook#288]
Is there a way to invoke "Capture tab" through command line?
Or some other way not by mouse clicking?
I ask that because I need to save too many pages, and looking for an automatic way mode.

In other words, I need to use WebScrapbook like a batch mode, in a bulk manner to grab many pages at once.

Thanks.

**Comment by danny0838** [comment]
You probably want `Batch capture all tabs`, which can be added from the options dialog. You can also enter `Advanced mode` for further customization with JSON in a `Batch capture` or `Capture as` dialog.

**Comment by Gabarito007** [comment]
Thank you, danny, for your promptly reply.

No, I'm not looking for `Batch capture all tabs`.
I want a way to copy an entire site, where I've already now all URLs.
And trying to write a script to pass URLs to WebScrapbook.

**Comment by danny0838** [comment]
To capture each page as an item, you can fill the URLs in the batch capture dialog.

To capture all pages interlinked as an item, tweak the `Capture links` related options in the `Capture as` dialog.

Off-browser capture is not supported as WSB is a browser extension and the capture processes requires browser rendering and its API. You do can write an extension to invoke a capture through message passing, but this is rather complicated and not yet documented. Check the test suite of this project for an illustration of an extension-invoked capture.

**Comment by Gabarito007** [comment]
Thank you, danny.

I guess, I'm done, now.
I was using a previous version, 0.42, no Batch Capture resource, and realized just now that there is a newer version.

I'm playing with it. Maybe, my needs will be solved.

**Comment by Gabarito007** [comment]
Hey! There are too many changes with the newer version...
It changes many things I'm doing here.

I could see that, now, it saves emoji's combo pictures, with 25 ones.
And some combos has emojis that it isn't used by the HTML file.
It wastes disk space.

How to handle that?

**Comment by Gabarito007** [comment]
Sorry, danny, to bring too many questions/issues, but I guess all of them are "on topic" subject.

Saving WhatsApp chat page (Firefox), WSB didn't grab images where referenced by blob tags.
Like this:
src="20220725115550021_arquivos/urn:scrapbook:download:error:blob:"

Previous version did not save it too, but I could know what image was in case.
src="blob:https://web.whatsapp.com/e83ba709-d82e-4b87-a13f-dba39c898ce4"

Is there a way to circumvent that?

**Comment by danny0838** [comment]
Please raise unrelated issue in individual thread. And read the [documentation](https://github.com/danny0838/webscrapbook/wiki), which may have answered your questions.

**Comment by Gabarito007** [comment]
> Please raise unrelated issue in individual thread. And read the [documentation](https://github.com/danny0838/webscrapbook/wiki), which may have answered your questions.


Sorry and thank you.
