### ISSUE TITLE
Combo of emojis images not used by index.html

### ISSUE THREAD

**Issue by Gabarito007** [danny0838/webscrapbook#289]
Recently, I updated WSB to version 1.4.3.
There are too many changes with this newer version, compared to 0.42, previous one that I was using.
It changes many things I'm doing here.

I could see that, now, it saves emoji's combo pictures, with 25 ones.
And some combos has emojis that it isn't used by the HTML file.
It wastes disk space.

How to handle that?

**Comment by danny0838** [comment]
I don't get you. Can you provide the source URL of the page, and possibly some screenshots to illustrate your problem?

**Comment by Gabarito007** [comment]
Source URL is
https://web.whatsapp.com/
but you have to use your own Whatsapp account to get that.

If I save the page of chats, WSB saves 136 webp images, each of them containing 25 emojis, like this:

![combo of images](https://user-images.githubusercontent.com/14959189/180974180-dd7a0134-a5ac-41ba-9ed5-00f4eec7fdbb.png)


The problem is because such image file is never used by index.html, even if it is called inside it.
Like this:
.emoji.wa.b67, .emojik.wa.b67 { background-image: url("emoji-67-40_bdf5816.webp"); }

...among all 135 of them together.

But the image does not exist on page. There is only one emoji, this one:


![whatsapp chat](https://user-images.githubusercontent.com/14959189/180974213-3bb0ae59-4382-4b92-a5f5-d512022469b5.png)


This is the list of combos were saving and wasting disk spaces:

[list of combos.txt](https://github.com/danny0838/webscrapbook/files/9188533/list.of.combos.txt)

**Comment by Gabarito007** [comment]
As I could found, the full call of the unique emoji is this:

<span>Mas essa ideia aí de turbinas tulipa já estão me dando mais ideias. <img src="d5fceb6532643d0d84ffe09c40c481ecdf59e15a.gif" alt="💡" draggable="false" style="background-position: -80px -60px;" class="b71 emoji wa i0jNr selectable-text copyable-text" data-plain-text="💡"></span></span><span class="_20bHr _2ui2p"></span>


That gif image is some kind of place hold, a picture of 1 pixel.
Emoji is called by:

class="b71 emoji wa i0jNr selectable-text copyable-text"

**Comment by danny0838** [comment]
Try setting the `Style Images` option to `Save used`.

**Comment by Gabarito007** [comment]
> Try setting the `Style Images` option to `Save used`.



It seems that your solution had solved the problem.
It saves only 8 combos now.
A big progress.

Later, I'll investigate more about.

**Comment by danny0838** [comment]
You should be able to describe it more detiled here (such as what CSS has the image as you did). You should be able to found my email address in my profile.

**Comment by Gabarito007** [comment]
As I said, I found 2 image files, with 25 emoji each, that is not shown at the page I saved with WSB.
I tried to save a page with less emojis to allow a better isolation of the problem.

Index.html calls that images like this:

[emojis.txt](https://github.com/danny0838/webscrapbook/files/9215038/emojis.txt)

emoji-98-40_a7cb14c.webp
and
emoji-3-40_5afa39d.webp

are not used by a rendered page.
Why were they saved?

The other ones are used:
emoji-38-40_242edea.webp
and
emoji-87-40_94538d3.webp

The full folder with the complete example was sent to your e-mail.

If I save a page with more emojis, the problem with no used images is far big...

**Comment by danny0838** [comment]
From the file you sent I see the images ARE referenced by the CSS and HTML, so it seems to just work as expected.

For `emoji-98-40_a7cb14c.webp`:
* CSS: `.emoji.wa.b98, .emojik.wa.b98 { background-image: url("emoji-98-40_a7cb14c.webp"); }` (in `index.html:47`)
* HTML: `<img src="d5fceb6532643d0d84ffe09c40c481ecdf59e15a.gif" alt="🤝🏻" draggable="false" style="background-position: -40px 0px;" class="b98 emoji wa i0jNr">` (in `index.html:138`)

For `emoji-3-40_5afa39d.webp`:
* CSS: `.emoji.wa.b3, .emojik.wa.b3 { background-image: url("emoji-3-40_5afa39d.webp"); }` (in `index.html:51`)
* HTML: `<img src="d5fceb6532643d0d84ffe09c40c481ecdf59e15a.gif" alt="♂" draggable="false" style="background-position: 0px -20px;" class="b3 emoji wa i0jNr">` (in `index.html:138`)

**Comment by Gabarito007** [comment]
Yes, you're right.
My fault not to pay attention.

Issue solved.
