### ISSUE TITLE
Implement a unit test

### ISSUE THREAD

**Issue by indikaPathi** [danny0838/webscrapbook#29]
Are there any unit tests for this?

**Comment by danny0838** [comment]
No. WebExt API is so limited that it's impossible to automate things using the browser extension alone. We have to write a local server application to achieve this.

We currently do have a test suite for many test cases, but they need further organization and have to be rewritten to be copyright-free to be public available.

**Comment by danny0838** [comment]
Finally unit test is implemented in 0.25.0 (what a big job ...). Not all tests can be done automatically, and the unit test for indexer is still pending, though.
