### ISSUE TITLE
WSB does not grab images where referenced by blob tags

### ISSUE THREAD

**Issue by Gabarito007** [danny0838/webscrapbook#290]
Saving WhatsApp chat page (Firefox), WSB didn't grab images where referenced by blob tags.
Like this:
src="urn:scrapbook:download:error:blob:"

Previous version did not save it too, but I could know what image was in case.
src="blob:https://web.whatsapp.com/e83ba709-d82e-4b87-a13f-dba39c898ce4"

Is there a way to circumvent that?

**Comment by danny0838** [comment]
Seems like the case as [Known Issues](https://github.com/danny0838/webscrapbook/wiki/Issues) have said: "A blob that is revoked after loaded by a script cannot be captured." This is the basic restriction of a browser extension and we cannot do anything on it.

**Comment by Gabarito007** [comment]
Thanks.

SOLVED.
