### ISSUE TITLE
Checkbox to skip already existed folder

### ISSUE THREAD

**Issue by Gabarito007** [danny0838/webscrapbook#291]
Hi.

I'm capturing an entire site, trying to have a backup of it.
WSB is a wonderful tool that is allowing me to do that.
Thank you very much to Danny and his great idea.

However, I miss an issue I guess it's very easy to implement.

This site has daily updates and, thus, I need to update the backup too.
I keep a full list of all pages to download and run the 'Batch capture selected links' resource.
When WSB find a folder that already exists, it renames that to something like 'This folder(1)', 'This folder(2)' and so on.
It's very correct and expected.

But it would be better if I have a checkbox to choose if I want to skip that already existed folder.
Instead of 'rename it', just put 'skip it'.

Is it possible?

**Comment by danny0838** [comment]
There is no easy way to merge a capture. All resources may be interlinked with each other, and each of them may change.

If you really merge files in a capture with files in a previous capture, you'll end up with a chaotic mix, and any existed interlink may become broken.

**Comment by Gabarito007** [comment]
But I'm not trying to merge captures.
The suggestion is just to skip folders that's already exists.
Just that.

**Comment by Gabarito007** [comment]
Example.

First run of Batch Capture.
Folders:

Folder for page A
Folder for page B
Folder for page C

One day later, the following new pages were created.
Page L
Page M
Page N


Second run of Batch Capture will save just those new pages.
Folders:

Folder for page L
Folder for page M
Folder for page N


My suggestion is to WSB ignores:
Folder for page A
Folder for page B
Folder for page C

...because they already got saved.


Nothing to do with merge captures.

**Comment by Gabarito007** [comment]
Note:
I tweaked to put page title as folder name:
%title%

**Comment by danny0838** [comment]
Unfortunately this is not possible for a browser extension. Additionally, the folder name is not accurate for deduplication as different web pages can be incidentally saved as the same name.

**Comment by Gabarito007** [comment]
I didn't get the point, because I thought it was just to change "rename it" to "skip it" where it currently rename the folder name, inside the code.
Accordingly to option checkbox.

But you know far more than me.
If you say "not possible", that's OK.

Thank you.

**Comment by danny0838** [comment]
All this is controlled by the WebExtension API, which does not provide an option for skipping duplicated name when saving a downloaded file.

**Comment by Gabarito007** [comment]
👍
