### ISSUE TITLE
Youtube covers

### ISSUE THREAD

**Issue by Gabarito007** [danny0838/webscrapbook#292]
Hi, Danny.

Is there a tweak to capture Youtube cover pic files?
I get this:

`Error downloading file (https://www.youtube.com/img/meh7.png): 404 Not Found`

And what this means?

`Error downloading file (https://scontent.fbfh3-3.fna.fbcdn.net/v/t39.30808-6/298990128_432814895550894_5647260839407426070_n.jpg?_nc_cat=106&ccb=1-7&_nc_sid=730e14&_nc_eui2=AeFpWdsiHDiCCl60wmDUS7_c6pFM6FcSReDqkUzoVxJF4CSj6KX8L5JnnQKxmdTkvftmZo5gu7IR6hiFAx9NFGg9&_nc_ohc=7K3kd0xNX1YAX_fj9qv&_nc_ht=scontent.fbfh3-3.fna&oh=00_AT8qyb7HM8dy6OYlqi9MxD6PYTRBpDZTQl1sWQ5JwaF1xw&oe=63008CC5): 403 Forbidden`

It says `URL signature expired` and if I remove the string beyond the filename, `Bad URL hash`.

I'm afraid, there is no way to capture that file...

**Comment by danny0838** [comment]
What is the URL of the page you are tying to capture?

**Comment by Gabarito007** [comment]
I'm working with many pages and I couldn't find exactly what of them was that gave that error.
But I found one with this:

https://clubeceticismo.com.br/viewtopic.php?f=20&t=82

`Error downloading file (https://scontent.fcwb2-2.fna.fbcdn.net/v/t1.0-9/s960x960/89505302_503953766961905_5784055560152285184_o.jpg?_nc_cat=109&_nc_sid=8024bb&_nc_ohc=4FQ2-UaOTIkAX_R61lv&_nc_ht=scontent.fcwb2-2.fna&_nc_tp=7&oh=d14b230d446aff3c7414d0a83b5270e9&oe=5E993BF0): Network request failed.`

Error is something different (it says `Network request failed`, not `403 Forbidden`).


The image is referred inside HTML code is:

`src="urn:scrapbook:download:error:https://scontent.fcwb2-2.fna.fbcdn.net/v/t1.0-9/s960x960/89505302_503953766961905_5784055560152285184_o.jpg?_nc_cat=109&amp;_nc_sid=8024bb&amp;_nc_ohc=4FQ2-UaOTIkAX_R61lv&amp;_nc_ht=scontent.fcwb2-2.fna&amp;_nc_tp=7&amp;oh=d14b230d446aff3c7414d0a83b5270e9&amp;oe=5E993BF0" class="postimage" alt="Imagem"><br>`

**Comment by Gabarito007** [comment]
Note:
The page I quoted in last comment does not have Youtube cover.
To test this (Youtube cover), please use this one:

https://clubeceticismo.com.br/viewtopic.php?f=20&t=256&start=300

**Comment by danny0838** [comment]
The image is seen in the source of the page `https://www.youtube.com/embed/6UhKXiE_NJc`:

    <style nonce="kXngrd-FJuOaEbPvGYeVcg">...
    .player-unavailable {...; background: url(/img/meh7.png) 50% 65% no-repeat;}

And the resolved URL `https://www.youtube.com/img/meh7.png` does not point to a valid resource.

It appears to be just a bad URL and bad CSS code the web master has written, you don't need to—and actually can't—do anything for that.

I don't have a problem capturing the `https://i.ytimg.com/vi/YckRV7-bl88/maxresdefault.jpg` cover image from the `https://clubeceticismo.com.br/viewtopic.php?f=20&t=256&start=300` page. If you still have the problem please check:
1. Whether it's affected by the capture options: tweak the options or report the options you are using for further investigation.
2. Whether it's blocked by another extension: use a clean profile or disabe all other extensions.
3. Whether it's a network issue: try performing the capture another day or check if your network is blocked by the ISP or antivirus software, etc.

**Comment by Gabarito007** [comment]
Surprisingly, when I capture again today, I could get all Youtube covers for the videos.
I don't know what happened.

So, I compared the folders and found a big difference among files.
Look:

First capture, 3 days ago:
[3daysAgo.txt](https://github.com/danny0838/webscrapbook/files/9428909/3daysAgo.txt)

Today:
[today.txt](https://github.com/danny0838/webscrapbook/files/9428910/today.txt)

There were too many SVG files before (27), but only 4 today.
And today, all Youtube covers were present.

This is my settings:
[webscrapbook.options.20220826.json.txt](https://github.com/danny0838/webscrapbook/files/9428918/webscrapbook.options.20220826.json.txt)
(I had to rename it to .txt to upload the file)

**Comment by Gabarito007** [comment]
I have news.

Capturing using "Batch capture", I got **no** Youtube covers and too many SVG files.
If I capture a single page (right click), I got Youtube covers.

**Comment by danny0838** [comment]
This is no news but the basic feature of WSB.

Batch capture works like "capture source", which is is headless and gets the page without any script execution, while a general capture gets a page that may be changed by scripts.

**Comment by Gabarito007** [comment]
> Batch capture works like "capture source", which is headless and gets the page without any script execution, while a general capture gets a page that may be changed by scripts.

I see. ☹️


is there a way to circunvent that? To have Youtube covers in a Batch capture?

**Comment by danny0838** [comment]
> is there a way to circumvent that? To have Youtube covers in a Batch capture?

If you don't want headless capture, mostly the simplest way is to open them in tabs (you can optionally move them to another window for better grouping), and select the tabs and perform a capture at once (there's also a "capture all tabs" command to capture all tabs in a window).

There is a way to do this using the batch capture dialog: through the advanced mode which supports automatically opening each URL and performing the capture after loading completes, but it won't work for all cases and you'll need some knowledge about JSON. The tooltips should have provided the required information.

**Comment by Gabarito007** [comment]
I could get with "capture all tabs", openning them in another window.
It solves a half of the problem.

But it would be better if I could use advanced mode, in a batch capture.

What to put here?

"mode": "source",
 "bookId": null,
 "parentId": "root",
 "index": null,
 "delay": null
