### ISSUE TITLE
not able to properly browse all subpages

### ISSUE THREAD

**Issue by ant666hw** [danny0838/webscrapbook#294]
Sorry for the non technical explication of the problem.
I'm trying to downlod the following website as a test: https://www.corroergosum.it/ ; in the upper menu there is a link in "tabelle e allenamenti" (https://www.corroergosum.it/tabelle), Webscrapbook download subpages, but after it finishes, while trying to explore the local copy, i can only see the page https://www.corroergosum.it/tabelle and not all the other subpages listed in the submenu like for example https://www.corroergosum.it/tabelle/tabelle-diecimila/calendario-settimanale-10-4g . it is downloaded but unreachable unless i open windows explorer and open the requested page. Am I missing some option when starting the download throug webscrapbook? Many thanks for support.

**Comment by danny0838** [comment]
The subpage menu is driven by page scripts, which are not captured by default. Although you can tweak the options to capture the scripts, they are not guaranteed to work as the environment is totally different. This is a basic technical restriction and is clearly stated in the [Known Issues](https://github.com/danny0838/webscrapbook/wiki/Issues).

**Comment by ant666hw** [comment]
> The subpage menu is driven by page scripts, which are not captured by default. Although you can tweak the options to capture the scripts, they are not guaranteed to work as the environment is totally different. This is a basic technical restriction and is clearly stated in the [Known Issues](https://github.com/danny0838/webscrapbook/wiki/Issues).

Thanks Danny. It worked perfectly (or at least as far as I need) in my situation. You gained the donation. Thanks for the work
