### ISSUE TITLE
Unable to capture as a folder on Kiki Browser

### ISSUE THREAD

**Issue by dhdiu** [danny0838/webscrapbook#295]
latest kiwi
Capturing (document) [] https://...
Saving data...
then unable to continue
it dosen't work

**Comment by danny0838** [comment]
What is the version of your WebScrapBook?

What is the URL of the web page?

What are your capture settings?

**Comment by danny0838** [comment]
A quick investigation shows that there's an issue of Kiwi Browser that it cannot download a file as a subfolder under the default download folder. As the default `Save captured data as: Folder`, `Scrapbook folder: WebScrapBook/data`, `Filename to save: %id%` requires data be saved at  `<default download folder>/WebScrapBook/data/<id>/*`, the wrapping folder is always saved as `<default download folder>/<id>`, which never passes an internal check and causes an infinite downloading loop.

We cannot really fix this issue as it's a limitation of the browser itself. Setting the option `Save captured data as` to a value other than `Folder` is a way to quickly circumvent it. 

You'd probably also want to change `Save captured data to` to another value (see the [1. Independent files approach](https://github.com/danny0838/webscrapbook/wiki/Basic#1-independent-files-approach) or [3. Browser sidebar approach](https://github.com/danny0838/webscrapbook/wiki/Basic#3-browser-sidebar-approach) section of the documentation) as the idea of saving to a subfolder defined by the `Scrapbook folder` value never works.

We'll do further investigation to find a way to mitigate the issue for a user using such mobile browser.

**Comment by dhdiu** [comment]
thanks
