### ISSUE TITLE
Downloading full site yields random results. Some pages and links are not downloaded (crawled)

### ISSUE THREAD

**Issue by BarbzYHOOL** [danny0838/webscrapbook#297]
Hey, @danny0838 

Like many, this extension is really helpful because httrack and wget are not working behind a login screen (i've tried all the techniques)

I am saving an entire site with indepth capture, BUT it is totally inconsistent. The site has several internal links, and I need webscrapbook to click them all and save each page and rebuild the links for local usage.
The site is behind a login so I can't sent it to you.

1) I tried several parameters, basically tweaking the capture interval (dunno if it is important), the depth level (i've put 5 to 90, the result seems to be similar after a certain threshold, ), and the urls to capture, example:

```regex
/^https://site\.com/products/smthg//
/^https://site\.com/products/smthg/categories//
/^https://site\.com/products/smthg/categories/572013//
/^https://site\.com/products/smthg/categories/572013/posts/\d{6}/
/^https://site\.com/products/smthg/categories/572013/posts/*/
/^https://site\.com/products/smthg/categories/572013/posts//
```
The more I add URLs the less it captures o_0

(Note that I try to force the download of the whole "categories/572013/posts/" path but it doesn't)

2) If I specify the url path containing "categories/572013", it doesn't download it better (or at all) than if I didn't specify it o_0

3) Every run seems to be different. There is NEVER the same amount of files downloaded. Even with the same parameters.
Also I managed to download the missing part of the site once, I don't know how, but it's missing the first part of the site that was usually downloaded. Makes me crazy for 6 hours now

4) I always use "capture tabs as". I don't know if it takes into account every opened tab, maybe if I open the missing pages in various tabs, it will download them? I'm totally lost you know

5) I set the same exact parameters, on one run I add "ignore similar urls" (in advanced), and on the other I do not. Result is: more files for "ignore similar urls"... makes no sense, right?

6) Can auto-capture help me with this problem?

7) Is auto-capture (in "options") the same thing as "Enable capture helpers " ???

8) Just tried to put every main "categories/xxxx" as URLs to download, and only these, and it again downloaded RANDOMLY, some categories are fully downloaded, some are partially, some aren't at all.

**Comment by danny0838** [comment]
Only pages (directly or indirectly) LINKED BY the captured page are captured. If the captured page (or pages linked by the captured page, if within the limited depth) does not include the links for all `https://site.com/products/smthg/categories/572013/*`, you won't get them all captured.

For the same reason, it is expected that you get a different result if the captured page has differed, even if the options are identical.

Please check it as well as the tooltips of the options and the [documentation wiki](https://github.com/danny0838/webscrapbook/wiki/Basic#capture-linked-web-pages-in-depth-capture) for a correct configuration and usage.

If the issue persists, please provide the version of your browser and WebScrapBook, the capture options (can be copied from the advanced dialog), and the log messages of the capture dialog for further investigation.

**Comment by BarbzYHOOL** [comment]
I tried by changing the url of the captured page too, same thing

I also can deduce if it improved or not just by seeing the number of files in the directory, it ranged from 380 to 560! and even at 560 it's missing some pages

Here is one of the log (I just replaced the url): https://pastebin.com/Lj46tjSC

Here is the configuration (same edit): https://pastebin.com/3VCSqeAe

**Comment by BarbzYHOOL** [comment]
And one last issue, I don't manage to save hidden parts of the page, under a "Show more comments" button for example

**Comment by danny0838** [comment]
> ??? so there is no "indepth capture" at all, right? also it doesn't make sense because on that captured page, there are many links that are NOT there but they have still been downloaded. These links are found on the other pages.

That's how it works. As the tooltip says, pages linked by the captured page is depth 1, and pages linked by depth 1 pages are depth 2, and so on. A page is captured only when it fits the configured depth and it's URL matches `Included URLs for capturing linked pages` (and doesn't match `Excluded URLs`, of course). Anyway, a page must be either directly (i.e. depth 1) or indirectly (i.e. depth 2 or more) linked by the captured page to be captured.

The client knows nothing about the server and it's not possible to capture a pages at `https://example.com/*` just by providing a pattern if there's no page at some depth linking to it explicitly.

> Here is one of the log (I just replaced the url): https://pastebin.com/Lj46tjSC
> Here is the configuration (same edit): https://pastebin.com/3VCSqeAe

Can you provide a few clear details to illustrate what's wrong about this case?

For example, the source and captured `https://site.com/products/smthg/categories/` both contain a link targeting `https://site.com/products/smthg/categories/572007`, while the page `https://site.com/products/smthg/categories/572007` is not captured. Something like that...

**Comment by BarbzYHOOL** [comment]
> Anyway, a page must be either directly (i.e. depth 1) or indirectly (i.e. depth 2 or more) linked by the captured page to be captured.

yes, that's what I'm talking about, it is but it's inconsistent/random. Only for indirect pages, never for the directly linked pages of course

> Can you provide a few clear details to illustrate what's wrong about this case?

The source has a link to https://site.com/products/smthg/categories/572007, and that page is correctly captured. But the indirect links on that page https://site.com/products/smthg/categories/572007 are not captured (I mean, it's random, sometimes it captures 4 pages, sometimes 0, sometimes it's another "categories" that doesn't get captured). In the end, I have two copies of the site, they both complement each other with the missing pages, but it's totally not how the program is intended to work and it's annoying :D

> It seems like the site you attempt to capture shows some random pages within a dynamic page when you visit. If that's the case, the result you've got is expected.

When I visit it manually there is no randomness

**Comment by danny0838** [comment]
> > Can you provide a few clear details to illustrate what's wrong about this case?
> 
> The source has a link to https://site.com/products/smthg/categories/572007, and that page is correctly captured. But the indirect links on that page https://site.com/products/smthg/categories/572007 are not captured (I mean, it's random, sometimes it captures 4 pages, sometimes 0, sometimes it's another "categories" that doesn't get captured). In the end, I have two copies of the site, they both complement each other with the missing pages, but it's totally not how the program is intended to work and it's annoying :D

The log you provided above does not show that https://site.com/products/smthg/categories/572007 is captured. Are you sure your description about https://site.com/products/smthg/categories/572007 is correct for THIS capture attempt?

Also, what is the URL of the indirect link on the https://site.com/products/smthg/categories/572007 is not captured, and what is the captured source HTML of  https://site.com/products/smthg/categories/572007 look like?

Please provide an accurate description about each capture attempt you have provided. If you find that the same configuration has got a different and seemingly random result on another capture attempt, provide full information (i.e. the capture options, the capture log, and an accurate description about a page at what URL is linked on what page but not captured as expected) for that capture attempt too. Otherwise I can not provide any further help for you.

> 
> > It seems like the site you attempt to capture shows some random pages within a dynamic page when you visit. If that's the case, the result you've got is expected.
> 
> When I visit it manually there is no randomness

An indirectly captured page does not run scripts, which could make it behave differently as a directly visited page.
