### ISSUE TITLE
the edit tab option is shutting out bottom contents

### ISSUE THREAD

**Issue by dhdiu** [danny0838/webscrapbook#300]
Hi.The toolbar of the edit tab option is blocking the bottom content of the page, so I can't select the bottom content, how can I fix it?Thank you very much.

**Comment by danny0838** [comment]
We know this issue. Unfortunately it's not easy to deal with. Dragging support of the toolbar is likely required...

**Comment by danny0838** [comment]
Since 1.6.0 we have added support of pinning the toolbar to the top (through a command in the `Save` dropdown). This should serve a temporarily solution before a more elegant solution has come out.
