### ISSUE TITLE
Problem with insert command in capture helper

### ISSUE THREAD

**Issue by thirdinsight** [danny0838/webscrapbook#303]
Hello,
I would like to use the "insert" command in a capture helper to insert a html link (`<a href="...`).

The following is an example of my test capture helper that I used to reproduce my problem:
```
    {
      "name": "insertTestLink",
      "description": "",
      "disabled": false,
      "debug": true,
      "commands": [
        ["insert", "h1.f0",
          {
            "name": "a",
            "value": "MY_INSERTED_LINK",
            "attrs": [["href", "http://ubuntu.com"]]
          }, "append", null]
      ]
    }

```
Before: The place where the html link is to be inserted looks like:
`<h1 class="f0">blah something blah</h1>`

Expected: The outcome as I had expected using the above capture helper after the page has been captured would be:
`<h1 class="f0">blah something blah<a href="http://ubuntu.com">MY_INSERTED_LINK</a></h1>`

Actual: The outcome using the above capture helper after the page has been captured was:
`<h1 class="f0">blah something blah<a>MY_INSERTED_LINK</a></h1>
`

So it seems the html link inserted by the capture helper is not correct (or is incomplete).

If it turns out that this is a bug then I would like to report this as a bug.

If I am missing something I would appreciate very much telling me what it is.

Thanks and best regards!

**Comment by danny0838** [comment]
There's a current bug causing `attrs` ignored if `value` is provided. You can use `"children": ["MY_INSERTED_LINK"]` to workaround before the next release is available.
