### ISSUE TITLE
download external resources

### ISSUE THREAD

**Issue by Hug0122** [danny0838/webscrapbook#304]
Hello, 
I've been using this module for a while, and I recently encountered a problem.
I do online training via an interactive MOOC, which I download with this Webscrapbook.
Once downloaded (offline), the MOOC works very well. Even the quizzes and their results embedded in the MOOC work very well.
However, the problem arises when there is an external resource to download. For example, clicking on a link on the MOOC that downloads a pdf, ods, odt,...
In offline mode, when I click on the link, it sends me to the corresponding web page but never downloads the file. So when I'm without internet, I get a firefox page that says there is a connection problem. When it should open the pdf or calc file that should have been downloaded locally.
I specify that in the options, I have set the parameter "Depth to capture linked pages" to a sufficient number.
Do you have any idea of a solution?

Regards

**Comment by danny0838** [comment]
Can you provide the aource URL of the page and the capture options you have used (copy from `Capture as` > `Advanced`)?

**Comment by Hug0122** [comment]
I still have a problem with the depth of the captured pages. 
To capture the whole course, I have to set a depth of 4 or 5. Except that if the captured site has a link to another site (to give a source for example), Webscrapbook will also download this site.
Is there a setting to limit the download to the desired domain?

I think I understand in the doc, that you can add domains, but I did not find the opposite
Regards

**Comment by danny0838** [comment]
@Hug0122 You can configure the `Included URLs for capturing linked pages:` to include a regex that matches only the domain of the site.

FYI: There are several available quick fillers to add a regex for the domain, site, path, etc. if you perform the capture through `Capture tabs as`.
