### ISSUE TITLE
Are there docs about onMessageExternal?

### ISSUE THREAD

**Issue by GHolk** [danny0838/webscrapbook#305]
I'm a webscrapbook and [tridactyl](https://github.com/tridactyl/tridactyl) user.
Recently I manage to bind capture page command to a tridactyl command:
`bind gc composite js activeTabId() | js -p browser.runtime.sendMessage("webscrapbook@danny0838.addons.mozilla.org",{cmd:"invokeCapture",args:[{tabId:JS_ARG}]})`

I figure out the code from your source code with debugger.
Are there any docs about the external message?
or can I write them down in wiki?

**Comment by danny0838** [comment]
Although we do provide API for external extensions, there is currently no clear plan for a doc, but it would be nice to have.

Not sure how you'd like to write them.  You can write a draft here or directly to the wiki (but we may edit or remove it afterwards if we found it undesired).

**Comment by GHolk** [comment]
It seem the api change, so I update the wiki page.

https://github.com/danny0838/webscrapbook/wiki/External-Message-API/_compare/d9858e58ab8bdd4ee6d0229d7ba0fc2d14add8ee...43144169c233a1958dd11cf0a8b6fb411ecb69af
