### ISSUE TITLE
It does save some html pages, that has nothing to do with the start page; and some twice

### ISSUE THREAD

**Issue by Golddouble** [danny0838/webscrapbook#307]
Hello,

This is really quite a good addon. I have tried out other addons and a standalone programme for the same purpose, but was not able to get with this other programmes and addons, what is possible with your addon. Thank you for creating this.

This is a question about this page:
https://forum.mxlinux.org/viewtopic.php?t=72858&start=20

I do not want to capture any link, except the html pages behind the following buttons:
![k20221209-095312](https://user-images.githubusercontent.com/13977359/206663301-fd4b5798-a37c-408c-8619-56fe7c404784.png)

Here are my settings:
![k20221209-093709](https://user-images.githubusercontent.com/13977359/206660039-96b33325-c48f-43fc-9705-70342cccb565.png)

It works quite good but ...

A) ... according to the download log it looks like there were downloaded some pages twice or more.

B) ... it does download some forum pages that have nothing to do with the starting page.

![k20221209-093852](https://user-images.githubusercontent.com/13977359/206660363-1fa2d6db-2fd5-41c0-8e54-07d2249a0f64.png)

Example for A): 
`https://forum.mxlinux.org/viewtopic.php?uid=22410&f=136&t=72858&unwatch=topic&start=30&hash=03d78ea8 `
is identical with ...
`https://forum.mxlinux.org/viewtopic.php?t=72858&start=30`
Why do I have it twice?

Example for B):
`https://forum.mxlinux.org/viewtopic.php?p=704766` (This is a html, that has nothing to do with the starting html. Nevertheless it was saved/downloaded.)

**Edit:** There is a bookmarking function in this forum. I have never used this function. But it seems like webscrabbook does create bookmarks, when I start it with capture tabs. Really? I can delete the bookmarks, but after a new capture I have again some bookmarks. Strange.

Thank you.

**Comment by danny0838** [comment]
> Example for A):
> `https://forum.mxlinux.org/viewtopic.php?uid=22410&f=136&t=72858&unwatch=topic&start=30&hash=03d78ea8 `
> is identical with ...
> `https://forum.mxlinux.org/viewtopic.php?t=72858&start=30`
> Why do I have it twice?

Each page is identified with its URL. Pages with different URLs will be treated as different even if they happen to contain the same content.

> Example for B):
> `https://forum.mxlinux.org/viewtopic.php?p=704766` (This is a html, that has nothing to do with the starting html. Nevertheless it was saved/downloaded.)

It's not possible for WSB to capture a totally untold page, so it must exists somewhere in the source page or one of its frames, possibly after a redirection. You should be able to find the downloaded filename of the URL from the `index.json` and perform a fulltext search among all downloaded files to see where it appears.

> **Edit:** There is a bookmarking function in this forum. I have never used this function. But it seems like webscrabbook does create bookmarks, when I start it with capture tabs. Really? I can delete the bookmarks, but after a new capture I have again some bookmarks. Strange.

If the bookmarking feature is invoked through a hyperlink, it may be "clicked" when WSB attempts to capture linked pages and travels all hyperlinks. Add its URL to the exclude list to prevent that.

**Comment by Golddouble** [comment]
Thank you again.

I was able to solve issue B) by adding in `options` in the section `Excluded URLs:` the following rule:
`/[/=]forum\.mxlinux\.org/viewtopic\.php\?p\=\b/i`
Essential to exclude was the phrase "**_php?p=_**" . Normal pages seems to have "_**php?t=**_" .

to A):
This may something have to do with the following feature of the homepage:
![k20221210-131151](https://user-images.githubusercontent.com/13977359/206854511-269454db-f501-481a-be1d-2449fce7b0bf.png)

So to exclude the `.*bookmark.*` link, I have added the following rule in options in the section `Excluded URLs:`:
`/[/=]forum\.mxlinux\.org/viewtopic\.php.*bookmark.*\b/i`

This works great now.

Question:
When I want to exclude `https://forum.mxlinux.org/viewtopic.php?t=43925&bookmark=1&hash=53b05b89`:
Why does the rule `/[/=]forum\.mxlinux\.org/viewtopic\.php.*bookmark.*\b/i` work, but not the rule `/[/=]bookmark\b/i` ?

`/[/=]bookmark\b/i` looks for me identical to `/[/=]viewforum\b/i`, which is included as default exclusion in options in the section `Excluded URLs:` .

**Comment by danny0838** [comment]
> Question:
> When I want to exclude `https://forum.mxlinux.org/viewtopic.php?t=43925&bookmark=1&hash=53b05b89`:
> Why does the rule `/[/=]forum\.mxlinux\.org/viewtopic\.php.*bookmark.*\b/i` work, but not the rule `/[/=]bookmark\b/i` ?

Because you are using regular expression (regex or RegExp) incorrectly. Search for a good tutorial (e.g. [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions)) and read it, and you'll know what the problem is.

**Comment by Golddouble** [comment]
Thank you for this valuable links.
