### ISSUE TITLE
Options: I do not understand the sense of `Included URLs for capturing linked pages:`

### ISSUE THREAD

**Issue by Golddouble** [danny0838/webscrapbook#309]
Hello

I do not understand the sense of `Included URLs for capturing linked pages:` in `Options`.
I understand, that when `Included URLs for capturing linked pages:` is empty, it does accept all url's but does exclude the url's with a match in `Excluded URLs: ` .

So I thought maybe if I write only the following line into `Included URLs for capturing linked pages:` ...
`/google\.de/i`
... that it will only accept google pages. But that is not true. It still accepts other pages that are not included in `Included URLs for capturing linked pages:` and not excluded in `Excluded URLs: .

(I have tested the regex rule `/google\.de/i` first in 
`https://regex101.com/?regex=%5B%2F%3D%5Dbookmark%5Cb&testString=https%3A%2F%2Fforum.mxlinux.org%2Fviewtopic.php%3Ft%3D43925%26bookmark%3D1%26hash%3D53b05b89&flavor=javascript&flags=`
It has a match. So I assume, that I have formulated this rule correctly.)

Can you give me an example, when it makes sense to use the section `Included URLs for capturing linked pages:` . What's the idea of this section? Thank you.

**Comment by danny0838** [comment]
Please provide the URLs of the "other pages" that you don't expect to capture.

**Comment by Golddouble** [comment]
With the rule `/google\.de/i` in `Included URLs for capturing linked pages:` it nevertheless accepts to capture the page:
`https://forum.mxlinux.org/viewtopic.php?t=72963`

**Comment by danny0838** [comment]
What is the URL of the starting page?

**Comment by Golddouble** [comment]
starting page is `https://forum.mxlinux.org/viewtopic.php?t=72963`

I go to `https://forum.mxlinux.org/viewtopic.php?t=72963` . After I choose "capture tabs".

**Comment by danny0838** [comment]
The starting page is always captured as it's not a linked page. Hyperlinks targeting to the page itself will be rewritten to target the downloaded version.
