### ISSUE TITLE
Problems with default download dir Win/Chrome

### ISSUE THREAD

**Issue by pbpb** [danny0838/webscrapbook#310]
Finally ported from ScrapbookX to WebScrapbook, and I have numerous issues.  Here are a couple of related ones:

1.  Although I have set up the backend server in my desired root dir, clicking 'capture tabs' nevertheless attempts to save to my system default download dir.  I created a symlink to send it to the right place, but why did it not work as advertised in the first place?  What have I configured wrong?
2.   If Chrome is set to "ask where to save each file", the 'capture tabs' results in a save dialog for every single element that it is trying to save.  That behavior probably can't be fixed if the saving is being done through Chrome, but shouldn't it be done via the python back end?  Is there a way for me to configure so that I can still have Chrome ask where to save each file, which I want in general for other downloads, but I don't get this problem?

I'm attaching the options json.

Thanks.
[webscrapbook.options.20221220.json.zip](https://github.com/danny0838/webscrapbook/files/10273398/webscrapbook.options.20221220.json.zip)

**Comment by danny0838** [comment]
You have to set `Save captured data to:` to `Backend server`. ([Related doc](https://github.com/danny0838/webscrapbook/wiki/Basic#3-browser-sidebar-approach).)

**Comment by pbpb** [comment]
Aha!  Thanks.  Yes, that worked.  Yes, it is in the documentation.  Yes, I did read the documentation.  About 20 times.  Somehow I did not see that, or realize that it was improperly set for my use case.  I guess my capacity for complexity is not up to configuring this beast the first time around.  Dazzled and dazed by too many options.
