### ISSUE TITLE
Improve the recycle bin

### ISSUE THREAD

**Issue by pbpb** [danny0838/webscrapbook#311]
Chrome  108.0.5359.99 (Official Build) (64-bit)/ win 7 

With backend installed and running, if I capture a page then click remove on the item in the sidebar, it is removed from the scrapbook index tree display, but not deleted from the 'data' directory.  Shouldn't it be?  And if so, what am I doing wrong?

Here is backend output from the time 'remove' is clicked;  also zip of options:

127.0.0.1 - - [21/Dec/2022 15:43:02] "POST /?a=token&f=json HTTP/1.1" 200 -
127.0.0.1 - - [21/Dec/2022 15:43:02] "POST /?a=lock&f=json HTTP/1.1" 200 -
127.0.0.1 - - [21/Dec/2022 15:43:03] "GET /tree/?a=list&f=json HTTP/1.1" 200 -
127.0.0.1 - - [21/Dec/2022 15:43:03] "POST /?a=token&f=json HTTP/1.1" 200 -
127.0.0.1 - - [21/Dec/2022 15:43:03] "POST /tree/meta.js?a=backup&ts=20221221234303005&note=transaction&f=json HTTP/1.1" 200 -
127.0.0.1 - - [21/Dec/2022 15:43:03] "POST /?a=token&f=json HTTP/1.1" 200 -
127.0.0.1 - - [21/Dec/2022 15:43:03] "POST /tree/toc.js?a=backup&ts=20221221234303005&note=transaction&f=json HTTP/1.1" 200 -
127.0.0.1 - - [21/Dec/2022 15:43:03] "POST /?a=token&f=json HTTP/1.1" 200 -
127.0.0.1 - - [21/Dec/2022 15:43:04] "POST /tree/meta.js?a=save&f=json HTTP/1.1" 200 -
127.0.0.1 - - [21/Dec/2022 15:43:04] "POST /?a=token&f=json HTTP/1.1" 200 -
127.0.0.1 - - [21/Dec/2022 15:43:04] "POST /tree/toc.js?a=save&f=json HTTP/1.1" 200 -
127.0.0.1 - - [21/Dec/2022 15:43:04] "GET /tree/?a=list&f=json HTTP/1.1" 200 -
127.0.0.1 - - [21/Dec/2022 15:43:04] "POST /?a=token&f=json HTTP/1.1" 200 -
127.0.0.1 - - [21/Dec/2022 15:43:04] "POST /tree/?a=unbackup&ts=20221221234303005&note=transaction&f=json HTTP/1.1" 200 -
127.0.0.1 - - [21/Dec/2022 15:43:05] "POST /?a=token&f=json HTTP/1.1" 200 -
127.0.0.1 - - [21/Dec/2022 15:43:05] "POST /?a=unlock&f=json HTTP/1.1" 200 -
[webscrapbook.options.20221221.json.zip](https://github.com/danny0838/webscrapbook/files/10282516/webscrapbook.options.20221221.json.zip)

**Comment by danny0838** [comment]
Items removed from the treewill be moved to the recycle bin. You have to delete it from the recycle bin to get the physical data really deleted.

**Comment by pbpb** [comment]
Aha.  Thanks.  I did not realize that it had its own recycle bin.  Analogously to Windows, is there also an option for "remove permanently"?  

I've become accustomed to the behavior of the Windows file manager, which offers the following options that I find useful:
1. shift-leftclick on 'delete', or shift-deletekey deletes without sending to recycle bin.
2.  interposed "are you sure" dialog that asks user to move to recycle bin and/or delete permanently.  (For wsb, this could include a check box that says "don't ask me again" with a corresponding settings option, i.e. whether a confirmation dialog appears.)

Also, you might consider adding:

1.  A "remove permanently" option in the tree list dropdown menu.
2.  Renaming "remove" to "move to recycle bin" or "move to trash"
3.  An "empty the trash" feature that deletes everything currently in the recycle bin.

Yeah, it's easy to request features;  not necessarily great fun to implement them.  But, food for thought, anyway.

**Comment by danny0838** [comment]
Thank you for the feedback. We'll take into consideration.

Something to note is that permanently deleting many item(s) may involve a large database reconstruction and take a very long time, which is a reason why this feature has not been provided directly in the tree manager, so that the user can defer the deleting and avoid an interruption for further manipulating the database.

**Comment by pbpb** [comment]
Aha.  Thanks for the info.

I guess the issue is basically garbage collection.  Is there a feature that says "You now have 10GB of removed items in your recycle bin, do you want to empty it?"

In my case, I only happened to notice that the data dir for the item was not being deleted because I was debugging.   Normally I would not notice that, since if I weren't debugging I wouldn't be looking at the data dir.

**Comment by danny0838** [comment]
Well, deleting an item implies deleting all descendant items. However, an item may appear under multiple items, and thus checking for what items are to be deleted is a large calculation. It may not be easy to quickly know how much data are to be deleted.

The performance may be improved if we have implemented all book management logic at the server side. This is a large code work and may require some time, though.

**Comment by pbpb** [comment]
Isn't this is similar to the problem of multiply linked file systems?  Seems like the data structure would need each item to include a list of pointers back to parents.  Or at least a count of parents.  I say that without actually knowing how file systems deal with it or fail to deal with it.

Anyway, thanks for thinking about it.

**Comment by danny0838** [comment]
It's much more complicated than that as WSB still needs to calculate whether an item will be "unconnected" from any parents after a deletion even if we have a list of all its parent items.

Anyway, this will be implemented in WSB 2.*, you can visit the #338 and test the beta version to see if it works as desired.

**Comment by pbpb** [comment]
Thanks.  I will check it out... eventually.  My time constant on installing new versions is even longer than yours on replying here.  (Not a complaint;  you will surely be rewarded in the next life for this service to humanity.)
