### ISSUE TITLE
The extension seems to ignore the character encoding of the existing MAFF archive

### ISSUE THREAD

**Issue by mcepl** [danny0838/webscrapbook#315]
When looking at [errata.zip](https://github.com/danny0838/webscrapbook/files/10334768/errata.zip) (file renamed to `.zip` to overcome GH limitations) I get wrong charset even though all files are clearly marked as `"windows-1250"`.

**Comment by danny0838** [comment]
We have released 1.5.4 which should fix this. Thank you for the report.

**Comment by mcepl** [comment]
Yes, this has been truly fixed. Thank you!
