### ISSUE TITLE
HTML note doesn't show keyboard cursor while in HTML editor mode

### ISSUE THREAD

**Issue by grotesque** [danny0838/webscrapbook#319]
It's very difficult to edit html notes because of lack of keyboard cursor. Can this be fixed?

**Comment by danny0838** [comment]
This is an old Firefox issue. Usually focusing on another tab or window and re-focus on the affected tab will get the cursor shown again.

**Comment by grotesque** [comment]
Okay. Maybe we could raise it at mozilla level.

**Comment by danny0838** [comment]
Have you confirmed whether refocusing solves the issue?

**Comment by grotesque** [comment]
Yes it does.
