### ISSUE TITLE
[Feature Request] decrease file size

### ISSUE THREAD

**Issue by mercurylmy** [danny0838/webscrapbook#32]
Web ScrapBook 是目前 （firefox 57+）唯一能准确保存网页原始状态的插件。相比 UnMHT 而言，存储的文件会大很多。保存为脚本化单一 HTML 文件虽然能缩小体积，但仍然比 MHT 格式大很多。
希望能像 Save Page WE 一样采用 URI 编码保存 css 和 js，base64 编码保存图片等资源，以减小保存文件的体积。

**Comment by danny0838** [comment]
1. 脚本化单一 HTML 文件本身也是用 base64 儲存，會造成檔案膨脹。能最有效壓縮體積的方法是儲存成 HTZ 或 MAFF 壓縮格式。

2. 我們有實測過，結論是「用 URI 编码保存 css 和 js，base64 编码保存图片」不一定比全部用 base64 編碼儲存更節省體積，因為 css 和 js 常含有大量空白字元（URI 編碼膨脹 3 倍， base64 膨脹 1.33 倍），如果 css 和 js 含有很多中文也會如此。

3. 除此之外，UnMHT 有時檔案看起來比較小，是因為它遺漏了網頁中的某些元素沒儲存所致。

**Comment by mercurylmy** [comment]
举个栗子：
随便打开一个维基页面 https://zh.wikipedia.org/zh-hans/HTML
使用火狐内建的保存，文件夹大小 912kb
使用 Save Page WE 保存，文件大小 1.02mb
使用 Web ScrapBook 保存(原样)，文件大小 2.8mb
使用 Web ScrapBook 保存(当前状态)，文件大小 3.33mb

实在有点难以接受这个膨胀度。特别是批量保存大量网页时。

**Comment by danny0838** [comment]
你可能要把擷取選項寫清楚才能客觀比較。

火狐內建保存丟失一大堆東西，應該不用比了；如果你可以接受那種程度的丟失，那你大概沒有精準儲存網頁的需求，繼續用內建儲存功能就可以了。

我剛才測試  Save Page WE 儲存會 1.02MB 應該是用預設的 pageloader 模式，而你說的 WSB 儲存成 3.3MB 應該是儲存成「單一 HTML 檔案」。這樣的比較基準並不恰當，因為 pageloader 模式是把資料儲存到腳本（檔案較小，但相應的也有一些代價），SBX 如果換成對應的 「腳本化單一 HTML 檔案」，檔案可以縮小到 2.7MB。

接著，Save Page WE 會丟掉圖片的 srcset 以及樣式表的一些背景圖片。srcset 通常是儲存不同大小的圖片供不同大小螢幕使用，但也可能是完全不一樣的圖片，丟棄 srcset 可能導致不同大小螢幕的顯示效果受影響。樣式表的背景圖片也一樣，有可能當時的螢幕沒有呈現，但是一些互動動作（例如滑鼠懸浮）會需要它們。

如果你希望盡可能壓縮大小，也可以接受丟掉 srcset 和當下沒呈現的背景圖片可能帶來的問題，你可以把圖片、背景圖片、字體都設定成「儲存現用」，然後以壓縮的 HTZ 格式儲存。這樣設定的擷取結果我測試是 421KB。

**Comment by mercurylmy** [comment]
HTZ 文件在没有安装扩展的浏览器打不开，不符合我的需求。存储现用不能准确保存页面，也不符合我的需求。

在 CSS 里 base64 编码的图片，随着 CSS 的 base64 编码又变大了一次。有没有办法只编码一次？

**Comment by danny0838** [comment]
1. HTZ 在[部分平台上經過設定可以雙擊開啟](https://github.com/danny0838/webscrapbook/wiki/(zh-tw)View)，但都需要做些設定或安裝，且有些平台尚未支援。

如果這也不能接受，還有一個方法就是全部存成資料夾（如果希望資料夾用像 HTZ 的方式命名，就下載 HTZ 後解壓縮），資料夾名稱可加個 `.htd` 之類的「副檔名」幫助辦識。

如果這也不能接受，那很遺憾，除非你能要求瀏覽器內建支援直接開啟 HTZ，否則現行的技術和資源就是沒有既精準、檔案小又開啟方便的方案，你得權衡你的需求去選擇次佳的。

2. 除了儲存成「單一 HTML 檔案」無解以外，勾選「將 data URL 儲存為檔案」就有這種效果。
