### ISSUE TITLE
What are these missing icon file errors I see in checker?

### ISSUE THREAD

**Issue by grotesque** [danny0838/webscrapbook#320]
```
Checking book "work" (work).
Loading tree...
Checking metadata...
"20230113091325055": missing icon file "work/.wsb/tree/favicon/1dac3bc978811c0d1a648e21d9d47a489d04210e.ico"
"20230113091632663": missing icon file "work/.wsb/tree/favicon/4bfa97160763500e33283a78d364ee40693a5820.ico"
"20230113091732353": missing icon file "work/.wsb/tree/favicon/c0c3dcc96aec2649a1bff0a7d67ebd1ea355edae.ico"
"20230113091918544": missing icon file "work/.wsb/tree/favicon/9f734086192177a3dacbf4f64d612a0d6779cb1b.ico"
"20230113092040445": missing icon file "work/.wsb/tree/favicon/54687f5dc4a1098b8d248f1feba411c36e095321.png"
"20230113122701732": missing icon file "work/.wsb/tree/favicon/ec617d715196dcad4ea326eda880d51f968b3811.ico"
"20230113123821509": missing icon file "work/.wsb/tree/favicon/52b661c97e7e8619a0327d3cad0584be91374fb3.ico"
"20230113140843343": missing icon file "work/.wsb/tree/favicon/07ed688be6d6288a669778f65f7eccdd96770925.ico"
"20230113141849745": missing icon file "work/.wsb/tree/favicon/07ed688be6d6288a669778f65f7eccdd96770925.ico"
"20230113142132026": missing icon file "work/.wsb/tree/favicon/86885cf7256045a76cc6b96b075a44fdae3a07b9.ico"
"20230113142508307": missing icon file "work/.wsb/tree/favicon/2e23c54a29686608c0c888b8c43dc2f1c226944e.png"
"20230113144833420": missing icon file "work/.wsb/tree/favicon/be510560e5870c42e7c6d15a429db4e479e509ef.png"
"20230113144957482": missing icon file "work/.wsb/tree/favicon/be510560e5870c42e7c6d15a429db4e479e509ef.png"
"20230113145044663": missing icon file "work/.wsb/tree/favicon/be510560e5870c42e7c6d15a429db4e479e509ef.png"
"20230113150408372": missing icon file "work/.wsb/tree/favicon/11a9504c4ae4e3ebc5ce0b5501268382e20340bc.png"
"20230114060457597": missing icon file "work/.wsb/tree/favicon/11a9504c4ae4e3ebc5ce0b5501268382e20340bc.png"
"20230114061321448": missing icon file "work/.wsb/tree/favicon/89ffec6c480c7d048de10b910173be55f933752c.png"
"20230116134243934": "modify" property (20230114143033793) is older than last modified time of index file (20230116134728945).
Checking data files...
Checking TOC...
Checking favicon cache...
Totally 190 items, 17 folders, 225 files, 100 MB.
Found 17 errors, 1 warnings. (Resolved 0)
Done.
```

Also what does ""modify" property is older than last modified time of index file" exactly mean? Does it mean the *.htz was modified outside scrapbook or something?

Thanks.

**Comment by danny0838** [comment]
It means what it says—i.e. the icon file (defined by the icon property of the item) cannot be found, and the mtime of the phyaical file ia newer than the modify property of the item.

Either should normally not happen when items are manipulated with WSB. You'd have to find out why and how the issue have happened.

**Comment by grotesque** [comment]
Ok. I think they haave something to do with running indexer and checker. It seems checker adds some files generated by indexer(like map.html) to the wsb database as a webpage and I deleted those notes manually(via wsb) which may have caused this issue. Can you advice how do I correct the above errors, I mean can I edit files manually and correct the errors?

**Comment by grotesque** [comment]
Regarding the favicon issue there was no folder named ".wsb\tree\favicon". But this seems optional. I don't need favicons. Does working without favicon folder stop the checker in between and make it skip other important tasks? I don't want it affecting functionality.

Thanks!

**Comment by danny0838** [comment]
If you really can't find the favicon and you are OK without it, you can empty the icon property of the affected items to stop getting the same warning.

The warning is warning only and won't affect other things, so you can also safely ignore them.
