### ISSUE TITLE
Options -> Editor ->  Insert date format: what does it do?

### ISSUE THREAD

**Issue by grotesque** [danny0838/webscrapbook#321]
I couldn't figure out what exactly it does. Where is the formatted date inserted? Can you help?
Thanks!

**Comment by danny0838** [comment]
It's for the Insert date command of the HTML editor dropdown of the page editor.

**Comment by grotesque** [comment]
Okay. Got it!

For others 

`new note -> html -> toggle html editor
`

Now right click the html editor button to get the dropdown.
