### ISSUE TITLE
sorting options are not saved

### ISSUE THREAD

**Issue by grotesque** [danny0838/webscrapbook#327]
`burger menu -> sort -> select "sort by" and direction -> ok
`
the sidepanel shows sorted webpages

Now again go to
`burger menu -> sort 
`
The selections in first steps are ignored and wsb goes back to defaults. This causes newly capture webpages to not be displayed at proper position.

**Comment by danny0838** [comment]
The `Sort` command is a one time operation that permanently changes the order of items. It will of course affect current items only. This is the behavior inherited from legacy ScrapBook.

**Comment by grotesque** [comment]
Okay, what I'm looking for is something like legacy scrapbook-x:

Put an item into "the bottom of a folder" or "the top of a folder"

feature.

**Comment by danny0838** [comment]
That is irrelevant to this and is a duplicatr of #120.
