### ISSUE TITLE
Export feature in Options page doesn't work 

### ISSUE THREAD

**Issue by cy7yz2rj** [danny0838/webscrapbook#33]
Firefox 57+ (64-bit), WS v0.21.3, previous versions' status unknown

Trying to export settings using the Export button at the bottom of the Options page always fails, a blank `moz-extension://####/core/options.html` page is displayed and as far as I can see no backup file is created anywhere.

**Comment by danny0838** [comment]
It's the dxmn Firefox bug again... Please check whether it's fixed in 0.21.4.

**Comment by cy7yz2rj** [comment]
Tested in 0.22.0, seems fixed. Export / import now behave as expected.
