### ISSUE TITLE
Fatal error: elemOrig is undefined

### ISSUE THREAD

**Issue by vsc55** [danny0838/webscrapbook#330]
Hi,
When trying to download any of the following two pages, the error "Fatal error: elemOrig is undefined" appears.
https://www.virtualizationhowto.com/2017/06/installing-avago-lsi-storcli-vmware-esxi/
https://www.virtualizationhowto.com/2017/06/update-avago-lsi-smis-provider-vmware-esxi/

![imagen](https://user-images.githubusercontent.com/13438676/215289475-6d04ab02-e006-4233-8db2-3cd840398155.png)

Firefox: 109.0 (x64)
Webscrapbook: 1.7.0

Webscrapbook is configured to store the captured pages on a backend server.

A greeting.

**Comment by danny0838** [comment]
Should be fixed in 1.7.1

**Comment by vsc55** [comment]
Hi @danny0838,
Now the error no longer appears, but the images from the URL's that I have put above are not downloaded.
With other web's it works without problem.

**Comment by danny0838** [comment]
The images seem to load dynamically. You have to scroll down the screen to get them loaded before performing a capture.
