### ISSUE TITLE
The % in title are replaced with underscore when capture

### ISSUE THREAD

**Issue by snowman** [danny0838/webscrapbook#332]
In Windows operating system, the following characters are considered as invalid for use in file or directory names:

![image](https://user-images.githubusercontent.com/16096559/218226500-85b74b4e-ebb2-41f2-80ef-4edff5930e72.png)

```text
\ / : * ? " < > |
```

Expected behavior:
- don't replace % symbol in title

#### Environment
- version: `1.8.0`

**Comment by danny0838** [comment]
This issue is reproduced in Chrome 109 and Edge 109 but not in Firefox 110 and Chromium 67.

It seems to be a browser feature (or issue) and we cannot change it. You can save captures to file or server to work around it.
