### ISSUE TITLE
not capturing in FF  ? WSB Version 1.8.1

### ISSUE THREAD

**Issue by mojorissin** [danny0838/webscrapbook#335]
FF for Linux Mint -001 - 1.0
FF ESR
Waterfox
TOR 

OK in Brave

most of W/c 27-03-23

**Comment by danny0838** [comment]
What have you done and what is going wrong? Please describe your problem in detail.

**Comment by mojorissin** [comment]
the web page is not being captured in FireFox ! - WSB not capturing (for me) . I tried : 2. Set config xpinstall.signatures.required to false. No good . 

3. Load the .xpi package file generated in the above section in a tab (through Install Add-on From File command in the add-on management page, or File > Open File from the main menu, or dragging and dropping the file to the tab list).
On last Wednesday am i searched for .xpi file & non were generated ? so could not attempt point 3.

WSB working in Brave browser !

mojorissin

**Comment by danny0838** [comment]
Please:

1. Provide the full version of your Firefox and WebScrapBook
2. Provide the source URL of the web page you have attempted to capture, the options used to capture the web page, and the log messages in the capture dialog.
3. Better provide a few screenshots to illustrate the what's not working as expected.

**Comment by mojorissin** [comment]
FF 102.9.0esr (64-bit)

WSB = Version 1.8.1 

https://www.investegate.co.uk/rainbFirefox for Linux Mint 111.0.1
Firefox Relow-rare-earths/rbw/holding-s--in-company/202303311352109936U/?fe=1&utm_source=FE%20Investegate%20Alerts&utm_medium=Email&utm_content=Announcement%20Alert%20Mail&utm_campaign=Rainbow+Rare+Earths%20Alert

Capturing (document) [33] https://www.investegate.co.uk/rainbow-rare-earths/rbw/holding-s--in-company/202303311352109936U/?fe=1&utm_source=FE%20Investegate%20Alerts&utm_medium=Email&utm_content=Announcement%20Alert%20Mail&utm_campaign=Rainbow+Rare+Earths%20Alert ...
Error downloading file (https://www.googletagmanager.com/ns.html?id=GTM-K9FK): Network request failed.
Error downloading file (https://tracker.live.rns-distribution.com/track.live-rns/4725256_c9454c56d48e843be9b5750e7410a3d9.png): 403 Forbidden
Error downloading file (http://wl.uk-wire.com/cgi-bin/logstat): Network request failed.
Saving data...
Saved to "/home/mojorissin/Downloads/WebScrapBook/data/20230401182828513/index.html"
Done.

3. Not showing captured item in left hand side scrapbook

mojorissin

On 1 Apr 2023 at 18:09, Danny Lin ***@***.***> wrote:

Please:Provide the full version of your Firefox and WebScrapBookProvide the source URL of the web page you have attempted to capture, the options used to capture the web page, and the log messages in the capture dialog.Better provide a few screenshots to illustrate the what's not working as expected.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Sent with https://mailfence.com  Secure and private email

**Comment by danny0838** [comment]
According to the log, the capture seems to work fine, but lnot saved to the backend. It seems that you did not set `Save capture data to` to `Server`. If that's not the case please provide the options you used to perform the capture.

**Comment by mojorissin** [comment]
you are correct ; it was not set to the backend server unlike Brave that was ! I had not spotted this ! Now working ,
Thank you
Mojorissin
