### ISSUE TITLE
Use last used object for "Capture tabs"

### ISSUE THREAD

**Issue by grotesque** [danny0838/webscrapbook#337]
![evernote-clipper-options](https://user-images.githubusercontent.com/305091/230775461-437095ae-c4d7-4637-ac17-1eaf4f2eb1c9.png)

Evernote web clipper allows to us save inside last used notebook. I think having a feature where webscrapbook automatically saves to last used folder or object will be beneficial. Even having an option to select an object to save inside by default will be a good start. 

Thanks Danny!

**Comment by danny0838** [comment]
Duplicate of #299.
