### ISSUE TITLE
Using regex doesn't capture linked webpages

### ISSUE THREAD

**Issue by Notnilc2107** [danny0838/webscrapbook#339]
An example webpage that I want to capture:

> https://blackboard.qut.edu.au/webapps/blackboard/content/listContent.jsp?course_id=_164929_1&content_id=_9748967_1

I want to capture every linked page that has a different course_id and content_id. The regex input I put in the included webpages is:

> /^https://blackboard\.qut\.edu\.au/webapps/blackboard/content/listContent\.jsp\?course_id\=

It works fine when I manually put in every linked page, but not when I use that regex input. I think it might be because of the ? after listContent.jsp but I'm not sure.
I've tried using regex with with https://demo.cyotek.com/ and it works there. The regex input I used for that was /^https://demo.cyotek.com/

**Comment by danny0838** [comment]
> The regex input I put in the included webpages is:
> 
> > /^[https://blackboard\.qut\.edu\.au/webapps/blackboard/content/listContent\.jsp\?course_id\=](https://blackboard%5C.qut%5C.edu%5C.au/webapps/blackboard/content/listContent%5C.jsp%5C?course_id%5C=)

As the tooltip says, a regex string must comply with the format `/<regex>/<flags>`. As what you input here has no ending `/`, it will be treated as matching the exact URL `/^https://blackboard\.qut\.edu\.au/webapps/blackboard/content/listContent\.jsp\?course_id\=`, which won't match any real world URL.

Fixing the format to something like `/^https://blackboard\.qut\.edu\.au/webapps/blackboard/content/listContent\.jsp\?course_id\=/` should get it work. If still not, please provide the exact capture options (which can be obtained from `Capture as` by copying the JSON from advanced mode) for further investigation.

**Comment by Notnilc2107** [comment]
It worked. Thanks for answering my rookie question. This is an amazing browser extension by the way, I'd send a tip on ko-fi or buymeacoffee if i could.
