### ISSUE TITLE
Title in file name

### ISSUE THREAD

**Issue by Purtzel** [danny0838/webscrapbook#34]
Hello,

I would like to have the titile of a page in the filename. I did it by modifiying capturer.js in this way:

Replacing the line
    filename = timeId + ".htz"; 
with
    filename = timeId + " " + (data.title ? data.title : scrapbook.urlToFilename(sourceUrl));
    filename = scrapbook.validateFilename(filename, options["capture.saveAsciiFilename"])+".htz";

and
    filename = timeId + ".maff";
with
    filename = timeId + " " + (data.title ? data.title : scrapbook.urlToFilename(sourceUrl));
    filename = scrapbook.validateFilename(filename, options["capture.saveAsciiFilename"])+".maff";

Please add this to the official version.

Thank you.

**Comment by danny0838** [comment]
We already have this. Uncheck "Save captured data in ScrapBook" to use the page title as filename.
