### ISSUE TITLE
search folder by name, clunky navigation in sidebar and managing of elements 

### ISSUE THREAD

**Issue by grotesque** [danny0838/webscrapbook#344]
I think search folder by name or ID is not supported. Can you support it?
Searching should search everything. Just like Scrapbook-X did. Search not searching for folder names annoys me. **It makes me not trust search**. Which is why I left evernote.

Also arranging captures, notes etc. inside folders and in a hierarchy is heavy, slow, difficult and old-fashioned.

Because of this I'm currently only using capture feature of webscrapbook. I then use copyinfo to copy IDs of captured webpages or notes and paste it manually in a text file to logically group things.

Arranging things in folders etc. is next to impossible at large scale or fast speed.

I think the only way I can define "clunky navigation" is it's nothing like Scrapbook-X.

**Comment by danny0838** [comment]
> I think search folder by name or ID is not supported. Can you support it? 
> Searching should search everything. Just like Scrapbook-X did. Search not searching for folder names annoys me. **It makes me not trust search**. Which is why I left evernote.

Not including folders and separators in fulltext search results is exactly the behavior inherited from ScrapBook X.

This can be tweaked from the `default search condition` option.

> Also arranging captures, notes etc. inside folders and in a hierarchy is heavy, slow, difficult and old-fashioned.
> Because of this I'm currently only using capture feature of webscrapbook. I then use copyinfo to copy IDs of captured webpages or notes and paste it manually in a text file to logically group things.
> 
> Arranging things in folders etc. is next to impossible at large scale or fast speed.
> 
> I think the only way I can define "clunky navigation" is it's nothing like Scrapbook-X.

I don't know what exactly you mean and how is it different from ScrapBook X. If you simply want to sort items by ID there is already a `Sort` command.

**Comment by grotesque** [comment]
Thanks. I didn't know about the default search condition option. Now it's searching folders after clearing out to NULL the search condition option text box.

>I don't know what exactly you mean

I'll try to make a list of issues while using the sidebar and arranging things.
