### ISSUE TITLE
adopt `.maff` file format of the Firefox MAF addon (with separate folder for html resources)

### ISSUE THREAD

**Issue by chrizilla** [danny0838/webscrapbook#346]
Would you be willing to adopt the `.maff` file format of the [Firefox MAF addon](https://en.wikipedia.org/wiki/Mozilla_Archive_Format) ?

The MAF addon created `.maff` files with this structure:
* .maff file
   * `directories\` for tabs
      * index.html
      * index.rdf
      * `index_files\`
         * **HTML RESOURCES**

... whereas WebScrapBook creates `.maff` files with this structure:

* .maff file
   * `directories\` for tabs
      * index.html
      * index.rdf
      * **HTML RESOURCES**

So index.html and index.rdf are mixed together with dozens of other html resources (fonts, images, css, etc.).
This is pretty chaotic.

Would you be willing to adopt the much cleaner structure above ?

**Comment by danny0838** [comment]
Similar to #185, which ias complicated to implement and is unlikely for now.
