### ISSUE TITLE
ubuntu firefox下不能编辑本地文件单个ＨＴＭＬ啊，怎么解决啊

### ISSUE THREAD

**Issue by aaawhale005** [danny0838/webscrapbook#347]
ubuntu firefox下不能编辑本地文件单个ＨＴＭＬ啊，没权限啊　，怎么解决
ubuntu chrome 可以编辑本地文件，用得还好

**Comment by aaawhale005** [comment]
编辑本地文件单个ＨＴＭＬ啊，firefox 　webscrapbook 　编辑分页不能用啊。灰色的，我主要是用来用标注功能。

**Comment by aaawhale005** [comment]
file:///home/ＸＸＸ.html 不能编辑，firefox 不能用，chrome 开了本地url权限可以用。。

**Comment by danny0838** [comment]
想要編輯擷取後的網頁並原地儲存，目前唯一方法是**安裝並設定後端伺服器**。

Firefox 和 Chrome 對瀏覽器套件編輯本地檔案的權限限制稍有不同，但無論何者，由於瀏覽器的權限限制，都無法儲存編輯後的本地檔案。

**Comment by aaawhale005** [comment]
那只好先用chrome 了。。。

**Comment by danny0838** [comment]
我是認為，即使能編輯開啟在瀏覽器中的本地檔案，無法儲存那意義也不大。而如果要儲存編輯後的檔案，無論用任何瀏覽器，都必須設定後端伺服器，使用側欄管理系統。

不過，如果你還是認為直接開啟本地網頁檔案，用瀏覽器編輯，再重新擷取，是你可以接受也認為很重要的功能，那使用目前有支援的 Chrome 系瀏覽器也不失是個選擇。
