### ISSUE TITLE
Right clicking opens link instead

### ISSUE THREAD

**Issue by Fixer-007** [danny0838/webscrapbook#35]
Firefox 57 with newest webscrapbook.
Say, I have archived webpage opened in viewer, I right click on some image to save it and instead it tries to open the link to article behind that image. Right clicking on other elements (like links) caused that problem too.

**Comment by danny0838** [comment]
Could you provide the URL of the page with this issue?

**Comment by Fixer-007** [comment]
https://www.pravda.com.ua/

**Comment by danny0838** [comment]
Fixed in b21bedbe143f0c2129d8bf29bc16102b1d951c78.

**Comment by Fixer-007** [comment]
Fixed issue for me, thank you very much.
