### ISSUE TITLE
A somewhat shameful but necessary request about license

### ISSUE THREAD

**Issue by kankanai** [danny0838/webscrapbook#353]
Dear project maintainer danny,

I am a long term user of webscrapbook. I am a student and have been using it since I started school and now I am about to graduate, thank you so much for the functionality of this program, it is so powerful and informative! Recently I have the personal need to reference and modify some parts of your project code(element location and delete) in a commercial application I am developing. However, due to the MPL 2.0 license used by your project, I am unable to apply the modified code for commercial use. Therefore I sincerely ask you to consider changing the open source license of your project to Apache 2.0 or MIT.
 some of the code modules in your project perfectly fit my needs and can be directly applied to bring significant efficiency improvement.
I learned through search that The strict restrictions of MPL 2.0 on commercial use and closed source modifications prevent me from using the related code in my commercial product.because I have to open source all the code, including other parts I have developed myself.  
I am also willing to continue open sourcing my modifications based on your project under Apache/MIT, to give back to the open source community.
I really hope you can consider my needs and change the license to Apache 2.0 or MIT. It will help me a lot. If I can assist the process in any way, please also let me know. Thank you very much for your understanding and help!

Best regards,
Kirby Leek

**Comment by danny0838** [comment]
This is not quite easy as you have to get an agreement from all collabators besides me.

Additionally, as some resources of WebScrapBook are taken from legacy ScrapBook, which is MPL-2, you have to get an agreement from its developers, too.

**Comment by kankanai** [comment]
> This is not quite easy as you have to get an agreement from all contributors besides me.
> 
> Additionally, as some resources of WebScrapBook are taken from legacy ScrapBook, which is MPL-2, you have to get an agreement from its developers, too.

ok,i know, anyway, thanks for the persistent updates and  love of code, and thanks again for the reply!
