### ISSUE TITLE
Backend initilization error: Unable to connect to backend server

### ISSUE THREAD

**Issue by grotesque** [danny0838/webscrapbook#354]
pywebscrapbook 2.0.1
chrome extension version 2.1.0

getting same error as mentioned in https://github.com/danny0838/webscrapbook/issues/269

it works for firefox which has firefox extension Version 2.0.4
i'm currently working with firefox so don't want to update it and see if it's a version issue

i tried disabling firewall still not working
i tried changing port to 4545 still not working with chrome (I changed port in ini and chrome extension)

danny please tell next steps to diagnose and fix this

**Comment by danny0838** [comment]
What is the configuration of your backend server?

Have you tried using the exactly same options for Chrome? (i.e. export the options from Firefox, import to Chrome and save)

**Comment by danny0838** [comment]
Close issue as no further details are provided.
