### ISSUE TITLE
有關使用的諮詢

### ISSUE THREAD

**Issue by kankanai** [danny0838/webscrapbook#355]
非常感謝你們開發出這樣的產品，用來做筆記很棒。

我已經配寘了後臺運行了8080，並且配寘好了保存檔案到服務端，有兩個問題需要諮詢：

1.

我想要看到的：

![image](https://github.com/danny0838/webscrapbook/assets/142068366/5806ccc8-6c9f-4cef-9acb-d596ac2ab9e3)

實際上我看到的：

![image](https://github.com/danny0838/webscrapbook/assets/142068366/15c72204-ad0f-459c-95e1-71a66bca3c5d)

2.保存的時候可以不使用彈框新標籤頁的管道，使用更友好的管道，如僅在頁面上提示保存中，保存失敗，保存成功的toast嗎？

**Comment by kankanai** [comment]
![image](https://github.com/danny0838/webscrapbook/assets/142068366/4a4c80bb-bbf5-4ddb-a1c9-d03101ef3ed8)
我是使用git clone https://github.com/danny0838/webscrapbook

獲取到程式碼，然後執行了python -m pip install -U webscrapbook

，最後新建了一個資料夾執行了wsb config -ba

然後wsb serve

。 我不太明白是否可以通過運行源碼的管道來執行本地服務端，而不是到另外的地方新建，因為我想二次開發後端，自己設定默認的保存位置

**Comment by kankanai** [comment]
請問在git clone的程式碼中，哪一個檔案是啟動檔案，希望可以本地啟動，比如指定8081埠啟動，然後我可以修改scrapy保存網頁的後端程式碼，因為我想要為每個保存的檔案，在後端做一點修改

**Comment by danny0838** [comment]
請參見[說明文件](https://github.com/danny0838/webscrapbook/wiki/Basic-(zh_TW)#3-%E7%80%8F%E8%A6%BD%E5%99%A8%E5%81%B4%E6%AC%84%E5%9E%8B)

**Comment by danny0838** [comment]
2\. 關於跳出新視窗的問題，請見 #191

**Comment by kankanai** [comment]
> 请参见[说明文件](https://github.com/danny0838/webscrapbook/wiki/Basic-(zh_TW)#3-%E7%80%8F%E8%A6%BD%E5%99%A8%E5%81%B4%E6%AC%84%E5%9E%8B)

是的，我差不多看完了檔案並設定了，我是通過wsb config -ba

之後執行了wsb serve

，但是我看到的介面仍然是這樣的：
![image](https://github.com/danny0838/webscrapbook/assets/142068366/0406c2b2-8041-4ddb-a6ee-fa6e28366f30)
它並不是一個管理介面，讓我很疑惑
