### ISSUE TITLE
Gmail messages saved as HTML use generic filenames for images

### ISSUE THREAD

**Issue by Knocks** [danny0838/webscrapbook#357]
When saving Gmail messages, Webscrapbook produces HTML code that looks like this, along with files named unnamed-1.png etc.

`<img border="0" src="https://ci5.googleusercontent.com/proxy/.....t#https://www.paypalobjects.com/digitalassets/c/system-triggered-email/n/layout/images/paypal-rebranding/footer-social-icons_linkedin-2x.png" width="28" height="28" style="display:block" alt="LinkedIn"></a>`

This results in broken formatting when saving several Gmail messages from the same thread/sender and unifying asset folders, because the naming of generic images is not consistent.

The process would work better if the local images saved from Gmail's proxied locations would be named after their sources instead of getting generic names.

**Comment by danny0838** [comment]
Can you provide screenshots to illustrate which specific part(s) is affected?

**Comment by danny0838** [comment]
Close due to lack of further information.
