### ISSUE TITLE
Save tab option explanation (answered)

### ISSUE THREAD

**Issue by Fixer-007** [danny0838/webscrapbook#36]
When clicking on webscrapbook icon there is presented a menu that have few entires, that are not clear (at least I did not find info about them), like:
Save tab (source) - seems same to "Save tab"
Save tab (bookmark) - saves bookmark?
Save following tabs - saves current tab? bug?

Can you some info about those somewhere? Or maybe add tooltips for menu entries.

**Comment by danny0838** [comment]
**Capture tab (source)**: Capture the original hypertext content of the page, that is, before any modification of the browser script.
**Capture tab (bookmark)**: Save a bookmark file (.htm), clicking which will take you the the original web page.
**Capture following tabs**: Capture the current tab and all tabs after it (at right side for left-to-right languages, and at left side for right-to-left languages). 

We are considering a better design of UI but haven't come up with a good idea. Feel free to provide an idea if you get one.
