### ISSUE TITLE
"Capture tabs as" should have an option to show only folders amongst the dropdown list of "Target item"

### ISSUE THREAD

**Issue by grotesque** [danny0838/webscrapbook#360]
Hi Danny,

Excellent work with webscrapbook.

I think given that folders exists in webscrapbook they(folders) should be shown automatically in the dropdown. The "Select..." button can be used to select other types of items to capture the webpage under.

![image](https://github.com/danny0838/webscrapbook/assets/305091/4283de18-d7f2-4b5b-a0d5-599d1abd1f34)

**Comment by danny0838** [comment]
We probably won't do that.

Due to the server-client and async nature of WebScrapBook, a significant performance issue will be introduced to load all scrapbook trees when performing a capture. Also, the HTML selector is linear and it's not easy to display hierarchical folders neatly.

**Comment by grotesque** [comment]
When we click select the response is fast suggesting the list is fetched locally and a python server network request isn't initiated. So it should be feasible to show only folders in the dropdown.

Regarding hierachical requirement we could just show 1st level of folders here.

**Comment by danny0838** [comment]
I don't think showing only the first level folders is a desired and helpful behavior as there's no way to further expand them.

Considering the many potential issues that can be introduced by reading and/or syncing with the book tree(s) in the detail dialog directly, it obviously doesn't worth it.

**Comment by grotesque** [comment]
When we click select we're already generating a server request. What I'm suggesting is have and option to only show folders as existence of folders mean they're more likely to be used to sort things by the webscrapbook users.

scrapbook-x had folder selection front and center.

![image](https://github.com/danny0838/webscrapbook/assets/305091/6885ed7a-564e-49c7-a17e-2d0ec42c948d)

![image](https://github.com/danny0838/webscrapbook/assets/305091/f57e3a29-e444-44ef-9e0a-55cd149e77f5)

![image](https://github.com/danny0838/webscrapbook/assets/305091/5347af5a-b730-4557-a049-d6730dc39295)
