### ISSUE TITLE
is it possible to have a global setting "Put an item into: top/bottom of folder/root" option like Scrapbook-X used to have

### ISSUE THREAD

**Issue by grotesque** [danny0838/webscrapbook#363]
![image](https://github.com/danny0838/webscrapbook/assets/305091/025e927f-5dfd-491d-867f-0b6e91262a8c)

**Comment by danny0838** [comment]
Configure the backend PyWebScrapBook. See #120

**Comment by grotesque** [comment]
for others refer this documentation

https://github.com/danny0838/PyWebScrapBook/blob/master/webscrapbook/resources/config.md

section [new_at_top](https://github.com/danny0838/PyWebScrapBook/blob/master/webscrapbook/resources/config.md#new_at_top)
