### ISSUE TITLE
shortcuts while dragging and dropping

### ISSUE THREAD

**Issue by grotesque** [danny0838/webscrapbook#365]
Today I discovered that 

- dragging and dropping items in sidebar while holding shift creates a copy (recursively) of that item
- dragging and dropping items in sidebar while holding alt creates a link (recursively) of that item

Are there any other shortcuts like these?

**Comment by danny0838** [comment]
Not sure how "like" is defined but there are shortkeys everywhere and difficult to list all of them in detail. Most of them are inherited from legacy ScrapBook (X), though.

Also, for correctness, linking is NOT recursive. Only an extra item X' is generated under the TOC of its parent when a linking is performed. The linked item X' works like a hard link of the original item X, and thus you see exactly same child items under X and X', and changing the children of one will affect the children of the other.
