### ISSUE TITLE
why is right click browse locally greyed out?

### ISSUE THREAD

**Issue by grotesque** [danny0838/webscrapbook#367]
![image](https://github.com/danny0838/webscrapbook/assets/305091/6c4e6a02-4829-4afc-8556-48d51b82942c)

**Comment by danny0838** [comment]
It works only when the backend server is hosted on the local device.

**Comment by grotesque** [comment]
I've connected to the server on the same node. But I'm using hostname instead of "localhost".

**Comment by danny0838** [comment]
Basically only localhost, 127.0.0.1 amd [::1] are recognized. Otherwise you'd have to make sure that the browser sends the exactly same client host and the remote host.
