### ISSUE TITLE
Support customization during a capture

### ISSUE THREAD

**Issue by Fixer-007** [danny0838/webscrapbook#37]
Are you planning to add dedicated "Capture Page as" window, as in Scrapbook to do custom/advanced saving (multilink saving, depth, folder, images, files, extensions) aka

![detail](https://user-images.githubusercontent.com/16494741/33851923-43ca2f0c-dec1-11e7-9fef-e60beaea62a8.png)

P.S. Rough TODO page for this addon would be nice.

**Comment by danny0838** [comment]
Maybe. But a real time option (rather than just the option page) is a lot more complicated and is nore likely to cause issues. We need furher investigation.

For the TODO you can visit the [Projects page](https://github.com/danny0838/webscrapbook/projects).

**Comment by pausto** [comment]
Thank you for your work!
