### ISSUE TITLE
Fatal Error (invalid URL) during rebuilding

### ISSUE THREAD

**Issue by FalxGod** [danny0838/webscrapbook#374]
I'm getting the following error when using webscrapbook and I have no idea how to fix it.

```
Rebuilding links...
Fatal error: URL constructor: https://*************/d0I0Mb1bub/Interactive__setup_v1.1_var is not a valid URL.

```
The URL doesn't even match my regex for included websites so I dont know why the rebuilding would fail.

The link is embedded like this:
`<a href="https://**********.com/" target="_blank" class="link link--external has-favicon" rel="nofollow noopener" style="background-image: url(&quot;https://external-content.duckduckgo.com/ip3/.ico&quot;);">https://**********.com/</a>`

I have no idea how to prevent webscrapbook from crashing if it encounters an invalid URL.
Help would be appreciated :)

Edit: I already added the following regex to "Excluded URLs":
`/^https:\/\/\*.*/`

**Comment by danny0838** [comment]
We cannot reproduce the issue according to the provided info. Please provide more details, including the version of the browser and WSB, the capture options (which can be copied from capture as > advanced), and the URL of the source page (or, alternatively, the minimal HTML file(s) that can trigger the same issue when hosted locally).

**Comment by FalxGod** [comment]
I'll gladly provide more info:
Tested on the following browsers: 
-Firefox 123.0 (x64)
-Firefox 123.0.1 (x64)

WSB backend server version:
2.3.0
WSB browser extension version:
- 2.8.1 on Firefox 123.0 and 123.0.1

The Fatal Error occurred when using the backend server and when not using it.

Sadly the source page is behind a login so here's the HTML snipped that I hosted on an apache and managed to reproduce the error:
`<!DOCTYPE html>
<html id="XF">
      <head></head>
      <body data-template="conversation_view">
        <ul>
            <li data-xf-list-type="ul">********** - <a href="https://**********.com/" target="_blank" class="link link--external" rel="nofollow noopener">https://**********.com/</a></li>
            <li data-xf-list-type="ul">And Then Forever (aka. ATF) - <a href="************************/" class="link link--internal">************************/</a></li>
            </ul>blabla<br />
      </body>
</html>`

And here are my capture options:
`{
 "tasks": [
  {
   "tabId": 227,
   "fullPage": true,
   "url": "https://localhost/test/1.html",
   "title": "localhost/test/1.html",
   "comment": ""
  }
 ],
 "bookId": null,
 "parentId": "root",
 "index": null,
 "mode": "",
 "delay": null,
 "options": {
  "capture.serverUploadWorkers": 4,
  "capture.serverUploadRetryCount": 3,
  "capture.serverUploadRetryDelay": 2000,
  "capture.downloadWorkers": 4,
  "capture.downloadRetryCount": 3,
  "capture.downloadRetryDelay": 1000,
  "capture.saveTo": "folder",
  "capture.saveFolder": "WebScrapBook/data",
  "capture.saveAs": "folder",
  "capture.saveFilename": "%id%",
  "capture.saveFilenameMaxLenUtf16": 120,
  "capture.saveFilenameMaxLenUtf8": 240,
  "capture.saveAsciiFilename": false,
  "capture.saveOverwrite": false,
  "capture.saveFileAsHtml": false,
  "capture.saveDataUriAsFile": true,
  "capture.saveDataUriAsSrcdoc": true,
  "capture.saveResourcesSequentially": false,
  "capture.resourceSizeLimit": null,
  "capture.image": "save",
  "capture.imageBackground": "save-used",
  "capture.favicon": "save",
  "capture.faviconAttrs": "",
  "capture.canvas": "save",
  "capture.audio": "save",
  "capture.video": "save",
  "capture.embed": "blank",
  "capture.object": "blank",
  "capture.applet": "blank",
  "capture.frame": "save",
  "capture.frameRename": true,
  "capture.font": "save-used",
  "capture.style": "save",
  "capture.styleInline": "save",
  "capture.rewriteCss": "url",
  "capture.mergeCssResources": true,
  "capture.script": "remove",
  "capture.noscript": "save",
  "capture.contentSecurityPolicy": "remove",
  "capture.ping": "blank",
  "capture.preload": "remove",
  "capture.prefetch": "remove",
  "capture.base": "blank",
  "capture.formStatus": "keep",
  "capture.shadowDom": "save",
  "capture.removeHidden": "none",
  "capture.linkUnsavedUri": false,
  "capture.downLink.file.mode": "none",
  "capture.downLink.file.extFilter": "###image\n#bmp, gif, ico, jpg, jpeg, jpe, jp2, png, tif, tiff, svg\n###audio\n#aac, ape, flac, mid, midi, mp3, ogg, oga, ra, ram, rm, rmx, wav, wma\n###video\n#avc, avi, flv, mkv, mov, mpg, mpeg, mp4, wmv\n###archive\n#zip, rar, jar, bz2, gz, tar, rpm, 7z, 7zip, xz, jar, xpi, lzh, lha, lzma\n#/z[0-9]{2}|r[0-9]{2}/\n###document\n#pdf, doc, docx, xls, xlsx, ppt, pptx, odt, ods, odp, odg, odf, rtf, txt, csv\n###executable\n#exe, msi, dmg, bin, xpi, iso\n###any non-web-page\n#/(?!$|html?|xht(ml)?|php|py|pl|aspx?|cgi|jsp)(.*)/i",
  "capture.downLink.doc.depth": 2,
  "capture.downLink.doc.delay": null,
  "capture.downLink.doc.mode": "source",
  "capture.downLink.doc.urlFilter": "",
  "capture.downLink.urlFilter": "###skip common logout URL\n/[/=]logout\\b/i",
  "capture.downLink.urlExtra": "",
  "capture.referrerPolicy": "",
  "capture.referrerSpoofSource": false,
  "capture.recordDocumentMeta": true,
  "capture.recordRewrites": false,
  "capture.prettyPrint": false,
  "capture.insertInfoBar": false,
  "capture.helpersEnabled": false,
  "capture.helpers": "",
  "capture.remoteTabDelay": null,
  "capture.deleteErasedOnCapture": true,
  "capture.deleteErasedOnSave": false,
  "capture.backupForRecapture": true,
  "capture.zipCompressLevel": null
 }
}`

I also tried using Chrome once, and the fatal error doesn't occur there. I need more testing to ensure this is a FIrefox only error first though. It might take a while because I'm at work at the moment

**Comment by danny0838** [comment]
We still cannot reproduce the issue using the file you provided.

After some further investigation it seems that any invalid URL can trigger the issue, and version 2.8.2 should have fixed the issue if our guess is correct. Please confirm it. If the issue still persists, please provide the file without masking content (which is likely the source of the error) or provide an non-masked file that can really trigger the issue for further investigation.

**Comment by FalxGod** [comment]
After extensive testing yesterday and today, I can confirm that version 2.8.2 fixed the fatal error.
Thank you danny you absolute GIGACHAD!
