### ISSUE TITLE
Unable to download to the folder

### ISSUE THREAD

**Issue by ninalanyon** [danny0838/webscrapbook#378]
Occasionally I get errors like this:

> Capturing (document) [6] https://similarworlds.com/lgbtq/cross-dressing/the-cdtv-closet-pics-share/4982732-Not-sure-if-Im-really-in-the-closet-any-more ...
> Saving data...
> Fatal error: Failed to download "WebScrapBook/data/similarworlds.com/lgbtq_cross-dressing_the-cdtv-closet-pics-share_4982732-Not-sure-if-Im-really-in-the-closet-any-more/_/_/Not sure if I'm really in the closet any more _ The CD_TV Closet (Pics Share)(1)/index.html": Unable to download to the folder.

In this case the url of the page is:

> https://similarworlds.com/lgbtq/cross-dressing/the-cdtv-closet-pics-share/4982732-Not-sure-if-Im-really-in-the-closet-any-more

**Comment by danny0838** [comment]
Please provide your capture options (copy from `capture as ...` => `Advanced`), and the version of your OS, browser, and WSB.

**Comment by ninalanyon** [comment]
OS: Linux Mint 20.3 Una
Browser: Firefox 124.0.2 (64-bit)
WSB: 2.9.1, Last Updated: 5 April 2024

Not quite sure what you mean by copy from capture as ... => Advanced.  Here are all the entries from the exported options that begin with capture.

  "capture.serverUploadWorkers": 4,
  "capture.serverUploadRetryCount": 3,
  "capture.serverUploadRetryDelay": 2000,
  "capture.downloadWorkers": 4,
  "capture.downloadRetryCount": 3,
  "capture.downloadRetryDelay": 1000,
  "capture.saveTo": "folder",
  "capture.saveFolder": "WebScrapBook/data",
  "capture.saveAs": "folder",
  "capture.saveFilename": "%source-host%/%source-pathname%/%source-search%/%source-hash%/%title%",
  "capture.saveFilenameMaxLenUtf16": 240,
  "capture.saveFilenameMaxLenUtf8": 480,
  "capture.saveAsciiFilename": false,
  "capture.saveOverwrite": false,
  "capture.saveFileAsHtml": false,
  "capture.saveDataUriAsFile": true,
  "capture.saveDataUriAsSrcdoc": true,
  "capture.saveResourcesSequentially": false,
  "capture.resourceSizeLimit": null,
  "capture.image": "save",
  "capture.imageBackground": "save-used",
  "capture.favicon": "save",
  "capture.faviconAttrs": "",
  "capture.canvas": "save",
  "capture.audio": "save",
  "capture.video": "save",
  "capture.embed": "blank",
  "capture.object": "blank",
  "capture.applet": "blank",
  "capture.frame": "save",
  "capture.frameRename": true,
  "capture.font": "save-used",
  "capture.style": "save",
  "capture.styleInline": "save",
  "capture.rewriteCss": "url",
  "capture.mergeCssResources": true,
  "capture.script": "remove",
  "capture.noscript": "save",
  "capture.contentSecurityPolicy": "remove",
  "capture.ping": "blank",
  "capture.preload": "remove",
  "capture.prefetch": "remove",
  "capture.base": "blank",
  "capture.formStatus": "keep",
  "capture.shadowDom": "save",
  "capture.removeHidden": "none",
  "capture.linkUnsavedUri": true,
  "capture.downLink.file.mode": "none",
  "capture.downLink.file.extFilter": "###image\n#bmp, gif, ico, jpg, jpeg, jpe, jp2, png, tif, tiff, svg\n###audio\n#aac, ape, flac, mid, midi, mp3, ogg, oga, ra, ram, rm, rmx, wav, wma\n###video\n#avc, avi, flv, mkv, mov, mpg, mpeg, mp4, wmv\n###archive\n#zip, rar, jar, bz2, gz, tar, rpm, 7z, 7zip, xz, jar, xpi, lzh, lha, lzma\n#/z[0-9]{2}|r[0-9]{2}/\n###document\n#pdf, doc, docx, xls, xlsx, ppt, pptx, odt, ods, odp, odg, odf, rtf, txt, csv\n###executable\n#exe, msi, dmg, bin, xpi, iso\n###any non-web-page\n#/(?!$|html?|xht(ml)?|php|py|pl|aspx?|cgi|jsp)(.*)/i",
  "capture.downLink.doc.depth": null,
  "capture.downLink.doc.delay": null,
  "capture.downLink.doc.mode": "source",
  "capture.downLink.doc.urlFilter": "",
  "capture.downLink.urlFilter": "###skip common logout URL\n/[/=]logout\\b/i",
  "capture.downLink.urlExtra": "",
  "capture.referrerPolicy": "",
  "capture.referrerSpoofSource": false,
  "capture.recordDocumentMeta": true,
  "capture.recordRewrites": false,
  "capture.prettyPrint": false,
  "capture.insertInfoBar": true,
  "capture.helpersEnabled": false,
  "capture.helpers": "",
  "capture.remoteTabDelay": null,
  "capture.deleteErasedOnCapture": true,
  "capture.deleteErasedOnSave": false,
  "capture.backupForRecapture": true,
  "capture.zipCompressLevel": null,

**Comment by danny0838** [comment]
I suspect that the filename you defined has exceeded the max allowed length of your OS. Reduce the allowed filename length and see if the same issue still happens.

**Comment by danny0838** [comment]
Close issue which lacks further information.
