### ISSUE TITLE
Unable to find a matching scrapbook item 

### ISSUE THREAD

**Issue by grotesque** [danny0838/webscrapbook#379]
even though the page is right there in sidebar I still get this error when I click "locator" button

**Comment by danny0838** [comment]
Please provide the detailed steps to reproduce the issue, better with screenshots. Thanks.

**Comment by grotesque** [comment]
happens when I press the red locator button
![image](https://github.com/danny0838/webscrapbook/assets/305091/d1761684-0d5a-4860-a7ab-32cc379e6cc4)

**Comment by danny0838** [comment]
Obviously you don't provide the detailed steps to reproduce the issue.

Please provide at least:
1. The version of your OS, browser, WSB, and backend PyWSB
2. The config of the backend server
3. The backend scrapbook data
4. The current URL of the page you attempt to invoke the locator

**Comment by grotesque** [comment]
it's too much of a trouble to provide all that. mostly due to privacy concerns.

**Comment by danny0838** [comment]
We cannot do further investigation without more detailed information. You can try crafting another backend or dataset that can still reproduce the issue and without the sensitive information.

**Comment by danny0838** [comment]
Close issue which lacks further information.
