### ISSUE TITLE
Support MHTML

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [danny0838/webscrapbook#38]
Mozilla Archive Format and UnMHT support saving and viewing MHTML format, both of them are wide spread until FF 57.0 released. But Web ScrapBook doesn't support it. MHTML is an open standard formatted in [RFC 2557](https://tools.ietf.org/html/rfc2557).

**Comment by danny0838** [comment]
This is currently in our [projects](https://github.com/danny0838/webscrapbook/projects/3).

Although MHTML is an open standard, there are still many issues making supporting MHT difficult. Additionally, MHT support is inconsistent across browsers and is decreasing (Edge, the descendant of IE, stops supporting it; Firefox lost the addon supporting it...).

Grossly speaking, MHT has almost no Advantage over our supported HTZ/MAFF (saves size, cross platform, easy restore) and single HTML (convenient in many browsers). We have difficulty, are not recommending it, and are not very willing to support it currently.

**Comment by cy7yz2rj** [comment]
I agree with disincentivising use of MHTML and preferring MAFF/HTZ over it. Not allowing creation of new .mht files and having only the option of opening already existing ones and possibly converting them to MAFF/HTZ sounds fine.

I have old .mht files that can't be displayed on my offline test browser, QupZilla.
On the other hand, not a single .maff has yet caused any trouble, just unzip and open index.html and everything renders fine on any browser I've tried.

While it is annoying not being able to doubleclick on a .maff and have it automatically open the browser and display the content, the reliability far outweighs the minor inconvenience of manually unzipping.

**Comment by danny0838** [comment]
We might implement the feature to view and to convert MHT, but it's of low priority since using it is really not recommended, and existed MHT can be converted to MAFF using the MAF addon anyway (MAF addon is not available in Fx 57+, but one can simply download a portable version of Fx 56 to install it and do the conversion, which is likely a one time job).

Besides, there's already a solution of viewing a MAFF file directly with double-clicking [here](https://github.com/danny0838/webscrapbook/wiki/View#open-directly-with-the-browser).

**Comment by KrasnayaPloshchad** [comment]
Here could found some source codes that you can works for this.
http://maf.mozdev.org/installation.html

**Comment by danny0838** [comment]
@KrasnayaPloshchad Thank you for the information. Unfortunately, the technique that MAF addon used for handling MHT are mostly dependent on XUL/XPCOM used in legacy addon API and are no more available in WebExtension.

**Comment by KrasnayaPloshchad** [comment]
The Internet Archive have some archives of UnMHT extension.
https://web.archive.org/web/20171029173137/https://addons.mozilla.org/en-US/firefox/addon/unmht/
https://web.archive.org/web/20140822150409/http://www.unmht.org/unmht/index.html

**Comment by danny0838** [comment]
We know that. UnMHT is also a legacy addon.

**Comment by danny0838** [comment]
We are not going to implement an ad hoc support to capture a page as MHT format, but may consider implementing a converter for PyWebScrapBook, which will be followed as the [new issue](https://github.com/danny0838/PyWebScrapBook/issues/27) in the future.
