### ISSUE TITLE
[Feature request] Show a list of recently used folder when saving the page

### ISSUE THREAD

**Issue by zenrabbit007** [danny0838/webscrapbook#380]
![image](https://github.com/danny0838/webscrapbook/assets/85089585/212debd7-6f88-4bee-83e5-5ddabd2095d4)

Show a list of recently used folder when saving the page. For instance, if I just recently saved a page to the lifestyle folder, when I saving a new page, form the folder list, the lifestyle folder will be one of the option I can choose from the list.

**Comment by danny0838** [comment]
You can see that within the `Select...` dialog.

**Comment by danny0838** [comment]
Close stale issue.
