### ISSUE TITLE
Question:  Is there a way to indicate that current viewing webpage was saved to scrapbook previously (when using backend server) 

### ISSUE THREAD

**Issue by coldwinds** [danny0838/webscrapbook#388]
Hello,

Is there a way to indicate that current viewing webpage was saved to scrapbook previously (when using backend server) 

Ideally it could be matched with custom url patterns(or the exact source url) with current url, and list the matched items in a dropdown of scrapbook browser icon.

Any idea?

**Comment by danny0838** [comment]
Check the `Show hint when browsing a page having been captured` option and the `View captured pages` dropdown command of the toolbar button.
