### ISSUE TITLE
Cannot start download because of unspecified illegal characters in file name

### ISSUE THREAD

**Issue by ninalanyon** [danny0838/webscrapbook#389]
Firefox 127.0 (64 bit), WSB 2.9.1

Capture dialog:

> Capturing (document) [7] https://similarworlds.com/social/blogs/5035279-Ninas-Blog-Tuesday-18th-June-2024 ...
> Saving data...
> Fatal error: Failed to download "WebScrapBook/data/similarworlds.com/social_blogs_5035279-Ninas-Blog-Tuesday-18th-June-2024/_/_/Nina's Blog - Tuesday 18th June 2024 Tuesday 18th June 2024, 10_41 Just spent an hour leafing... _ Blogs/index.html": Unable to start downloading: filename must not contain illegal characters

The URL of the page I am trying to capture is:

[https://similarworlds.com/social/blogs/5035279-Ninas-Blog-Tuesday-18th-June-2024](url)

Using File|Save As works but typically only after retrying.

The problem occurs with all of my blog pages, or at least all those I have recently tried.
Perhaps the error message should include the offending string.

**Comment by danny0838** [comment]
This is [an issue of Firefox > 126](https://bugzilla.mozilla.org/show_bug.cgi?id=1903780) ([details](https://github.com/eight04/webext-illegal-filename/blob/master/report.md)) when the folder name of a download contains a `.` and a space after it.

Some ways to workaround before Firefox is Fixed:
1. use a browser other than Firefox > 126
2. do NOT use the downloads API (i.e. `Save captured data to:  Scrapbook folder`)
3. config a filename without the affected char(s)

**Comment by ninalanyon** [comment]
What worked for me was just dropping the %title% from the "Filename to save:" setting.  I changed from:
> %source-host%/%source-pathname%/%source-search%/%source-hash%/%title%

to
> %source-host%/%source-pathname%/%source-search%/%source-hash%

Thanks for the suggestions.

**Comment by danny0838** [comment]
Fixed in Firefox 130.
