### ISSUE TITLE
[Question] is there any CHANGELOG somewhere?

### ISSUE THREAD

**Issue by Atanacius** [danny0838/webscrapbook#39]
All is said in title I think.

Any changelog would be great for know new fixes/features/caveats..

If it already exists, please give me a link.
If not, please add to the wiki (or a changelog.txt) file.

Thanks!

**Comment by danny0838** [comment]
We are currently in the fast-developing status and just too busy to write a detailed changelog. Important changes that could involve a compatibility issue may be included in the wiki. For now you can simply view the commit log.

**Comment by danny0838** [comment]
Added `CHANGES.md` with change summary since 0.79
