### ISSUE TITLE
Google Chrome: This extension may soon no longer be supported

### ISSUE THREAD

**Issue by pausto** [danny0838/webscrapbook#393]
This extension may soon no longer be supported
Remove or replace it with similar extensions from the Chrome Web Store
Webscrapbook version: 2.13.1
Chrome version: 128.0.6613.120

![webscrapbook](https://github.com/user-attachments/assets/ac54768b-7ab8-4c3f-8480-24fbe1c9e624)

**Comment by danny0838** [comment]
Duplicated of #377
