### ISSUE TITLE
On a page is a youtube video - is it possible to download it? And pdf does not download too...

### ISSUE THREAD

**Issue by leonidrysev** [danny0838/webscrapbook#394]
Thank you for a GREAT app!!!! A lot of year I could not find the same!

Could you help me? 
On a page is a youtube video - is it possible to download it?
And pdf does not download too. There is the Link to the original file, but not download((
I set 2 in Depth to capture linked pages:

CODE:

<iframe width="560" height="315" src=https://www.youtube.com/embed/e-2L10SG5Ns frameborder="0" allowfullscreen="" allow="autoplay; encrypted-media"></iframe>
-----------------------------------------
<a style="text-decoration: underline" target="_blank" href=https://sisterproject.getcourse.ru/pl/fileservice/user/file/download/h/321a8a333dc3b9d0e61272abfcfe31a0.pdf>обеды.pdf</a>

**Comment by danny0838** [comment]
Streamed video cannot be captured. This is [documented in the known issues](https://github.com/danny0838/webscrapbook/wiki/Issues).

Linked PDF files can be downloaded (but not too much different from a normal browser save). However, the PDF link you have provided seems to be protected, you need to get the right to access to download it.

**Comment by leonidrysev** [comment]
Thank you!
But about pdf - if I get it by right buttom of mouse? it download..
![image](https://github.com/user-attachments/assets/accde9aa-7a31-465e-b0b9-45dd0ba7f80f)

**Comment by leonidrysev** [comment]
It works!!!
I need to set here so. Right&)
![image](https://github.com/user-attachments/assets/2750936f-bd1e-467f-8d24-25a8d6f25955)

**Comment by leonidrysev** [comment]
Just not right cyrillic symbols in url, **but url works**
Is it possible to fix cyrillic symbols ?
![image](https://github.com/user-attachments/assets/b1c03808-9902-4e5f-8918-67c3a8dca66f)

**Comment by leonidrysev** [comment]
One more last question!
Is it possible to keep link to youtube? Now just black
![image](https://github.com/user-attachments/assets/6e474e45-71aa-4a25-841f-d5e9a5f1a2d2)

**Comment by danny0838** [comment]
> Just not right cyrillic symbols in url, **but url works** Is it possible to fix cyrillic symbols ?

I don't get it. Please be clear about:
1. what you have done
2. what is the expected result
3. what is the actual result

**Comment by danny0838** [comment]
> One more last question! Is it possible to keep link to youtube? Now just black 

Unfortunately, no.

A stream video is not just a URL. WSB only sees a blob UTL that can not be directly accessed.

You'll need a specialized tool to download a streamed video.

**Comment by leonidrysev** [comment]
I record video: https://www.dropbox.com/scl/fi/bb70xoug9vakktoym7kaf/Video_2024-09-22_141730.mp4?rlkey=4gu7nwvnytekg8iyqltopqsjz&dl=0

Name in web is:
https://sisterproject.getcourse.ru/pl/fileservice/user/file/download/h/**86f4606649bd3458f7ffb23011b72c67.pdf**

Name in data is 
**ÐÐ¿Ð¿ÐµÑÐ¸Ñ%20Ð½Ð¾Ð².pdf**

**Comment by leonidrysev** [comment]
> > One more last question! Is it possible to keep link to youtube? Now just black
> 
> Unfortunately, no.
> 
> A stream video is not just a URL. WSB only sees a blob URL that can not be directly accessed.
> 
> You'll need a specialized tool to download a streamed video.

After reset options I see preveiw youtube ok and with link.
To download video I got links from data and used https://youtubeplaylist.cc/ ))
Its great! Thank you again!)

![image](https://github.com/user-attachments/assets/80798e58-d708-4572-83a5-29b932955499)

**Comment by danny0838** [comment]
> I record video: https://www.dropbox.com/scl/fi/bb70xoug9vakktoym7kaf/Video_2024-09-22_141730.mp4?rlkey=4gu7nwvnytekg8iyqltopqsjz&dl=0
> 
> Name in web is: https://sisterproject.getcourse.ru/pl/fileservice/user/file/download/h/**86f4606649bd3458f7ffb23011b72c67.pdf**
> 
> Name in data is **ÐÐ¿Ð¿ÐµÑÐ¸Ñ%20Ð½Ð¾Ð².pdf**

I don't see the relationship between video and the PDF? Please be more clear about it.

**Comment by leonidrysev** [comment]
Is it possible to use normal symbols in file name?
No strang such:
![image](https://github.com/user-attachments/assets/2a7d4911-92f9-435c-87de-e3f6139258ea)

Name in web is: https://sisterproject.getcourse.ru/pl/fileservice/user/file/download/h/**86f4606649bd3458f7ffb23011b72c67.pdf**

Name in data is ÐÐ¿Ð¿ÐµÑÐ¸Ñ%20Ð½Ð¾Ð².pdf

**Comment by danny0838** [comment]
Please be clear about the detailed steps of how you captured the PDF file.

**Comment by leonidrysev** [comment]
> Please be clear about the detailed steps of how you captured the PDF file.

I show it on my video)
https://www.dropbox.com/scl/fi/bb70xoug9vakktoym7kaf/Video_2024-09-22_141730.mp4?rlkey=4gu7nwvnytekg8iyqltopqsjz&dl=0

I reset setting
On download pdf
![image](https://github.com/user-attachments/assets/9fd85205-1eba-42b9-b7c6-0d3aa995b33c)

Clicked
![image](https://github.com/user-attachments/assets/c0439661-3f99-423b-ac31-23208359cb0f)

Got pdf in data
![image](https://github.com/user-attachments/assets/2b5bb56c-d1c7-406c-8f1e-37eaf93d2fe0)

**Comment by danny0838** [comment]
The filename is usually determined by the header. Unfortunately the webpage you provided is protected and I cannot access it, and thus you have to do the investigation by yourself.

Please Provide the filename if you save the PDF file with native browser saving.

If possible please also try getting the header of the file:
1. Open the network section of the console (usually by right clicking on the web page > `Inspect` > `Network`)
2. Click on the PDF file link to visit it.
3. Find the corresponding URL of the PDF file in the list of the console, and report the response headers, especially the `Content-Disposition`.

![圖片](https://github.com/user-attachments/assets/fbe34bb0-b203-4284-94a4-30d854ae5707)

**Comment by leonidrysev** [comment]
Dear Danny!
I provide you 1 time password https://share.1password.com/s#Oc72n87uI3OziFbxHHuchTsc042geK8ovaBmPH58nms 
https://sisterproject.getcourse.ru/pl/teach/control/lesson/view?id=268586929&editMode=0

**Comment by danny0838** [comment]
Thank you.

The `Content-Disposition` response header of the web app for `https://sisterproject.getcourse.ru/pl/fileservice/user/file/download/h/321a8a333dc3b9d0e61272abfcfe31a0.pdf` is malformed:

It looks like:
```
Content-Disposition: inline; filename="Ð¾Ð±ÐµÐ´Ñ.pdf"
```

Where the filename `обеды.pdf` is incorrectly encoded as `\xD0\xBE\xD0\xB1\xD0\xB5\xD0\xB4\xD1\x8B.pdf`.

This is not compliant with the [spec of HTTP headers](https://httpwg.org/specs/rfc6266.html#rfc.section.4.3), where `filename` allows only ISO-8859-1 encoded chars, and any other multi-byte chars should be sent with `filename*` field with UTF-8 encoding like:

```
Content-Disposition: inline; filename*=UTF-8''%D0%BE%D0%B1%D0%B5%D0%B4%D1%8B.pdf; filename=_.pdf
```

This is an issue of the website rather than WSB. To fix it you have to request the website master.

**Comment by leonidrysev** [comment]
Thank you very much! 
Happyness and Greate project!
