### ISSUE TITLE
Preview video youtube

### ISSUE THREAD

**Issue by leonidrysev** [danny0838/webscrapbook#397]
Dear Danny!
Need again ask you.

If I capture just 1 page (Depth to capture linked pages EMPTY)
https://sisterproject.getcourse.ru/pl/teach/control/lesson/view?id=268586925&editMode=0

I see in data Preview video youtube
![image](https://github.com/user-attachments/assets/ee0f3b41-c806-4138-a049-9c2c970e2335)

If I capture root page (Depth to capture linked pages 1)
https://sisterproject.getcourse.ru/teach/control/stream/view/id/696469686
There is no Preview video youtube in data
![image](https://github.com/user-attachments/assets/c1698b27-3aeb-4a93-bdf0-51c1003a4618)

**Comment by danny0838** [comment]
Deep pages are captured headlessly, which works mostly like `Capture source` and scripts do not run. As a YouTube page requires scripts, it doesn't work well with capture source or indepth capture.

You'd have to load it in a tab to capture it. For multi-pages a workaround is to load all of them in a separated window, select all tabs to capture all of them at once.

**Comment by leonidrysev** [comment]
I understand. But How can I: select all tabs to capture all of them at once ??

**Comment by danny0838** [comment]
Just shift/ctrl click to select tabs. Alternatively there is a `Batch apture all tabs` dropdown command that can be configured in the options.

If you choose to capture each tab as an item, then of course a side effect is that the linked pages are not captured.

If you really want to deeply capture multiple dynamic pages together, there are 2 advanced ways to do so:
1. Merge capture: capture the main page with depth 0 (to build a site data), and then open each page in a tab and perform a merge capture into the previously captured main page item.
2. Tab mode for indepth capture: prepare an indepth capture with `Capture as`, and go to the `Advanced` dialog and set `capture.downLink.doc.mode` to `tab`. This will automatically open each deep page in a tab and start a capture after it completely loads.
   A caveat is that during the whole capture this may be very disrupting, and you have to be very carefully not to interrupt every opened tab.

**Comment by leonidrysev** [comment]
Could you explane:  ...and perform a merge capture into the previously captured main page item.

**Comment by leonidrysev** [comment]
I did seconse metod - att the video. But every page in separeta folder and I links on pages to www, no to data

https://github.com/user-attachments/assets/8a44fcfc-a7c1-49d6-b444-00cc672a2074

**Comment by danny0838** [comment]
1. Read the [doc](https://github.com/danny0838/webscrapbook/wiki/Basic#merge-capture) for details about merge capture.
2. In this way you should perform a depth capture for the main page that covers the linked pages (like you previously have done). Not opening all pages in tabs.

**Comment by leonidrysev** [comment]
I did it!) Thank you, Danny!

Noticed in **some** pages no preview youtube. Looked at code - there is **aria-hidden="true"**
`<div class="ytp-cued-thumbnail-overlay" **aria-hidden="true"** data-layer="4" style="">`

I deleted this and preview appears.
What do you think — can I corrected during capture?

![image](https://github.com/user-attachments/assets/e1208c04-6750-41f0-982d-dc467278b528)

**Comment by danny0838** [comment]
You can set up a capture helper for a capture. See the tooltips in the options dialog for details.

**Comment by leonidrysev** [comment]
Thank you!
