### ISSUE TITLE
One manifest.json

### ISSUE THREAD

**Issue by yfdyh000** [danny0838/webscrapbook#4]
Keep the `manifest-firefox.json` will bring trouble for debugging add-on, select it will load the `manifest.json` of the folder instead of the `manifest-firefox.json`. This may cause the temporary ID to be used, then [bug 1323228](https://bugzilla.mozilla.org/show_bug.cgi?id=1323228).

I guess you want to avoid Chrome warning the `"applications"`, it seems unavoidable (unless a gulpfile to workflow), but the warning is harmless.

**Comment by danny0838** [comment]
Currently the debug is performed on Chrome more than on Firefox. The package script will automatically remove unnecessary files. For debugging purpose on Firefox, simply replace `manifest.json` with `manifest-firefox.json`.

**Comment by yfdyh000** [comment]
Okay, it looks work, but it depend on environment. If you wish, maybe you can try some more common techniques to pack and lint, although they have greater requirements. Just a suggestion, because of homemade cmd let me be hesitate (especially with del command, worry like "install script does rm -rf /usr for ubuntu"), this issue may block new contributors.

**Comment by danny0838** [comment]
Is there any specific recommendation? Such as what package tool?

**Comment by yfdyh000** [comment]
I'm not familiar with it too, only know `npm` and `gulpfile.js`. Just as a suggestion.
Also, have continuous integration for checks and lint would be better.

**Comment by danny0838** [comment]
Close issue as wont fix. May consider switch to another packing mechanism but it's not related with the "one manifest.json" topic.
