### ISSUE TITLE
Need just the regular options in this new version (still browsing & Learning)

### ISSUE THREAD

**Issue by Theo-Smallie** [danny0838/webscrapbook#40]
Hello,

I'm using scrapbook X (Putt Firefox on hold for 56.x) and as i read all the text, english is not my native language, it seems to me that there's little left going from X to Web version.

I understand that there are things not possible but as it seems the basic functions are gone to.
Little explanation:
As i say i use scrapbook X.
Every month I export de entire dir.
Doing that i rename de map / folder from datetime stamp to date (Year&Month) a hyphen domainname incl. subdomain a hyphen and dayHourMinute and seconds (Example; 201801-sub.domain.ext-01010101) to another folder called Year & subfolder month on my server (For humans easer to read and find if neccassary).
Thru a series of macros (Excel)  i generate the above and a  index.html file in the root of this folder and a CSV or TXT file for import in a database, currently MS ACCES but soon a PHP / MYSQL one.

For this i need the scrapbook.rdf file and for security reasons the index.dat with data as stored in Scrapbook X (id	 like 20171205203037, create	20171205203037, modify	20171205203037, 
title	Smallenbroek | Facebook, chars	UTF-8, icon	H3nktOa7ZMg.ico, source	https://nl-nl.facebook.com/smallenbroek and comment)

Both they are gone, 
GUI is very rudimentary,
The site indexer shows no, or I can't find it, usefull data,
and the view archive page makes a zip file (having trouble to get usefull data from it) that is, for me, not functional.

Is it possible to restore these two basic but importent elements?

Gr.

Theo Smallenbroek

**Comment by danny0838** [comment]
If you run the site indexer correctly, the generated meta.js and toc.js files will contain all information the scrapbook.rdf has, and json format is generally more easier than rdf for scripts to parse (you'd have to modify your scripts to get them work with json data format, though). If you have problem using the site indexer, be more specific about it, and we may consider an improvement.
