### ISSUE TITLE
Unknown commands for auto-scrolling

### ISSUE THREAD

**Issue by pbz134** [danny0838/webscrapbook#402]
Hello,

I am using the Firefox addon and tried this command right here: https://github.com/danny0838/webscrapbook/wiki/FAQ-(zh_TW)#%E6%9C%89%E4%BA%9B%E7%B6%B2%E9%A0%81%E8%A6%81%E5%90%91%E4%B8%8B%E6%8D%B2%E5%8B%95%E8%9E%A2%E5%B9%95%E6%89%8D%E6%9C%83%E8%BC%89%E5%85%A5%E5%9C%96%E7%89%87%E6%88%96%E6%96%87%E5%AD%97%E6%9C%89%E8%BE%A6%E6%B3%95%E4%B8%8D%E4%B8%8B%E6%8B%89%E5%B0%B1%E6%93%B7%E5%8F%96%E5%AE%8C%E6%95%B4%E9%A0%81%E9%9D%A2%E5%97%8E

I inserted the script into the "Capture - capture helpers" box, but get the following error when capturing a website with the script enabled:
![grafik](https://github.com/user-attachments/assets/92af92b8-7050-44a4-ad6e-55dd6e945646)

Error running capture helper command: ["scroll",{"y":"100000"}]: Unknown helper command: scroll
Error running capture helper command: ["wait",{"time":2000}]: Unknown helper command: wait
Error running capture helper command: ["capture"]: Unknown helper command: capture

The website I tried is https://genshin-impact.fandom.com/wiki/Fischl (notice the dozens of small images as you scroll down the page)

Any help would be appreciated!

**Comment by danny0838** [comment]
`scroll`, `wait`, `capture` are not available commands, and are not mentioned in the doc page you have referenced, either. You should use the code like the doc page. See the tooltip for more available commands for the capture helper.

**Comment by pbz134** [comment]
> `scroll`, `wait`, `capture` are not available commands, and are not mentioned in the doc page you have referenced, either. You should use the code like the doc page. See the tooltip for more available commands for the capture helper.

Sorry, I must have sent you the wrong script. I tried the script from the docs and it still doesn't make any difference when executed.

**Comment by pbz134** [comment]
Here is a video of my workflow. I hope it includes everything you need.

https://github.com/user-attachments/assets/0b57c28b-636c-40af-9223-7b36b5ae7766

**Comment by danny0838** [comment]
The website has special CSS for lazyloaded and not-lazyloaded images, and as a result you have to also replace `lazyload` class with `lazyloaded`, like:

```JSON
[
  {
   "description": "save deferred images defined by data-* for fandom",
   "pattern": "/^https://(?:[\\w-]+\\.)*fandom.com//",
   "commands": [
     ["attr", {"css": "img.lazyload[data-src]"}, {
       "src": ["get_attr", null, "data-src"],
       "class": ["*replace", ["get_attr", null, "class"], "/\\blazyload\\b/", "lazyloaded"]
     }]
   ]
  }
]
```

**Comment by pbz134** [comment]
This indeed made a difference with the images. However, (at least for me), this only displays the file names instead of the full images:
![grafik](https://github.com/user-attachments/assets/53748d5c-d13a-4fa3-adef-dee563e2e384)

**Comment by danny0838** [comment]
I cannot reproduce the issue. Maybe there are additional DOM changes during image loading and needs further care. Also there may be another browser extension that interferes with it.

**Comment by pbz134** [comment]
After some tinkering, I'm happy to report it's working just fine!
I changed "Images" from Save current to Save, and disabled "Remove hidden elements"

Thank you for your help! :)
You can close this issue now.

**Comment by danny0838** [comment]
`Images` is unlikely to cause such difference, and `Remove hidden elements` is also unlikely unless there's another active browser extension that alters the webpage.

As above mentioned, websites may alter the DOM during a lazy-loading, which can make a different result if you happen to execute the capture just at the time that some images haven't finished a lazy-loading. A deeper research and tweaking would be required to perfectly handle such cases with a capture helper.
