### ISSUE TITLE
Save dynamic web page processed by server-side (Dynamic Web page scripts not loaded)

### ISSUE THREAD

**Issue by fede220** [danny0838/webscrapbook#41]
Hi Danny Lin, I would like to request a new feature for Web Scrapbook: Save dynamic webpage processed by server-side with dynamic script (asset/resources, AJAX, JavaScript, XHR, and Websocket for debug test offline) and keep dynamic html/scripts to html file, example is https://kiwiirc.com/client , saving dynamic webpage but dynamic scripts not loaded. Example in this video: http://android2.altervista.org/Save-processed-webpage.mp4

**Comment by danny0838** [comment]
This is impossible. Dynamic scripts often requires a connection to the server to work, but [same origin policy](https://en.wikipedia.org/wiki/Same-origin_policy) does not allow the script to connect the server unless they are in the same domain (of course you won't host the page captured by Web ScrapBook in the same domain as the original domain). 

For other dynamic scripts that doesn't need a connection to the server, you can select "save" for scripts in the options page.
