### ISSUE TITLE
Cross-domain stylesheets cannot be accessed

### ISSUE THREAD

**Issue by danny0838** [danny0838/webscrapbook#43]
If a stylesheet is in another domain form the current web page, extension scripts cannot read the stylesheet rule from them. As a result, if "save current used" is set for "background images" and "fonts", background images or fonts referenced by the stylesheet are never saved.

**Comment by kirill9000** [comment]
Do not use CSSOM to access them - just download via XHR.

**Comment by serj-kzv** [comment]
Hi,

It's my IMHO. I can by wrong and there is can be another way. :)

I've tried to do some tricks. It's not a solution, I think loading ```.css``` and redirecting ```blabla.css``` to its base64 representation is a better solution. But anyway.

(Replace css' ```@import``` rules with one huge ```.css``)[https://github.com/serj-kzv/save-whole-page-in-one-file/blob/3b2de28f1f21c79dd7295971e29bb390570dd89a/src/main/content_scripts/save-whole-page-in-one-file.js#L663]

It was a long time ago and I don't remember this exact. I've not finished that. Main idea was:
1. Download ```.css``` of ```@import`` and ```<link rel="...">``` through XHR
2. Replace them with their base64 representation
3. Now it's the same domain and CSSOM is available

You should know that there're a lot of tricks need to do it. You will have to correct URLs with js that browser correct itself automatically when you just ```click a link```, parse CSS, do something with strange XHR errors that is called by external resources (fonts for example). Virtually you will have to write whole right working CSS parser in JavaScript.

**Comment by danny0838** [comment]
Fixed in 0.42
