### ISSUE TITLE
After update to firefox 58, view archived page can't show the saved image

### ISSUE THREAD

**Issue by gakinccc** [danny0838/webscrapbook#45]
Hi
The View archived page have problem at Firefox 58. It can't shown saved page's images.
HTZ file or MAFF file have same result.
After decompress the HTZ file, the images was saved success.
And use Chrome to open the saved HTZ file, the images can be showed without problem.

**Comment by danny0838** [comment]
It seems to happen on Firefox 58 but does not happen on Firefox 59 (Developer Edition). I'm not sure whether it's a bug of Fx 58 currently...

**Comment by gakinccc** [comment]
This issue will not happened in new version Firefox
