### ISSUE TITLE
Web page recording

### ISSUE THREAD

**Issue by fede220** [danny0838/webscrapbook#46]
Hi Danny Lin, I would like to request a new feature for Web Scrapbook: web page recording (web page with all assets, css and JavaScript recorded during the session and saved to html file). Its possible add this feature in Web Scrapbook?

**Comment by danny0838** [comment]
I don't understand what you mean by saying "web page with all assets, css and JavaScript recorded during the session and saved to html file". Could you provide a more clear description?

**Comment by fede220** [comment]
I intend to record the web page interactions with all assets, css and JavaScript, example
this site https://webrecorder.io record the interactions of the Web page.

**Comment by fede220** [comment]
I intend to record the web page interactions with all assets, css and JavaScript, example
this site https://webrecorder.io record the interactions of the web page.

**Comment by fede220** [comment]
I intend to record the web page interactions with all assets, css and JavaScript, example
this site https://webrecorder.io record the interactions of the web page.

**Comment by danny0838** [comment]
This is too far beyond the scope of Web ScrapBook. You should use the site directly if the functionality is required.
