### ISSUE TITLE
uncomfortable in relation to scrapbook

### ISSUE THREAD

**Issue by reallylikeit** [danny0838/webscrapbook#47]
scrapbook / webscrapbook ist a very good tool, I need and use every day. I'm very thankful that you took on the task to transport scrapbook to the new firefox. The proble is, up to now webscrapbook lacks many features (or I haven't discovered them yet) the old one had. Webscrapbook today is not really fit to be used. We need urgently the possibility to save and see and use what has been saved immediately.
The multiple steps we need now are disfunctional. Same goes for the former possibility to organize the saved file in folders before saving them.
Is there any hope you will find the time and the technical possibility to implement these functions again?
Grateful nevertheless
Robin

**Comment by danny0838** [comment]
Could you be more specific about what is the feature you are looking for and is missing? With the [site indexer](https://github.com/danny0838/webscrapbook/wiki/Import) one should be able to view the saved data in a way just like ScrapBook X using frames, which is sufficient for "to save and see and use what has been saved immediately". Although a GUI for sidebar and for editing the data tree is still [in the to-do list](https://github.com/danny0838/webscrapbook/projects/1).

**Comment by reallylikeit** [comment]
Hi Danny,
please excuse my belated reaction to your post. I've been on holiday. Answering your question: 
In the original Scrapbook you had one gui, you cold use for everything that was needed for daily working with a bigger amount of webpages. 
You could decide in which folder to store the webpage the moment you decided to store it. 
You were able to reorganize your different folders an their content be dragging it to another place.
You could organize all folders by name by one click.
Having stored the webpage you could open it immediately and work with it.
Now you have to store the webpage, call the indexer, search the webfolder, run the indexer and reopen the frame in the tree.  Even if yo have bookmarked it, it	's no workflow to really work with. And that's only, if you use the uncompressed html file for storing the webpages.
I haven't  found a possibility to organize the folders in any way. 
If you have many different folders with many webpages, it takes a very long time to open the bookmarked frame (I have a very fine machine and use the latest Version of Firefox).
As I said, maybe I overlooked a possibility for a better workflow. In addition, I've read that a new gui is on the to do list. So I'm hoping for future things to come.
Many thanks again for your initiative and time invested.
Robin

**Comment by danny0838** [comment]
Thank you for the thorough feedback.

Most of the problem is the GUI thing, which is what we are still investigating for.

Additionally:

1. The indexer also works for other web archive formats. Just check the "Save captured files in ScrapBook" option. It works fine with (scripted) single HTML archived. If you use htz or maff, you may need to use Chrome with file URL allowed, or use the server script or host them with a web server and access the data with a browser with Web ScrapBook installed.

2. Currently you can organize your folders and items or modify their metadata by manually editing the meta.js or toc.js. It's not as easy as using the GUI, but at least it works.

**Comment by tasket** [comment]
The following extension has a sidebar list GUI:

https://addons.mozilla.org/en-US/firefox/addon/tab-center-redux
