### ISSUE TITLE
Let Web Scrapbook works on mozilla pages cause there is possibility to capture those pages

### ISSUE THREAD

**Issue by serj-kzv** [danny0838/webscrapbook#48]
There is possibility for the Web Scrapbook to work on mozilla.com pages.

For normal work on addons.mozilla.org pages

1. in the address bar: about:config
2. right-click to create a logical
3. setting name: privacy.resistFingerprinting.block_mozAddonManager
4. value: true

But "Capture tab" menu items of Web Scrapbook are disabled and I can not capture these pages. Can you create option to enable them or replace this functionality by some notification?

**UPD**
Also I suggest you add this note to your addons.mozilla.org page as author of [Screengrab!](https://addons.mozilla.org/en-US/firefox/addon/screengrab-fix-version/) did.

**Comment by danny0838** [comment]
Implemented (97ac3716aa27b16448a8a61bb4860d1ea92e0379).
