### ISSUE TITLE
HTML archive format and implementation

### ISSUE THREAD

**Issue by danny0838** [danny0838/webscrapbook#5]
In version 0.3.0 we use `.htz` extension as the zipped package of a captured web page. We also implemented a viewer that can directly load a .htz file in the browser, including the direct method (directly open the htz file in Chrome; the user must check "allow file url access") and the indirect method (open the viewer from the toolbar dropdown list and then pick an .htz file). Unfortunately, the viewer requires the `requestFileSystem` API, which is currently not available in Firefox.

**Is there other way to implement the `.htz` viewer using currently available WebExtension APIs in Firefox?** One idea may be the technique that [EPUBReader](https://addons.mozilla.org/zh-TW/firefox/addon/epubreader/) use, but it seems that its source code is obfuscated and is not available for us to study.

We currently consider the best cross-platform HTML archive format to be zip based. Besides current `.htz` one, another zip based approach is `MAFF` that [MAF addon](https://addons.mozilla.org/zh-TW/firefox/addon/mozilla-archive-format/) uses, which, unfortunately, seems to be unmaintained. Besides zips, there are still many types of HTML archive, such as: `.mhtml`, `.warc`, `.webarchive`, or so. **Is there other recommended format?**

**Comment by yfdyh000** [comment]
FYI: https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryReader

**Comment by danny0838** [comment]
We now move the viewer functionality to another addon [Web Archive Viewer](https://github.com/danny0838/webarchiveviewer). Support for Firefox is implemented.

**Comment by danny0838** [comment]
We decided to merge the viewer functionality back. (The decision to split the function before was because it seems impossible to implement some functionality in Firefox for Android, but finally those issues are solved and WebScrapBook can basically work on Firefox for Android now)

**Comment by vensko** [comment]
Calibre supports zipped HTML files and uses **.htmlz** extension. Renamed .htz files work fine, with minor issues. Could you allow to use Calibre's extension, at least optionally?

**Comment by danny0838** [comment]
Thank you for the information. In a quick glance it seems that .htmlz is an archive for a ebook and its purpose could be different from .htz. We need a further investigation sometime.

By the way, could you be more specific about what are the "minor issues" you met? This could help us identify them.

**Comment by vensko** [comment]
CSS mostly. For instance,
original rendering in Firefox 57 https://imgur.com/XezAxWa
Calibre viewer https://imgur.com/JNeEzWS

**Comment by KrasnayaPloshchad** [comment]
A Pale Moon add-on [MozArchiver](https://addons.palemoon.org/addon/mozarchiver/) can be used to compare, if you installed Pale Moon and you added MozArchiver, then you'll see the performances with the same MAFF file if you want to do improves.

**Comment by danny0838** [comment]
This is a very old issue. As there's no promising archive format found, we decide to stick to HTZ, MAFF, and single HTML currently. Conversion between these formats and other formats like MHT, .archive, .warc, etc., may be implemented in PyWebScrapBook in the future, though.
