### ISSUE TITLE
Shortcut save

### ISSUE THREAD

**Issue by marty90** [danny0838/webscrapbook#55]
Hello,
I need to autosave a webpage within a python script. Is there a shortcut for saving a page, like in the old Scrapbook plugin which allowed?
```
pref("scrapbook.data.default", false);
pref("scrapbook.data.path", "/Path/to/store/webpage");
pref("scrapbook.key.save", "D");
```

**Comment by danny0838** [comment]
Hotkey support has been implemented in 0.49.0.

Autosave feature is with lower priority and would probably be pending until other features have been complemented.

Though, WSB provides APIs allowing other extention to invoke a WSB capture. You can write an extension for uch purpose for now. :)
