### ISSUE TITLE
write some text from page content after data-time string in folder/archive name

### ISSUE THREAD

**Issue by qdinar** [danny0838/webscrapbook#61]
in old scrapbooks, it was possible to see title of page in saved pages' list. now there is no list, and i use just simple windows explorer file/folder listing. so i do not see what is what until open that. i would like to easily see what i have saved and what not, to not make duplicates (also to delete duplicates created by mistake). adding after several minutes: to avoid duplicates and to know whether i have saved an opened page or not. and to easily find an older saved page just by scrolling the list and reading headings, ie without going to search.

**Comment by qdinar** [comment]
seems this idea is not good if specialised listing file or sidebar appears as in old "scrapbooks" f firefox, because file/folder names do not support some characters and... seems simple date-time string is more optimal to save in the visible listing's internal database table...

**Comment by danny0838** [comment]
[Site indexer](https://github.com/danny0838/webscrapbook/wiki/Indexer) is made for that.
