### ISSUE TITLE
Angular based site saving does not work

### ISSUE THREAD

**Issue by serj-kzv** [danny0838/webscrapbook#64]
**OS:**
kubuntu 18.04 x64
The Firefox with latest WebScrapbook
The Chrome with latest WebScrapbook (newer than the Firefox's WebScrapbook)

**Steps to reproduce:**
1. Switch on "_Scripts: Save_"
2. Go to https://angular.io/tutorial
3. Try to save

**Result:**
Page is saved, you can open the page but you can see the page content few second only. After that the saved page becomes blank.

**Notice.** 
[Save Page WE](https://addons.mozilla.org/en-US/firefox/addon/save-page-we/) can save the angular based page.
With "_Scripts: Blank_"  option you can save the page.

**Suggestion.**
Please, add "save with scripts" and "save without scripts" items to the WebScapbook menu.

**Comment by danny0838** [comment]
Angular script requires network connection to work and thus connect work correctly in the off-line environment. Do not set "Scripts: Save" and the web page shows correctly (SavePageWE does not save scripts, and that's why the page captured by it works).
