### ISSUE TITLE
Firefox Tabs crash when I want to open some saved page

### ISSUE THREAD

**Issue by JEskandari** [danny0838/webscrapbook#65]
the problem is Firefox tab will crash when you try to open some saved page such as Pages from IMDB 
the problem is something new as I can open paged saved 1 to 2 month ago but when I try some new pages the crash happen
interestingly other browsers like edge and Chrome don't have the problem

I attached two file both in scripted html
(2010)Loups-Garous - IMDb can be opened with Firefox and is made on 03-09-2018
[(2010)Loups-Garous - IMDb.zip](https://github.com/danny0838/webscrapbook/files/2083054/2010.Loups-Garous.-.IMDb.zip)

(2010)Loups-Garous - IMDb(NEW) can't be opened with Firefox and is made on 06-08-2018

[(2010)Loups-Garous - IMDb(NEW).zip](https://github.com/danny0838/webscrapbook/files/2083072/2010.Loups-Garous.-.IMDb.NEW.zip)

firefox version is 60.0.2 and the files are Scripted Single HTML if I Don't use Scripted Single HTML and instead of that use Single HTML then there is no problem

**Comment by danny0838** [comment]
It seems to be an issue of Firefox rather than Web ScrapBook, and, unfortunately, we currently cannot figure out why it happens. You can report this issue to [bugzilla.mozilla (Firefox development)](https://bugzilla.mozilla.org/enter_bug.cgi) to get them investigate on it as well.

**Comment by danny0838** [comment]
Close this issue as it's likely Firefox browser related, and scripted single HTML is no more supported.
