### ISSUE TITLE
error in script: "Open directly with the browser" (Firefox, Linux)

### ISSUE THREAD

**Issue by serj-kzv** [danny0838/webscrapbook#66]
**OS: Kubuntu 18.04 x64  
Firefox 60.0.2 x64**  
See the screenshot please. If I try to open `maff` file and the Firefox is opened **already** then a path to the file `index.html` is wrong. The path point to `index.html` as `jar:file:///.../file.maff!/1528806833368_334/index_files/index.html` but a real path is `jar:file:///.../file.maff!/1528806833368_334/index.html`
![screenshot_20180616_154925](https://user-images.githubusercontent.com/22834344/41498748-891ec956-717d-11e8-9617-1fd423a7f681.png)

**Comment by danny0838** [comment]
Could you provide a sample maff file with such issue?

**Comment by serj-kzv** [comment]
Here it is. The maff file is packed as zip (github does not allow upload maff)  
[SamyPesse_How-to-Make-a-Computer-Operating-System · GitHub.maff.zip](https://github.com/danny0838/webscrapbook/files/2108145/SamyPesse_How-to-Make-a-Computer-Operating-System.GitHub.maff.zip)
