### ISSUE TITLE
enhancement: integrate 'capture tab' in right-click menu under 'save page as'

### ISSUE THREAD

**Issue by StephanBusch** [danny0838/webscrapbook#69]
please integrate 'capture tab' functionality in right-click menu under 'save page as'.
The MAFF plugin did the same - you just had to select .maff as filetype once.

**Comment by danny0838** [comment]
The feature you mentioned is not possible under the restriction of the WebExtension framework. (MAFF is a legacy addon and does not support WebExtension.)
