### ISSUE TITLE
Images in webscrapbook saved MAFF files are not visible to decMaffWLX.

### ISSUE THREAD

**Issue by liuxb** [danny0838/webscrapbook#7]
我一直用scrapbook + scrapbook MAF creator来保存maf格式文件，查看是使用文件管理器totalcommander的一个插件decMaffWLX来查看https://totalcmd.net/plugring/MaffWlx.html。
最近试用webscrapbook，发现一个问题：
使用webscrapbook保存的maff文件在使用decMaffWLX查看的时候，网页中的图片不能显示，其他文字、样式都正常。
然后把这个maff文件解压，解压得到的目录再手动压缩为zip文件并改后缀为maff，然后再使用decMaffWLX来浏览，图片就可以显示了。
这是否说明webscrapbook的maff格式和scrapbook MAF creator的有所区别？
同样的情况在htz中也存在，解压htz，把得到的所有文件重新打包为zip并改后缀，就正常了。
作者能不能帮忙看看这个问题？ 谢谢！

另外，现在默认保存目录是%USERPROFILE%\Downloads\下面，这个目录如果能自定义就好了。

**Comment by danny0838** [comment]
比較可能造成問題的應該是壓縮方式：WebScrapBook 對於二進位檔案是不壓縮的（因為圖片壓縮省下的空間很少，有時甚至會變大，並且會使存取速度變差），而對文字檔案採最大壓縮，相較之下  ScrapBook X MAF Creator 是對所有類型的檔案做 deflate 壓縮。

你可以先試試用 ScrapBook X Converter 把 ScrapBook 資料轉換為 maff 或 zip 試試能否用 decMaffWLX 開啟，如果也不能，大概就是 decMaffWLX 處理未壓縮的檔案有某些問題，也許你可以回報給作者看看。

**Comment by liuxb** [comment]
不好意思忘了这个贴子了。
刚试过了，
使用WebScrapBook生成的maff档解压后再压缩（压缩率0即不压缩），生成的zip文件使用decMaffWLX打开时失败（弹出来一个下载窗口提示保存index.html）。
在56上使用ScrapBook X Converter生成的maff，也是直接用decMaffWLX无法显示图片。
应该就是decMaffWLX的原因，这个插件很久没人维护，估计没法了。
谢谢。

**Comment by danny0838** [comment]
感謝回應，那就結案了。

要直接開啟封存檔還有其他方法，可參見： https://github.com/danny0838/webscrapbook/wiki/(zh-tw)View
