### ISSUE TITLE
Save folder box in options too small, make wider

### ISSUE THREAD

**Issue by bulrush15** [danny0838/webscrapbook#71]
The Save Folder box in the options is not wide enough. Can you make it as wide as the browser window? 

Image: http://nimb.ws/2X4Em8

**Comment by danny0838** [comment]
Due to browser restriction it's merely a subdirectory name under the default download directory, and thus a large input area is probably not necessary.

**Comment by bulrush15** [comment]
@danny0838 So we cannot use an absolute path to change the directory? This directory is always a subdir under the Windows Downloads folder? That's kind of inconvenient because I've used c:\downloads as my download dir for 35 years.

**Comment by danny0838** [comment]
@bulrush15 No, we can't. But we can work around this using a symbolic link. See the related [FAQ](https://github.com/danny0838/webscrapbook/wiki/FAQ#is-there-a-way-to-specify-a-folder-outside-the-default-download-folder-to-save-captured-data-to) for details.

**Comment by bulrush15** [comment]
So we cannot use an absolute path for the download dir? Is that due to browser security and restrictions? I'm just trying to understand the issue here.
