### ISSUE TITLE
idea to make "this page is already saved (in this session)" indicator

### ISSUE THREAD

**Issue by qdinar** [danny0838/webscrapbook#73]
i forget whether i have saved a page, that stays currently opened in a tab, or not. please, make an indicator to show that, if it is easily possible. since automatical regeneration of saved pages index is not possible in the new firefox. such indicator would be even more comfortable than the saved pages index, because last saved pages used to go to bottom of the index and might not be immediately visible.

**Comment by qdinar** [comment]
do you need to read from file system? why not just save that in a local variable? for an additional example/proof, adblock plus addon icon shows how many images are blocked in the page.

**Comment by danny0838** [comment]
The user could move, rename, or delete the captured page afterwards. Saving in a variable cannot know such change.

**Comment by qdinar** [comment]
of course, you can show how many times page was saved, (instead of just was it saved or not).

**Comment by qdinar** [comment]
problem of duplicates was one of reasons i started to use scrapbook instead of firefox's built-in save. i had also other problems, see https://bugzilla.mozilla.org/show_bug.cgi?id=922968 .

**Comment by qdinar** [comment]
can you get local file system address of the last saved index.html? it could be useful feature. i have thought this, just now, and then remembered: this feature is already in downloads tab. i tried it, and i see that it does not work! so anyway, i write about this. ( i see you said "The extension framework does not allow reading the local file system", but what about giving you back the saved local address? ) (what happens with the downloads menu: i click copy link to file, paste in address bar and see: " blob:moz-extension://c13dc9e8-0382-4e7b-97de-4cdabd4487be/39c49a62-5b7f-4e3f-8845-451949a41189 " , instead of something like "file:/home/dinar/downloads/webscrapbook/data/202009071343.../index.html" . )

**Comment by danny0838** [comment]
Yes, the browser does support a feedback of the download local path. So we can provide a feedback of the saved path of a capture like this:

![圖片](https://user-images.githubusercontent.com/531417/95478174-c85cee80-09bb-11eb-9684-f709bae6d019.png)

This is implemented and will be available in the next release.

Additionally, you can click the `Show in folder` in the download manager to open the downloaded file in the file manager, like this:

![圖片](https://user-images.githubusercontent.com/531417/95478297-f2161580-09bb-11eb-866f-f0f607b3e257.png)

**Comment by danny0838** [comment]
Implement captured page hinting in 0.85.0. This requires backend server, though.

**Comment by qdinar** [comment]
additional idea is implemented. but i have not tested it yet. my firefox is bloced by apparmor, and running file manager is not allowed. i cannot decide to allow it, it looks dangerous. when i try to copy link do downoad, it still gives blob:moz-extension://c13dc9e8-0382-4e7b-97de-4cdabd4487be/ea5ec08e-7c6d-48f0-93e5-755c13f93de2 .

but the first idea is not implemented. it looks for me as easy and not requiring backend server.

you replied

"The user could move, rename, or delete the captured page afterwards. Saving in a variable cannot know such change."

maybe you do not understand, what and why i want.

imagine that you browse a list of links one after another opening them in a new tab, and you scroll every of them and save them and close them. that can be news links from a email, it can be search results, it can be news site. imagine you opened 3 links in new tab, started to read them, and there are recommendations in side bars of them, and you opened another 7 links for them, and also only started to read them. and you continue to read them parts of one and another, like randomly, which you want to read. and you want to save interesting pages, and to not save useless pages. you have the idea to save page after reading 1-2 paragraphs of some of them. you can save them immediately, or can save them later. when you read them to bottom, you do not remember, have you saved this page yet. if it is already saved, you make a dublicate, if you save it, and you do not want a dublicate.

**Comment by danny0838** [comment]
Well, I still cannot get what you exactly want. I know you want a solution without the backend server, but I'd suggest you install the backend temporarily and report whether it behaves as what you desired or not. If still not, you may need to provide a much more clear description about what you actually want.

For what I currently get: Although we do support quick local capture for convenience in case backend is not available or desired, implementing a more dedicated management feature like the backend server does, yet still handicapped here and there due to the restriction of the browser extension framework, is likely something repeating ourselves (in contrast to the [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principle) and is too far away from our design goal. We won't firmly say no about this, but as we have very limited resource and there's still a long pending TODO list, implementation of anything like this would unlikely be happen in the near future anyway.

**Comment by qdinar** [comment]
"a more dedicated management feature like the backend server does",
"you may need to provide a much more clear description about what you actually want"

i say about changing the icon on the toolbar. for example, if current page (url in currently selected/opened/active tab) is not saved in this time this tab is opened or reopened (by restore closed tab or by going back or by going forward but not by reloading page...) then usual icon should be shown, else (ie if/when the page is saved) icon with same image with a green "checked" mark should be shown. i had said, initially, "in this session". it is also a possible solution. since every page like an article is going to be opened just once, it is ok... but, if it is a user profile page, or an article with lots of comments, it can be saved several times in a browser session (time after browser is started), and for that case it (counting by session) is not very good.

**Comment by danny0838** [comment]
If I understand you right, current implementation should match the needs (except for the "without backend server" thing).

As previously mentioned, there's no plan to implement more dedicated management feature for local capture in the near future. If you have time, consider try the backend server and check if it behaves as you want (or see [here](https://github.com/danny0838/webscrapbook/issues/153#issuecomment-717359343) for a short text description) and provide a feedback, so that we can improve it for now and get it implemented more smoothly if one day we decide to do it.

**Comment by qdinar** [comment]
i have read the description.

you said "When the option "hint captured pages" is checked, a badge number will be shown at the webscrapbook toolbar button, with different color for the level of matched captured pages: red for same URL (excluding the #fragment), yellow for same path ..."

it looks like ok for me.

"Although we do support quick local capture for convenience in case backend is not available or desired, implementing a more dedicated management feature like the backend server does, yet still handicapped here and there due to the restriction of the browser extension framework, is likely a violation of the DRY principle and is too far away from our design goal."

"there's no plan to implement more dedicated management feature for local capture in the near future"

i do not want to install backend server because i like to install things from central repositories as much as possible, because it looks more secure to me, because users may report a malicious addon to repository owners and they can block that addon, but in case i download a software from software author directly, i am afraid i may use a malicious software for years without knowing it. if i downloaded a script software directly from author, i would have to check its sources and of all of its updates. if it is a binary software, i cannot even check it, i do not feel it easy to check it with a disassembler. in both cases, (getting script or binary directly from author), it is harder than just trusting a central repository and all of its users.

if you make 2 versions of addon, manually, to work with and without backend, it will be violating DRY. but if you make one addon which knows about whether does it work with or without backend, or if you genereate 2 addons from one script, which also knows which version to generate, it will not be violating DRY.

if you want to show the level of how much the saved urls match with the current url, and to give list of the matching saved urls, it is not going to work with the new firefox api without backend. but if you just save in a local variable, whether url was saved in some period of time, like i said, browser session, or by other criteria, it looks easy, and it would be enough, very satisfying for me. seems i do not very need the features that can be done only using the backend technology.

as i know, firefox developers had cut off many api possibilities of old api, in the new addon api, for securiy reasons. but you want to bring all of old possibilities back using a backend. but, i think, it is like a workaround, a hack, relating to the new firefox policy. it probably brings insecurities of old api (probably like free file system access etc).

though i can download and block the backend server with apparmor or to not block but research its code (source), they are not easy works, i prefer to just use simple firefox addon, i can continue to save with possible duplicates.

i cannot just trust you, because i do not know your intentions/plans. to trust you i need either check the sources, and develop trust after some time, or, maybe, read your blogs and see your personality and see you have some religious intentions to not send malware to users, and that you are a real person...

also i can trust microsoft in managing github, it is also a central repository, i should think about it... its users also can report malware, i need to check its terms and i would like to see some news articles about github blocked malware on it...

**Comment by danny0838** [comment]
If you have read the manual you should know that PyWebScrapBook, the backend server and toolkit that WebScrapBook uses, is written in Python and all its source code is open. You can either install the packaged version from PyPI or download the source code from repository and install it. Everything is transparent. 

Almost all open source softwares from the web are in the same situation, you can choose to either review the code by yourself or get someone do it, trust the author, user, and reviewers, or don't use it. That's how the world works, and what to do is up to you anyway.

According to our evaluation, either write 2 addons, write a framework to generate code for multiple addons, or write an ad hoc version to handle record and check captured URLs, or anything similar we can currently thought of, is a work large enough, so we don't plan to do it. If you really think it's easy, you can try to write the code and submit a PR (or get someone do it for you) :)

**Comment by danny0838** [comment]
@qdinar This feature should have been implemented in 0.111.0, mainly it's somehow a prerequisite for autocapture to work well. Due to the uncertainty of captures in recent session, only identical URL is matched and are shown as level 5 in gray color.

**Comment by qdinar** [comment]
i have version 0.112.0 but webscrapbook icon stays same, when i am on a tab which is already saved. wsb icon is in a menu (under >> icon). i expected it to be changed.

**Comment by danny0838** [comment]
Have you checked the option?

**Comment by qdinar** [comment]
now, i have found the option and enabled it and it works. thank you. (in the previous time, i looked at options but very quickly and did not see it).
