### ISSUE TITLE
Absolute File Paths

### ISSUE THREAD

**Issue by FluidNets-DamianS** [danny0838/webscrapbook#74]
Is there any way to download the content with  absolute file paths to images saved?

**Comment by danny0838** [comment]
You mean link images to source web page instead of save them to local disk? It you do, set "capture" > "images" to "links" does it.

**Comment by FluidNets-DamianS** [comment]
No.. in the html the paths are all relative..  \image.jpg instead of c:\path\image.jpg.  I need absolute paths to images

**Comment by danny0838** [comment]
It's not possible. The browser extension cannot get the absolute path in the filesystem.
