### ISSUE TITLE
Output folder and page title

### ISSUE THREAD

**Issue by cpshanley** [danny0838/webscrapbook#75]
I want the default page title (not using indexer, as saved). So I uncheck Save captured data in ScrapBook.

The HTZ is now saved with an intuitive name. But always in the default Downloads folder (which gets pretty messy pretty quickly).

Is there a way to specify a default folder for saving?

THX

**Comment by danny0838** [comment]
If your browser is not configured to download files to default download folder, you should be able to specify the target folder when downloading.

**Comment by cpshanley** [comment]
Blimey, that was quick!
Unfortunately, it is (/Downloads).
I wondered if I could config a folder just for the captures (e.g. /Downloads/Captures)?

Cheers

**Comment by danny0838** [comment]
Unfortunately, it's not possible due to the restriction of browser extensions.

**Comment by cpshanley** [comment]
Cheers, Danny. Thanks for your efforts.

**Comment by cpshanley** [comment]
Would still be nice to have the option of saving the title for all captures, though.

All the best.

**Comment by danny0838** [comment]
Implemented in 39.0.
