### ISSUE TITLE
Incomplete (MAFF) page

### ISSUE THREAD

**Issue by ChrisBertrandDotNet** [danny0838/webscrapbook#77]
Hi

When I save the following page as MAFF, most of the content is missing, even the HTML content.
https://michaelscodingspot.com/2017/10/19/visual-studio-2017-extension-development-tutorial-part-3-add-context-menu-get-selected-code/

Please note all scripts were disabled (using NoScript) on that page.

The saved page (as MAFF, renamed Zip for GitHub):
[Part 3_ Add to context menu, Get selected code.maff.zip](https://github.com/danny0838/webscrapbook/files/2378877/Part.3_.Add.to.context.menu.Get.selected.code.maff.zip)

The same page saved as scripted HTML is complete (same options apart the file format):
[part 3.zip](https://github.com/danny0838/webscrapbook/files/2378918/part.3.zip)

WSB options:
![webscrapbook options](https://user-images.githubusercontent.com/33118130/45483369-0772d400-b751-11e8-9b88-0d8db4a3e78b.png)

**Comment by danny0838** [comment]
I cannot reproduce the issue. Capturing the page with the provided options in MAFF, HTZ or other formats work just fine.

Could you stably reproduce the issue (that is, visit the page and capture it for several times, and all get the same result)? Also, could you provide your WSB, browser, and OS version?

**Comment by danny0838** [comment]
Thank you for following up. Could you stably reproduce it?

**Comment by ChrisBertrandDotNet** [comment]
Guess what ? Know it works fine on Windows 10 too.
I don't understand what happened.
For what I know, I did not change the configuration of WSB, nor the configuration of FireFox.
Another mystery of Windows 10, maybe.

Sorry to have made you waste time on that.

By the way, **thank you for this good work** and for supporting MAFF.
This is a very useful format. In fact, I even made [a program](https://github.com/ChrisBertrandDotNet/OpenMAFF) that opens these files.

**Comment by danny0838** [comment]
Thank you for further feedback. There could be some factors such as network connection issue causing a temporary failure of a capture. If similar issue still occurs frequently in the future, you can check the browser console of the capturing dialog for further information.

FYI, we also provide some basic mechanisms to view MAFF and/or HTZ files on several platforms, see [here](https://github.com/danny0838/webscrapbook/wiki/View).

**Comment by ChrisBertrandDotNet** [comment]
This time I have a procedure where WSB fails systematically:

1. Ensure no firefox instance is running (just in case).
2. Open FireFox.
3. Open this page: https://michaelscodingspot.com/2017/10/08/visual-studio-2017-extension-development-tutorial-part-1/
4. Save it as MAFF.
5. In the same page, near the end there is a table of content. Click on the second part of the tutorial. Direct address: https://michaelscodingspot.com/2017/10/08/visual-studio-2017-extension-development-tutorial-part-2-add-menu-item/
**Important**: open the second page in the same tab. Do not open a new tab.

On FireFox 62.0 (64 bits) on Windows 10 (1803), I obtain this message:
> Capturing (document) [1] https://michaelscodingspot.com/2017/10/08/visual-studio-2017-extension-development-tutorial-part-2-add-menu-item/ ... Fatal error: response is undefined

I tried several times and obtained the same result.
I noted when I open the second page in a new tab, no problem occurs.

In the past, I have already been forced to open new tabs or new windows because of this kind of failures. Notably after having saved many pages as MAFF.
I don't know if it is related to the initial problem of this ticket.

**Comment by danny0838** [comment]
The source page must be kept open during the capture process. If you close the tab or visit another page before the capture completes, the capture may error out.

**Comment by danny0838** [comment]
Close issue due to lack of further information. Report if there's an update.
