### ISSUE TITLE
bookmark saved page

### ISSUE THREAD

**Issue by cyrant** [danny0838/webscrapbook#78]
Please, add an option to "_bookmark saved page after scrapping_".

Firefox Bookmarks allow:
* add tags to (bookmarks of) saved pages
* search saved pages by (bookmark's) name and by tags
* import/export list of (bookmarked) saved pages

It looks like it is not hard to implement with `bookmarks.create()`:
* https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Work_with_the_Bookmarks_API
* https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks/create

**Comment by danny0838** [comment]
What to bookmark? The URL of the source page? Or the URL of the downloaded page?

**Comment by cyrant** [comment]
The URL of the downloaded page (file://*).

**Comment by danny0838** [comment]
This is not possible, since the browser cannot know the full path of the download directory.

**Comment by cyrant** [comment]
Can it be explicitly specified by user?

**Comment by cyrant** [comment]
For example, I add 'file:///home/user/Downloads/Scrapbook' to input field on extension settings page. And the extension adds this string as prefix to saved filename.

**Comment by cyrant** [comment]
I am not familiar with JavaScript, but from my point of view, if I can do it manually (all steps in browser only), there is must be a way to automate it.

For now I am doing like this:
* scrap web page;
* press 'Display the progress of ongoing downloads' button;
* click on last saved 'index.html' in drop-down menu (to open it in tab);
* press 'Bookmark this page button' (CTRL+D), where I can choose title (by default it is same as web page title - sane defaults), choose folder, add tags.
And now I can search saved page by bookmark name or assigned tags in address line (CTRL+L) or on bookmarks panel (CTRL+B). And I can sort bookmarks with "folders" in traditional way.

Additionally, I use custom filters in **uBlock** for frequently saved sites to replace editor of old good ScrapBook. And **Recoll** tool is good enough for rarely needed full-text search.

Unfortunately, I can't view and navigate saved page's source URL in one click.  (Can the URL be placed at the top of HTML page?). And there is no easy way to delete saved page (not bookmark) and to redownload it from source. It looks much harder (or even impossible) to implement these features with new restrictive Filesystem API. Anyway, these rare tasks are not big issues for me. But things like search and organize (by folders and/or tags) are "must have" features for any organizer tool in my opinion. I have 1200+ saved web pages and bookmarks help me a lot. Give them a chance. (I wonder, how other people use the extension without them?)

**Comment by danny0838** [comment]
We have implemented the [site indexer](https://github.com/danny0838/webscrapbook/wiki/Indexer) feature for data organization and full text search. Though the GUI is still under development, and the user has to organize data by editing the `*.js` file manually for now.

**Comment by danny0838** [comment]
Bookmark for local file is not portable and we are less likely doing that. We have implemented [site indexer](https://github.com/danny0838/webscrapbook/wiki/Indexer) feature for data organization as well as full text search.

**Comment by cyrant** [comment]
At least bookmarks are as portable as the Indexer. You can import/export bookmarks to/from json/html. And now, you can place resulting file near Scrapbook's data directory. Moreover, you can synchronize bookmarks through devices with Firefox Sync.
Also you can change prefix dir in settings with no breakage.
The only problem is moving the data directory. But it is uncommon action. It can not be done with the extension, so it is not an issue that the extension can't fix URLs in bookmarks.
In such rare case URLs can be exported, renamed with jq/sed/{your favorite text editor with regex support} and imported again.

In turn the Indexer is more awkward. It don't allow search pages by name in place. It don't handle new saved pages without rerun. It has issues with filesystem-restrictive browser settings (like ghacks-user.js). Etc.

**Comment by danny0838** [comment]
Local filesystem paths are not useful as long as it's moved to another platform, making corresponding bookmarks meaningless even though it's synced. The user does can modify the bookmarks using some file path replacing technique, but it's still rather hacky and is not the solution we are looking for.

**Comment by cyrant** [comment]
There are more options for end-user to use same bookmarks on different devices:
- same pathes (including same usernames)
- bind mount
- symlink

I don't offer to replace the Indexer. I offer to add extra solution for those who found bookmarks reasonable.

It looks only need to add "add to bookmarks" checkbox and "bookmarks prefix" input field in settings and to add bookmark.create() after saving.

--

I've closed this issue since you found this option is unfit.
