### ISSUE TITLE
Picture names in single HTML files

### ISSUE THREAD

**Issue by xghub** [danny0838/webscrapbook#79]
Hello, is there a reason why the original file names of pictures are not retained when saving as a single HTML file? I noticed that file names are retained when saving to .maff.

Asking because sometimes I want to extract pictures from archived webpages.

**Comment by danny0838** [comment]
Following the spec of HTML, a single HTML file can only embed media using data URI. The original filename is included in the data URI as `;filename=xxx`.

**Comment by danny0838** [comment]
You're welcome.
