### ISSUE TITLE
请问webscrapbook网页保存功能的局限？

### ISSUE THREAD

**Issue by woyaojizhu8** [danny0838/webscrapbook#80]
我以前对比了各种笔记软件、各浏览器自身的保存网页功能、数个带网页保存功能的Firefox扩展的保存效果之后，发现scrapbook x保存效果最好，其他的都在部分网页上有缺失错位等问题。现在由于Firefox旧扩展体系被舍弃，新开发了此扩展webscrapbook，请问webscrapbook相比scrapbook x，不论管理组织功能，单在保存网页的效果上，有什么局限吗？我已经看过   https://github.com/danny0838/webscrapbook/wiki/(zh-tw)Caveats ，除了这些文件太大会出错等问题之外，还有什么局限吗？

**Comment by danny0838** [comment]
WebExtension API 和舊 XUL API 一個主要差異是後者可以直接存取所有 frame，WebExtension 則會受同源政策限制，只能在 frame 插入 content script 取得其內容，因此不同源且無法插入 content script 的 frame 就無法取得瀏覽器呈現的即時內容，只能退而求其次取原始碼，甚至完全無法擷取。

另外前者只能用 AJAX 向特定 URL 擷取資料，後者則有獨立的 nsChannel Interface，對於某些會傳回較特殊 HTML header 的網站，前者相對於後者可能有較多限制。

**Comment by woyaojizhu8** [comment]
不好意思，俗务缠身，现在才想起来回复。请问什么情况下会无法插入content script？我看了代码里的注释，是指frame还没有加载完毕的时候？这个时候即使扩展不能保存frame，也不能算有问题吧。
`// Simply detect the main frame and executeScript for allFrames doesn't`
    `// work since it's possible that only partial frames have the content`
    `// script loaded. E.g. the user ran this when the main frame hadn't been`
   ` // completed and some subframes hadn't been loaded.`

**Comment by danny0838** [comment]
按目前 WebExtension 的設計，只有 `http:` 和 `https:` 協定可以插入 content script，Chromium 系瀏覽器經過設定可以允許 `file:` 協定，其他都不行，比如 `data:`、`chrome-extension` 或 `moz-extension` 等等，不過這些情況都非常少見，一般使用可以忽略。

至於你提到的那段程式碼，和這問題無關，要詳細解釋說來話長，這裡就不贅述了。

**Comment by woyaojizhu8** [comment]
根据这里的说明 https://github.com/danny0838/firefox-scrapbook/issues/93 ：

> 不是沒考慮過，但目前看來 Chrome Extension 缺乏完整擷取網頁的某些必要功能，比如存取非同域 iframe 內容的權限（Single File 目前也沒辦法），因此無法勝任。

 那么现在来看，请问这个问题能说是基本解决（既然能在http和https协议的页面实现，就能算基本解决了吧，需要在其他协议的页面抓取的情况也非常少）了吗？

另外，你说`data:` 也无法插入content script，但是这一般不影响页面内部`data:` 编码的内容的获取吧？

**Comment by danny0838** [comment]
> 根据这里的说明 [danny0838/firefox-scrapbook#93](https://github.com/danny0838/firefox-scrapbook/issues/93) ：
> 
> > 不是沒考慮過，但目前看來 Chrome Extension 缺乏完整擷取網頁的某些必要功能，比如存取非同域 iframe 內容的權限（Single File 目前也沒辦法），因此無法勝任。
> 
> 那么现在来看，请问这个问题能说是基本解决（既然能在http和https协议的页面实现，就能算基本解决了吧，需要在其他协议的页面抓取的情况也非常少）了吗？
> 
可以這麼說，只要能寫入 content script 就能擷取到目前呈現的內容。

> 另外，你说`data:` 也无法插入content script，但是这一般不影响页面内部`data:` 编码的内容的获取吧？
如果 data URL 內容不是頁面，而是 CSS、JS、圖片等檔案，直接抓取 data URL 本身就好。但如果 data URL 是 iframe 裡的頁面，其內容可能被腳本動態修改，無法寫入 content script 就會導致無法擷取目前狀態（只能退而求其次抓 data URL 原始碼，即頁面的初始狀態），所以會有一些影響。

不過實際上幾乎沒有網站會用 data URL 呈現 iframe，所以影響不大。
