### ISSUE TITLE
Feature request: Open site index in the sidebar

### ISSUE THREAD

**Issue by olliebean** [danny0838/webscrapbook#81]
Up until now, I've been doing this by bookmarking the site index and setting the bookmark to open in the sidebar, but with Firefox 63 this functionality seems to have been removed. It appears to still be possible, as the Test Pilot experiment "Side View" can open pages and bookmarks in the sidebar, but unfortunately that extension doesn't work with local html files. Would it be possible to add this as an option to Web Scrapbook?

**Comment by olliebean** [comment]
Ah, thank you - I'd forgotten about that; I've been opening `web.html` in the sidebar. `frame.html` is part of the way there but I'd still sooner have an index in the proper sidebar, i.e. so I can switch tabs while keeping the index in view, or open and close . But apparently FF63 is no longer capable of opening a local file in the sidebar at all. I guess there must be a way for extensions to do it, as some of them do have their own custom sidebars - was just wondering if this was something you would consider implementing.

**Comment by danny0838** [comment]
The site indexer doesn't generate `web.html`. Do you mean `map.html`?

You mean you attempt to add a captured web page to the Firefox bookmark, open the bookmark list in the sidebar, and select the bookmarked captured web page from the sidebar? Firefox 63 seems to have no problem doing this, according to my test.

**Comment by olliebean** [comment]
Yes, sorry, I meant `map.html`. I had that file bookmarked, and that bookmark had the "Open in Sidebar" option enabled.

I tried using the Side View extension, which can open bookmarks in the sidebar, as well as a couple of other extensions that can do the same, but none of them worked with `map.html`, or with any other local file.

Somebody has pointed me to [https://github.com/mozilla/side-view/issues/298], which suggests that it's not possible for a web extension to open a local file in the sidebar because of "security restrictions." It's also not possible any longer to do it without an extension, due to the removal of the "Open in Sidebar" bookmark option.

However, it is still possible for extensions to open sidebars containing their own content, so there must still be a way of getting custom content into the sidebar, if not via a local html file.

I guess, though, just writing it out like this, that it probably isn't as simple to implement as I was hoping it might be.

**Comment by olliebean** [comment]
Thanks for your replies - I don't really understand all the points mentioned in the issues you linked to, but I do understand that this is a more complicated thing to implement than I had hoped. I guess I will just have to put up with this as another new restriction that Mozilla has placed on extensions being able to do useful things.

I still love the extension, though, and will continue to use it despite Mozilla reducing the convenience.

**Comment by danny0838** [comment]
Thank you for the feedback. For further discussion aboit the sidebar issue, go to #2.
