### ISSUE TITLE
This website cannot be saved as .maff

### ISSUE THREAD

**Issue by StephanBusch** [danny0838/webscrapbook#82]
This website cannot be saved as .maff - Is there something you can do about it?

https://squeezechart.wixsite.com/meinewebsite

Thank you

**Comment by danny0838** [comment]
I cannot reproduce this issue using WSB 0.27.0. Could you provide your OS, browser, WSB version and your capture settings?

**Comment by StephanBusch** [comment]
I use Win10 x64, Firefox 65.0a1 and WSB 0.27.0 with the following options:

Maff package;

the following options are ticked:
save data url as file
record removed elements
record rewritten attributes
record source URL
view HTZ file
view MAFF file
use filesystem API
update fulltext cache

capture content: everything is selected as 'save';
canvases: save current status
rewrite CSS: no rewrite
form status: keep

**Comment by StephanBusch** [comment]
Error downloading file (about:blank): Network request failed.

**Comment by StephanBusch** [comment]
I have played with the settings and cannot reproduce it anymore.
Now I am getting the same yellow error message but the .maff gets saved.
Th previous error was red and no .maff was saved.

**Comment by danny0838** [comment]
Close stale issue. Respond if there's further information.
