### ISSUE TITLE
"generate site index" fails prematurely

### ISSUE THREAD

**Issue by leedoyle** [danny0838/webscrapbook#84]
Getting either 
`"Got directory 'scrapbook'. Inspecting files... Skipped invalid ScrapBook folder.  Got file 'scrapbook.zip'" for a for a folder with *.htz files"`
or 
`"Extracting zip content... Skipped invalid zip of ScrapBook folder" `
for a zip file with two scripted html files within and for a zip file with a folder with two html files within.

**Comment by leedoyle** [comment]
Update: after turning on the option "Save captured data"  it started working. Not closing the issue because it hadn't worked with folders created manually

**Comment by danny0838** [comment]
A manually created folder can be provided to the site indexer as long as it follows the scheme of a WSB folder, that is, data files (.htz, .maff, .htm, etc.) are placed under `<folder>/data`, tree information files placed under `<folder>/tree`, icons placed under `<folder>/icon`, etc.
