### ISSUE TITLE
 Capture tab vs Capture tab (source)

### ISSUE THREAD

**Issue by nikosvaggalis** [danny0838/webscrapbook#86]
What is the difference between Capture tab and Capture tab (source)? I see that Capture source has better results than the plain Capture

**Comment by danny0838** [comment]
Capture tab is to capture the current rendered page (which may have been processed by scripts) of a tab, while capture tab (source) is to retrieve the page from the original URL of a tab (and the content is never processed by scripts).

**Comment by danny0838** [comment]
Close stale issue.
