### ISSUE TITLE
请求两个功能

### ISSUE THREAD

**Issue by Azureki** [danny0838/webscrapbook#89]
首先，感谢您开发这个扩展，我可以更新firefox了。但是现在功能似乎不是很完善，因此我请求添加两个功能。

## 1. 保存的页面都在根目录下，是否可以变成嵌套结构？

有一些文件是相关的，想放在一个文件夹里。  
比如一个教程，有多个页面，我想保存在一个文件夹里。

`toc.js`是可以编辑的，但是这样不方便……有没有不手动编辑`toc.js`的方法呢？（就是用鼠标点击按钮啦……

或者，`generate site index`的时候，根据文件夹的层次来构建`tree`可以吗？我在`WebScrapBook/data/`下有几个文件，一个文件夹。但是generate之后tree中只有那几个文件，那个文件夹被忽略了。

## 2. 保存的时候可以自定义标题

有些文章的标题和web页面的标题不一样。  
比如[这个文章](https://mp.weixin.qq.com/s?__biz=MzI3NDU3NTYzMg==&mid=2247483881&idx=1&sn=7c99351888a289fd82ccc9eeca8d18ea&chksm=eb10b996dc673080119f9dea4eb6a28ad6a0a1da015f97e800dfbbe8d2a178c57f8860dd9a5b&scene=0&xtrack=1&subscene=131&ascene=7&devicetype=android-27&version=2607033a&nettype=3gnet&abtest_cookie=BAABAAoACwANABQABAAllx4AWZkeAIiZHgCLmR4AAAA%3D&lang=zh_CN&pass_ticket=wGwbqoywVH0rR07yIqbD1bpZhxk00S0xPPW%2B%2BzZ%2BcfU25CWcrhipslvot1Vksm6w&wx_header=1)。文章标题是：

> 《临高启明》中的澳宋让日本人当兵，是否会引发老百姓反感？ 

但是页面标题是：

> 直江信纲之船

保存之后，标题是`直江信纲之船`，这并不是我想要的结果。

我记得以前scrapbook是可以自定义的，可否加上这个功能呢？

**Comment by hexiyou** [comment]
第一个问题不作评价，第二个明明就是网站问题，不关拓展的事，这需求太小众了
