### ISSUE TITLE
Display the original URL for archive files.

### ISSUE THREAD

**Issue by silriozs** [danny0838/webscrapbook#9]
Is it possible to display the original URL when opening an archive file, just like the [Mozilla Archive Format extension](https://addons.mozilla.org/firefox/addon/mozilla-archive-format/) did? And may I request for this feature if it is able to implement?

Thanks for your great work.

**Comment by Fixer-007** [comment]
I've seen in options "Record original URL", is it possible to view it via UI right now?

**Comment by danny0838** [comment]
@Fixer-007 The option is for a different thing—it records the original for any link in the captured page that get rewritten during the capture process; while what we've mentioned here is the original URL of the captured page, which is always recorded during the capture process.

The challenge is that we need a good design to provide a nice way to show it by user request and do not let it simply mingle into normal page display, and we need a further investigation.

**Comment by danny0838** [comment]
Implemented in the sidebar (backend server required), see #2.
