### ISSUE TITLE
Add the ability to output multiple formats at the same time.

### ISSUE THREAD

**Issue by nightson** [danny0838/webscrapbook#90]
Hi. I save some webpages in both MAFF (for faithful backup) and SingleHTML (easy to use on computers that don't have Web ScrapBook installed) formats. Right now I have to save the webpage in one format , change the format setting and then save in another format. Can you add the ability to output multiple formats at the same time? Thank you!

**Comment by danny0838** [comment]
We probably won't do that. But we may implement the feature to convert a captured web page into another format in the future.

For now, it's more recommended to capture a web page as "folder", "htz", or "maff", which are loseless and better for long-term preservation.

**Comment by danny0838** [comment]
With the help of [PyWebScrapBook](https://github.com/danny0838/PyWebScrapBook), you can create another scrapbook, copy items to it, and convert items in it using the conversion tool (`wsb convert items --format=single_file ...`). For more details see [here](https://github.com/danny0838/webscrapbook/wiki/Backend).

As aforementioned, it's generally recommended to capture a web page as folder, HTZ, or MAFF for better long-term preservation, and convert them to single HTML only when necessary.

As such, we decide not to implement such feature which is of similar purpose.
