### ISSUE TITLE
Linked files are not saved when their URL contains parameters

### ISSUE THREAD

**Issue by ChrisBertrandDotNet** [danny0838/webscrapbook#91]
Linked files, such as pictures stored on an external server, are not saved when their URL contains parameters.

Example of URL:
`https://lh5.ggpht.com/-6V0B2FzeqNI/UhKWo51Pb9I/AAAAAAAAB3w/WrQuffKQF-k/Reference%252520Manager%252520-%252520RoslynDemo1_2013-08-19_15-25-47_thumb%25255B1%25255D.png?imgmax=800`
The page that links the latter image:
`https://ebeid-soliman.blogspot.com/2013/08/getting-started-with-microsoft-roslyn.html`

**Comment by danny0838** [comment]
We cannot reproduce the issue as `https://lh5.ggpht.com/-6V0B2FzeqNI/UhKWo51Pb9I/AAAAAAAAB3w/WrQuffKQF-k/Reference%252520Manager%252520-%252520RoslynDemo1_2013-08-19_15-25-47_thumb%25255B1%25255D.png?imgmax=800` cannot be found in the page `https://ebeid-soliman.blogspot.com/2013/08/getting-started-with-microsoft-roslyn.html`.

**Comment by ChrisBertrandDotNet** [comment]
Apparently, in the source code, the address starts by `http://` (and not `https://`) :
```HTML
<img alt="Reference Manager - RoslynDemo1_2013-08-19_15-25-47" border="0" height="215" src="//lh5.ggpht.com/-6V0B2FzeqNI/UhKWo51Pb9I/AAAAAAAAB3w/WrQuffKQF-k/Reference%252520Manager%252520-%252520RoslynDemo1_2013-08-19_15-25-47_thumb%25255B1%25255D.png?imgmax=800" style="background-image: none; border-right-width: 0px; padding-left: 0px; padding-right: 0px; display: inline; border-top-width: 0px; border-bottom-width: 0px; border-left-width: 0px; padding-top: 0px" title="Reference Manager - RoslynDemo1_2013-08-19_15-25-47" width="525">
```

**Comment by danny0838** [comment]
We cannot reproduce the issue (the image is saved correctly). What is your WSB version and your capture options?

**Comment by ChrisBertrandDotNet** [comment]
After having tried with the last version of WSB today, I did not have the problem.

Maybe a recent version solved the problem.

Thank you anyway.
