### ISSUE TITLE
save even if document is not loaded completely

### ISSUE THREAD

**Issue by qdinar** [danny0838/webscrapbook#94]
sometimes some images may be not loaded. and images may be even set to be not saved in wsb options. but if images are not loaded, wsb says "document not loaded completely" and does not save. now, i wanted to save a text from google cache. i could not save. document was still loading. then i pressed "stop loading" button of browser, and tried to save with wsb, and it again does not work. but, html itself is loaded completely.

**Comment by danny0838** [comment]
Please provide an URL of issue so that we can do further investigation.

**Comment by danny0838** [comment]
Implemented in 0.40.0
