### ISSUE TITLE
能夠批量保存html檔嗎

### ISSUE THREAD

**Issue by s4028600** [danny0838/webscrapbook#95]
我想批量保存html檔
比如這些網頁
http://www.dm5.com/bookmarker-p1
http://www.dm5.com/bookmarker-p2
...
有300多頁

而且目前的保存都會跳轉到登入頁面
有沒有辦法呢

**Comment by danny0838** [comment]
批量保存尚未實做，即使做了也很難處理需要 JavaScript 的網站。

要下載漫畫建議用專用的工具，例如 [ComicCrawler](https://github.com/eight04/ComicCrawler)。

**Comment by s4028600** [comment]
JavaScript是指？

不是要下載漫畫
是要html檔

好像很久之前的舊版的scrapbook可以
只是下載下來不是封包的html檔...

**Comment by danny0838** [comment]
1\. JavaScript 是在瀏覽器執行的腳本程式碼，可以動態修改網頁裡的內容，甚至連線擷取更多內容插入網頁。ScrapBook 的深層擷取只能擷取到原始碼，如果你要擷取的頁面有內容是透過 JavaScript 加載的，就會抓不到。

2\. 如果是指以前 ScrapBook 的深層擷取（把目前頁面連到的頁面一併擷取），存成一筆記錄，此功能尚未實做。

如果是把每個頁面個別擷取成一筆記錄，可以把這些頁面全部開啟放在同一視窗，然後用「擷取所有分頁」。
