### ISSUE TITLE
Capture does not response since version 0.30.0 on Firefox 55

### ISSUE THREAD

**Issue by Binjohn** [danny0838/webscrapbook#96]
請問新版是不是只支援Firefox Quantum了？

我試到0.29.1都沒問題，但更新0.30.0後「擷取分頁」就沒反應了。
我試過修改封存格式的設定，沒用。

OS: Windows 7 SP1
Firefox version: 55.0.3 64-bit

**Comment by danny0838** [comment]
沒有這樣的規畫。你再檢查看看是否所有網頁都有同樣問題，並試試重啟瀏覽器及關掉其他套件是否還有同樣問題

**Comment by Binjohn** [comment]
我幫Firefox開了全新的使用者設定檔，然後安裝0.31.0，但還是沒反應。

**Comment by danny0838** [comment]
終於查出來了，30 版改進的擷取功能使用了某些技術，在舊版 Firefox 沒有支援（但是文檔根本看不出不支援……開發者表示極度不爽）。32 版會修正。

**Comment by Binjohn** [comment]
居然是文件有缺失，這是陷阱啊！感謝幫忙，這樣就能繼續到處擷取資料了。
